# 08 - Normalización de platos y construcción del catálogo inicial

## Objetivo

Este notebook inicia el módulo de normalización de platos de Hidden Gems.

Partimos de las menciones detectadas por el modelo `Dish NER v1`:

`dish_mentions_model_v1_full.jsonl`

El objetivo es pasar de menciones textuales sueltas a un catálogo inicial de platos:

```text
burger
burgers
cheeseburger
burger with bacon
→ burger / cheeseburger / bacon burger

taco
tacos
tuna tacos
→ tacos / tuna tacos

fries
french fries
home fries
→ fries
```

## Salidas esperadas

Este notebook generará artefactos como:

`dish_mentions_normalized_v1.jsonl`
`dish_surface_forms_v1.csv`
`dish_catalog_seed_v1.csv`
`dish_aliases_seed_v1.csv`
`dish_normalization_summary_v1.json`

Estos archivos serán la base del siguiente módulo:

09_dish_mention_sentiment.ipynb

## Enfoque

La normalización se hará de forma híbrida:

limpieza textual;
reglas lingüísticas simples;
agrupación singular/plural;
detección de variantes;
creación de familias de plato;
preparación para revisión manual futura.

Este primer normalizador no será perfecto, pero sí debe ser estable, trazable y útil para construir rankings iniciales.

In [5]:
# ============================================================
# 01. Imports y configuración base
# ============================================================

from pathlib import Path
import json
import random
import re
import os
import warnings
from collections import Counter, defaultdict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

RANDOM_STATE = 42

random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

pd.set_option("display.max_columns", 150)
pd.set_option("display.max_colwidth", 300)

print("Entorno inicializado correctamente.")

Entorno inicializado correctamente.

In [6]:
# ============================================================
# 02. Detectar entorno y preparar carpetas
# ============================================================

IS_KAGGLE = Path("/kaggle/input").exists()
IS_COLAB = "google.colab" in str(get_ipython()) if "get_ipython" in globals() else False

if IS_KAGGLE:
    ENV_NAME = "kaggle"
elif IS_COLAB:
    ENV_NAME = "colab"
else:
    ENV_NAME = "local"

print("Entorno detectado:", ENV_NAME)

if IS_KAGGLE:
    INPUT_DIR = Path("/kaggle/input")
    WORKING_DIR = Path("/kaggle/working")
    PROJECT_DIR = WORKING_DIR / "hidden_gems_ai"

elif IS_COLAB:
    from google.colab import drive

    try:
        !fusermount -u /content/drive 2>/dev/null || true
        !rm -rf /content/drive

        drive.mount("/content/drive", force_remount=True, timeout_ms=120000)

        PROJECT_DIR = Path("/content/drive/MyDrive/hidden_gems_ai")

    except Exception as e:
        print("No se ha podido montar Drive. Se usará almacenamiento temporal.")
        print("Error:", e)

        PROJECT_DIR = Path("/content/hidden_gems_ai")

else:
    PROJECT_DIR = Path.cwd()

OUTPUT_DIR = PROJECT_DIR / "outputs" / "dish_normalization"
MENTIONS_DIR = OUTPUT_DIR / "mentions"
CATALOG_DIR = OUTPUT_DIR / "catalog"
ALIASES_DIR = OUTPUT_DIR / "aliases"
ARTIFACTS_DIR = OUTPUT_DIR / "artifacts"
SAMPLES_DIR = OUTPUT_DIR / "samples"

for path in [
    PROJECT_DIR,
    OUTPUT_DIR,
    MENTIONS_DIR,
    CATALOG_DIR,
    ALIASES_DIR,
    ARTIFACTS_DIR,
    SAMPLES_DIR,
]:
    path.mkdir(parents=True, exist_ok=True)

print("PROJECT_DIR:", PROJECT_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)

Entorno detectado: kaggle
PROJECT_DIR: /kaggle/working/hidden_gems_ai
OUTPUT_DIR: /kaggle/working/hidden_gems_ai/outputs/dish_normalization

In [7]:
# ============================================================
# 03. Diagnóstico de archivos disponibles
# ============================================================

if IS_KAGGLE:
    print("Archivos disponibles en /kaggle/input:")

    for dirname, _, filenames in os.walk("/kaggle/input"):
        for filename in filenames:
            print(os.path.join(dirname, filename))
else:
    print("No estás en Kaggle. Se buscarán archivos en el proyecto local.")

Archivos disponibles en /kaggle/input:
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_labels.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_bio_high_precision_with_negatives.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_detection_manual_review_sample_v2_150.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/transformer_sentiment_metrics.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/weak_dish_candidates_v2.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_inference_summary_full.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_detection_exploration_summary_v2.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/yelp_translation_gold_seed_300_es_ready_v1.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_model_v1_full.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_bio_smoke_test.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/weak_dish_candidate_frequencies_v2.csv
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_lexicon_seed_v1.csv
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/classic_model_metrics.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/yelp_food_reviews_corpus_sample_100k_lines.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full/config.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full/training_args.bin
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full/tokenizer.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full/tokenizer_config.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full/model.safetensors

In [8]:
# ============================================================
# 04. Localizar archivos necesarios
# ============================================================

MENTIONS_FILENAME = "dish_mentions_model_v1_full.jsonl"
INFERENCE_SUMMARY_FILENAME = "dish_ner_inference_summary_full.json"

def find_file(filename: str) -> Path:
    candidate_paths = []

    if IS_KAGGLE:
        candidate_paths.extend(list(Path("/kaggle/input").rglob(filename)))

    candidate_paths.extend(list(PROJECT_DIR.rglob(filename)))
    candidate_paths.extend(list(Path.cwd().rglob(filename)))

    candidate_paths = list(dict.fromkeys(candidate_paths))

    if not candidate_paths:
        raise FileNotFoundError(
            f"No se ha encontrado el archivo requerido: {filename}\n"
            "En Kaggle, asegúrate de haberlo añadido desde Add Data."
        )

    return candidate_paths[0]


MENTIONS_PATH = find_file(MENTIONS_FILENAME)

try:
    INFERENCE_SUMMARY_PATH = find_file(INFERENCE_SUMMARY_FILENAME)
except FileNotFoundError:
    INFERENCE_SUMMARY_PATH = None

print("MENTIONS_PATH:", MENTIONS_PATH)
print("INFERENCE_SUMMARY_PATH:", INFERENCE_SUMMARY_PATH)

MENTIONS_PATH: /kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_model_v1_full.jsonl
INFERENCE_SUMMARY_PATH: /kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_inference_summary_full.json

In [9]:
# ============================================================
# 05. Funciones auxiliares de carga y guardado
# ============================================================

def load_jsonl(path: Path) -> pd.DataFrame:
    records = []
    invalid_json_count = 0

    with path.open("r", encoding="utf-8") as f:
        for line in tqdm(f, desc=f"Leyendo {path.name}"):
            line = line.strip()

            if not line:
                continue

            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                invalid_json_count += 1

    print(f"Archivo: {path.name}")
    print(f"Registros cargados: {len(records):,}")
    print(f"Líneas JSON inválidas: {invalid_json_count:,}")

    return pd.DataFrame(records)


def make_json_safe(value):
    if isinstance(value, (np.integer,)):
        return int(value)

    if isinstance(value, (np.floating,)):
        if np.isnan(value):
            return None
        return float(value)

    if isinstance(value, (np.bool_,)):
        return bool(value)

    if isinstance(value, float) and np.isnan(value):
        return None

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, set):
        return sorted(list(value))

    return value


def save_jsonl(df_to_save: pd.DataFrame, path: Path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as f:
        for record in df_to_save.to_dict(orient="records"):
            clean_record = {
                str(key): make_json_safe(value)
                for key, value in record.items()
            }

            f.write(json.dumps(clean_record, ensure_ascii=False) + "\n")

    print(f"Guardado: {path} ({len(df_to_save):,} registros)")

In [10]:
# ============================================================
# 06. Cargar menciones detectadas por Dish NER v1
# ============================================================

mentions_raw_df = load_jsonl(MENTIONS_PATH)

print("Shape:", mentions_raw_df.shape)

print("\nColumnas:")
print(mentions_raw_df.columns.tolist())

display(mentions_raw_df.head(5))

if INFERENCE_SUMMARY_PATH is not None:
    with INFERENCE_SUMMARY_PATH.open("r", encoding="utf-8") as f:
        inference_summary = json.load(f)

    print("\nResumen de inferencia:")
    print(json.dumps(inference_summary, indent=2, ensure_ascii=False)[:3000])

Leyendo dish_mentions_model_v1_full.jsonl: 0it [00:00, ?it/s]

Archivo: dish_mentions_model_v1_full.jsonl
Registros cargados: 95,061
Líneas JSON inválidas: 0
Shape: (95061, 31)

Columnas:
['mention_id', 'corpus_document_id', 'review_id', 'business_id', 'business_name', 'city', 'state', 'split', 'rating_value', 'sentiment_label', 'language', 'source_system_code', 'source_dataset', 'dish_mention_text', 'dish_mention_normalized', 'start_char', 'end_char', 'start_token', 'end_token', 'token_count', 'confidence_mean', 'confidence_min', 'confidence_max', 'tokens', 'review_text', 'was_review_truncated', 'model_name', 'model_checkpoint', 'inference_run_name', 'human_review_status', 'normalization_status']

,mention_id,corpus_document_id,review_id,business_id,business_name,city,state,split,rating_value,sentiment_label,language,source_system_code,source_dataset,dish_mention_text,dish_mention_normalized,start_char,end_char,start_token,end_token,token_count,confidence_mean,confidence_min,confidence_max,tokens,review_text,was_review_truncated,model_name,model_checkpoint,inference_run_name,human_review_status,normalization_status
0,dish_mention_c6a233f28ab0ec50a4bf,yelp_94c5a64cecd4448d105e5c8a,saUsX_uimxRlCVr67Z4Jig,YjUWPpI6HXG530lwP-fb2A,Kettle Restaurant,Tucson,AZ,train,3.0,neutral,en,yelp_open_dataset,yelp_open_dataset,tamale,tamale,88,94,18,19,1,0.997417,0.997417,0.997417,[tamale],"Family diner. Had the buffet. Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon. All good. Lots of Mexican choices there. Also has a menu with breakfast served all day long. Friendly, attentive staff. Good place for a casual relaxed meal with ...",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,pending
1,dish_mention_370e33f760028e4e87a3,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,5.0,positive,en,yelp_open_dataset,yelp_open_dataset,lamb curry,lamb curry,54,64,12,14,2,0.996373,0.993416,0.999331,"[lamb, curry]","Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,pending
2,dish_mention_2c51d464763786d9fef2,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,5.0,positive,en,yelp_open_dataset,yelp_open_dataset,korma,korma,69,74,15,16,1,0.997466,0.997466,0.997466,[korma],"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,pending
3,dish_mention_6cfa246893992204e58a,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,5.0,positive,en,yelp_open_dataset,yelp_open_dataset,naan,naan,103,107,22,23,1,0.998627,0.998627,0.998627,[naan],"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,pending
4,dish_mention_e468cc705c76b7c9e84f,yelp_95095495afc3a77ce68723a2,Sx8TMOWLNuJBWer-0pcmoA,e4Vwtrqf-wpJfwesgvdgxQ,Melt,New Orleans,LA,train,4.0,positive,en,yelp_open_dataset,yelp_open_dataset,sandwiches,sandwiches,185,195,38,39,1,0.999447,0.999447,0.999447,[sandwiches],"Cute interior and owner (?) gave us tour of upcoming patio/rooftop area which will be great on beautiful days like today. Cheese curds were very good and very filling. Really like that sandwiches come w salad, esp after eating too many curds! Had the onion, gruyere, tomato sandwich. Wasn't too m...",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,pending

Resumen de inferencia:
{
  "run_name": "full",
  "fast_dev_run": false,
  "total_reviews_processed": 79270,
  "total_mentions_detected": 95061,
  "reviews_with_mentions": 42471,
  "reviews_without_mentions": 36799,
  "truncated_reviews": 8279,
  "avg_mentions_per_review": 1.1992052478869686,
  "avg_mentions_per_review_with_mentions": 2.2382566928021475,
  "confidence": {
    "mean": 0.975224027584393,
    "median": 0.9990728795528412,
    "min": 0.35621654987335205,
    "max": 0.9997578263282776
  },
  "top_mentions": {
    "pizza": 8682,
    "burger": 5756,
    "fries": 4848,
    "sushi": 4461,
    "shrimp": 4398,
    "tacos": 2912,
    "steak": 2789,
    "ice cream": 2371,
    "burgers": 2334,
    "wings": 2213,
    "sandwiches": 2034,
    "oysters": 1691,
    "pancakes": 1536,
    "crab": 1530,
    "taco": 1475,
    "donuts": 1419,
    "pho": 1219,
    "salmon": 1134,
    "ribs": 1093,
    "burrito": 993,
    "fried chicken": 933,
    "tuna": 889,
    "french toast": 862,
    "donut": 756,
    "brisket": 750,
    "lobster": 725,
    "mac and cheese": 707,
    "nachos": 678,
    "hummus": 630,
    "pulled pork": 600,
    "calamari": 598,
    "pad thai": 542,
    "fried rice": 538,
    "mussels": 517,
    "pancake": 498,
    "ramen": 455,
    "latte": 444,
    "waffle": 440,
    "waffles": 439,
    "oyster": 438,
    "dumplings": 432,
    "spring rolls": 412,
    "burritos": 403,
    "cheesecake": 392,
    "mashed potatoes": 377,
    "eggplant": 377,
    "omelette": 368,
    "french fries": 350,
    "naan": 345,
    "smoothie": 341
  },
  "split_counts_reviews": {
    "train": 63540,
    "test": 7881,
    "validation": 7849
  },
  "split_counts_mentions": {
    "train": 76050,
    "validation": 9564,
    "test": 9447
  },
  "sentiment_counts_mentions": {
    "positive": 64727,
    "negative": 16411,
    "neutral": 13923
  }
}

In [11]:
# ============================================================
# 07. Validación de columnas obligatorias
# ============================================================

required_cols = [
    "mention_id",
    "review_id",
    "business_id",
    "dish_mention_text",
    "dish_mention_normalized",
    "confidence_mean",
    "rating_value",
    "sentiment_label",
    "split",
    "review_text",
]

missing_cols = [
    col for col in required_cols
    if col not in mentions_raw_df.columns
]

if missing_cols:
    raise ValueError(f"Faltan columnas obligatorias: {missing_cols}")

print("Columnas obligatorias presentes.")

print("\nNulos principales:")
display(
    mentions_raw_df[required_cols]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print("\nDuplicados mention_id:")
print(mentions_raw_df["mention_id"].duplicated().sum())

Columnas obligatorias presentes.

Nulos principales:

mention_id                 0
review_id                  0
business_id                0
dish_mention_text          0
dish_mention_normalized    0
confidence_mean            0
rating_value               0
sentiment_label            0
split                      0
review_text                0
dtype: int64

Duplicados mention_id:
0

In [12]:
# ============================================================
# 08. Preparar dataframe base de menciones
# ============================================================

mentions_df = mentions_raw_df.copy()

mentions_df["mention_id"] = mentions_df["mention_id"].astype(str)
mentions_df["review_id"] = mentions_df["review_id"].astype(str)
mentions_df["business_id"] = mentions_df["business_id"].astype(str)

mentions_df["dish_mention_text"] = (
    mentions_df["dish_mention_text"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

mentions_df["dish_mention_normalized"] = (
    mentions_df["dish_mention_normalized"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.lower()
    .str.strip()
)

mentions_df["confidence_mean"] = pd.to_numeric(
    mentions_df["confidence_mean"],
    errors="coerce"
)

mentions_df["rating_value"] = pd.to_numeric(
    mentions_df["rating_value"],
    errors="coerce"
)

mentions_df["sentiment_label"] = (
    mentions_df["sentiment_label"]
    .astype(str)
    .str.lower()
    .str.strip()
)

mentions_df["split"] = (
    mentions_df["split"]
    .astype(str)
    .str.lower()
    .str.strip()
)

mentions_df["mention_token_count"] = pd.to_numeric(
    mentions_df.get("token_count", np.nan),
    errors="coerce"
)

mentions_df["mention_char_length"] = mentions_df["dish_mention_normalized"].str.len()

# Limpieza básica
before_count = len(mentions_df)

mentions_df = mentions_df[
    mentions_df["dish_mention_normalized"].notna()
    & (mentions_df["dish_mention_normalized"].str.len() > 0)
    & mentions_df["confidence_mean"].notna()
].copy()

after_count = len(mentions_df)

print("Menciones antes:", before_count)
print("Menciones después:", after_count)
print("Descartadas:", before_count - after_count)

display(mentions_df.head(5))

Menciones antes: 95061
Menciones después: 95061
Descartadas: 0

,mention_id,corpus_document_id,review_id,business_id,business_name,city,state,split,rating_value,sentiment_label,language,source_system_code,source_dataset,dish_mention_text,dish_mention_normalized,start_char,end_char,start_token,end_token,token_count,confidence_mean,confidence_min,confidence_max,tokens,review_text,was_review_truncated,model_name,model_checkpoint,inference_run_name,human_review_status,normalization_status,mention_token_count,mention_char_length
0,dish_mention_c6a233f28ab0ec50a4bf,yelp_94c5a64cecd4448d105e5c8a,saUsX_uimxRlCVr67Z4Jig,YjUWPpI6HXG530lwP-fb2A,Kettle Restaurant,Tucson,AZ,train,3.0,neutral,en,yelp_open_dataset,yelp_open_dataset,tamale,tamale,88,94,18,19,1,0.997417,0.997417,0.997417,[tamale],"Family diner. Had the buffet. Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon. All good. Lots of Mexican choices there. Also has a menu with breakfast served all day long. Friendly, attentive staff. Good place for a casual relaxed meal with ...",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,pending,1,6
1,dish_mention_370e33f760028e4e87a3,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,5.0,positive,en,yelp_open_dataset,yelp_open_dataset,lamb curry,lamb curry,54,64,12,14,2,0.996373,0.993416,0.999331,"[lamb, curry]","Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,pending,2,10
2,dish_mention_2c51d464763786d9fef2,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,5.0,positive,en,yelp_open_dataset,yelp_open_dataset,korma,korma,69,74,15,16,1,0.997466,0.997466,0.997466,[korma],"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,pending,1,5
3,dish_mention_6cfa246893992204e58a,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,5.0,positive,en,yelp_open_dataset,yelp_open_dataset,naan,naan,103,107,22,23,1,0.998627,0.998627,0.998627,[naan],"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,pending,1,4
4,dish_mention_e468cc705c76b7c9e84f,yelp_95095495afc3a77ce68723a2,Sx8TMOWLNuJBWer-0pcmoA,e4Vwtrqf-wpJfwesgvdgxQ,Melt,New Orleans,LA,train,4.0,positive,en,yelp_open_dataset,yelp_open_dataset,sandwiches,sandwiches,185,195,38,39,1,0.999447,0.999447,0.999447,[sandwiches],"Cute interior and owner (?) gave us tour of upcoming patio/rooftop area which will be great on beautiful days like today. Cheese curds were very good and very filling. Really like that sandwiches come w salad, esp after eating too many curds! Had the onion, gruyere, tomato sandwich. Wasn't too m...",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,pending,1,10

In [13]:
# ============================================================
# 09. QA inicial de menciones
# ============================================================

qa_initial = {
    "total_mentions": int(len(mentions_df)),
    "unique_reviews": int(mentions_df["review_id"].nunique()),
    "unique_businesses": int(mentions_df["business_id"].nunique()),
    "unique_surface_forms": int(mentions_df["dish_mention_normalized"].nunique()),
    "confidence": {
        "min": float(mentions_df["confidence_mean"].min()),
        "mean": float(mentions_df["confidence_mean"].mean()),
        "median": float(mentions_df["confidence_mean"].median()),
        "max": float(mentions_df["confidence_mean"].max()),
    },
    "split_counts": {
        str(k): int(v)
        for k, v in mentions_df["split"].value_counts().to_dict().items()
    },
    "sentiment_counts": {
        str(k): int(v)
        for k, v in mentions_df["sentiment_label"].value_counts().to_dict().items()
    },
}

print(json.dumps(qa_initial, indent=2, ensure_ascii=False))

print("\nTop menciones normalizadas:")
display(
    mentions_df["dish_mention_normalized"]
    .value_counts()
    .head(50)
    .reset_index()
    .rename(columns={
        "index": "dish_mention_normalized",
        "dish_mention_normalized": "count"
    })
)

print("\nDistribución de confianza:")
display(mentions_df["confidence_mean"].describe())

print("\nDistribución longitud de mención:")
display(mentions_df["mention_char_length"].describe())

{
  "total_mentions": 95061,
  "unique_reviews": 42471,
  "unique_businesses": 4091,
  "unique_surface_forms": 10258,
  "confidence": {
    "min": 0.35621654987335205,
    "mean": 0.975224027584393,
    "median": 0.9990728795528412,
    "max": 0.9997578263282776
  },
  "split_counts": {
    "train": 76050,
    "validation": 9564,
    "test": 9447
  },
  "sentiment_counts": {
    "positive": 64727,
    "negative": 16411,
    "neutral": 13923
  }
}

Top menciones normalizadas:

              count  count
0             pizza   8682
1            burger   5756
2             fries   4848
3             sushi   4461
4            shrimp   4398
5             tacos   2912
6             steak   2789
7         ice cream   2371
8           burgers   2334
9             wings   2213
10       sandwiches   2034
11          oysters   1691
12         pancakes   1536
13             crab   1530
14             taco   1475
15           donuts   1419
16              pho   1219
17           salmon   1134
18             ribs   1093
19          burrito    993
20    fried chicken    933
21             tuna    889
22     french toast    862
23            donut    756
24          brisket    750
25          lobster    725
26   mac and cheese    707
27           nachos    678
28           hummus    630
29      pulled pork    600
30         calamari    598
31         pad thai    542
32       fried rice    538
33          mussels    517
34          pancake    498
35            ramen    455
36            latte    444
37           waffle    440
38          waffles    439
39           oyster    438
40        dumplings    432
41     spring rolls    412
42         burritos    403
43       cheesecake    392
44         eggplant    377
45  mashed potatoes    377
46         omelette    368
47     french fries    350
48             naan    345
49         smoothie    341

Distribución de confianza:

count    95061.000000
mean         0.975224
std          0.079815
min          0.356217
25%          0.997282
50%          0.999073
75%          0.999427
max          0.999758
Name: confidence_mean, dtype: float64

Distribución longitud de mención:

count    95061.000000
mean         8.236301
std          5.736856
min          1.000000
25%          5.000000
50%          6.000000
75%          9.000000
max         62.000000
Name: mention_char_length, dtype: float64

## 1. Normalización textual inicial

En esta primera fase se aplican reglas ligeras para limpiar las menciones.

La idea no es perder información, sino crear columnas adicionales:

- `mention_clean`: texto limpio de la mención;
- `mention_canonical_rule`: primera propuesta de forma canónica;
- `normalization_flags`: señales sobre posibles problemas;
- `is_noise_candidate`: posible mención no útil;
- `normalization_confidence_hint`: confianza aproximada de la normalización.

La mención original siempre se conserva.

In [14]:
# ============================================================
# 10. Reglas de limpieza textual
# ============================================================

LEADING_DETERMINERS = {
    "the", "a", "an", "some", "my", "our", "your", "their", "this", "that"
}

TRAILING_NOISE_WORDS = {
    "and", "or", "but", "with", "without", "for", "of", "to", "from"
}

# Términos que pueden ser comida, pero no son plato útil para ranking.
CONTEXT_ONLY_TERMS = {
    "food",
    "dish",
    "dishes",
    "meal",
    "menu",
    "appetizer",
    "appetizers",
    "starter",
    "starters",
    "entree",
    "entrees",
    "dessert",
    "desserts",
    "breakfast",
    "brunch",
}

# Términos no deseados si el modelo los detecta por error.
CLEAR_NOISE_TERMS = {
    "service",
    "staff",
    "server",
    "waiter",
    "waitress",
    "place",
    "restaurant",
    "atmosphere",
    "ambiance",
    "price",
    "prices",
    "drink",
    "drinks",
    "water",
    "table",
    "bathroom",
    "parking",
}

def basic_clean_mention(text: str) -> str:
    if not isinstance(text, str):
        return ""

    text = text.lower().strip()
    text = re.sub(r"\s+", " ", text)
    text = text.strip(" -_:;,.!?()[]{}\"'")

    words = text.split()

    while words and words[0] in LEADING_DETERMINERS:
        words = words[1:]

    while words and words[-1] in TRAILING_NOISE_WORDS:
        words = words[:-1]

    text = " ".join(words)
    text = text.strip(" -_:;,.!?()[]{}\"'")

    return text


def singularize_simple_token(token: str) -> str:
    """
    Singularización ligera para inglés.
    No pretende ser lingüísticamente perfecta.
    Solo reduce plurales frecuentes para agrupar variantes básicas.
    """

    irregular = {
        "fries": "fries",
        "tacos": "taco",
        "burgers": "burger",
        "sandwiches": "sandwich",
        "pizzas": "pizza",
        "wings": "wing",
        "ribs": "rib",
        "oysters": "oyster",
        "pancakes": "pancake",
        "donuts": "donut",
        "burritos": "burrito",
        "dumplings": "dumpling",
        "waffles": "waffle",
        "enchiladas": "enchilada",
        "quesadillas": "quesadilla",
        "tamales": "tamale",
        "noodles": "noodle",
        "eggs": "egg",
        "mussels": "mussel",
        "clams": "clam",
    }

    if token in irregular:
        return irregular[token]

    if len(token) > 4 and token.endswith("ies"):
        return token[:-3] + "y"

    if len(token) > 4 and token.endswith("es"):
        return token[:-2]

    if len(token) > 3 and token.endswith("s") and not token.endswith("ss"):
        return token[:-1]

    return token


def singularize_phrase_simple(text: str) -> str:
    words = text.split()

    if not words:
        return text

    # Singularizamos principalmente el núcleo final.
    words[-1] = singularize_simple_token(words[-1])

    return " ".join(words)


def detect_noise_flags(text: str) -> list[str]:
    flags = []

    if not text:
        flags.append("empty_after_cleaning")
        return flags

    if text in CONTEXT_ONLY_TERMS:
        flags.append("context_only_term")

    if text in CLEAR_NOISE_TERMS:
        flags.append("clear_noise_term")

    words = text.split()

    if len(words) > 7:
        flags.append("very_long_mention")

    if len(text) <= 2:
        flags.append("too_short")

    if any(word in CLEAR_NOISE_TERMS for word in words):
        flags.append("contains_noise_word")

    if re.search(r"\d", text):
        flags.append("contains_digit")

    return flags


def build_rule_canonical(text: str) -> str:
    clean = basic_clean_mention(text)
    canonical = singularize_phrase_simple(clean)
    canonical = basic_clean_mention(canonical)

    return canonical

In [15]:
# ============================================================
# 11. Aplicar normalización textual inicial
# ============================================================

mentions_df["mention_clean"] = mentions_df["dish_mention_normalized"].apply(
    basic_clean_mention
)

mentions_df["mention_canonical_rule"] = mentions_df["mention_clean"].apply(
    build_rule_canonical
)

mentions_df["normalization_flags"] = mentions_df["mention_canonical_rule"].apply(
    detect_noise_flags
)

mentions_df["is_noise_candidate"] = mentions_df["normalization_flags"].apply(
    lambda flags: len(flags) > 0
)

def compute_normalization_confidence_hint(row) -> float:
    confidence = float(row["confidence_mean"])

    if row["is_noise_candidate"]:
        confidence -= 0.25

    if row["mention_canonical_rule"] != row["mention_clean"]:
        confidence -= 0.02

    confidence = max(0.0, min(1.0, confidence))

    return round(confidence, 4)


mentions_df["normalization_confidence_hint"] = mentions_df.apply(
    compute_normalization_confidence_hint,
    axis=1
)

print("Menciones:", len(mentions_df))
print("Noise candidates:", int(mentions_df["is_noise_candidate"].sum()))

display(
    mentions_df[
        [
            "dish_mention_text",
            "dish_mention_normalized",
            "mention_clean",
            "mention_canonical_rule",
            "confidence_mean",
            "normalization_flags",
            "normalization_confidence_hint",
        ]
    ].head(20)
)

print("\nTop canonical rule:")
display(
    mentions_df["mention_canonical_rule"]
    .value_counts()
    .head(50)
    .reset_index()
    .rename(columns={
        "index": "mention_canonical_rule",
        "mention_canonical_rule": "count"
    })
)

Menciones: 95061
Noise candidates: 758

,dish_mention_text,dish_mention_normalized,mention_clean,mention_canonical_rule,confidence_mean,normalization_flags,normalization_confidence_hint
0,tamale,tamale,tamale,tamale,0.997417,[],0.9974
1,lamb curry,lamb curry,lamb curry,lamb curry,0.996373,[],0.9964
2,korma,korma,korma,korma,0.997466,[],0.9975
3,naan,naan,naan,naan,0.998627,[],0.9986
4,sandwiches,sandwiches,sandwiches,sandwich,0.999447,[],0.9794
5,wings,wings,wings,wing,0.999090,[],0.9791
6,sushi,sushi,sushi,sushi,0.999515,[],0.9995
7,gnocchi with marinara,gnocchi with marinara,gnocchi with marinara,gnocchi with marinara,0.850407,[],0.8504
8,baked eggplant appetizer,baked eggplant appetizer,baked eggplant appetizer,baked eggplant appetizer,0.773023,[],0.7730
9,Sonoran Dog,sonoran dog,sonoran dog,sonoran dog,0.986196,[],0.9862
10,Sonoran Dogs,sonoran dogs,sonoran dogs,sonoran dog,0.984542,[],0.9645
11,waffle,waffle,waffle,waffle,0.998554,[],0.9986
12,home fries,home fries,home fries,home fries,0.999263,[],0.9993
13,latte,latte,latte,latte,0.999360,[],0.9994
14,pumpkin pie,pumpkin pie,pumpkin pie,pumpkin pie,0.998669,[],0.9987
15,frozen custard,frozen custard,frozen custard,frozen custard,0.998867,[],0.9989
16,burgers,burgers,burgers,burger,0.999447,[],0.9794
17,pizza,pizza,pizza,pizza,0.999582,[],0.9996
18,pizza,pizza,pizza,pizza,0.998652,[],0.9987
19,pizza,pizza,pizza,pizza,0.998444,[],0.9984

Top canonical rule:

             count  count
0            pizza   8751
1           burger   8095
2            fries   4848
3            sushi   4470
4             taco   4436
5           shrimp   4421
6            steak   2794
7        ice cream   2411
8             wing   2215
9            donut   2175
10          oyster   2129
11        sandwich   2127
12         pancake   2035
13            crab   1535
14         burrito   1405
15             pho   1225
16          salmon   1137
17             rib   1095
18   fried chicken    933
19            tuna    890
20          waffle    879
21    french toast    877
22           nacho    763
23         brisket    753
24         lobster    745
25  mac and cheese    707
26           hummu    630
27     pulled pork    601
28        calamari    600
29        pad thai    543
30      fried rice    539
31          mussel    538
32        dumpling    498
33           ramen    460
34           latte    446
35      quesadilla    434
36     spring roll    418
37          omelet    411
38       enchilada    407
39   mashed potato    400
40      cheesecake    392
41        eggplant    381
42        omelette    368
43            naan    359
44    french fries    350
45        smoothie    342
46         ravioli    328
47    cheeseburger    320
48        crab cak    291
49    chicken wing    280

In [16]:
# ============================================================
# 12. Crear tabla de surface forms
# ============================================================

surface_forms_df = (
    mentions_df
    .groupby(["dish_mention_normalized", "mention_clean", "mention_canonical_rule"], dropna=False)
    .agg(
        mention_count=("mention_id", "size"),
        review_count=("review_id", "nunique"),
        business_count=("business_id", "nunique"),
        avg_confidence=("confidence_mean", "mean"),
        min_confidence=("confidence_mean", "min"),
        max_confidence=("confidence_mean", "max"),
        avg_normalization_confidence=("normalization_confidence_hint", "mean"),
        avg_rating=("rating_value", "mean"),
        positive_mentions=("sentiment_label", lambda s: int((s == "positive").sum())),
        neutral_mentions=("sentiment_label", lambda s: int((s == "neutral").sum())),
        negative_mentions=("sentiment_label", lambda s: int((s == "negative").sum())),
        noise_candidate_count=("is_noise_candidate", "sum"),
    )
    .reset_index()
)

surface_forms_df["is_noise_candidate"] = (
    surface_forms_df["noise_candidate_count"] > 0
)

surface_forms_df = surface_forms_df.sort_values(
    ["mention_count", "avg_confidence"],
    ascending=[False, False]
).reset_index(drop=True)

print("Surface forms únicas:", len(surface_forms_df))

display(surface_forms_df.head(50))

Surface forms únicas: 10258

,dish_mention_normalized,mention_clean,mention_canonical_rule,mention_count,review_count,business_count,avg_confidence,min_confidence,max_confidence,avg_normalization_confidence,avg_rating,positive_mentions,neutral_mentions,negative_mentions,noise_candidate_count,is_noise_candidate
0,pizza,pizza,pizza,8682,4579,853,0.997651,0.510894,0.999738,0.997651,3.647662,5618,1140,1924,0,False
1,burger,burger,burger,5756,3458,718,0.992488,0.502620,0.999721,0.992488,3.660181,3612,1048,1096,0,False
2,fries,fries,fries,4848,3707,991,0.997342,0.508097,0.999758,0.997342,3.599216,2952,909,987,0,False
3,sushi,sushi,sushi,4461,2475,266,0.999148,0.881908,0.999708,0.999147,3.834566,3061,612,788,0,False
4,shrimp,shrimp,shrimp,4398,3259,865,0.995150,0.540861,0.999727,0.995149,3.903365,3153,549,696,0,False
5,tacos,tacos,taco,2912,2061,419,0.995019,0.504338,0.999729,0.975019,3.910027,2098,340,474,0,False
6,steak,steak,steak,2789,2101,829,0.994946,0.500823,0.999732,0.994948,3.558265,1658,441,690,0,False
7,ice cream,ice cream,ice cream,2371,1564,473,0.999370,0.978565,0.999612,0.999370,4.098271,1857,252,262,0,False
8,burgers,burgers,burger,2334,1871,506,0.999211,0.842032,0.999687,0.979211,3.746358,1548,413,373,0,False
9,wings,wings,wing,2213,1493,588,0.995358,0.526581,0.999702,0.975357,3.596927,1367,357,489,0,False
10,sandwiches,sandwiches,sandwich,2034,1781,798,0.998893,0.920336,0.999688,0.978894,4.019174,1537,253,244,0,False
11,oysters,oysters,oyster,1691,1129,170,0.996766,0.507655,0.999569,0.976766,4.060911,1294,213,184,0,False
12,pancakes,pancakes,pancake,1536,1054,233,0.995378,0.521068,0.999658,0.975379,3.941406,1110,235,191,0,False
13,crab,crab,crab,1530,1136,423,0.993790,0.545026,0.999705,0.993790,3.868627,1086,207,237,0,False
14,taco,taco,taco,1475,1066,336,0.995216,0.519741,0.999681,0.995216,3.530847,869,225,381,0,False
15,donuts,donuts,donut,1419,800,142,0.998370,0.528895,0.999715,0.978370,4.063425,1067,178,174,0,False
16,pho,pho,pho,1219,708,91,0.997328,0.660771,0.999648,0.997326,3.961444,895,172,152,0,False
17,salmon,salmon,salmon,1134,917,454,0.994066,0.556145,0.999693,0.994066,3.731041,753,166,215,0,False
18,ribs,ribs,rib,1093,836,320,0.995873,0.541326,0.999699,0.975871,3.698994,703,169,221,0,False
19,burrito,burrito,burrito,993,723,278,0.996071,0.552682,0.999734,0.996072,3.678751,641,134,218,0,False
20,fried chicken,fried chicken,fried chicken,933,781,247,0.998554,0.875684,0.999611,0.998555,3.857449,646,151,136,0,False
21,tuna,tuna,tuna,889,687,336,0.994037,0.602092,0.999696,0.994036,3.798650,605,123,161,0,False
22,french toast,french toast,french toast,862,707,203,0.999271,0.954830,0.999585,0.999270,4.149652,691,84,87,0,False
23,donut,donut,donut,756,458,83,0.995680,0.507568,0.999658,0.995680,4.056878,557,119,80,0,False
24,brisket,brisket,brisket,750,567,165,0.993665,0.500057,0.999628,0.993669,3.720000,486,109,155,0,False
25,lobster,lobster,lobster,725,526,202,0.995504,0.640900,0.999660,0.995504,3.790345,498,106,121,0,False
26,mac and cheese,mac and cheese,mac and cheese,707,584,217,0.998984,0.986915,0.999400,0.998985,3.855728,484,121,102,0,False
27,nachos,nachos,nacho,678,531,239,0.998142,0.915110,0.999552,0.978143,3.737463,447,103,128,0,False
28,hummus,hummus,hummu,630,503,179,0.996838,0.741851,0.999597,0.976839,4.022222,485,76,69,0,False
29,pulled pork,pulled pork,pulled pork,600,528,202,0.998262,0.879202,0.999587,0.998260,3.901667,423,96,81,0,False
30,calamari,calamari,calamari,598,483,239,0.996551,0.556643,0.999600,0.996551,3.735786,384,116,98,0,False
31,pad thai,pad thai,pad thai,542,412,102,0.999094,0.988685,0.999596,0.999098,3.749077,361,63,118,0,False
32,fried rice,fried rice,fried rice,538,450,222,0.999038,0.979397,0.999626,0.999038,3.587361,332,70,136,0,False
33,mussels,mussels,mussel,517,414,163,0.997707,0.850850,0.999541,0.977706,4.025145,392,69,56,0,False
34,pancake,pancake,pancake,498,404,112,0.996615,0.669083,0.999615,0.996615,3.915663,352,79,67,0,False
35,ramen,ramen,ramen,455,251,41,0.993462,0.682340,0.999647,0.993464,3.659341,278,84,93,0,False
36,latte,latte,latte,444,369,149,0.994690,0.511434,0.999567,0.994690,4.117117,334,65,45,0,False
37,waffle,waffle,waffle,440,327,151,0.997084,0.560835,0.999680,0.997082,3.743182,293,72,75,0,False
38,waffles,waffles,waffle,439,362,134,0.998370,0.860072,0.999665,0.978369,4.132118,343,61,35,0,False
39,oyster,oyster,oyster,438,364,100,0.993516,0.518754,0.999629,0.993517,4.136986,347,48,43,0,False
40,dumplings,dumplings,dumpling,432,351,162,0.989668,0.505833,0.999674,0.969668,3.907407,317,55,60,0,False
41,spring rolls,spring rolls,spring roll,412,358,140,0.999233,0.970169,0.999639,0.979232,3.980583,307,50,55,0,False
42,burritos,burritos,burrito,403,355,168,0.999346,0.981790,0.999728,0.979346,3.853598,283,51,69,0,False
43,cheesecake,cheesecake,cheesecake,392,308,163,0.995714,0.726788,0.999520,0.995716,3.964286,280,53,59,0,False
44,mashed potatoes,mashed potatoes,mashed potato,377,338,204,0.999169,0.997088,0.999547,0.979168,3.509284,216,65,96,0,False
45,eggplant,eggplant,eggplant,377,325,195,0.994589,0.553932,0.999532,0.994588,3.978780,284,55,38,0,False
46,omelette,omelette,omelette,368,312,150,0.994894,0.789886,0.999485,0.994896,3.801630,257,49,62,0,False
47,french fries,french fries,french fries,350,328,230,0.999346,0.998376,0.999637,0.999348,3.485714,195,70,85,0,False
48,naan,naan,naan,345,281,71,0.996431,0.935645,0.999431,0.996430,3.979710,259,37,49,0,False
49,smoothie,smoothie,smoothie,341,250,106,0.994032,0.607347,0.999396,0.994032,3.844575,237,46,58,0,False

In [17]:
# ============================================================
# 13. Crear catálogo semilla por regla
# ============================================================

# Excluimos ruido claro del catálogo, pero lo mantendremos en menciones con flags.
catalog_source_df = surface_forms_df[
    ~surface_forms_df["is_noise_candidate"]
    & surface_forms_df["mention_canonical_rule"].notna()
    & (surface_forms_df["mention_canonical_rule"].str.len() > 0)
].copy()

catalog_seed_df = (
    catalog_source_df
    .groupby("mention_canonical_rule", dropna=False)
    .agg(
        total_mentions=("mention_count", "sum"),
        total_reviews=("review_count", "sum"),
        total_businesses=("business_count", "sum"),
        surface_form_count=("dish_mention_normalized", "nunique"),
        avg_confidence=("avg_confidence", "mean"),
        avg_rating=("avg_rating", "mean"),
        positive_mentions=("positive_mentions", "sum"),
        neutral_mentions=("neutral_mentions", "sum"),
        negative_mentions=("negative_mentions", "sum"),
    )
    .reset_index()
    .rename(columns={"mention_canonical_rule": "canonical_dish_name"})
)

catalog_seed_df["dish_id"] = [
    f"dish_seed_{idx:06d}"
    for idx in range(1, len(catalog_seed_df) + 1)
]

catalog_seed_df["language"] = "en"
catalog_seed_df["catalog_version"] = "dish_catalog_seed_v1"
catalog_seed_df["normalization_method"] = "rule_based_v1"
catalog_seed_df["manual_review_status"] = "pending"

# Prioridad de revisión manual
def compute_manual_review_priority(row):
    if row["total_mentions"] >= 500:
        return 3
    if row["total_mentions"] >= 100:
        return 2
    return 1

catalog_seed_df["manual_review_priority"] = catalog_seed_df.apply(
    compute_manual_review_priority,
    axis=1
)

catalog_seed_df = catalog_seed_df.sort_values(
    ["total_mentions", "surface_form_count"],
    ascending=[False, False]
).reset_index(drop=True)

# Reordenar dish_id tras ordenar
catalog_seed_df["dish_id"] = [
    f"dish_seed_{idx:06d}"
    for idx in range(1, len(catalog_seed_df) + 1)
]

print("Platos canónicos iniciales:", len(catalog_seed_df))

display(catalog_seed_df.head(50))

Platos canónicos iniciales: 9401

,canonical_dish_name,total_mentions,total_reviews,total_businesses,surface_form_count,avg_confidence,avg_rating,positive_mentions,neutral_mentions,negative_mentions,dish_id,language,catalog_version,normalization_method,manual_review_status,manual_review_priority
0,pizza,8751,4640,900,4,0.972458,4.005505,5661,1154,1936,dish_seed_000001,en,dish_catalog_seed_v1,rule_based_v1,pending,3
1,burger,8095,5334,1229,4,0.960858,3.726635,5164,1462,1469,dish_seed_000002,en,dish_catalog_seed_v1,rule_based_v1,pending,3
2,fries,4848,3707,991,1,0.997342,3.599216,2952,909,987,dish_seed_000003,en,dish_catalog_seed_v1,rule_based_v1,pending,3
3,sushi,4470,2484,275,3,0.999205,3.349617,3067,613,790,dish_seed_000004,en,dish_catalog_seed_v1,rule_based_v1,pending,3
4,taco,4436,3165,789,3,0.995807,3.759203,3003,571,862,dish_seed_000005,en,dish_catalog_seed_v1,rule_based_v1,pending,3
5,shrimp,4421,3281,881,4,0.819895,4.130603,3167,553,701,dish_seed_000006,en,dish_catalog_seed_v1,rule_based_v1,pending,3
6,steak,2794,2106,834,3,0.897557,2.852755,1660,441,693,dish_seed_000007,en,dish_catalog_seed_v1,rule_based_v1,pending,3
7,ice cream,2411,1604,499,2,0.998952,4.049135,1888,255,268,dish_seed_000008,en,dish_catalog_seed_v1,rule_based_v1,pending,3
8,wing,2215,1495,590,3,0.817018,4.198976,1369,357,489,dish_seed_000009,en,dish_catalog_seed_v1,rule_based_v1,pending,3
9,donut,2175,1258,225,2,0.997025,4.060152,1624,297,254,dish_seed_000010,en,dish_catalog_seed_v1,rule_based_v1,pending,3
10,oyster,2129,1493,270,2,0.995141,4.098949,1641,261,227,dish_seed_000011,en,dish_catalog_seed_v1,rule_based_v1,pending,3
11,sandwich,2127,1870,882,4,0.752680,3.654794,1595,269,263,dish_seed_000012,en,dish_catalog_seed_v1,rule_based_v1,pending,3
12,pancake,2035,1459,346,3,0.996992,3.952356,1463,314,258,dish_seed_000013,en,dish_catalog_seed_v1,rule_based_v1,pending,3
13,crab,1535,1140,427,3,0.938591,3.956209,1090,208,237,dish_seed_000014,en,dish_catalog_seed_v1,rule_based_v1,pending,3
14,burrito,1405,1086,454,3,0.998225,3.770042,930,186,289,dish_seed_000015,en,dish_catalog_seed_v1,rule_based_v1,pending,3
15,pho,1225,714,96,3,0.996735,3.542703,898,174,153,dish_seed_000016,en,dish_catalog_seed_v1,rule_based_v1,pending,3
16,salmon,1137,920,457,3,0.942490,4.410347,756,166,215,dish_seed_000017,en,dish_catalog_seed_v1,rule_based_v1,pending,3
17,rib,1095,838,322,2,0.819390,3.849497,704,170,221,dish_seed_000018,en,dish_catalog_seed_v1,rule_based_v1,pending,3
18,fried chicken,933,781,247,1,0.998554,3.857449,646,151,136,dish_seed_000019,en,dish_catalog_seed_v1,rule_based_v1,pending,3
19,tuna,890,688,337,2,0.976428,3.399325,605,124,161,dish_seed_000020,en,dish_catalog_seed_v1,rule_based_v1,pending,3
20,waffle,879,689,285,2,0.997727,3.937650,636,133,110,dish_seed_000021,en,dish_catalog_seed_v1,rule_based_v1,pending,3
21,french toast,877,721,213,3,0.942647,4.073694,704,86,87,dish_seed_000022,en,dish_catalog_seed_v1,rule_based_v1,pending,3
22,nacho,763,610,310,4,0.990720,3.934677,493,117,153,dish_seed_000023,en,dish_catalog_seed_v1,rule_based_v1,pending,3
23,brisket,753,570,168,2,0.996481,4.193333,489,109,155,dish_seed_000024,en,dish_catalog_seed_v1,rule_based_v1,pending,3
24,lobster,745,544,209,2,0.919894,3.920172,513,108,124,dish_seed_000025,en,dish_catalog_seed_v1,rule_based_v1,pending,3
25,mac and cheese,707,584,217,1,0.998984,3.855728,484,121,102,dish_seed_000026,en,dish_catalog_seed_v1,rule_based_v1,pending,3
26,hummu,630,503,179,1,0.996838,4.022222,485,76,69,dish_seed_000027,en,dish_catalog_seed_v1,rule_based_v1,pending,3
27,pulled pork,601,529,203,2,0.875620,3.950833,424,96,81,dish_seed_000028,en,dish_catalog_seed_v1,rule_based_v1,pending,3
28,calamari,600,484,240,2,0.997774,2.867893,384,116,100,dish_seed_000029,en,dish_catalog_seed_v1,rule_based_v1,pending,3
29,pad thai,543,413,103,2,0.999198,3.874539,362,63,118,dish_seed_000030,en,dish_catalog_seed_v1,rule_based_v1,pending,3
30,fried rice,539,451,223,2,0.998879,4.293680,333,70,136,dish_seed_000031,en,dish_catalog_seed_v1,rule_based_v1,pending,3
31,mussel,538,435,184,3,0.998086,4.208382,404,72,62,dish_seed_000032,en,dish_catalog_seed_v1,rule_based_v1,pending,3
32,dumpling,498,407,204,4,0.940333,3.945602,366,64,68,dish_seed_000033,en,dish_catalog_seed_v1,rule_based_v1,pending,2
33,ramen,460,255,45,2,0.994165,3.729670,282,84,94,dish_seed_000034,en,dish_catalog_seed_v1,rule_based_v1,pending,2
34,latte,446,371,151,2,0.996788,4.308559,336,65,45,dish_seed_000035,en,dish_catalog_seed_v1,rule_based_v1,pending,2
35,quesadilla,434,370,237,3,0.996334,3.864796,278,61,95,dish_seed_000036,en,dish_catalog_seed_v1,rule_based_v1,pending,2
36,spring roll,418,364,146,2,0.902988,3.823625,310,52,56,dish_seed_000037,en,dish_catalog_seed_v1,rule_based_v1,pending,2
37,omelet,411,362,209,3,0.941888,3.902753,277,73,61,dish_seed_000038,en,dish_catalog_seed_v1,rule_based_v1,pending,2
38,enchilada,407,350,161,3,0.995405,3.988880,251,57,99,dish_seed_000039,en,dish_catalog_seed_v1,rule_based_v1,pending,2
39,mashed potato,400,359,225,3,0.993145,3.812618,231,66,103,dish_seed_000040,en,dish_catalog_seed_v1,rule_based_v1,pending,2
40,cheesecake,392,308,163,1,0.995714,3.964286,280,53,59,dish_seed_000041,en,dish_catalog_seed_v1,rule_based_v1,pending,2
41,eggplant,381,329,199,4,0.929995,4.619695,288,55,38,dish_seed_000042,en,dish_catalog_seed_v1,rule_based_v1,pending,2
42,omelette,368,312,150,1,0.994894,3.801630,257,49,62,dish_seed_000043,en,dish_catalog_seed_v1,rule_based_v1,pending,2
43,naan,359,293,82,3,0.996336,3.104348,264,39,56,dish_seed_000044,en,dish_catalog_seed_v1,rule_based_v1,pending,2
44,french fries,350,328,230,1,0.999346,3.485714,195,70,85,dish_seed_000045,en,dish_catalog_seed_v1,rule_based_v1,pending,2
45,smoothie,342,251,107,2,0.994860,4.422287,238,46,58,dish_seed_000046,en,dish_catalog_seed_v1,rule_based_v1,pending,2
46,ravioli,328,271,133,3,0.979965,3.073728,231,44,53,dish_seed_000047,en,dish_catalog_seed_v1,rule_based_v1,pending,2
47,cheeseburger,320,289,195,2,0.995575,3.550858,184,63,73,dish_seed_000048,en,dish_catalog_seed_v1,rule_based_v1,pending,2
48,crab cak,291,253,136,1,0.998895,3.735395,190,56,45,dish_seed_000049,en,dish_catalog_seed_v1,rule_based_v1,pending,2
49,chicken wing,280,245,186,2,0.898259,2.947273,185,43,52,dish_seed_000050,en,dish_catalog_seed_v1,rule_based_v1,pending,2

In [18]:
# ============================================================
# 14. Crear aliases semilla
# ============================================================

dish_id_map = dict(
    zip(
        catalog_seed_df["canonical_dish_name"],
        catalog_seed_df["dish_id"]
    )
)

aliases_seed_df = surface_forms_df.copy()

aliases_seed_df = aliases_seed_df[
    aliases_seed_df["mention_canonical_rule"].isin(dish_id_map)
].copy()

aliases_seed_df["dish_id"] = aliases_seed_df["mention_canonical_rule"].map(dish_id_map)
aliases_seed_df["alias_text"] = aliases_seed_df["dish_mention_normalized"]
aliases_seed_df["canonical_dish_name"] = aliases_seed_df["mention_canonical_rule"]
aliases_seed_df["alias_language"] = "en"
aliases_seed_df["alias_source"] = "model_mentions_rule_based_v1"
aliases_seed_df["alias_type"] = np.where(
    aliases_seed_df["alias_text"] == aliases_seed_df["canonical_dish_name"],
    "canonical",
    "surface_variant"
)

aliases_seed_df["manual_review_status"] = "pending"

aliases_seed_df = aliases_seed_df[
    [
        "dish_id",
        "canonical_dish_name",
        "alias_text",
        "alias_type",
        "alias_language",
        "alias_source",
        "mention_count",
        "review_count",
        "business_count",
        "avg_confidence",
        "avg_normalization_confidence",
        "manual_review_status",
    ]
].copy()

aliases_seed_df = aliases_seed_df.sort_values(
    ["mention_count", "avg_confidence"],
    ascending=[False, False]
).reset_index(drop=True)

print("Aliases semilla:", len(aliases_seed_df))

display(aliases_seed_df.head(50))

Aliases semilla: 9692

,dish_id,canonical_dish_name,alias_text,alias_type,alias_language,alias_source,mention_count,review_count,business_count,avg_confidence,avg_normalization_confidence,manual_review_status
0,dish_seed_000001,pizza,pizza,canonical,en,model_mentions_rule_based_v1,8682,4579,853,0.997651,0.997651,pending
1,dish_seed_000002,burger,burger,canonical,en,model_mentions_rule_based_v1,5756,3458,718,0.992488,0.992488,pending
2,dish_seed_000003,fries,fries,canonical,en,model_mentions_rule_based_v1,4848,3707,991,0.997342,0.997342,pending
3,dish_seed_000004,sushi,sushi,canonical,en,model_mentions_rule_based_v1,4461,2475,266,0.999148,0.999147,pending
4,dish_seed_000006,shrimp,shrimp,canonical,en,model_mentions_rule_based_v1,4398,3259,865,0.995150,0.995149,pending
5,dish_seed_000005,taco,tacos,surface_variant,en,model_mentions_rule_based_v1,2912,2061,419,0.995019,0.975019,pending
6,dish_seed_000007,steak,steak,canonical,en,model_mentions_rule_based_v1,2789,2101,829,0.994946,0.994948,pending
7,dish_seed_000008,ice cream,ice cream,canonical,en,model_mentions_rule_based_v1,2371,1564,473,0.999370,0.999370,pending
8,dish_seed_000002,burger,burgers,surface_variant,en,model_mentions_rule_based_v1,2334,1871,506,0.999211,0.979211,pending
9,dish_seed_000009,wing,wings,surface_variant,en,model_mentions_rule_based_v1,2213,1493,588,0.995358,0.975357,pending
10,dish_seed_000012,sandwich,sandwiches,surface_variant,en,model_mentions_rule_based_v1,2034,1781,798,0.998893,0.978894,pending
11,dish_seed_000011,oyster,oysters,surface_variant,en,model_mentions_rule_based_v1,1691,1129,170,0.996766,0.976766,pending
12,dish_seed_000013,pancake,pancakes,surface_variant,en,model_mentions_rule_based_v1,1536,1054,233,0.995378,0.975379,pending
13,dish_seed_000014,crab,crab,canonical,en,model_mentions_rule_based_v1,1530,1136,423,0.993790,0.993790,pending
14,dish_seed_000005,taco,taco,canonical,en,model_mentions_rule_based_v1,1475,1066,336,0.995216,0.995216,pending
15,dish_seed_000010,donut,donuts,surface_variant,en,model_mentions_rule_based_v1,1419,800,142,0.998370,0.978370,pending
16,dish_seed_000016,pho,pho,canonical,en,model_mentions_rule_based_v1,1219,708,91,0.997328,0.997326,pending
17,dish_seed_000017,salmon,salmon,canonical,en,model_mentions_rule_based_v1,1134,917,454,0.994066,0.994066,pending
18,dish_seed_000018,rib,ribs,surface_variant,en,model_mentions_rule_based_v1,1093,836,320,0.995873,0.975871,pending
19,dish_seed_000015,burrito,burrito,canonical,en,model_mentions_rule_based_v1,993,723,278,0.996071,0.996072,pending
20,dish_seed_000019,fried chicken,fried chicken,canonical,en,model_mentions_rule_based_v1,933,781,247,0.998554,0.998555,pending
21,dish_seed_000020,tuna,tuna,canonical,en,model_mentions_rule_based_v1,889,687,336,0.994037,0.994036,pending
22,dish_seed_000022,french toast,french toast,canonical,en,model_mentions_rule_based_v1,862,707,203,0.999271,0.999270,pending
23,dish_seed_000010,donut,donut,canonical,en,model_mentions_rule_based_v1,756,458,83,0.995680,0.995680,pending
24,dish_seed_000024,brisket,brisket,canonical,en,model_mentions_rule_based_v1,750,567,165,0.993665,0.993669,pending
25,dish_seed_000025,lobster,lobster,canonical,en,model_mentions_rule_based_v1,725,526,202,0.995504,0.995504,pending
26,dish_seed_000026,mac and cheese,mac and cheese,canonical,en,model_mentions_rule_based_v1,707,584,217,0.998984,0.998985,pending
27,dish_seed_000023,nacho,nachos,surface_variant,en,model_mentions_rule_based_v1,678,531,239,0.998142,0.978143,pending
28,dish_seed_000027,hummu,hummus,surface_variant,en,model_mentions_rule_based_v1,630,503,179,0.996838,0.976839,pending
29,dish_seed_000028,pulled pork,pulled pork,canonical,en,model_mentions_rule_based_v1,600,528,202,0.998262,0.998260,pending
30,dish_seed_000029,calamari,calamari,canonical,en,model_mentions_rule_based_v1,598,483,239,0.996551,0.996551,pending
31,dish_seed_000030,pad thai,pad thai,canonical,en,model_mentions_rule_based_v1,542,412,102,0.999094,0.999098,pending
32,dish_seed_000031,fried rice,fried rice,canonical,en,model_mentions_rule_based_v1,538,450,222,0.999038,0.999038,pending
33,dish_seed_000032,mussel,mussels,surface_variant,en,model_mentions_rule_based_v1,517,414,163,0.997707,0.977706,pending
34,dish_seed_000013,pancake,pancake,canonical,en,model_mentions_rule_based_v1,498,404,112,0.996615,0.996615,pending
35,dish_seed_000034,ramen,ramen,canonical,en,model_mentions_rule_based_v1,455,251,41,0.993462,0.993464,pending
36,dish_seed_000035,latte,latte,canonical,en,model_mentions_rule_based_v1,444,369,149,0.994690,0.994690,pending
37,dish_seed_000021,waffle,waffle,canonical,en,model_mentions_rule_based_v1,440,327,151,0.997084,0.997082,pending
38,dish_seed_000021,waffle,waffles,surface_variant,en,model_mentions_rule_based_v1,439,362,134,0.998370,0.978369,pending
39,dish_seed_000011,oyster,oyster,canonical,en,model_mentions_rule_based_v1,438,364,100,0.993516,0.993517,pending
40,dish_seed_000033,dumpling,dumplings,surface_variant,en,model_mentions_rule_based_v1,432,351,162,0.989668,0.969668,pending
41,dish_seed_000037,spring roll,spring rolls,surface_variant,en,model_mentions_rule_based_v1,412,358,140,0.999233,0.979232,pending
42,dish_seed_000015,burrito,burritos,surface_variant,en,model_mentions_rule_based_v1,403,355,168,0.999346,0.979346,pending
43,dish_seed_000041,cheesecake,cheesecake,canonical,en,model_mentions_rule_based_v1,392,308,163,0.995714,0.995716,pending
44,dish_seed_000040,mashed potato,mashed potatoes,surface_variant,en,model_mentions_rule_based_v1,377,338,204,0.999169,0.979168,pending
45,dish_seed_000042,eggplant,eggplant,canonical,en,model_mentions_rule_based_v1,377,325,195,0.994589,0.994588,pending
46,dish_seed_000043,omelette,omelette,canonical,en,model_mentions_rule_based_v1,368,312,150,0.994894,0.994896,pending
47,dish_seed_000045,french fries,french fries,canonical,en,model_mentions_rule_based_v1,350,328,230,0.999346,0.999348,pending
48,dish_seed_000044,naan,naan,canonical,en,model_mentions_rule_based_v1,345,281,71,0.996431,0.996430,pending
49,dish_seed_000046,smoothie,smoothie,canonical,en,model_mentions_rule_based_v1,341,250,106,0.994032,0.994032,pending

In [19]:
# ============================================================
# 15. Añadir dish_id y canonical_dish_name a cada mención
# ============================================================

mentions_normalized_df = mentions_df.copy()

mentions_normalized_df["canonical_dish_name"] = mentions_normalized_df["mention_canonical_rule"]
mentions_normalized_df["dish_id"] = mentions_normalized_df["canonical_dish_name"].map(dish_id_map)

mentions_normalized_df["normalization_status"] = np.where(
    mentions_normalized_df["dish_id"].notna(),
    "normalized_rule_based_v1",
    "excluded_or_pending_review"
)

mentions_normalized_df["normalization_method"] = np.where(
    mentions_normalized_df["dish_id"].notna(),
    "rule_based_v1",
    "none"
)

print("Menciones normalizadas:", int(mentions_normalized_df["dish_id"].notna().sum()))
print("Menciones pendientes/excluidas:", int(mentions_normalized_df["dish_id"].isna().sum()))

display(
    mentions_normalized_df[
        [
            "dish_mention_text",
            "dish_mention_normalized",
            "canonical_dish_name",
            "dish_id",
            "normalization_status",
            "confidence_mean",
            "normalization_flags",
            "review_id",
            "business_id",
        ]
    ].head(20)
)

Menciones normalizadas: 94303
Menciones pendientes/excluidas: 758

,dish_mention_text,dish_mention_normalized,canonical_dish_name,dish_id,normalization_status,confidence_mean,normalization_flags,review_id,business_id
0,tamale,tamale,tamale,dish_seed_000063,normalized_rule_based_v1,0.997417,[],saUsX_uimxRlCVr67Z4Jig,YjUWPpI6HXG530lwP-fb2A
1,lamb curry,lamb curry,lamb curry,dish_seed_000208,normalized_rule_based_v1,0.996373,[],AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA
2,korma,korma,korma,dish_seed_000078,normalized_rule_based_v1,0.997466,[],AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA
3,naan,naan,naan,dish_seed_000044,normalized_rule_based_v1,0.998627,[],AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA
4,sandwiches,sandwiches,sandwich,dish_seed_000012,normalized_rule_based_v1,0.999447,[],Sx8TMOWLNuJBWer-0pcmoA,e4Vwtrqf-wpJfwesgvdgxQ
5,wings,wings,wing,dish_seed_000009,normalized_rule_based_v1,0.999090,[],_ZeMknuYdlQcUqng_Im3yg,LHSTtnW3YHCeUkRDGyJOyw
6,sushi,sushi,sushi,dish_seed_000004,normalized_rule_based_v1,0.999515,[],pUycOfUwM8vqX7KjRRhUEA,gebiRewfieSdtt17PTW6Zg
7,gnocchi with marinara,gnocchi with marinara,gnocchi with marinara,dish_seed_004624,normalized_rule_based_v1,0.850407,[],8JFGBuHMoiNDyfcxuWNtrA,RZtGWDLCAtuipwaZ-UfjmQ
8,baked eggplant appetizer,baked eggplant appetizer,baked eggplant appetizer,dish_seed_001796,normalized_rule_based_v1,0.773023,[],8JFGBuHMoiNDyfcxuWNtrA,RZtGWDLCAtuipwaZ-UfjmQ
9,Sonoran Dog,sonoran dog,sonoran dog,dish_seed_000092,normalized_rule_based_v1,0.986196,[],UBp0zWyH60Hmw6Fsasei7w,otQS34_MymijPTdNBoBdCw
10,Sonoran Dogs,sonoran dogs,sonoran dog,dish_seed_000092,normalized_rule_based_v1,0.984542,[],UBp0zWyH60Hmw6Fsasei7w,otQS34_MymijPTdNBoBdCw
11,waffle,waffle,waffle,dish_seed_000021,normalized_rule_based_v1,0.998554,[],OAhBYw8IQ6wlfw1owXWRWw,BVndHaLihEYbr76Z0CMEGw
12,home fries,home fries,home fries,dish_seed_000065,normalized_rule_based_v1,0.999263,[],OAhBYw8IQ6wlfw1owXWRWw,BVndHaLihEYbr76Z0CMEGw
13,latte,latte,latte,dish_seed_000035,normalized_rule_based_v1,0.999360,[],Xs8Z8lmKkosqW5mw_sVAoA,eFvzHawVJofxSnD7TgbZtg
14,pumpkin pie,pumpkin pie,pumpkin pie,dish_seed_000155,normalized_rule_based_v1,0.998669,[],vBK79c3_1Ff_oqkh5VpfGg,nRKndeZLQ3eDL10UMwS2rQ
15,frozen custard,frozen custard,frozen custard,dish_seed_000069,normalized_rule_based_v1,0.998867,[],vBK79c3_1Ff_oqkh5VpfGg,nRKndeZLQ3eDL10UMwS2rQ
16,burgers,burgers,burger,dish_seed_000002,normalized_rule_based_v1,0.999447,[],ZVvhc3Go7v5I8XTiVoWmqQ,ut6fi2W2YaipNOqvi7e0jw
17,pizza,pizza,pizza,dish_seed_000001,normalized_rule_based_v1,0.999582,[],ZVvhc3Go7v5I8XTiVoWmqQ,ut6fi2W2YaipNOqvi7e0jw
18,pizza,pizza,pizza,dish_seed_000001,normalized_rule_based_v1,0.998652,[],ZVvhc3Go7v5I8XTiVoWmqQ,ut6fi2W2YaipNOqvi7e0jw
19,pizza,pizza,pizza,dish_seed_000001,normalized_rule_based_v1,0.998444,[],ZVvhc3Go7v5I8XTiVoWmqQ,ut6fi2W2YaipNOqvi7e0jw

In [20]:
# ============================================================
# 16. Guardar outputs v1
# ============================================================

mentions_normalized_path = MENTIONS_DIR / "dish_mentions_normalized_v1.jsonl"
surface_forms_path = ARTIFACTS_DIR / "dish_surface_forms_v1.csv"
catalog_seed_path = CATALOG_DIR / "dish_catalog_seed_v1.csv"
aliases_seed_path = ALIASES_DIR / "dish_aliases_seed_v1.csv"
summary_path = ARTIFACTS_DIR / "dish_normalization_summary_v1.json"

save_jsonl(mentions_normalized_df, mentions_normalized_path)
surface_forms_df.to_csv(surface_forms_path, index=False)
catalog_seed_df.to_csv(catalog_seed_path, index=False)
aliases_seed_df.to_csv(aliases_seed_path, index=False)

normalization_summary = {
    "notebook": "08_dish_normalization_and_catalog_builder",
    "version": "v1_rule_based_seed",
    "source_mentions_path": str(MENTIONS_PATH),
    "input": qa_initial,
    "outputs": {
        "mentions_normalized": str(mentions_normalized_path),
        "surface_forms": str(surface_forms_path),
        "catalog_seed": str(catalog_seed_path),
        "aliases_seed": str(aliases_seed_path),
    },
    "normalization": {
        "total_mentions": int(len(mentions_normalized_df)),
        "normalized_mentions": int(mentions_normalized_df["dish_id"].notna().sum()),
        "pending_or_excluded_mentions": int(mentions_normalized_df["dish_id"].isna().sum()),
        "surface_forms": int(len(surface_forms_df)),
        "canonical_dishes_seed": int(len(catalog_seed_df)),
        "aliases_seed": int(len(aliases_seed_df)),
        "noise_candidate_mentions": int(mentions_normalized_df["is_noise_candidate"].sum()),
    },
    "top_canonical_dishes": (
        catalog_seed_df
        .head(50)
        .to_dict(orient="records")
    ),
}

with summary_path.open("w", encoding="utf-8") as f:
    json.dump(normalization_summary, f, indent=2, ensure_ascii=False)

print("Resumen guardado en:")
print(summary_path)

print(json.dumps(normalization_summary, indent=2, ensure_ascii=False)[:5000])

Guardado: /kaggle/working/hidden_gems_ai/outputs/dish_normalization/mentions/dish_mentions_normalized_v1.jsonl (95,061 registros)
Resumen guardado en:
/kaggle/working/hidden_gems_ai/outputs/dish_normalization/artifacts/dish_normalization_summary_v1.json
{
  "notebook": "08_dish_normalization_and_catalog_builder",
  "version": "v1_rule_based_seed",
  "source_mentions_path": "/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_model_v1_full.jsonl",
  "input": {
    "total_mentions": 95061,
    "unique_reviews": 42471,
    "unique_businesses": 4091,
    "unique_surface_forms": 10258,
    "confidence": {
      "min": 0.35621654987335205,
      "mean": 0.975224027584393,
      "median": 0.9990728795528412,
      "max": 0.9997578263282776
    },
    "split_counts": {
      "train": 76050,
      "validation": 9564,
      "test": 9447
    },
    "sentiment_counts": {
      "positive": 64727,
      "negative": 16411,
      "neutral": 13923
    }
  },
  "outputs": {
    "mentions_normalized": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/mentions/dish_mentions_normalized_v1.jsonl",
    "surface_forms": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/artifacts/dish_surface_forms_v1.csv",
    "catalog_seed": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/catalog/dish_catalog_seed_v1.csv",
    "aliases_seed": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/aliases/dish_aliases_seed_v1.csv"
  },
  "normalization": {
    "total_mentions": 95061,
    "normalized_mentions": 94303,
    "pending_or_excluded_mentions": 758,
    "surface_forms": 10258,
    "canonical_dishes_seed": 9401,
    "aliases_seed": 9692,
    "noise_candidate_mentions": 758
  },
  "top_canonical_dishes": [
    {
      "canonical_dish_name": "pizza",
      "total_mentions": 8751,
      "total_reviews": 4640,
      "total_businesses": 900,
      "surface_form_count": 4,
      "avg_confidence": 0.9724581097010846,
      "avg_rating": 4.005505200857654,
      "positive_mentions": 5661,
      "neutral_mentions": 1154,
      "negative_mentions": 1936,
      "dish_id": "dish_seed_000001",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v1",
      "normalization_method": "rule_based_v1",
      "manual_review_status": "pending",
      "manual_review_priority": 3
    },
    {
      "canonical_dish_name": "burger",
      "total_mentions": 8095,
      "total_reviews": 5334,
      "total_businesses": 1229,
      "surface_form_count": 4,
      "avg_confidence": 0.9608580466666912,
      "avg_rating": 3.7266347161011675,
      "positive_mentions": 5164,
      "neutral_mentions": 1462,
      "negative_mentions": 1469,
      "dish_id": "dish_seed_000002",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v1",
      "normalization_method": "rule_based_v1",
      "manual_review_status": "pending",
      "manual_review_priority": 3
    },
    {
      "canonical_dish_name": "fries",
      "total_mentions": 4848,
      "total_reviews": 3707,
      "total_businesses": 991,
      "surface_form_count": 1,
      "avg_confidence": 0.997342479086355,
      "avg_rating": 3.5992161716171616,
      "positive_mentions": 2952,
      "neutral_mentions": 909,
      "negative_mentions": 987,
      "dish_id": "dish_seed_000003",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v1",
      "normalization_method": "rule_based_v1",
      "manual_review_status": "pending",
      "manual_review_priority": 3
    },
    {
      "canonical_dish_name": "sushi",
      "total_mentions": 4470,
      "total_reviews": 2484,
      "total_businesses": 275,
      "surface_form_count": 3,
      "avg_confidence": 0.9992045097301906,
      "avg_rating": 3.349617318346303,
      "positive_mentions": 3067,
      "neutral_mentions": 613,
      "negative_mentions": 790,
      "dish_id": "dish_seed_000004",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v1",
      "normalization_method": "rule_based_v1",
      "manual_review_status": "pending",
      "manual_review_priority": 3
    },
    {
      "canonical_dish_name": "taco",
      "total_mentions": 4436,
      "total_reviews": 3165,
      "total_businesses": 789,
      "surface_form_count": 3,
      "avg_confidence": 0.9958066058306333,
      "avg_rating": 3.759203208010714,
      "positive_mentions": 3003,
      "neutral_mentions": 571,
      "negative_mentions": 862,
      "dish_id": "dish_seed_000005",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v1",
      "normalization_method": "rule_based_v1",
      "manual_review_status": "pending",
      "manual_review_priority": 3
    },
    {
      "canonical_dish_name": "shrimp",
      "total_mentions": 4421,
      "total_reviews": 3281,
      "total_businesses": 881,
      "surface_form_count": 4,
      "avg_confidence": 0.8198946862580336,
      "avg_rating": 4.13060319625804,
      "positive_mentions": 3167,
      "neutral_mentions": 553,
      "negative_mentions": 701,
      "dish_id": "dish_seed_000006",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v1",
      "normalization_method": "rule_based_v1",
      "manual_review_status": "pending",
      "manual_review_priority":

## 2. Refinamiento de normalización v2

La versión v1 ha generado una primera base trazable, pero algunas reglas de singularización han producido formas poco naturales o incorrectas.

Ejemplos detectados:

- `hummus` → `hummu`
- `crab cakes` → `crab cak`
- `wings` → `wing`
- `ribs` → `rib`
- `nachos` → `nacho`
- `mashed potatoes` → `mashed potato`

En este bloque se crea una versión v2 con:

1. correcciones manuales controladas;
2. aliases más consistentes;
3. formas canónicas más naturales;
4. detección de duplicados potenciales;
5. generación de nuevos artefactos v2.

In [21]:
# ============================================================
# 17. Reglas de corrección v2
# ============================================================

# Correcciones exactas sobre canonical_dish_name generado por v1.
CANONICAL_OVERRIDES_V2 = {
    # Errores claros de singularización
    "hummu": "hummus",
    "crab cak": "crab cakes",

    # Plurales naturales como platos
    "wing": "wings",
    "rib": "ribs",
    "nacho": "nachos",
    "mashed potato": "mashed potatoes",
    "spring roll": "spring rolls",
    "dumpling": "dumplings",
    "mussel": "mussels",
    "clam": "clams",
    "oyster": "oysters",

    # Variantes ortográficas
    "omelette": "omelet",
    "doughnut": "donut",
    "doughnuts": "donut",

    # Agrupaciones evidentes
    "french fries": "fries",
    "home fries": "fries",

    # Tacos suele funcionar mejor como familia plural en ranking
    "taco": "tacos",
}

# Correcciones sobre surface forms concretas.
SURFACE_FORM_OVERRIDES_V2 = {
    "hummus": "hummus",
    "crab cakes": "crab cakes",
    "crab cake": "crab cakes",
    "wings": "wings",
    "chicken wings": "chicken wings",
    "ribs": "ribs",
    "nachos": "nachos",
    "mashed potatoes": "mashed potatoes",
    "french fries": "fries",
    "home fries": "fries",
    "taco": "tacos",
    "tacos": "tacos",
    "omelette": "omelet",
    "omelet": "omelet",
}

# Términos que siguen siendo demasiado genéricos o poco útiles para ranking.
CONTEXT_OR_LOW_VALUE_DISH_TERMS_V2 = {
    "food",
    "dish",
    "dishes",
    "meal",
    "menu",
    "breakfast",
    "brunch",
    "appetizer",
    "appetizers",
    "starter",
    "starters",
    "entree",
    "entrees",
}

# Palabras que suelen indicar que una mención está demasiado extendida.
OVEREXTENSION_WORDS_V2 = {
    "with",
    "without",
    "and",
    "or",
    "plus",
    "side",
    "sides",
    "sauce",
    "sauces",
    "dressing",
    "topping",
    "toppings",
}


def normalize_canonical_v2(row) -> str:
    """
    Genera la forma canónica v2 combinando:
    - surface form original;
    - canonical rule v1;
    - overrides manuales controlados.
    """

    surface = str(row.get("dish_mention_normalized", "")).lower().strip()
    clean = str(row.get("mention_clean", "")).lower().strip()
    canonical_v1 = str(row.get("mention_canonical_rule", "")).lower().strip()

    # 1. Overrides por surface form exacta
    if surface in SURFACE_FORM_OVERRIDES_V2:
        return SURFACE_FORM_OVERRIDES_V2[surface]

    if clean in SURFACE_FORM_OVERRIDES_V2:
        return SURFACE_FORM_OVERRIDES_V2[clean]

    # 2. Overrides por canonical v1
    if canonical_v1 in CANONICAL_OVERRIDES_V2:
        return CANONICAL_OVERRIDES_V2[canonical_v1]

    # 3. Si no hay override, conservar v1
    return canonical_v1


def build_normalization_flags_v2(row) -> list[str]:
    flags = []

    canonical_v1 = str(row.get("mention_canonical_rule", "")).strip()
    canonical_v2 = str(row.get("canonical_dish_name_v2", "")).strip()
    surface = str(row.get("dish_mention_normalized", "")).strip()

    if not canonical_v2:
        flags.append("empty_canonical_v2")

    if canonical_v2 in CONTEXT_OR_LOW_VALUE_DISH_TERMS_V2:
        flags.append("context_or_low_value_term")

    if canonical_v1 != canonical_v2:
        flags.append("canonical_override_applied")

    words = canonical_v2.split()

    if len(words) > 6:
        flags.append("very_long_canonical")

    if any(word in OVEREXTENSION_WORDS_V2 for word in words):
        flags.append("possible_overextended_entity")

    if row.get("confidence_mean", 1.0) < 0.80:
        flags.append("low_model_confidence")

    # Casos típicos de stemming defectuoso
    if canonical_v2.endswith(" cak") or canonical_v2.endswith(" caks"):
        flags.append("bad_stemming_suspected")

    if canonical_v2.endswith("u") and surface.endswith("us"):
        flags.append("bad_stemming_suspected")

    return flags


def compute_v2_review_priority(row) -> int:
    """
    Prioridad de revisión manual:
    4 = revisar sí o sí
    3 = alta
    2 = media
    1 = baja
    """

    total_mentions = row.get("total_mentions", 0)
    surface_count = row.get("surface_form_count", 0)
    avg_confidence = row.get("avg_confidence", 1.0)
    canonical = str(row.get("canonical_dish_name", "")).lower()

    if total_mentions >= 1000:
        return 4

    if total_mentions >= 500:
        return 3

    if surface_count >= 5:
        return 3

    if avg_confidence < 0.85:
        return 3

    if any(word in canonical.split() for word in OVEREXTENSION_WORDS_V2):
        return 3

    if total_mentions >= 100:
        return 2

    return 1

In [23]:
# ============================================================
# 18. Aplicar normalización v2 a menciones
# ============================================================

mentions_v2_df = mentions_normalized_df.copy()

mentions_v2_df["canonical_dish_name_v1"] = mentions_v2_df["canonical_dish_name"]

mentions_v2_df["canonical_dish_name_v2"] = mentions_v2_df.apply(
    normalize_canonical_v2,
    axis=1
)

mentions_v2_df["normalization_flags_v2"] = mentions_v2_df.apply(
    build_normalization_flags_v2,
    axis=1
)

mentions_v2_df["is_noise_candidate_v2"] = mentions_v2_df["normalization_flags_v2"].apply(
    lambda flags: "context_or_low_value_term" in flags or "empty_canonical_v2" in flags
)

mentions_v2_df["normalization_status_v2"] = np.where(
    ~mentions_v2_df["is_noise_candidate_v2"]
    & mentions_v2_df["canonical_dish_name_v2"].notna()
    & (mentions_v2_df["canonical_dish_name_v2"].str.len() > 0),
    "normalized_rule_based_v2",
    "excluded_or_pending_review_v2"
)

mentions_v2_df["normalization_method_v2"] = np.where(
    mentions_v2_df["normalization_status_v2"] == "normalized_rule_based_v2",
    "rule_based_v2_overrides",
    "none"
)

print("Total menciones:", len(mentions_v2_df))
print("Normalizadas v2:", int((mentions_v2_df["normalization_status_v2"] == "normalized_rule_based_v2").sum()))
print("Pendientes/excluidas v2:", int((mentions_v2_df["normalization_status_v2"] != "normalized_rule_based_v2").sum()))

print("\nCambios de canonical v1 -> v2:")

changed_df = mentions_v2_df[
    mentions_v2_df["canonical_dish_name_v1"] != mentions_v2_df["canonical_dish_name_v2"]
].copy()

changed_display_df = changed_df[
    [
        "dish_mention_normalized",
        "canonical_dish_name_v1",
        "canonical_dish_name_v2",
        "confidence_mean",
        "normalization_flags_v2"
    ]
].copy()

# Convertimos la lista de flags a texto para poder usar drop_duplicates()
changed_display_df["normalization_flags_v2_str"] = changed_display_df["normalization_flags_v2"].apply(
    lambda flags: ", ".join(flags) if isinstance(flags, list) else str(flags)
)

changed_display_df = changed_display_df.drop(columns=["normalization_flags_v2"])

display(
    changed_display_df
    .drop_duplicates()
    .head(50)
)

Total menciones: 95061
Normalizadas v2: 94932
Pendientes/excluidas v2: 129

Cambios de canonical v1 -> v2:

,dish_mention_normalized,canonical_dish_name_v1,canonical_dish_name_v2,confidence_mean,normalization_flags_v2_str
5,wings,wing,wings,0.999090,canonical_override_applied
12,home fries,home fries,fries,0.999263,canonical_override_applied
40,mashed potatoes,mashed potato,mashed potatoes,0.999185,canonical_override_applied
47,taco,taco,tacos,0.999622,canonical_override_applied
58,nachos,nacho,nachos,0.998848,canonical_override_applied
61,nachos,nacho,nachos,0.998776,canonical_override_applied
65,wings,wing,wings,0.999503,canonical_override_applied
74,wings,wing,wings,0.996667,canonical_override_applied
98,oysters,oyster,oysters,0.999094,canonical_override_applied
99,oysters,oyster,oysters,0.998860,canonical_override_applied
100,oyster,oyster,oysters,0.998892,canonical_override_applied
102,tacos,taco,tacos,0.997015,canonical_override_applied
105,tacos,taco,tacos,0.993561,canonical_override_applied
111,ribs,rib,ribs,0.993422,canonical_override_applied
123,mussels,mussel,mussels,0.998596,canonical_override_applied
126,mussels,mussel,mussels,0.998887,canonical_override_applied
129,crab cake,crab cake,crab cakes,0.998829,canonical_override_applied
142,tacos,taco,tacos,0.997769,canonical_override_applied
150,wings,wing,wings,0.998654,canonical_override_applied
175,ribs,rib,ribs,0.997152,canonical_override_applied
227,ribs,rib,ribs,0.998322,canonical_override_applied
232,oyster,oyster,oysters,0.999121,canonical_override_applied
244,french fries,french fries,fries,0.999160,canonical_override_applied
245,taco's,taco,tacos,0.999149,canonical_override_applied
246,nacho's,nacho,nachos,0.984178,canonical_override_applied
249,tacos,taco,tacos,0.998850,canonical_override_applied
250,taco,taco,tacos,0.999462,canonical_override_applied
251,tacos,taco,tacos,0.999559,canonical_override_applied
252,taco,taco,tacos,0.999448,canonical_override_applied
254,wings,wing,wings,0.991432,canonical_override_applied
255,wings,wing,wings,0.999548,canonical_override_applied
264,home fries,home fries,fries,0.999328,canonical_override_applied
265,home fries,home fries,fries,0.999156,canonical_override_applied
267,wings,wing,wings,0.980877,canonical_override_applied
269,tacos,taco,tacos,0.998835,canonical_override_applied
274,oysters,oyster,oysters,0.998530,canonical_override_applied
275,oysters,oyster,oysters,0.997947,canonical_override_applied
276,oysters,oyster,oysters,0.998297,canonical_override_applied
277,oyster,oyster,oysters,0.998750,canonical_override_applied
278,oysters,oyster,oysters,0.998837,canonical_override_applied
279,oysters,oyster,oysters,0.999281,canonical_override_applied
299,ribs,rib,ribs,0.951790,canonical_override_applied
304,spring rolls,spring roll,spring rolls,0.999274,canonical_override_applied
322,taco,taco,tacos,0.999472,canonical_override_applied
348,taco,taco,tacos,0.999580,canonical_override_applied
352,hummus,hummu,hummus,0.996980,canonical_override_applied
365,taco,taco,tacos,0.996893,canonical_override_applied
403,taco,taco,tacos,0.997390,canonical_override_applied
406,mashed potatoes,mashed potato,mashed potatoes,0.999452,canonical_override_applied
417,oyster,oyster,oysters,0.985621,canonical_override_applied

In [24]:
# ============================================================
# 19. Recalcular surface forms v2
# ============================================================

surface_forms_v2_df = (
    mentions_v2_df
    .groupby(
        [
            "dish_mention_normalized",
            "mention_clean",
            "canonical_dish_name_v2"
        ],
        dropna=False
    )
    .agg(
        mention_count=("mention_id", "size"),
        review_count=("review_id", "nunique"),
        business_count=("business_id", "nunique"),
        avg_confidence=("confidence_mean", "mean"),
        min_confidence=("confidence_mean", "min"),
        max_confidence=("confidence_mean", "max"),
        avg_rating=("rating_value", "mean"),
        positive_mentions=("sentiment_label", lambda s: int((s == "positive").sum())),
        neutral_mentions=("sentiment_label", lambda s: int((s == "neutral").sum())),
        negative_mentions=("sentiment_label", lambda s: int((s == "negative").sum())),
        noise_candidate_count_v2=("is_noise_candidate_v2", "sum"),
    )
    .reset_index()
    .rename(columns={"canonical_dish_name_v2": "canonical_dish_name"})
)

surface_forms_v2_df["is_noise_candidate_v2"] = (
    surface_forms_v2_df["noise_candidate_count_v2"] > 0
)

surface_forms_v2_df = surface_forms_v2_df.sort_values(
    ["mention_count", "avg_confidence"],
    ascending=[False, False]
).reset_index(drop=True)

print("Surface forms v1:", len(surface_forms_df))
print("Surface forms v2:", len(surface_forms_v2_df))

display(surface_forms_v2_df.head(50))

Surface forms v1: 10258
Surface forms v2: 10258

,dish_mention_normalized,mention_clean,canonical_dish_name,mention_count,review_count,business_count,avg_confidence,min_confidence,max_confidence,avg_rating,positive_mentions,neutral_mentions,negative_mentions,noise_candidate_count_v2,is_noise_candidate_v2
0,pizza,pizza,pizza,8682,4579,853,0.997651,0.510894,0.999738,3.647662,5618,1140,1924,0,False
1,burger,burger,burger,5756,3458,718,0.992488,0.502620,0.999721,3.660181,3612,1048,1096,0,False
2,fries,fries,fries,4848,3707,991,0.997342,0.508097,0.999758,3.599216,2952,909,987,0,False
3,sushi,sushi,sushi,4461,2475,266,0.999148,0.881908,0.999708,3.834566,3061,612,788,0,False
4,shrimp,shrimp,shrimp,4398,3259,865,0.995150,0.540861,0.999727,3.903365,3153,549,696,0,False
5,tacos,tacos,tacos,2912,2061,419,0.995019,0.504338,0.999729,3.910027,2098,340,474,0,False
6,steak,steak,steak,2789,2101,829,0.994946,0.500823,0.999732,3.558265,1658,441,690,0,False
7,ice cream,ice cream,ice cream,2371,1564,473,0.999370,0.978565,0.999612,4.098271,1857,252,262,0,False
8,burgers,burgers,burger,2334,1871,506,0.999211,0.842032,0.999687,3.746358,1548,413,373,0,False
9,wings,wings,wings,2213,1493,588,0.995358,0.526581,0.999702,3.596927,1367,357,489,0,False
10,sandwiches,sandwiches,sandwich,2034,1781,798,0.998893,0.920336,0.999688,4.019174,1537,253,244,0,False
11,oysters,oysters,oysters,1691,1129,170,0.996766,0.507655,0.999569,4.060911,1294,213,184,0,False
12,pancakes,pancakes,pancake,1536,1054,233,0.995378,0.521068,0.999658,3.941406,1110,235,191,0,False
13,crab,crab,crab,1530,1136,423,0.993790,0.545026,0.999705,3.868627,1086,207,237,0,False
14,taco,taco,tacos,1475,1066,336,0.995216,0.519741,0.999681,3.530847,869,225,381,0,False
15,donuts,donuts,donut,1419,800,142,0.998370,0.528895,0.999715,4.063425,1067,178,174,0,False
16,pho,pho,pho,1219,708,91,0.997328,0.660771,0.999648,3.961444,895,172,152,0,False
17,salmon,salmon,salmon,1134,917,454,0.994066,0.556145,0.999693,3.731041,753,166,215,0,False
18,ribs,ribs,ribs,1093,836,320,0.995873,0.541326,0.999699,3.698994,703,169,221,0,False
19,burrito,burrito,burrito,993,723,278,0.996071,0.552682,0.999734,3.678751,641,134,218,0,False
20,fried chicken,fried chicken,fried chicken,933,781,247,0.998554,0.875684,0.999611,3.857449,646,151,136,0,False
21,tuna,tuna,tuna,889,687,336,0.994037,0.602092,0.999696,3.798650,605,123,161,0,False
22,french toast,french toast,french toast,862,707,203,0.999271,0.954830,0.999585,4.149652,691,84,87,0,False
23,donut,donut,donut,756,458,83,0.995680,0.507568,0.999658,4.056878,557,119,80,0,False
24,brisket,brisket,brisket,750,567,165,0.993665,0.500057,0.999628,3.720000,486,109,155,0,False
25,lobster,lobster,lobster,725,526,202,0.995504,0.640900,0.999660,3.790345,498,106,121,0,False
26,mac and cheese,mac and cheese,mac and cheese,707,584,217,0.998984,0.986915,0.999400,3.855728,484,121,102,0,False
27,nachos,nachos,nachos,678,531,239,0.998142,0.915110,0.999552,3.737463,447,103,128,0,False
28,hummus,hummus,hummus,630,503,179,0.996838,0.741851,0.999597,4.022222,485,76,69,0,False
29,pulled pork,pulled pork,pulled pork,600,528,202,0.998262,0.879202,0.999587,3.901667,423,96,81,0,False
30,calamari,calamari,calamari,598,483,239,0.996551,0.556643,0.999600,3.735786,384,116,98,0,False
31,pad thai,pad thai,pad thai,542,412,102,0.999094,0.988685,0.999596,3.749077,361,63,118,0,False
32,fried rice,fried rice,fried rice,538,450,222,0.999038,0.979397,0.999626,3.587361,332,70,136,0,False
33,mussels,mussels,mussels,517,414,163,0.997707,0.850850,0.999541,4.025145,392,69,56,0,False
34,pancake,pancake,pancake,498,404,112,0.996615,0.669083,0.999615,3.915663,352,79,67,0,False
35,ramen,ramen,ramen,455,251,41,0.993462,0.682340,0.999647,3.659341,278,84,93,0,False
36,latte,latte,latte,444,369,149,0.994690,0.511434,0.999567,4.117117,334,65,45,0,False
37,waffle,waffle,waffle,440,327,151,0.997084,0.560835,0.999680,3.743182,293,72,75,0,False
38,waffles,waffles,waffle,439,362,134,0.998370,0.860072,0.999665,4.132118,343,61,35,0,False
39,oyster,oyster,oysters,438,364,100,0.993516,0.518754,0.999629,4.136986,347,48,43,0,False
40,dumplings,dumplings,dumplings,432,351,162,0.989668,0.505833,0.999674,3.907407,317,55,60,0,False
41,spring rolls,spring rolls,spring rolls,412,358,140,0.999233,0.970169,0.999639,3.980583,307,50,55,0,False
42,burritos,burritos,burrito,403,355,168,0.999346,0.981790,0.999728,3.853598,283,51,69,0,False
43,cheesecake,cheesecake,cheesecake,392,308,163,0.995714,0.726788,0.999520,3.964286,280,53,59,0,False
44,mashed potatoes,mashed potatoes,mashed potatoes,377,338,204,0.999169,0.997088,0.999547,3.509284,216,65,96,0,False
45,eggplant,eggplant,eggplant,377,325,195,0.994589,0.553932,0.999532,3.978780,284,55,38,0,False
46,omelette,omelette,omelet,368,312,150,0.994894,0.789886,0.999485,3.801630,257,49,62,0,False
47,french fries,french fries,fries,350,328,230,0.999346,0.998376,0.999637,3.485714,195,70,85,0,False
48,naan,naan,naan,345,281,71,0.996431,0.935645,0.999431,3.979710,259,37,49,0,False
49,smoothie,smoothie,smoothie,341,250,106,0.994032,0.607347,0.999396,3.844575,237,46,58,0,False

In [25]:
# ============================================================
# 20. Crear catálogo semilla v2
# ============================================================

catalog_source_v2_df = surface_forms_v2_df[
    ~surface_forms_v2_df["is_noise_candidate_v2"]
    & surface_forms_v2_df["canonical_dish_name"].notna()
    & (surface_forms_v2_df["canonical_dish_name"].str.len() > 0)
].copy()

catalog_v2_df = (
    catalog_source_v2_df
    .groupby("canonical_dish_name", dropna=False)
    .agg(
        total_mentions=("mention_count", "sum"),
        total_reviews=("review_count", "sum"),
        total_businesses=("business_count", "sum"),
        surface_form_count=("dish_mention_normalized", "nunique"),
        avg_confidence=("avg_confidence", "mean"),
        avg_rating=("avg_rating", "mean"),
        positive_mentions=("positive_mentions", "sum"),
        neutral_mentions=("neutral_mentions", "sum"),
        negative_mentions=("negative_mentions", "sum"),
    )
    .reset_index()
)

catalog_v2_df["language"] = "en"
catalog_v2_df["catalog_version"] = "dish_catalog_seed_v2"
catalog_v2_df["normalization_method"] = "rule_based_v2_overrides"
catalog_v2_df["manual_review_status"] = "pending"

catalog_v2_df["manual_review_priority"] = catalog_v2_df.apply(
    compute_v2_review_priority,
    axis=1
)

catalog_v2_df = catalog_v2_df.sort_values(
    ["total_mentions", "surface_form_count"],
    ascending=[False, False]
).reset_index(drop=True)

catalog_v2_df["dish_id"] = [
    f"dish_seed_v2_{idx:06d}"
    for idx in range(1, len(catalog_v2_df) + 1)
]

# Reordenar columnas
catalog_v2_df = catalog_v2_df[
    [
        "dish_id",
        "canonical_dish_name",
        "language",
        "catalog_version",
        "normalization_method",
        "total_mentions",
        "total_reviews",
        "total_businesses",
        "surface_form_count",
        "avg_confidence",
        "avg_rating",
        "positive_mentions",
        "neutral_mentions",
        "negative_mentions",
        "manual_review_status",
        "manual_review_priority",
    ]
].copy()

print("Platos canónicos v1:", len(catalog_seed_df))
print("Platos canónicos v2:", len(catalog_v2_df))

display(catalog_v2_df.head(60))

Platos canónicos v1: 9401
Platos canónicos v2: 9937

,dish_id,canonical_dish_name,language,catalog_version,normalization_method,total_mentions,total_reviews,total_businesses,surface_form_count,avg_confidence,avg_rating,positive_mentions,neutral_mentions,negative_mentions,manual_review_status,manual_review_priority
0,dish_seed_v2_000001,pizza,en,dish_catalog_seed_v2,rule_based_v2_overrides,8751,4640,900,4,0.972458,4.005505,5661,1154,1936,pending,4
1,dish_seed_v2_000002,burger,en,dish_catalog_seed_v2,rule_based_v2_overrides,8095,5334,1229,4,0.960858,3.726635,5164,1462,1469,pending,4
2,dish_seed_v2_000003,fries,en,dish_catalog_seed_v2,rule_based_v2_overrides,5375,4192,1314,3,0.998209,3.651662,3275,1010,1090,pending,4
3,dish_seed_v2_000004,sushi,en,dish_catalog_seed_v2,rule_based_v2_overrides,4470,2484,275,3,0.999205,3.349617,3067,613,790,pending,4
4,dish_seed_v2_000005,tacos,en,dish_catalog_seed_v2,rule_based_v2_overrides,4436,3165,789,3,0.995807,3.759203,3003,571,862,pending,4
5,dish_seed_v2_000006,shrimp,en,dish_catalog_seed_v2,rule_based_v2_overrides,4421,3281,881,4,0.819895,4.130603,3167,553,701,pending,4
6,dish_seed_v2_000007,steak,en,dish_catalog_seed_v2,rule_based_v2_overrides,2794,2106,834,3,0.897557,2.852755,1660,441,693,pending,4
7,dish_seed_v2_000008,ice cream,en,dish_catalog_seed_v2,rule_based_v2_overrides,2411,1604,499,2,0.998952,4.049135,1888,255,268,pending,4
8,dish_seed_v2_000009,wings,en,dish_catalog_seed_v2,rule_based_v2_overrides,2215,1495,590,3,0.817018,4.198976,1369,357,489,pending,4
9,dish_seed_v2_000010,donut,en,dish_catalog_seed_v2,rule_based_v2_overrides,2175,1258,225,2,0.997025,4.060152,1624,297,254,pending,4
10,dish_seed_v2_000011,oysters,en,dish_catalog_seed_v2,rule_based_v2_overrides,2129,1493,270,2,0.995141,4.098949,1641,261,227,pending,4
11,dish_seed_v2_000012,sandwich,en,dish_catalog_seed_v2,rule_based_v2_overrides,2127,1870,882,4,0.752680,3.654794,1595,269,263,pending,4
12,dish_seed_v2_000013,pancake,en,dish_catalog_seed_v2,rule_based_v2_overrides,2035,1459,346,3,0.996992,3.952356,1463,314,258,pending,4
13,dish_seed_v2_000014,crab,en,dish_catalog_seed_v2,rule_based_v2_overrides,1535,1140,427,3,0.938591,3.956209,1090,208,237,pending,4
14,dish_seed_v2_000015,burrito,en,dish_catalog_seed_v2,rule_based_v2_overrides,1405,1086,454,3,0.998225,3.770042,930,186,289,pending,4
15,dish_seed_v2_000016,pho,en,dish_catalog_seed_v2,rule_based_v2_overrides,1225,714,96,3,0.996735,3.542703,898,174,153,pending,4
16,dish_seed_v2_000017,salmon,en,dish_catalog_seed_v2,rule_based_v2_overrides,1137,920,457,3,0.942490,4.410347,756,166,215,pending,4
17,dish_seed_v2_000018,ribs,en,dish_catalog_seed_v2,rule_based_v2_overrides,1095,838,322,2,0.819390,3.849497,704,170,221,pending,4
18,dish_seed_v2_000019,fried chicken,en,dish_catalog_seed_v2,rule_based_v2_overrides,933,781,247,1,0.998554,3.857449,646,151,136,pending,3
19,dish_seed_v2_000020,tuna,en,dish_catalog_seed_v2,rule_based_v2_overrides,890,688,337,2,0.976428,3.399325,605,124,161,pending,3
20,dish_seed_v2_000021,waffle,en,dish_catalog_seed_v2,rule_based_v2_overrides,879,689,285,2,0.997727,3.937650,636,133,110,pending,3
21,dish_seed_v2_000022,french toast,en,dish_catalog_seed_v2,rule_based_v2_overrides,877,721,213,3,0.942647,4.073694,704,86,87,pending,3
22,dish_seed_v2_000023,omelet,en,dish_catalog_seed_v2,rule_based_v2_overrides,779,674,359,4,0.955139,3.877472,534,122,123,pending,3
23,dish_seed_v2_000024,nachos,en,dish_catalog_seed_v2,rule_based_v2_overrides,764,611,311,5,0.992353,3.347742,493,117,154,pending,3
24,dish_seed_v2_000025,brisket,en,dish_catalog_seed_v2,rule_based_v2_overrides,753,570,168,2,0.996481,4.193333,489,109,155,pending,3
25,dish_seed_v2_000026,lobster,en,dish_catalog_seed_v2,rule_based_v2_overrides,745,544,209,2,0.919894,3.920172,513,108,124,pending,3
26,dish_seed_v2_000027,mac and cheese,en,dish_catalog_seed_v2,rule_based_v2_overrides,707,584,217,1,0.998984,3.855728,484,121,102,pending,3
27,dish_seed_v2_000028,hummus,en,dish_catalog_seed_v2,rule_based_v2_overrides,632,504,180,2,0.997942,4.011111,487,76,69,pending,3
28,dish_seed_v2_000029,pulled pork,en,dish_catalog_seed_v2,rule_based_v2_overrides,601,529,203,2,0.875620,3.950833,424,96,81,pending,3
29,dish_seed_v2_000030,calamari,en,dish_catalog_seed_v2,rule_based_v2_overrides,600,484,240,2,0.997774,2.867893,384,116,100,pending,3
30,dish_seed_v2_000031,pad thai,en,dish_catalog_seed_v2,rule_based_v2_overrides,543,413,103,2,0.999198,3.874539,362,63,118,pending,3
31,dish_seed_v2_000032,fried rice,en,dish_catalog_seed_v2,rule_based_v2_overrides,539,451,223,2,0.998879,4.293680,333,70,136,pending,3
32,dish_seed_v2_000033,mussels,en,dish_catalog_seed_v2,rule_based_v2_overrides,538,435,184,3,0.998086,4.208382,404,72,62,pending,3
33,dish_seed_v2_000034,crab cakes,en,dish_catalog_seed_v2,rule_based_v2_overrides,534,456,244,2,0.998332,3.738068,352,92,90,pending,3
34,dish_seed_v2_000035,dumplings,en,dish_catalog_seed_v2,rule_based_v2_overrides,498,407,204,4,0.940333,3.945602,366,64,68,pending,2
35,dish_seed_v2_000036,ramen,en,dish_catalog_seed_v2,rule_based_v2_overrides,460,255,45,2,0.994165,3.729670,282,84,94,pending,2
36,dish_seed_v2_000037,latte,en,dish_catalog_seed_v2,rule_based_v2_overrides,446,371,151,2,0.996788,4.308559,336,65,45,pending,2
37,dish_seed_v2_000038,quesadilla,en,dish_catalog_seed_v2,rule_based_v2_overrides,434,370,237,3,0.996334,3.864796,278,61,95,pending,2
38,dish_seed_v2_000039,spring rolls,en,dish_catalog_seed_v2,rule_based_v2_overrides,418,364,146,2,0.902988,3.823625,310,52,56,pending,2
39,dish_seed_v2_000040,enchilada,en,dish_catalog_seed_v2,rule_based_v2_overrides,407,350,161,3,0.995405,3.988880,251,57,99,pending,2
40,dish_seed_v2_000041,mashed potatoes,en,dish_catalog_seed_v2,rule_based_v2_overrides,400,359,225,3,0.993145,3.812618,231,66,103,pending,2
41,dish_seed_v2_000042,cheesecake,en,dish_catalog_seed_v2,rule_based_v2_overrides,392,308,163,1,0.995714,3.964286,280,53,59,pending,2
42,dish_seed_v2_000043,eggplant,en,dish_catalog_seed_v2,rule_based_v2_overrides,381,329,199,4,0.929995,4.619695,288,55,38,pending,2
43,dish_seed_v2_000044,naan,en,dish_catalog_seed_v2,rule_based_v2_overrides,359,293,82,3,0.996336,3.104348,264,39,56,pending,2
44,dish_seed_v2_000045,smoothie,en,dish_catalog_seed_v2,rule_based_v2_overrides,342,251,107,2,0.994860,4.422287,238,46,58,pending,2
45,dish_seed_v2_000046,ravioli,en,dish_catalog_seed_v2,rule_based_v2_overrides,328,271,133,3,0.979965,3.073728,231,44,53,pending,2
46,dish_seed_v2_000047,cheeseburger,en,dish_catalog_seed_v2,rule_based_v2_overrides,320,289,195,2,0.995575,3.550858,184,63,73,pending,2
47,dish_seed_v2_000048,custard,en,dish_catalog_seed_v2,rule_based_v2_overrides,276,202,62,2,0.969466,4.363636,220,47,9,pending,2
48,dish_seed_v2_000049,chicken wings,en,dish_catalog_seed_v2,rule_based_v2_overrides,275,240,181,1,0.997783,3.694545,184,43,48,pending,2
49,dish_seed_v2_000050,eggs benedict,en,dish_catalog_seed_v2,rule_based_v2_overrides,271,243,116,2,0.998565,4.223978,198,33,40,pending,2
50,dish_seed_v2_000051,spaghetti,en,dish_catalog_seed_v2,rule_based_v2_overrides,268,226,135,1,0.997130,3.567164,162,40,66,pending,2
51,dish_seed_v2_000052,gnocchi,en,dish_catalog_seed_v2,rule_based_v2_overrides,251,202,87,2,0.997540,2.944220,196,29,26,pending,2
52,dish_seed_v2_000053,sashimi,en,dish_catalog_seed_v2,rule_based_v2_overrides,251,198,87,1,0.997422,3.780876,163,43,45,pending,2
53,dish_seed_v2_000054,fish and chip,en,dish_catalog_seed_v2,rule_based_v2_overrides,235,201,87,1,0.998813,3.591489,141,49,45,pending,3
54,dish_seed_v2_000055,milkshake,en,dish_catalog_seed_v2,rule_based_v2_overrides,232,194,94,1,0.994847,3.732759,145,45,42,pending,2
55,dish_seed_v2_000056,clams,en,dish_catalog_seed_v2,rule_based_v2_overrides,230,189,115,3,0.787618,4.044048,155,28,47,pending,3
56,dish_seed_v2_000057,lasagna,en,dish_catalog_seed_v2,rule_based_v2_overrides,219,185,102,1,0.998267,3.753425,145,28,46,pending,2
57,dish_seed_v2_000058,risotto,en,dish_catalog_seed_v2,rule_based_v2_overrides,208,176,95,2,0.998203,4.417874,141,33,34,pending,2
58,dish_seed_v2_000059,tempura,en,dish_catalog_seed_v2,rule_based_v2_overrides,191,161,96,1,0.995472,3.523560,112,33,46,pending,2
59,dish_seed_v2_000060,tamale,en,dish_catalog_seed_v2,rule_based_v2_overrides,184,148,91,3,0.993847,4.009030,123,28,33,pending,2

In [26]:
# ============================================================
# 21. Crear aliases v2
# ============================================================

dish_id_map_v2 = dict(
    zip(
        catalog_v2_df["canonical_dish_name"],
        catalog_v2_df["dish_id"]
    )
)

aliases_v2_df = surface_forms_v2_df.copy()

aliases_v2_df = aliases_v2_df[
    aliases_v2_df["canonical_dish_name"].isin(dish_id_map_v2)
].copy()

aliases_v2_df["dish_id"] = aliases_v2_df["canonical_dish_name"].map(dish_id_map_v2)
aliases_v2_df["alias_text"] = aliases_v2_df["dish_mention_normalized"]
aliases_v2_df["alias_language"] = "en"
aliases_v2_df["alias_source"] = "model_mentions_rule_based_v2"

aliases_v2_df["alias_type"] = np.where(
    aliases_v2_df["alias_text"] == aliases_v2_df["canonical_dish_name"],
    "canonical",
    "surface_variant"
)

aliases_v2_df["manual_review_status"] = "pending"

aliases_v2_df = aliases_v2_df[
    [
        "dish_id",
        "canonical_dish_name",
        "alias_text",
        "alias_type",
        "alias_language",
        "alias_source",
        "mention_count",
        "review_count",
        "business_count",
        "avg_confidence",
        "manual_review_status",
    ]
].copy()

aliases_v2_df = aliases_v2_df.sort_values(
    ["mention_count", "avg_confidence"],
    ascending=[False, False]
).reset_index(drop=True)

print("Aliases v1:", len(aliases_seed_df))
print("Aliases v2:", len(aliases_v2_df))

display(aliases_v2_df.head(60))

Aliases v1: 9692
Aliases v2: 10235

,dish_id,canonical_dish_name,alias_text,alias_type,alias_language,alias_source,mention_count,review_count,business_count,avg_confidence,manual_review_status
0,dish_seed_v2_000001,pizza,pizza,canonical,en,model_mentions_rule_based_v2,8682,4579,853,0.997651,pending
1,dish_seed_v2_000002,burger,burger,canonical,en,model_mentions_rule_based_v2,5756,3458,718,0.992488,pending
2,dish_seed_v2_000003,fries,fries,canonical,en,model_mentions_rule_based_v2,4848,3707,991,0.997342,pending
3,dish_seed_v2_000004,sushi,sushi,canonical,en,model_mentions_rule_based_v2,4461,2475,266,0.999148,pending
4,dish_seed_v2_000006,shrimp,shrimp,canonical,en,model_mentions_rule_based_v2,4398,3259,865,0.995150,pending
5,dish_seed_v2_000005,tacos,tacos,canonical,en,model_mentions_rule_based_v2,2912,2061,419,0.995019,pending
6,dish_seed_v2_000007,steak,steak,canonical,en,model_mentions_rule_based_v2,2789,2101,829,0.994946,pending
7,dish_seed_v2_000008,ice cream,ice cream,canonical,en,model_mentions_rule_based_v2,2371,1564,473,0.999370,pending
8,dish_seed_v2_000002,burger,burgers,surface_variant,en,model_mentions_rule_based_v2,2334,1871,506,0.999211,pending
9,dish_seed_v2_000009,wings,wings,canonical,en,model_mentions_rule_based_v2,2213,1493,588,0.995358,pending
10,dish_seed_v2_000012,sandwich,sandwiches,surface_variant,en,model_mentions_rule_based_v2,2034,1781,798,0.998893,pending
11,dish_seed_v2_000011,oysters,oysters,canonical,en,model_mentions_rule_based_v2,1691,1129,170,0.996766,pending
12,dish_seed_v2_000013,pancake,pancakes,surface_variant,en,model_mentions_rule_based_v2,1536,1054,233,0.995378,pending
13,dish_seed_v2_000014,crab,crab,canonical,en,model_mentions_rule_based_v2,1530,1136,423,0.993790,pending
14,dish_seed_v2_000005,tacos,taco,surface_variant,en,model_mentions_rule_based_v2,1475,1066,336,0.995216,pending
15,dish_seed_v2_000010,donut,donuts,surface_variant,en,model_mentions_rule_based_v2,1419,800,142,0.998370,pending
16,dish_seed_v2_000016,pho,pho,canonical,en,model_mentions_rule_based_v2,1219,708,91,0.997328,pending
17,dish_seed_v2_000017,salmon,salmon,canonical,en,model_mentions_rule_based_v2,1134,917,454,0.994066,pending
18,dish_seed_v2_000018,ribs,ribs,canonical,en,model_mentions_rule_based_v2,1093,836,320,0.995873,pending
19,dish_seed_v2_000015,burrito,burrito,canonical,en,model_mentions_rule_based_v2,993,723,278,0.996071,pending
20,dish_seed_v2_000019,fried chicken,fried chicken,canonical,en,model_mentions_rule_based_v2,933,781,247,0.998554,pending
21,dish_seed_v2_000020,tuna,tuna,canonical,en,model_mentions_rule_based_v2,889,687,336,0.994037,pending
22,dish_seed_v2_000022,french toast,french toast,canonical,en,model_mentions_rule_based_v2,862,707,203,0.999271,pending
23,dish_seed_v2_000010,donut,donut,canonical,en,model_mentions_rule_based_v2,756,458,83,0.995680,pending
24,dish_seed_v2_000025,brisket,brisket,canonical,en,model_mentions_rule_based_v2,750,567,165,0.993665,pending
25,dish_seed_v2_000026,lobster,lobster,canonical,en,model_mentions_rule_based_v2,725,526,202,0.995504,pending
26,dish_seed_v2_000027,mac and cheese,mac and cheese,canonical,en,model_mentions_rule_based_v2,707,584,217,0.998984,pending
27,dish_seed_v2_000024,nachos,nachos,canonical,en,model_mentions_rule_based_v2,678,531,239,0.998142,pending
28,dish_seed_v2_000028,hummus,hummus,canonical,en,model_mentions_rule_based_v2,630,503,179,0.996838,pending
29,dish_seed_v2_000029,pulled pork,pulled pork,canonical,en,model_mentions_rule_based_v2,600,528,202,0.998262,pending
30,dish_seed_v2_000030,calamari,calamari,canonical,en,model_mentions_rule_based_v2,598,483,239,0.996551,pending
31,dish_seed_v2_000031,pad thai,pad thai,canonical,en,model_mentions_rule_based_v2,542,412,102,0.999094,pending
32,dish_seed_v2_000032,fried rice,fried rice,canonical,en,model_mentions_rule_based_v2,538,450,222,0.999038,pending
33,dish_seed_v2_000033,mussels,mussels,canonical,en,model_mentions_rule_based_v2,517,414,163,0.997707,pending
34,dish_seed_v2_000013,pancake,pancake,canonical,en,model_mentions_rule_based_v2,498,404,112,0.996615,pending
35,dish_seed_v2_000036,ramen,ramen,canonical,en,model_mentions_rule_based_v2,455,251,41,0.993462,pending
36,dish_seed_v2_000037,latte,latte,canonical,en,model_mentions_rule_based_v2,444,369,149,0.994690,pending
37,dish_seed_v2_000021,waffle,waffle,canonical,en,model_mentions_rule_based_v2,440,327,151,0.997084,pending
38,dish_seed_v2_000021,waffle,waffles,surface_variant,en,model_mentions_rule_based_v2,439,362,134,0.998370,pending
39,dish_seed_v2_000011,oysters,oyster,surface_variant,en,model_mentions_rule_based_v2,438,364,100,0.993516,pending
40,dish_seed_v2_000035,dumplings,dumplings,canonical,en,model_mentions_rule_based_v2,432,351,162,0.989668,pending
41,dish_seed_v2_000039,spring rolls,spring rolls,canonical,en,model_mentions_rule_based_v2,412,358,140,0.999233,pending
42,dish_seed_v2_000015,burrito,burritos,surface_variant,en,model_mentions_rule_based_v2,403,355,168,0.999346,pending
43,dish_seed_v2_000042,cheesecake,cheesecake,canonical,en,model_mentions_rule_based_v2,392,308,163,0.995714,pending
44,dish_seed_v2_000041,mashed potatoes,mashed potatoes,canonical,en,model_mentions_rule_based_v2,377,338,204,0.999169,pending
45,dish_seed_v2_000043,eggplant,eggplant,canonical,en,model_mentions_rule_based_v2,377,325,195,0.994589,pending
46,dish_seed_v2_000023,omelet,omelette,surface_variant,en,model_mentions_rule_based_v2,368,312,150,0.994894,pending
47,dish_seed_v2_000003,fries,french fries,surface_variant,en,model_mentions_rule_based_v2,350,328,230,0.999346,pending
48,dish_seed_v2_000044,naan,naan,canonical,en,model_mentions_rule_based_v2,345,281,71,0.996431,pending
49,dish_seed_v2_000045,smoothie,smoothie,canonical,en,model_mentions_rule_based_v2,341,250,106,0.994032,pending
50,dish_seed_v2_000023,omelet,omelet,canonical,en,model_mentions_rule_based_v2,335,288,149,0.994306,pending
51,dish_seed_v2_000046,ravioli,ravioli,canonical,en,model_mentions_rule_based_v2,321,265,127,0.986229,pending
52,dish_seed_v2_000034,crab cakes,crab cakes,canonical,en,model_mentions_rule_based_v2,291,253,136,0.998895,pending
53,dish_seed_v2_000038,quesadilla,quesadilla,canonical,en,model_mentions_rule_based_v2,287,237,142,0.992525,pending
54,dish_seed_v2_000040,enchilada,enchiladas,surface_variant,en,model_mentions_rule_based_v2,279,245,95,0.997126,pending
55,dish_seed_v2_000049,chicken wings,chicken wings,canonical,en,model_mentions_rule_based_v2,275,240,181,0.997783,pending
56,dish_seed_v2_000047,cheeseburger,cheeseburger,canonical,en,model_mentions_rule_based_v2,272,243,152,0.997810,pending
57,dish_seed_v2_000050,eggs benedict,eggs benedict,canonical,en,model_mentions_rule_based_v2,269,241,114,0.998541,pending
58,dish_seed_v2_000051,spaghetti,spaghetti,canonical,en,model_mentions_rule_based_v2,268,226,135,0.997130,pending
59,dish_seed_v2_000048,custard,custard,canonical,en,model_mentions_rule_based_v2,264,192,55,0.962910,pending

In [27]:
# ============================================================
# 22. Añadir dish_id v2 a cada mención
# ============================================================

mentions_v2_df["dish_id_v2"] = mentions_v2_df["canonical_dish_name_v2"].map(dish_id_map_v2)

mentions_v2_df["normalization_status_v2"] = np.where(
    mentions_v2_df["dish_id_v2"].notna(),
    "normalized_rule_based_v2",
    "excluded_or_pending_review_v2"
)

print("Menciones con dish_id_v2:", int(mentions_v2_df["dish_id_v2"].notna().sum()))
print("Menciones sin dish_id_v2:", int(mentions_v2_df["dish_id_v2"].isna().sum()))

display(
    mentions_v2_df[
        [
            "dish_mention_text",
            "dish_mention_normalized",
            "canonical_dish_name_v1",
            "canonical_dish_name_v2",
            "dish_id_v2",
            "normalization_status_v2",
            "confidence_mean",
            "normalization_flags_v2",
        ]
    ].head(30)
)

Menciones con dish_id_v2: 94932
Menciones sin dish_id_v2: 129

,dish_mention_text,dish_mention_normalized,canonical_dish_name_v1,canonical_dish_name_v2,dish_id_v2,normalization_status_v2,confidence_mean,normalization_flags_v2
0,tamale,tamale,tamale,tamale,dish_seed_v2_000060,normalized_rule_based_v2,0.997417,[]
1,lamb curry,lamb curry,lamb curry,lamb curry,dish_seed_v2_000205,normalized_rule_based_v2,0.996373,[]
2,korma,korma,korma,korma,dish_seed_v2_000074,normalized_rule_based_v2,0.997466,[]
3,naan,naan,naan,naan,dish_seed_v2_000044,normalized_rule_based_v2,0.998627,[]
4,sandwiches,sandwiches,sandwich,sandwich,dish_seed_v2_000012,normalized_rule_based_v2,0.999447,[]
5,wings,wings,wing,wings,dish_seed_v2_000009,normalized_rule_based_v2,0.999090,[canonical_override_applied]
6,sushi,sushi,sushi,sushi,dish_seed_v2_000004,normalized_rule_based_v2,0.999515,[]
7,gnocchi with marinara,gnocchi with marinara,gnocchi with marinara,gnocchi with marinara,dish_seed_v2_004917,normalized_rule_based_v2,0.850407,[possible_overextended_entity]
8,baked eggplant appetizer,baked eggplant appetizer,baked eggplant appetizer,baked eggplant appetizer,dish_seed_v2_001954,normalized_rule_based_v2,0.773023,[low_model_confidence]
9,Sonoran Dog,sonoran dog,sonoran dog,sonoran dog,dish_seed_v2_000088,normalized_rule_based_v2,0.986196,[]
10,Sonoran Dogs,sonoran dogs,sonoran dog,sonoran dog,dish_seed_v2_000088,normalized_rule_based_v2,0.984542,[]
11,waffle,waffle,waffle,waffle,dish_seed_v2_000021,normalized_rule_based_v2,0.998554,[]
12,home fries,home fries,home fries,fries,dish_seed_v2_000003,normalized_rule_based_v2,0.999263,[canonical_override_applied]
13,latte,latte,latte,latte,dish_seed_v2_000037,normalized_rule_based_v2,0.999360,[]
14,pumpkin pie,pumpkin pie,pumpkin pie,pumpkin pie,dish_seed_v2_000152,normalized_rule_based_v2,0.998669,[]
15,frozen custard,frozen custard,frozen custard,frozen custard,dish_seed_v2_000065,normalized_rule_based_v2,0.998867,[]
16,burgers,burgers,burger,burger,dish_seed_v2_000002,normalized_rule_based_v2,0.999447,[]
17,pizza,pizza,pizza,pizza,dish_seed_v2_000001,normalized_rule_based_v2,0.999582,[]
18,pizza,pizza,pizza,pizza,dish_seed_v2_000001,normalized_rule_based_v2,0.998652,[]
19,pizza,pizza,pizza,pizza,dish_seed_v2_000001,normalized_rule_based_v2,0.998444,[]
20,pizza,pizza,pizza,pizza,dish_seed_v2_000001,normalized_rule_based_v2,0.999308,[]
21,burgers,burgers,burger,burger,dish_seed_v2_000002,normalized_rule_based_v2,0.999339,[]
22,sushi,sushi,sushi,sushi,dish_seed_v2_000004,normalized_rule_based_v2,0.999364,[]
23,sushi,sushi,sushi,sushi,dish_seed_v2_000004,normalized_rule_based_v2,0.999502,[]
24,salmon,salmon,salmon,salmon,dish_seed_v2_000017,normalized_rule_based_v2,0.998853,[]
25,salmon,salmon,salmon,salmon,dish_seed_v2_000017,normalized_rule_based_v2,0.999052,[]
26,edamame,edamame,edamame,edamame,dish_seed_v2_000068,normalized_rule_based_v2,0.997953,[]
27,tempura,tempura,tempura,tempura,dish_seed_v2_000059,normalized_rule_based_v2,0.999418,[]
28,sushi bowl,sushi bowl,sushi bowl,sushi bowl,dish_seed_v2_000859,normalized_rule_based_v2,0.997440,[]
29,sushi bowl,sushi bowl,sushi bowl,sushi bowl,dish_seed_v2_000859,normalized_rule_based_v2,0.979868,[]

In [28]:
# ============================================================
# 23. Detectar posibles duplicados para revisión
# ============================================================

!pip -q install rapidfuzz

from rapidfuzz import fuzz

# Para no hacer una comparación masiva 9k x 9k, trabajamos con candidatos relevantes.
duplicate_pool_df = catalog_v2_df[
    (catalog_v2_df["total_mentions"] >= 20)
    | (catalog_v2_df["manual_review_priority"] >= 2)
].copy()

names = duplicate_pool_df["canonical_dish_name"].tolist()

duplicate_candidate_rows = []

for i in tqdm(range(len(names)), desc="Buscando duplicados potenciales"):
    name_a = names[i]

    for j in range(i + 1, len(names)):
        name_b = names[j]

        # Evitar pares muy diferentes en longitud para reducir ruido
        if abs(len(name_a) - len(name_b)) > 15:
            continue

        ratio = fuzz.token_sort_ratio(name_a, name_b)
        partial = fuzz.partial_ratio(name_a, name_b)

        if ratio >= 92 or partial >= 96:
            row_a = duplicate_pool_df[duplicate_pool_df["canonical_dish_name"] == name_a].iloc[0]
            row_b = duplicate_pool_df[duplicate_pool_df["canonical_dish_name"] == name_b].iloc[0]

            duplicate_candidate_rows.append({
                "canonical_a": name_a,
                "canonical_b": name_b,
                "similarity_token_sort": ratio,
                "similarity_partial": partial,
                "mentions_a": int(row_a["total_mentions"]),
                "mentions_b": int(row_b["total_mentions"]),
                "review_priority_a": int(row_a["manual_review_priority"]),
                "review_priority_b": int(row_b["manual_review_priority"]),
                "suggested_action": "manual_review",
            })

duplicate_candidates_v2_df = pd.DataFrame(duplicate_candidate_rows)

if len(duplicate_candidates_v2_df) > 0:
    duplicate_candidates_v2_df = duplicate_candidates_v2_df.sort_values(
        ["similarity_token_sort", "similarity_partial", "mentions_a", "mentions_b"],
        ascending=[False, False, False, False]
    ).reset_index(drop=True)

print("Duplicados potenciales:", len(duplicate_candidates_v2_df))

display(duplicate_candidates_v2_df.head(100))

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 41.0 MB/s eta 0:00:0000:0100:01

Buscando duplicados potenciales:   0%|          | 0/4299 [00:00<?, ?it/s]

Duplicados potenciales: 6984

,canonical_a,canonical_b,similarity_token_sort,similarity_partial,mentions_a,mentions_b,review_priority_a,review_priority_b,suggested_action
0,goat curry with sweet potato gnocchi,curry goat with sweet potato gnocchi,100.00000,92.537313,2,1,3,3,manual_review
1,caesar side salad,side caesar salad,100.00000,82.758621,1,1,3,3,manual_review
2,mango sticky rice,sticky mango rice,100.00000,78.571429,2,1,3,3,manual_review
3,shrimp tempura,tempura shrimp,100.00000,66.666667,62,30,1,1,manual_review
4,cheeseburger with bacon,cheeseburgers with bacon,97.87234,95.652174,1,1,3,3,manual_review
...,...,...,...,...,...,...,...,...,...
95,mac and cheese,mac and cheese bit,87.50000,100.000000,707,2,3,3,manual_review
96,mac and cheese,$ 5 mac and cheese,87.50000,100.000000,707,1,3,3,manual_review
97,mac and cheese,mac and cheese one,87.50000,100.000000,707,1,3,3,manual_review
98,ordered,i ordered,87.50000,100.000000,10,1,3,3,manual_review
99,mac and cheese burger,fried mac and cheese burger,87.50000,100.000000,6,1,3,3,manual_review

In [29]:
# ============================================================
# 24. Crear muestras de revisión manual v2
# ============================================================

# Top platos del catálogo
catalog_review_top_df = catalog_v2_df.head(200).copy()

# Platos con baja confianza
catalog_review_low_conf_df = (
    catalog_v2_df
    .sort_values("avg_confidence", ascending=True)
    .head(200)
    .copy()
)

# Platos con muchas variantes surface
catalog_review_many_aliases_df = (
    catalog_v2_df
    .sort_values("surface_form_count", ascending=False)
    .head(200)
    .copy()
)

# Menciones marcadas con flags v2
mentions_review_flags_df = mentions_v2_df[
    mentions_v2_df["normalization_flags_v2"].apply(lambda flags: len(flags) > 0)
].copy()

mentions_review_flags_df = (
    mentions_review_flags_df
    .sort_values(["confidence_mean"], ascending=True)
    .head(300)
    .copy()
)

print("catalog_review_top_df:", len(catalog_review_top_df))
print("catalog_review_low_conf_df:", len(catalog_review_low_conf_df))
print("catalog_review_many_aliases_df:", len(catalog_review_many_aliases_df))
print("mentions_review_flags_df:", len(mentions_review_flags_df))

display(catalog_review_top_df.head(10))
display(catalog_review_low_conf_df.head(10))
display(catalog_review_many_aliases_df.head(10))
display(mentions_review_flags_df.head(10))

catalog_review_top_df: 200
catalog_review_low_conf_df: 200
catalog_review_many_aliases_df: 200
mentions_review_flags_df: 300

,dish_id,canonical_dish_name,language,catalog_version,normalization_method,total_mentions,total_reviews,total_businesses,surface_form_count,avg_confidence,avg_rating,positive_mentions,neutral_mentions,negative_mentions,manual_review_status,manual_review_priority
0,dish_seed_v2_000001,pizza,en,dish_catalog_seed_v2,rule_based_v2_overrides,8751,4640,900,4,0.972458,4.005505,5661,1154,1936,pending,4
1,dish_seed_v2_000002,burger,en,dish_catalog_seed_v2,rule_based_v2_overrides,8095,5334,1229,4,0.960858,3.726635,5164,1462,1469,pending,4
2,dish_seed_v2_000003,fries,en,dish_catalog_seed_v2,rule_based_v2_overrides,5375,4192,1314,3,0.998209,3.651662,3275,1010,1090,pending,4
3,dish_seed_v2_000004,sushi,en,dish_catalog_seed_v2,rule_based_v2_overrides,4470,2484,275,3,0.999205,3.349617,3067,613,790,pending,4
4,dish_seed_v2_000005,tacos,en,dish_catalog_seed_v2,rule_based_v2_overrides,4436,3165,789,3,0.995807,3.759203,3003,571,862,pending,4
5,dish_seed_v2_000006,shrimp,en,dish_catalog_seed_v2,rule_based_v2_overrides,4421,3281,881,4,0.819895,4.130603,3167,553,701,pending,4
6,dish_seed_v2_000007,steak,en,dish_catalog_seed_v2,rule_based_v2_overrides,2794,2106,834,3,0.897557,2.852755,1660,441,693,pending,4
7,dish_seed_v2_000008,ice cream,en,dish_catalog_seed_v2,rule_based_v2_overrides,2411,1604,499,2,0.998952,4.049135,1888,255,268,pending,4
8,dish_seed_v2_000009,wings,en,dish_catalog_seed_v2,rule_based_v2_overrides,2215,1495,590,3,0.817018,4.198976,1369,357,489,pending,4
9,dish_seed_v2_000010,donut,en,dish_catalog_seed_v2,rule_based_v2_overrides,2175,1258,225,2,0.997025,4.060152,1624,297,254,pending,4

,dish_id,canonical_dish_name,language,catalog_version,normalization_method,total_mentions,total_reviews,total_businesses,surface_form_count,avg_confidence,avg_rating,positive_mentions,neutral_mentions,negative_mentions,manual_review_status,manual_review_priority
7003,dish_seed_v2_007004,pinwheel,en,dish_catalog_seed_v2,rule_based_v2_overrides,1,1,1,1,0.434031,4.0,1,0,0,pending,3
8670,dish_seed_v2_008671,st,en,dish_catalog_seed_v2,rule_based_v2_overrides,1,1,1,1,0.459022,2.0,0,0,1,pending,3
1939,dish_seed_v2_001940,baguette,en,dish_catalog_seed_v2,rule_based_v2_overrides,1,1,1,1,0.462592,4.0,1,0,0,pending,3
4884,dish_seed_v2_004885,gilled,en,dish_catalog_seed_v2,rule_based_v2_overrides,1,1,1,1,0.463758,4.0,1,0,0,pending,3
1523,dish_seed_v2_001524,tso,en,dish_catalog_seed_v2,rule_based_v2_overrides,2,2,2,1,0.467482,2.5,1,0,1,pending,3
1644,dish_seed_v2_001645,2-salad,en,dish_catalog_seed_v2,rule_based_v2_overrides,1,1,1,1,0.467583,3.0,0,1,0,pending,3
8302,dish_seed_v2_008303,slaw,en,dish_catalog_seed_v2,rule_based_v2_overrides,1,1,1,1,0.489394,5.0,1,0,0,pending,3
6822,dish_seed_v2_006823,patrol,en,dish_catalog_seed_v2,rule_based_v2_overrides,1,1,1,1,0.490808,4.0,1,0,0,pending,3
1741,dish_seed_v2_001742,all,en,dish_catalog_seed_v2,rule_based_v2_overrides,1,1,1,1,0.494391,5.0,1,0,0,pending,3
6285,dish_seed_v2_006286,mother,en,dish_catalog_seed_v2,rule_based_v2_overrides,1,1,1,1,0.494748,5.0,1,0,0,pending,3

,dish_id,canonical_dish_name,language,catalog_version,normalization_method,total_mentions,total_reviews,total_businesses,surface_form_count,avg_confidence,avg_rating,positive_mentions,neutral_mentions,negative_mentions,manual_review_status,manual_review_priority
23,dish_seed_v2_000024,nachos,en,dish_catalog_seed_v2,rule_based_v2_overrides,764,611,311,5,0.992353,3.347742,493,117,154,pending,3
0,dish_seed_v2_000001,pizza,en,dish_catalog_seed_v2,rule_based_v2_overrides,8751,4640,900,4,0.972458,4.005505,5661,1154,1936,pending,4
61,dish_seed_v2_000062,salad,en,dish_catalog_seed_v2,rule_based_v2_overrides,176,173,154,4,0.741223,3.260174,105,30,41,pending,3
34,dish_seed_v2_000035,dumplings,en,dish_catalog_seed_v2,rule_based_v2_overrides,498,407,204,4,0.940333,3.945602,366,64,68,pending,2
22,dish_seed_v2_000023,omelet,en,dish_catalog_seed_v2,rule_based_v2_overrides,779,674,359,4,0.955139,3.877472,534,122,123,pending,3
11,dish_seed_v2_000012,sandwich,en,dish_catalog_seed_v2,rule_based_v2_overrides,2127,1870,882,4,0.752680,3.654794,1595,269,263,pending,4
5,dish_seed_v2_000006,shrimp,en,dish_catalog_seed_v2,rule_based_v2_overrides,4421,3281,881,4,0.819895,4.130603,3167,553,701,pending,4
42,dish_seed_v2_000043,eggplant,en,dish_catalog_seed_v2,rule_based_v2_overrides,381,329,199,4,0.929995,4.619695,288,55,38,pending,2
1,dish_seed_v2_000002,burger,en,dish_catalog_seed_v2,rule_based_v2_overrides,8095,5334,1229,4,0.960858,3.726635,5164,1462,1469,pending,4
122,dish_seed_v2_000123,caesar,en,dish_catalog_seed_v2,rule_based_v2_overrides,21,20,20,3,0.595430,4.017544,11,3,7,pending,3

,mention_id,corpus_document_id,review_id,business_id,business_name,city,state,split,rating_value,sentiment_label,language,source_system_code,source_dataset,dish_mention_text,dish_mention_normalized,start_char,end_char,start_token,end_token,token_count,confidence_mean,confidence_min,confidence_max,tokens,review_text,was_review_truncated,model_name,model_checkpoint,inference_run_name,human_review_status,normalization_status,mention_token_count,mention_char_length,mention_clean,mention_canonical_rule,normalization_flags,is_noise_candidate,normalization_confidence_hint,canonical_dish_name,dish_id,normalization_method,canonical_dish_name_v1,canonical_dish_name_v2,normalization_flags_v2,is_noise_candidate_v2,normalization_status_v2,normalization_method_v2,dish_id_v2
19337,dish_mention_54624608d71a1e8d2832,yelp_39a61463c6f167fdd244d064,_Pj3AEJ5DU2ScrnJwmwkFQ,6CsLAjWXFlLpErBZEmGQ5g,Sky Cafe,Philadelphia,PA,train,4.0,positive,en,yelp_open_dataset,yelp_open_dataset,tempeh,tempeh,479,485,100,101,1,0.356217,0.356217,0.356217,[tempeh],"Great little Indonesian restaurant near Cacias bakery on corner of Ritner & 16th. There is a sign inside warning not to park in front of Cacias. Mostly Indonesian clientele. Food was really good and came out fast. Menu is divided into noodle(w/ broth or stir-fried), rice dishes, a few starters a...",True,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,normalized_rule_based_v1,1,6,tempeh,tempeh,[],False,0.3562,tempeh,dish_seed_000238,rule_based_v1,tempeh,tempeh,[low_model_confidence],False,normalized_rule_based_v2,rule_based_v2_overrides,dish_seed_v2_000235
71605,dish_mention_8f89d5b7fa9c0a6ef9b0,yelp_7619577b390c28556a51de64,C30mh2VJ5VmCGdtqvYILVw,1LVMlrAQeqLgiwFu06kFfw,The Workshop Eatery,Edmonton,AB,validation,3.0,neutral,en,yelp_open_dataset,yelp_open_dataset,loin,loin,718,722,144,145,1,0.366022,0.366022,0.366022,[loin],My wife and I decided to give Workshop Eatery a try after a friend recommended it. We arrived 5:15pm on a Thursday and were promptly seated. The server asked for our drink order and delivered it 10 minutes later at which time she took our order. We started with the Arancini which was very good m...,False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,normalized_rule_based_v1,1,4,loin,loin,[],False,0.3660,loin,dish_seed_000762,rule_based_v1,loin,loin,[low_model_confidence],False,normalized_rule_based_v2,rule_based_v2_overrides,dish_seed_v2_000775
2599,dish_mention_9827050706b82291ce95,yelp_6d425329644c5061f553c795,wKVScyIiwc3cFwyNqLedAw,Gw7UW0E2BguzL9suQnwDeg,SPOT Gourmet Burgers,Philadelphia,PA,train,4.0,positive,en,yelp_open_dataset,yelp_open_dataset,bun,bun,967,970,202,203,1,0.397663,0.397663,0.397663,[bun],"Spot has been on my burger list to try for sometime. Spot burger consistently shows up on numerous best of Philly burger lists. When they opened up shop in Brewery town, I quickly bookmarked Spot and waited for a burger craving to hit me to give it a try. Spot is on West Girard Ave and I was abl...",True,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,normalized_rule_based_v1,1,3,bun,bun,[],False,0.3977,bun,dish_seed_000522,rule_based_v1,bun,bun,[low_model_confidence],False,normalized_rule_based_v2,rule_based_v2_overrides,dish_seed_v2_000529
32966,dish_mention_f83f8e98e3b0e17e5d99,yelp_2f79c62ace9b56eac5db0609,T-qChKcyxWjU5qZEEd4kxA,mCo2uVTTGYrEhRrkQW-CMw,Empress Garden,Philadelphia,PA,train,5.0,positive,en,yelp_open_dataset,yelp_open_dataset,noodle,noodle,210,216,45,46,1,0.398607,0.398607,0.398607,[noodle],"I've been going here since I was a kid. The same waitress that served me twenty years ago is still there. Fast, courteous, even too polite at times. Went today for lunch to get my favorite dish- Taiwanese beef noodle soup. This soup is the best; it certainly holds up against the stuff I've had i...",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,normalized_rule_based_v1,1,6,noodle,noodle,[],False,0.3986,noodle,dish_seed_000150,rule_based_v1,noodle,noodle,[low_model_confidence],False,normalized_rule_based_v2,rule_based_v2_overrides,dish_seed_v2_000147
8814,dish_mention_fd5bea25ff9f98d483b8,yelp_b5fc4ee8f1590138c53aef9d,TeARi2ytr48ynz36u-1ilA,MnxMt3CErrx4dXll4ADqLg,The Flying Cupcake,Indianapolis,IN,train,4.0,positive,en,yelp_open_dataset,yelp_open_dataset,cupcake,cupcake,395,402,79,80,1,0.404182,0.404182,0.404182,[cupcake],"We were shopping in Indianapolis on recent trip and craving something sweet. We saw The Flying Cupcake and stopped by on the way back from the mall. It was around 6 or 7 on a Saturday afternoon and there was not many cupcakes left choose from. I think they had wedding cake cupcake, lemon, bluebe...",True,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,normalized_rule_based_v1,1,7,cupcake,cupcake,[],False,0.4042,cupcake,dish_seed_000128,rule_based_v1,cupcake,cupcake,[low_model_confidence],False,normalized_rule_based_v2,rule_based_v2_overrides,dish_seed_v2_000124
64529,dish_mention_3cd147cc0b830f55f74c,yelp_8c5670e9f1aaba57a1cd0d0e,EaZdky8oXda83zqfVk9FAQ,kKPJLiHIr9Gd9sYs3GhxDQ,Brick & Mortar,Saint Petersburg,FL,train,5.0,positive,en,yelp_open_dataset,yelp_open_dataset,salad,salad,424,429,91,92,1,0.414822,0.414822,0.414822,[salad],My mom and I had a delicious meal here! We are from New Jersey and wanted some good food after a day of travel. We read great reviews and were not disappointed. We started with the Carpaccio which was amazing!! I got the B&M burger for my meal and it had a delicious combination with the aged che...,False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,normalized_rule_based_v1,1,5,salad,salad,[],False,0.4148,salad,dish_seed_000066,rule_based_v1,salad,salad,[low_model_confidence],False,normalized_rule_based_v2,rule_based_v2_overrides,dish_seed_v2_000062
39284,dish_mention_16e53a829ebe0d99b179,yelp_d0d93a240162500337d9e04f,e2hB3V7urRiad9fMgrWOGQ,3JxlbnKRymk8waQ5Z4rQzQ,Ceriello Market Place,Medford,NJ,train,4.0,positive,en,yelp_open_dataset,yelp_open_dataset,pinwheel,pinwheel,311,319,61,62,1,0.434031,0.434031,0.434031,[pinwheel],"I'm originally from Brooklyn, and am an Italian American. I really like Ceriello's. I discovered it first at their location in Grand Central, and was happy to discover their location in Medford, way closer to where I live. Great meats, including Veal, but our favorite is the Brooklyn/Long Island...",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,normalized_rule_based_v1,1,8,pinwheel,pinwheel,[],False,0.4340,pinwheel,dish_seed_006587,rule_based_v1,pinwheel,pinwheel,[low_model_confidence],False,normalized_rule_based_v2,rule_based_v2_overrides,dish_seed_v2_007004
52084,dish_mention_2fedcee70c2e814ce63d,yelp_37cf76d0ed795a4522b56752,sjbp5LeeiMe4hXmqf4iL4A,2rQFgavS-942RapZTBSBTw,Gullifty's Restaurant,Bryn Mawr,PA,train,5.0,positive,en,yelp_open_dataset,yelp_open_dataset,sandwich,sandwich,193,201,40,41,1,0.438024,0.438024,0.438024,[sandwich],"The food and service was excellent. We had wings, Portobello pesto sandwich with sweet potato fries, and an asparagus pasta dish. These were the best wings I ever had, right off the grill. The sandwich was delicious and the pasta dish was creamy with great blend of flavors. Next time I want to t...",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,normalized_rule_based_v1,1,8,sandwich,sandwich,[],False,0.4380,sandwich,dish_seed_000012,rule_based_v1,sandwich,sandwich,[low_model_confidence],False,normalized_rule_based_v2,rule_based_v2_overrides,dish_seed_v2_000012
45154,dish_mention_cbc177ea2f3390ed6a98,yelp_af23410c1c2a6aad5f346f79,j2TVWKKdbWeo9u4oJG3_ww,bjhCtlYHrkgA5Ku8l-rB3g,Our Daily Bread,Santa Barbara,CA,train,4.0,positive,en,yelp_open_dataset,yelp_open_dataset,tomatos,tomatos,1058,1065,237,238,1,0.447881,0.447881,0.447881,[tomatos],Hooray for YELP. How did I get by before Yelp? I was up in Santa Barbara the other day and we noticed this Cafe as we drove around. The next day when we wanted to go out for breakfast I went to YELP to read the reviews. Its rating was good enough for us to go try it and we are so happy we did. T...,True,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,normalized_rule_based_v1,1,7,tomatos,tomato,[],False,0.4279,tomato,dish_seed_000347,rule_based_v1,tomato,tomato,[low_model_confidence],False,normalized_rule_based_v2,rule_based_v2_overrides,dish_seed_v2_000346
57500,dish_mention_454e9bd898c17ecb3b8d,yelp_a4fbe32d4b195c6def404322,3KWAsUQAxewDPd3ZYvimTw,jMZ56S8Y1t7cA1Ob-d-qeA,Three Muses,New Orleans,LA,train,4.0,positive,en,yelp_open_dataset,yelp_open_dataset,Cake,cake,983,987,192,193,1,0.455745,0.455745,0.455745,[Cake],"Really enjoyed this New Orleans gem on Sunday, it was recommended to us by our amazing cocktail tour guide from Drink & Learn. She said this was a favorite place of hers for live music. We walked from our hotel on Canal Street to Frenchman Street and enjoyed the leisurely stroll on some of the n...",False,dish_ner_transformer_full,/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full,full,not_reviewed,normalized_rule_based_v1,1,4,cake,cake,[],False,0.4557,cake,dish_seed_000075,rule_based_v1,cake,cake,[low_model_confidence],False,normalized_rule_based_v2,rule_based_v2_overrides,dish_seed_v2_000071

In [30]:
# ============================================================
# 25. Guardar outputs v2
# ============================================================

mentions_normalized_v2_path = MENTIONS_DIR / "dish_mentions_normalized_v2.jsonl"
surface_forms_v2_path = ARTIFACTS_DIR / "dish_surface_forms_v2.csv"
catalog_v2_path = CATALOG_DIR / "dish_catalog_seed_v2.csv"
aliases_v2_path = ALIASES_DIR / "dish_aliases_seed_v2.csv"
duplicate_candidates_v2_path = ARTIFACTS_DIR / "dish_normalization_duplicate_candidates_v2.csv"

catalog_review_top_path = SAMPLES_DIR / "dish_catalog_review_top_v2.csv"
catalog_review_low_conf_path = SAMPLES_DIR / "dish_catalog_review_low_confidence_v2.csv"
catalog_review_many_aliases_path = SAMPLES_DIR / "dish_catalog_review_many_aliases_v2.csv"
mentions_review_flags_path = SAMPLES_DIR / "dish_mentions_review_flags_v2.jsonl"

summary_v2_path = ARTIFACTS_DIR / "dish_normalization_summary_v2.json"

save_jsonl(mentions_v2_df, mentions_normalized_v2_path)
surface_forms_v2_df.to_csv(surface_forms_v2_path, index=False)
catalog_v2_df.to_csv(catalog_v2_path, index=False)
aliases_v2_df.to_csv(aliases_v2_path, index=False)

if len(duplicate_candidates_v2_df) > 0:
    duplicate_candidates_v2_df.to_csv(duplicate_candidates_v2_path, index=False)
else:
    pd.DataFrame(columns=[
        "canonical_a",
        "canonical_b",
        "similarity_token_sort",
        "similarity_partial",
        "mentions_a",
        "mentions_b",
        "review_priority_a",
        "review_priority_b",
        "suggested_action",
    ]).to_csv(duplicate_candidates_v2_path, index=False)

catalog_review_top_df.to_csv(catalog_review_top_path, index=False)
catalog_review_low_conf_df.to_csv(catalog_review_low_conf_path, index=False)
catalog_review_many_aliases_df.to_csv(catalog_review_many_aliases_path, index=False)
save_jsonl(mentions_review_flags_df, mentions_review_flags_path)

normalization_summary_v2 = {
    "notebook": "08_dish_normalization_and_catalog_builder",
    "version": "v2_rule_based_overrides",
    "source_mentions_path": str(MENTIONS_PATH),
    "input": qa_initial,
    "v1": {
        "normalized_mentions": int(mentions_normalized_df["dish_id"].notna().sum()),
        "pending_or_excluded_mentions": int(mentions_normalized_df["dish_id"].isna().sum()),
        "surface_forms": int(len(surface_forms_df)),
        "canonical_dishes_seed": int(len(catalog_seed_df)),
        "aliases_seed": int(len(aliases_seed_df)),
    },
    "v2": {
        "normalized_mentions": int(mentions_v2_df["dish_id_v2"].notna().sum()),
        "pending_or_excluded_mentions": int(mentions_v2_df["dish_id_v2"].isna().sum()),
        "surface_forms": int(len(surface_forms_v2_df)),
        "canonical_dishes_seed": int(len(catalog_v2_df)),
        "aliases_seed": int(len(aliases_v2_df)),
        "duplicate_candidates": int(len(duplicate_candidates_v2_df)),
        "mentions_with_flags": int(len(mentions_review_flags_df)),
    },
    "outputs": {
        "mentions_normalized_v2": str(mentions_normalized_v2_path),
        "surface_forms_v2": str(surface_forms_v2_path),
        "catalog_seed_v2": str(catalog_v2_path),
        "aliases_seed_v2": str(aliases_v2_path),
        "duplicate_candidates_v2": str(duplicate_candidates_v2_path),
        "catalog_review_top_v2": str(catalog_review_top_path),
        "catalog_review_low_confidence_v2": str(catalog_review_low_conf_path),
        "catalog_review_many_aliases_v2": str(catalog_review_many_aliases_path),
        "mentions_review_flags_v2": str(mentions_review_flags_path),
    },
    "top_canonical_dishes_v2": (
        catalog_v2_df
        .head(50)
        .to_dict(orient="records")
    ),
}

with summary_v2_path.open("w", encoding="utf-8") as f:
    json.dump(normalization_summary_v2, f, indent=2, ensure_ascii=False)

print("Resumen v2 guardado en:")
print(summary_v2_path)

print(json.dumps(normalization_summary_v2, indent=2, ensure_ascii=False)[:5000])

Guardado: /kaggle/working/hidden_gems_ai/outputs/dish_normalization/mentions/dish_mentions_normalized_v2.jsonl (95,061 registros)
Guardado: /kaggle/working/hidden_gems_ai/outputs/dish_normalization/samples/dish_mentions_review_flags_v2.jsonl (300 registros)
Resumen v2 guardado en:
/kaggle/working/hidden_gems_ai/outputs/dish_normalization/artifacts/dish_normalization_summary_v2.json
{
  "notebook": "08_dish_normalization_and_catalog_builder",
  "version": "v2_rule_based_overrides",
  "source_mentions_path": "/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_model_v1_full.jsonl",
  "input": {
    "total_mentions": 95061,
    "unique_reviews": 42471,
    "unique_businesses": 4091,
    "unique_surface_forms": 10258,
    "confidence": {
      "min": 0.35621654987335205,
      "mean": 0.975224027584393,
      "median": 0.9990728795528412,
      "max": 0.9997578263282776
    },
    "split_counts": {
      "train": 76050,
      "validation": 9564,
      "test": 9447
    },
    "sentiment_counts": {
      "positive": 64727,
      "negative": 16411,
      "neutral": 13923
    }
  },
  "v1": {
    "normalized_mentions": 94303,
    "pending_or_excluded_mentions": 758,
    "surface_forms": 10258,
    "canonical_dishes_seed": 9401,
    "aliases_seed": 9692
  },
  "v2": {
    "normalized_mentions": 94932,
    "pending_or_excluded_mentions": 129,
    "surface_forms": 10258,
    "canonical_dishes_seed": 9937,
    "aliases_seed": 10235,
    "duplicate_candidates": 6984,
    "mentions_with_flags": 300
  },
  "outputs": {
    "mentions_normalized_v2": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/mentions/dish_mentions_normalized_v2.jsonl",
    "surface_forms_v2": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/artifacts/dish_surface_forms_v2.csv",
    "catalog_seed_v2": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/catalog/dish_catalog_seed_v2.csv",
    "aliases_seed_v2": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/aliases/dish_aliases_seed_v2.csv",
    "duplicate_candidates_v2": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/artifacts/dish_normalization_duplicate_candidates_v2.csv",
    "catalog_review_top_v2": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/samples/dish_catalog_review_top_v2.csv",
    "catalog_review_low_confidence_v2": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/samples/dish_catalog_review_low_confidence_v2.csv",
    "catalog_review_many_aliases_v2": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/samples/dish_catalog_review_many_aliases_v2.csv",
    "mentions_review_flags_v2": "/kaggle/working/hidden_gems_ai/outputs/dish_normalization/samples/dish_mentions_review_flags_v2.jsonl"
  },
  "top_canonical_dishes_v2": [
    {
      "dish_id": "dish_seed_v2_000001",
      "canonical_dish_name": "pizza",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v2",
      "normalization_method": "rule_based_v2_overrides",
      "total_mentions": 8751,
      "total_reviews": 4640,
      "total_businesses": 900,
      "surface_form_count": 4,
      "avg_confidence": 0.9724581097010846,
      "avg_rating": 4.005505200857654,
      "positive_mentions": 5661,
      "neutral_mentions": 1154,
      "negative_mentions": 1936,
      "manual_review_status": "pending",
      "manual_review_priority": 4
    },
    {
      "dish_id": "dish_seed_v2_000002",
      "canonical_dish_name": "burger",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v2",
      "normalization_method": "rule_based_v2_overrides",
      "total_mentions": 8095,
      "total_reviews": 5334,
      "total_businesses": 1229,
      "surface_form_count": 4,
      "avg_confidence": 0.9608580466666912,
      "avg_rating": 3.7266347161011675,
      "positive_mentions": 5164,
      "neutral_mentions": 1462,
      "negative_mentions": 1469,
      "manual_review_status": "pending",
      "manual_review_priority": 4
    },
    {
      "dish_id": "dish_seed_v2_000003",
      "canonical_dish_name": "fries",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v2",
      "normalization_method": "rule_based_v2_overrides",
      "total_mentions": 5375,
      "total_reviews": 4192,
      "total_businesses": 1314,
      "surface_form_count": 3,
      "avg_confidence": 0.9982086711850222,
      "avg_rating": 3.651662318168863,
      "positive_mentions": 3275,
      "neutral_mentions": 1010,
      "negative_mentions": 1090,
      "manual_review_status": "pending",
      "manual_review_priority": 4
    },
    {
      "dish_id": "dish_seed_v2_000004",
      "canonical_dish_name": "sushi",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v2",
      "normalization_method": "rule_based_v2_overrides",
      "total_mentions": 4470,
      "total_reviews": 2484,
      "total_businesses": 275,
      "surface_form_count": 3,
      "avg_confidence": 0.9992045097301906,
      "avg_rating": 3.349617318346303,
      "positive_mentions": 3067,
      "neutral_mentions": 613,
      "negative_mentions": 790,
      "manual_review_status": "pending",
      "manual_review_priority": 4
    },
    {
      "dish_id": "dish_seed_v2_000005",
      "canonical_dish_name": "tacos",
      "language": "en",
      "catalog_version": "dish_catalog_seed_v2",
      "normalization_method": "rule_based_

## Cierre provisional del bloque 2

En este bloque se ha generado una versión v2 del normalizador de platos.

La v2 corrige errores claros de la v1, especialmente derivados de una singularización demasiado agresiva:

- `hummu` → `hummus`
- `crab cak` → `crab cakes`
- `wing` → `wings`
- `rib` → `ribs`
- `nacho` → `nachos`
- `mashed potato` → `mashed potatoes`
- `french fries` → `fries`

También se han generado candidatos de duplicados y muestras de revisión manual.

El archivo principal para continuar el flujo será:

`dish_mentions_normalized_v2.jsonl`

Este archivo servirá como entrada para el siguiente módulo:

`09_dish_mention_sentiment.ipynb`