# 10 - Agregación de señales gastronómicas

## Objetivo

Este notebook construye el primer sistema de agregación de señales para Hidden Gems.

Partimos del archivo:

`dish_mentions_with_sentiment_hybrid_v1.jsonl`

Ese archivo contiene menciones de platos ya detectadas, normalizadas y enriquecidas con sentimiento por mención.

El objetivo de este módulo es transformar menciones individuales en señales agregadas:

```text
mención individual
→ plato normalizado
→ sentimiento
→ confianza
→ fiabilidad
→ agregación por plato
→ agregación por plato + negocio

```
## Agregaciones principales

Se generarán dos tablas principales:

dish_global_signals_v1.csv

Agregación global por plato:

pizza
burger
fries
sushi
tacos
...
dish_business_signals_v1.csv

Agregación por plato dentro de cada negocio:

business_id + dish_id

Esta segunda tabla será fundamental para el ranking posterior.

## Métricas calculadas

Se calcularán señales como:

- número de menciones;
- número de reviews;
- número de negocios;
- menciones positivas, neutrales y negativas;
- ratio positivo;
- ratio negativo;
- sentimiento medio;
- sentimiento ponderado por confianza;
- menciones de alta fiabilidad;
- confianza media del NER;
- confianza media del sentimiento;
- señales mínimas para ranking.


## Salidas esperadas

dish_global_signals_v1.csv
dish_business_signals_v1.csv
dish_signal_aggregation_summary_v1.json
muestras de revisión para ranking posterior

In [1]:
# ============================================================
# 01. Imports y configuración base
# ============================================================

from pathlib import Path
import json
import random
import re
import os
import warnings
from collections import Counter

import numpy as np
import pandas as pd

from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

RANDOM_STATE = 42

random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

pd.set_option("display.max_columns", 180)
pd.set_option("display.max_colwidth", 350)

print("Entorno inicializado correctamente.")

Entorno inicializado correctamente.

In [2]:
# ============================================================
# 02. Detectar entorno y preparar carpetas
# ============================================================

IS_KAGGLE = Path("/kaggle/input").exists()
IS_COLAB = "google.colab" in str(get_ipython()) if "get_ipython" in globals() else False

if IS_KAGGLE:
    ENV_NAME = "kaggle"
elif IS_COLAB:
    ENV_NAME = "colab"
else:
    ENV_NAME = "local"

print("Entorno detectado:", ENV_NAME)

if IS_KAGGLE:
    INPUT_DIR = Path("/kaggle/input")
    WORKING_DIR = Path("/kaggle/working")
    PROJECT_DIR = WORKING_DIR / "hidden_gems_ai"

elif IS_COLAB:
    from google.colab import drive

    try:
        !fusermount -u /content/drive 2>/dev/null || true
        !rm -rf /content/drive

        drive.mount("/content/drive", force_remount=True, timeout_ms=120000)

        PROJECT_DIR = Path("/content/drive/MyDrive/hidden_gems_ai")

    except Exception as e:
        print("No se ha podido montar Drive. Se usará almacenamiento temporal.")
        print("Error:", e)

        PROJECT_DIR = Path("/content/hidden_gems_ai")

else:
    PROJECT_DIR = Path.cwd()

OUTPUT_DIR = PROJECT_DIR / "outputs" / "dish_signal_aggregation"
SIGNALS_DIR = OUTPUT_DIR / "signals"
ARTIFACTS_DIR = OUTPUT_DIR / "artifacts"
SAMPLES_DIR = OUTPUT_DIR / "samples"

for path in [
    PROJECT_DIR,
    OUTPUT_DIR,
    SIGNALS_DIR,
    ARTIFACTS_DIR,
    SAMPLES_DIR,
]:
    path.mkdir(parents=True, exist_ok=True)

print("PROJECT_DIR:", PROJECT_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)

Entorno detectado: kaggle
PROJECT_DIR: /kaggle/working/hidden_gems_ai
OUTPUT_DIR: /kaggle/working/hidden_gems_ai/outputs/dish_signal_aggregation

In [3]:
# ============================================================
# 03. Diagnóstico de archivos disponibles
# ============================================================

if IS_KAGGLE:
    print("Archivos disponibles en /kaggle/input:")

    for dirname, _, filenames in os.walk("/kaggle/input"):
        for filename in filenames:
            print(os.path.join(dirname, filename))
else:
    print("No estás en Kaggle. Se buscarán archivos en el proyecto local.")

Archivos disponibles en /kaggle/input:
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_labels.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_bio_high_precision_with_negatives.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_normalization_summary_v2.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_detection_manual_review_sample_v2_150.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/transformer_sentiment_metrics.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_with_sentiment_hybrid_v1.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/weak_dish_candidates_v2.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_inference_summary_full.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_detection_exploration_summary_v2.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mention_sentiment_summary_hybrid_v1.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/yelp_translation_gold_seed_300_es_ready_v1.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_normalized_v2.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_model_v1_full.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_bio_smoke_test.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/weak_dish_candidate_frequencies_v2.csv
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_lexicon_seed_v1.csv
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/classic_model_metrics.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/yelp_food_reviews_corpus_sample_100k_lines.jsonl
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full/config.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full/training_args.bin
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full/tokenizer.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full/tokenizer_config.json
/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_ner_transformer_full/model.safetensors

In [4]:
# ============================================================
# 04. Localizar archivo de menciones con sentimiento
# ============================================================

MENTIONS_SENTIMENT_FILENAME = "dish_mentions_with_sentiment_hybrid_v1.jsonl"
SENTIMENT_SUMMARY_FILENAME = "dish_mention_sentiment_summary_hybrid_v1.json"

def find_file(filename: str) -> Path:
    candidate_paths = []

    if IS_KAGGLE:
        candidate_paths.extend(list(Path("/kaggle/input").rglob(filename)))

    candidate_paths.extend(list(PROJECT_DIR.rglob(filename)))
    candidate_paths.extend(list(Path.cwd().rglob(filename)))

    candidate_paths = list(dict.fromkeys(candidate_paths))

    if not candidate_paths:
        raise FileNotFoundError(
            f"No se ha encontrado el archivo requerido: {filename}\n"
            "En Kaggle, asegúrate de haberlo añadido desde Add Data."
        )

    return candidate_paths[0]


MENTIONS_SENTIMENT_PATH = find_file(MENTIONS_SENTIMENT_FILENAME)

try:
    SENTIMENT_SUMMARY_PATH = find_file(SENTIMENT_SUMMARY_FILENAME)
except FileNotFoundError:
    SENTIMENT_SUMMARY_PATH = None

print("MENTIONS_SENTIMENT_PATH:", MENTIONS_SENTIMENT_PATH)
print("SENTIMENT_SUMMARY_PATH:", SENTIMENT_SUMMARY_PATH)

MENTIONS_SENTIMENT_PATH: /kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_with_sentiment_hybrid_v1.jsonl
SENTIMENT_SUMMARY_PATH: /kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mention_sentiment_summary_hybrid_v1.json

In [5]:
# ============================================================
# 05. Funciones auxiliares de carga y guardado
# ============================================================

def load_jsonl(path: Path) -> pd.DataFrame:
    records = []
    invalid_json_count = 0

    with path.open("r", encoding="utf-8") as f:
        for line in tqdm(f, desc=f"Leyendo {path.name}"):
            line = line.strip()

            if not line:
                continue

            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                invalid_json_count += 1

    print(f"Archivo: {path.name}")
    print(f"Registros cargados: {len(records):,}")
    print(f"Líneas JSON inválidas: {invalid_json_count:,}")

    return pd.DataFrame(records)


def make_json_safe(value):
    if isinstance(value, (np.integer,)):
        return int(value)

    if isinstance(value, (np.floating,)):
        if np.isnan(value):
            return None
        return float(value)

    if isinstance(value, (np.bool_,)):
        return bool(value)

    if isinstance(value, float) and np.isnan(value):
        return None

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, set):
        return sorted(list(value))

    return value


def save_jsonl(df_to_save: pd.DataFrame, path: Path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as f:
        for record in df_to_save.to_dict(orient="records"):
            clean_record = {
                str(key): make_json_safe(value)
                for key, value in record.items()
            }

            f.write(json.dumps(clean_record, ensure_ascii=False) + "\n")

    print(f"Guardado: {path} ({len(df_to_save):,} registros)")

In [6]:
# ============================================================
# 06. Cargar menciones con sentimiento
# ============================================================

mentions_raw_df = load_jsonl(MENTIONS_SENTIMENT_PATH)

print("Shape:", mentions_raw_df.shape)

print("\nColumnas:")
print(mentions_raw_df.columns.tolist())

display(mentions_raw_df.head(5))

if SENTIMENT_SUMMARY_PATH is not None:
    with SENTIMENT_SUMMARY_PATH.open("r", encoding="utf-8") as f:
        sentiment_summary = json.load(f)

    print("\nResumen del módulo 09:")
    print(json.dumps(sentiment_summary, indent=2, ensure_ascii=False)[:4000])

Leyendo dish_mentions_with_sentiment_hybrid_v1.jsonl: 0it [00:00, ?it/s]

Archivo: dish_mentions_with_sentiment_hybrid_v1.jsonl
Registros cargados: 94,932
Líneas JSON inválidas: 0
Shape: (94932, 48)

Columnas:
['mention_id', 'corpus_document_id', 'review_id', 'business_id', 'business_name', 'city', 'state', 'split', 'language', 'source_system_code', 'source_dataset', 'dish_mention_text', 'dish_mention_normalized', 'canonical_dish_name_v2', 'dish_id_v2', 'normalization_status_v2', 'normalization_method_v2', 'start_char', 'end_char', 'start_token', 'end_token', 'token_count', 'confidence_mean', 'confidence_min', 'confidence_max', 'rating_value', 'sentiment_label', 'review_text', 'sentence_context', 'window_context', 'target_clause_context_v11', 'near_mention_context_v11', 'mention_sentiment_label_final', 'mention_sentiment_score_final', 'mention_sentiment_confidence_final', 'sentiment_reliability_tier', 'sentiment_reason_final', 'sentiment_flags_final', 'sentiment_method_final', 'positive_terms_v11', 'negative_terms_v11', 'target_signal_strength_v11', 'rating_prior_score_v11', 'review_prior_score_v11', 'direct_positive_count_v11', 'direct_negative_count_v11', 'is_sentiment_training_candidate', 'human_review_status']

,mention_id,corpus_document_id,review_id,business_id,business_name,city,state,split,language,source_system_code,source_dataset,dish_mention_text,dish_mention_normalized,canonical_dish_name_v2,dish_id_v2,normalization_status_v2,normalization_method_v2,start_char,end_char,start_token,end_token,token_count,confidence_mean,confidence_min,confidence_max,rating_value,sentiment_label,review_text,sentence_context,window_context,target_clause_context_v11,near_mention_context_v11,mention_sentiment_label_final,mention_sentiment_score_final,mention_sentiment_confidence_final,sentiment_reliability_tier,sentiment_reason_final,sentiment_flags_final,sentiment_method_final,positive_terms_v11,negative_terms_v11,target_signal_strength_v11,rating_prior_score_v11,review_prior_score_v11,direct_positive_count_v11,direct_negative_count_v11,is_sentiment_training_candidate,human_review_status
0,dish_mention_c6a233f28ab0ec50a4bf,yelp_94c5a64cecd4448d105e5c8a,saUsX_uimxRlCVr67Z4Jig,YjUWPpI6HXG530lwP-fb2A,Kettle Restaurant,Tucson,AZ,train,en,yelp_open_dataset,yelp_open_dataset,tamale,tamale,tamale,dish_seed_v2_000060,normalized_rule_based_v2,rule_based_v2_overrides,88,94,18,19,1,0.997417,0.997417,0.997417,3.0,neutral,"Family diner. Had the buffet. Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon. All good. Lots of Mexican choices there. Also has a menu with breakfast served all day long. Friendly, attentive staff. Good place for a casual relaxed meal with no expectations. Next to the Clarion Hotel.","Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon.","Family diner. Had the buffet. Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon. All good. Lots of Mexican choices there. Also has a menu with breakfast served a","Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon.","rtment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon. All good. Lots of Mexican choices there. Also has",positive,1.1500,0.7066,medium,target_context_primary,[],hybrid_context_lexicon_v1_1,"[fresh:positive_lexicon, good:positive_lexicon]",[],1.8,0.00,0.00,0,0,False,not_reviewed
1,dish_mention_370e33f760028e4e87a3,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,en,yelp_open_dataset,yelp_open_dataset,lamb curry,lamb curry,lamb curry,dish_seed_v2_000205,normalized_rule_based_v2,rule_based_v2_overrides,54,64,12,14,2,0.996373,0.993416,0.999331,5.0,positive,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",Our favorite is the lamb curry and korma.,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...g",Our favorite is the lamb curry and korma.,"y, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we",positive,1.2130,0.7128,medium,target_context_primary,[],hybrid_context_lexicon_v1_1,"[delicious:positive_lexicon, favorite:positive_lexicon]",[],1.8,0.75,0.35,0,0,False,not_reviewed
2,dish_mention_2c51d464763786d9fef2,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,en,yelp_open_dataset,yelp_open_dataset,korma,korma,korma,dish_seed_v2_000074,normalized_rule_based_v2,rule_based_v2_overrides,69,74,15,16,1,0.997466,0.997466,0.997466,5.0,positive,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",Our favorite is the lamb curry and korma.,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and t",Our favorite is the lamb curry and korma.,elicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost ch,positive,0.9630,0.6720,medium,target_context_primary,[],hybrid_context_lexicon_v1_1,[favorite:positive_lexicon],[],1.4,0.75,0.35,0,0,False,not_reviewed
3,dish_mention_6cfa246893992204e58a,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,en,yelp_open_dataset,yelp_open_dataset,naan,naan,naan,dish_seed_v2_000044,normalized_rule_based_v2,rule_based_v2_overrides,103,107,22,23,1,0.998627,0.998627,0.998627,5.0,positive,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",With 10 different kinds of naan!!!,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad",With 10 different kinds of naan!,curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try,neutral,0.3465,0.2876,low,review_prior_fallback,"[used_review_prior_fallback, weak_target_sentiment_signal]",hybrid_context_lexicon_v1_1,[],[],0.0,0.75,0.35,0,0,False,not_reviewed
4,dish_mention_e468cc705c76b7c9e84f,yelp_95095495afc3a77ce68723a2,Sx8TMOWLNuJBWer-0pcmoA,e4Vwtrqf-wpJfwesgvdgxQ,Melt,New Orleans,LA,train,en,yelp_open_dataset,yelp_open_dataset,sandwiches,sandwiches,sandwich,dish_seed_v2_000012,normalized_rule_based_v2,rule_based_v2_overrides,185,195,38,39,1,0.999447,0.999447,0.999447,4.0,positive,"Cute interior and owner (?) gave us tour of upcoming patio/rooftop area which will be great on beautiful days like today. Cheese curds were very good and very filling. Really like that sandwiches come w salad, esp after eating too many curds! Had the onion, gruyere, tomato sandwich. Wasn't too much cheese which I liked. Needed something else......","Really like that sandwiches come w salad, esp after eating too many curds!","p area which will be great on beautiful days like today. Cheese curds were very good and very filling. Really like that sandwiches come w salad, esp after eating too many curds! Had the onion, gruyere, tomato sandwich. Wasn't too much cheese which I","Really like that sandwiches come w salad, esp after eating too many curds!","very good and very filling. Really like that sandwiches come w salad, esp after eating too many curds! Had the onion, gruyere, tomato sandwich. W",positive,0.8545,0.6574,medium,target_context_primary,[],hybrid_context_lexicon_v1_1,"[good:positive_lexicon, positive_phrase:positive_phrase]",[],1.3,0.45,0.35,0,0,False,not_reviewed

Resumen del módulo 09:
{
  "notebook": "09_dish_mention_sentiment_hybrid_v1",
  "version": "hybrid_context_lexicon_v1_1",
  "source_mentions_path": "/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_normalized_v2.jsonl",
  "input": {
    "total_mentions_for_sentiment": 94932,
    "unique_reviews": 42461,
    "unique_businesses": 4088,
    "unique_dishes": 9937,
    "unique_canonical_dish_names": 9937,
    "confidence": {
      "min": 0.35621654987335205,
      "mean": 0.97570959051333,
      "median": 0.9990743398666382,
      "max": 0.9997578263282776
    },
    "rating_counts": {
      "1.0": 7363,
      "2.0": 9032,
      "3.0": 13904,
      "4.0": 29471,
      "5.0": 35162
    },
    "review_sentiment_counts": {
      "positive": 64633,
      "negative": 16395,
      "neutral": 13904
    },
    "split_counts": {
      "train": 75951,
      "validation": 9546,
      "test": 9435
    },
    "top_dishes": {
      "pizza": 8751,
      "burger": 8095,
      "fries": 5375,
      "sushi": 4470,
      "tacos": 4436,
      "shrimp": 4421,
      "steak": 2794,
      "ice cream": 2411,
      "wings": 2215,
      "donut": 2175,
      "oysters": 2129,
      "sandwich": 2127,
      "pancake": 2035,
      "crab": 1535,
      "burrito": 1405,
      "pho": 1225,
      "salmon": 1137,
      "ribs": 1095,
      "fried chicken": 933,
      "tuna": 890,
      "waffle": 879,
      "french toast": 877,
      "omelet": 779,
      "nachos": 764,
      "brisket": 753,
      "lobster": 745,
      "mac and cheese": 707,
      "hummus": 632,
      "pulled pork": 601,
      "calamari": 600,
      "pad thai": 543,
      "fried rice": 539,
      "mussels": 538,
      "crab cakes": 534,
      "dumplings": 498,
      "ramen": 460,
      "latte": 446,
      "quesadilla": 434,
      "spring rolls": 418,
      "enchilada": 407,
      "mashed potatoes": 400,
      "cheesecake": 392,
      "eggplant": 381,
      "naan": 359,
      "smoothie": 342,
      "ravioli": 328,
      "cheeseburger": 320,
      "custard": 276,
      "chicken wings": 275,
      "eggs benedict": 271
    }
  },
  "final_sentiment_qa": {
    "total_mentions": 94932,
    "mention_sentiment_counts": {
      "neutral": 45366,
      "positive": 43142,
      "negative": 6424
    },
    "sentiment_reliability_tier_counts": {
      "low": 44426,
      "medium": 25495,
      "high": 25011
    },
    "sentiment_reason_counts": {
      "target_context_primary": 50956,
      "review_prior_fallback": 43976
    },
    "sentiment_flag_counts": {
      "used_review_prior_fallback": 43976,
      "weak_target_sentiment_signal": 43976,
      "contrast_marker_nearby": 22594,
      "direct_positive_pattern": 17883,
      "mixed_target_evidence": 8166,
      "low_ner_confidence": 4769,
      "ambiguous_mixed_resolved_as_neutral": 4068,
      "direct_negative_pattern": 2365
    },
    "training_candidate_counts": {
      "False": 69921,
      "True": 25011
    },
    "confidence": {
      "min": 0.166,
      "mean": 0.5511806840685965,
      "median": 0.6141,
      "max": 0.95
    },
    "label_by_review_sentiment": {
      "negative": {
        "negative": 4076,
        "neutral": 1249,
        "positive": 1099
      },
      "neutral": {
        "negative": 10127,
        "neutral": 8246,
        "positive": 26993
      },
      "positive": {
        "negative": 2192,
        "neutral": 4409,
        "positive": 36541
      }
    },
    "label_by_rating": {
      "negative": {
        "1.0": 2184,
        "2.0": 1892,
        "3.0": 1249,
        "4.0": 726,
        "5.0": 373
      },
      "neutral": {
        "1.0": 4452,
        "2.0": 5675,
        "3.0": 8246,
        "4.0": 13769,
        "5.0": 13224
      },
      "positive": {
        "1.0": 727,
        "2.0": 1465,
        "3.0": 4409,
        "4.0": 14976,
        "5.0": 21565
      }
    },
    "label_by_reliability": {
      "negative": {
        "high": 2689,
        "low": 345,
        "medium": 3390
      },
      "neutral": {
        "hig

In [7]:
# ============================================================
# 07. Validación de columnas necesarias
# ============================================================

required_cols = [
    "mention_id",
    "review_id",
    "business_id",
    "dish_id_v2",
    "canonical_dish_name_v2",
    "dish_mention_text",
    "confidence_mean",
    "rating_value",
    "sentiment_label",
    "mention_sentiment_label_final",
    "mention_sentiment_score_final",
    "mention_sentiment_confidence_final",
    "sentiment_reliability_tier",
    "sentiment_reason_final",
    "is_sentiment_training_candidate",
]

missing_cols = [
    col for col in required_cols
    if col not in mentions_raw_df.columns
]

if missing_cols:
    raise ValueError(f"Faltan columnas obligatorias: {missing_cols}")

print("Columnas obligatorias presentes.")

print("\nNulos principales:")
display(
    mentions_raw_df[required_cols]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print("\nDuplicados mention_id:")
print(mentions_raw_df["mention_id"].duplicated().sum())

Columnas obligatorias presentes.

Nulos principales:

mention_id                            0
review_id                             0
business_id                           0
dish_id_v2                            0
canonical_dish_name_v2                0
dish_mention_text                     0
confidence_mean                       0
rating_value                          0
sentiment_label                       0
mention_sentiment_label_final         0
mention_sentiment_score_final         0
mention_sentiment_confidence_final    0
sentiment_reliability_tier            0
sentiment_reason_final                0
is_sentiment_training_candidate       0
dtype: int64

Duplicados mention_id:
0

In [8]:
# ============================================================
# 08. Preparar dataframe base para agregación
# ============================================================

mentions_df = mentions_raw_df.copy()

# IDs
mentions_df["mention_id"] = mentions_df["mention_id"].astype(str)
mentions_df["review_id"] = mentions_df["review_id"].astype(str)
mentions_df["business_id"] = mentions_df["business_id"].astype(str)
mentions_df["dish_id_v2"] = mentions_df["dish_id_v2"].astype(str)

# Texto de plato
mentions_df["canonical_dish_name_v2"] = (
    mentions_df["canonical_dish_name_v2"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.lower()
    .str.strip()
)

mentions_df["dish_mention_text"] = (
    mentions_df["dish_mention_text"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

# Numéricos
numeric_cols = [
    "confidence_mean",
    "confidence_min",
    "confidence_max",
    "rating_value",
    "mention_sentiment_score_final",
    "mention_sentiment_confidence_final",
]

for col in numeric_cols:
    if col in mentions_df.columns:
        mentions_df[col] = pd.to_numeric(mentions_df[col], errors="coerce")

# Categóricos
mentions_df["mention_sentiment_label_final"] = (
    mentions_df["mention_sentiment_label_final"]
    .astype(str)
    .str.lower()
    .str.strip()
)

mentions_df["sentiment_reliability_tier"] = (
    mentions_df["sentiment_reliability_tier"]
    .astype(str)
    .str.lower()
    .str.strip()
)

mentions_df["sentiment_label"] = (
    mentions_df["sentiment_label"]
    .astype(str)
    .str.lower()
    .str.strip()
)

if "split" in mentions_df.columns:
    mentions_df["split"] = mentions_df["split"].astype(str).str.lower().str.strip()
else:
    mentions_df["split"] = "unknown"

# Limpieza de válidos
valid_sentiment_labels = {"positive", "neutral", "negative"}
valid_reliability_tiers = {"high", "medium", "low"}

before_count = len(mentions_df)

mentions_df = mentions_df[
    mentions_df["dish_id_v2"].notna()
    & (mentions_df["dish_id_v2"].str.len() > 0)
    & mentions_df["canonical_dish_name_v2"].notna()
    & (mentions_df["canonical_dish_name_v2"].str.len() > 0)
    & mentions_df["mention_sentiment_label_final"].isin(valid_sentiment_labels)
    & mentions_df["sentiment_reliability_tier"].isin(valid_reliability_tiers)
    & mentions_df["mention_sentiment_score_final"].notna()
    & mentions_df["mention_sentiment_confidence_final"].notna()
].copy()

after_count = len(mentions_df)

print("Menciones antes:", before_count)
print("Menciones válidas para agregación:", after_count)
print("Descartadas:", before_count - after_count)

display(mentions_df.head(5))

Menciones antes: 94932
Menciones válidas para agregación: 94932
Descartadas: 0

,mention_id,corpus_document_id,review_id,business_id,business_name,city,state,split,language,source_system_code,source_dataset,dish_mention_text,dish_mention_normalized,canonical_dish_name_v2,dish_id_v2,normalization_status_v2,normalization_method_v2,start_char,end_char,start_token,end_token,token_count,confidence_mean,confidence_min,confidence_max,rating_value,sentiment_label,review_text,sentence_context,window_context,target_clause_context_v11,near_mention_context_v11,mention_sentiment_label_final,mention_sentiment_score_final,mention_sentiment_confidence_final,sentiment_reliability_tier,sentiment_reason_final,sentiment_flags_final,sentiment_method_final,positive_terms_v11,negative_terms_v11,target_signal_strength_v11,rating_prior_score_v11,review_prior_score_v11,direct_positive_count_v11,direct_negative_count_v11,is_sentiment_training_candidate,human_review_status
0,dish_mention_c6a233f28ab0ec50a4bf,yelp_94c5a64cecd4448d105e5c8a,saUsX_uimxRlCVr67Z4Jig,YjUWPpI6HXG530lwP-fb2A,Kettle Restaurant,Tucson,AZ,train,en,yelp_open_dataset,yelp_open_dataset,tamale,tamale,tamale,dish_seed_v2_000060,normalized_rule_based_v2,rule_based_v2_overrides,88,94,18,19,1,0.997417,0.997417,0.997417,3.0,neutral,"Family diner. Had the buffet. Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon. All good. Lots of Mexican choices there. Also has a menu with breakfast served all day long. Friendly, attentive staff. Good place for a casual relaxed meal with no expectations. Next to the Clarion Hotel.","Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon.","Family diner. Had the buffet. Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon. All good. Lots of Mexican choices there. Also has a menu with breakfast served a","Eclectic assortment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon.","rtment: a large chicken leg, fried jalapeño, tamale, two rolled grape leaves, fresh melon. All good. Lots of Mexican choices there. Also has",positive,1.1500,0.7066,medium,target_context_primary,[],hybrid_context_lexicon_v1_1,"[fresh:positive_lexicon, good:positive_lexicon]",[],1.8,0.00,0.00,0,0,False,not_reviewed
1,dish_mention_370e33f760028e4e87a3,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,en,yelp_open_dataset,yelp_open_dataset,lamb curry,lamb curry,lamb curry,dish_seed_v2_000205,normalized_rule_based_v2,rule_based_v2_overrides,54,64,12,14,2,0.996373,0.993416,0.999331,5.0,positive,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",Our favorite is the lamb curry and korma.,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...g",Our favorite is the lamb curry and korma.,"y, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we",positive,1.2130,0.7128,medium,target_context_primary,[],hybrid_context_lexicon_v1_1,"[delicious:positive_lexicon, favorite:positive_lexicon]",[],1.8,0.75,0.35,0,0,False,not_reviewed
2,dish_mention_2c51d464763786d9fef2,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,en,yelp_open_dataset,yelp_open_dataset,korma,korma,korma,dish_seed_v2_000074,normalized_rule_based_v2,rule_based_v2_overrides,69,74,15,16,1,0.997466,0.997466,0.997466,5.0,positive,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",Our favorite is the lamb curry and korma.,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and t",Our favorite is the lamb curry and korma.,elicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost ch,positive,0.9630,0.6720,medium,target_context_primary,[],hybrid_context_lexicon_v1_1,[favorite:positive_lexicon],[],1.4,0.75,0.35,0,0,False,not_reviewed
3,dish_mention_6cfa246893992204e58a,yelp_69e10d25d69774ab39af6571,AqPFMleE6RsU23_auESxiA,kxX2SOes4o-D3ZQBkiMRfA,Zaika,Philadelphia,PA,train,en,yelp_open_dataset,yelp_open_dataset,naan,naan,naan,dish_seed_v2_000044,normalized_rule_based_v2,rule_based_v2_overrides,103,107,22,23,1,0.998627,0.998627,0.998627,5.0,positive,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad you did!",With 10 different kinds of naan!!!,"Wow! Yummy, different, delicious. Our favorite is the lamb curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try something new! You'll be glad",With 10 different kinds of naan!,curry and korma. With 10 different kinds of naan!!! Don't let the outside deter you (because we almost changed our minds)...go in and try,neutral,0.3465,0.2876,low,review_prior_fallback,"[used_review_prior_fallback, weak_target_sentiment_signal]",hybrid_context_lexicon_v1_1,[],[],0.0,0.75,0.35,0,0,False,not_reviewed
4,dish_mention_e468cc705c76b7c9e84f,yelp_95095495afc3a77ce68723a2,Sx8TMOWLNuJBWer-0pcmoA,e4Vwtrqf-wpJfwesgvdgxQ,Melt,New Orleans,LA,train,en,yelp_open_dataset,yelp_open_dataset,sandwiches,sandwiches,sandwich,dish_seed_v2_000012,normalized_rule_based_v2,rule_based_v2_overrides,185,195,38,39,1,0.999447,0.999447,0.999447,4.0,positive,"Cute interior and owner (?) gave us tour of upcoming patio/rooftop area which will be great on beautiful days like today. Cheese curds were very good and very filling. Really like that sandwiches come w salad, esp after eating too many curds! Had the onion, gruyere, tomato sandwich. Wasn't too much cheese which I liked. Needed something else......","Really like that sandwiches come w salad, esp after eating too many curds!","p area which will be great on beautiful days like today. Cheese curds were very good and very filling. Really like that sandwiches come w salad, esp after eating too many curds! Had the onion, gruyere, tomato sandwich. Wasn't too much cheese which I","Really like that sandwiches come w salad, esp after eating too many curds!","very good and very filling. Really like that sandwiches come w salad, esp after eating too many curds! Had the onion, gruyere, tomato sandwich. W",positive,0.8545,0.6574,medium,target_context_primary,[],hybrid_context_lexicon_v1_1,"[good:positive_lexicon, positive_phrase:positive_phrase]",[],1.3,0.45,0.35,0,0,False,not_reviewed

In [9]:
# ============================================================
# 09. Crear pesos y señales numéricas
# ============================================================

RELIABILITY_WEIGHT_MAP = {
    "high": 1.00,
    "medium": 0.65,
    "low": 0.25,
}

SENTIMENT_LABEL_SCORE_MAP = {
    "positive": 1.0,
    "neutral": 0.0,
    "negative": -1.0,
}

mentions_df["reliability_weight"] = mentions_df["sentiment_reliability_tier"].map(
    RELIABILITY_WEIGHT_MAP
).fillna(0.25)

mentions_df["sentiment_label_score"] = mentions_df["mention_sentiment_label_final"].map(
    SENTIMENT_LABEL_SCORE_MAP
).fillna(0.0)

# Score híbrido normalizado a [-1, 1].
# El score del módulo 09 está aproximadamente en [-5, 5].
mentions_df["sentiment_score_normalized"] = (
    mentions_df["mention_sentiment_score_final"] / 5.0
).clip(-1.0, 1.0)

# Peso total de señal: fiabilidad * confianza del sentimiento * confianza NER.
mentions_df["ner_confidence"] = mentions_df["confidence_mean"].fillna(1.0).clip(0.0, 1.0)
mentions_df["sentiment_confidence"] = mentions_df["mention_sentiment_confidence_final"].fillna(0.0).clip(0.0, 1.0)

mentions_df["signal_weight"] = (
    mentions_df["reliability_weight"]
    * mentions_df["sentiment_confidence"]
    * mentions_df["ner_confidence"]
)

# Señal final combinada: usamos etiqueta y score continuo.
mentions_df["weighted_sentiment_value"] = (
    0.65 * mentions_df["sentiment_label_score"]
    + 0.35 * mentions_df["sentiment_score_normalized"]
)

mentions_df["weighted_sentiment_value"] = mentions_df["weighted_sentiment_value"].clip(-1.0, 1.0)

mentions_df["weighted_sentiment_contribution"] = (
    mentions_df["weighted_sentiment_value"]
    * mentions_df["signal_weight"]
)

mentions_df["positive_signal"] = np.where(
    mentions_df["mention_sentiment_label_final"] == "positive",
    mentions_df["signal_weight"],
    0.0
)

mentions_df["negative_signal"] = np.where(
    mentions_df["mention_sentiment_label_final"] == "negative",
    mentions_df["signal_weight"],
    0.0
)

mentions_df["neutral_signal"] = np.where(
    mentions_df["mention_sentiment_label_final"] == "neutral",
    mentions_df["signal_weight"],
    0.0
)

mentions_df["is_high_reliability"] = mentions_df["sentiment_reliability_tier"] == "high"
mentions_df["is_medium_reliability"] = mentions_df["sentiment_reliability_tier"] == "medium"
mentions_df["is_low_reliability"] = mentions_df["sentiment_reliability_tier"] == "low"

print("Distribución de signal_weight:")
display(mentions_df["signal_weight"].describe())

print("\nDistribución de weighted_sentiment_value:")
display(mentions_df["weighted_sentiment_value"].describe())

display(
    mentions_df[
        [
            "dish_mention_text",
            "canonical_dish_name_v2",
            "mention_sentiment_label_final",
            "mention_sentiment_score_final",
            "sentiment_score_normalized",
            "sentiment_reliability_tier",
            "signal_weight",
            "weighted_sentiment_value",
            "weighted_sentiment_contribution",
        ]
    ].head(10)
)

Distribución de signal_weight:

count    94932.000000
mean         0.377814
std          0.336725
min          0.020312
25%          0.071769
50%          0.362497
75%          0.753798
max          0.949770
Name: signal_weight, dtype: float64

Distribución de weighted_sentiment_value:

count    94932.000000
mean         0.311703
std          0.480739
min         -1.000000
25%          0.013090
50%          0.041755
75%          0.752410
max          1.000000
Name: weighted_sentiment_value, dtype: float64

,dish_mention_text,canonical_dish_name_v2,mention_sentiment_label_final,mention_sentiment_score_final,sentiment_score_normalized,sentiment_reliability_tier,signal_weight,weighted_sentiment_value,weighted_sentiment_contribution
0,tamale,tamale,positive,1.1500,0.2300,medium,0.458103,0.730500,0.334645
1,lamb curry,lamb curry,positive,1.2130,0.2426,medium,0.461640,0.734910,0.339264
2,korma,korma,positive,0.9630,0.1926,medium,0.435693,0.717410,0.312571
3,naan,naan,neutral,0.3465,0.0693,low,0.071801,0.024255,0.001742
4,sandwiches,sandwich,positive,0.8545,0.1709,medium,0.427074,0.709815,0.303143
5,wings,wings,positive,1.7130,0.3426,high,0.794477,0.769910,0.611675
6,sushi,sushi,neutral,0.0000,0.0000,low,0.064969,0.000000,0.000000
7,gnocchi with marinara,gnocchi with marinara,positive,5.0000,1.0000,high,0.734242,1.000000,0.734242
8,baked eggplant appetizer,baked eggplant appetizer,positive,4.8670,0.9734,medium,0.426894,0.990690,0.422920
9,Sonoran Dog,sonoran dog,neutral,0.2310,0.0462,low,0.068467,0.016170,0.001107

In [10]:
# ============================================================
# 10. QA inicial de señales
# ============================================================

aggregation_input_qa = {
    "total_mentions": int(len(mentions_df)),
    "unique_reviews": int(mentions_df["review_id"].nunique()),
    "unique_businesses": int(mentions_df["business_id"].nunique()),
    "unique_dishes": int(mentions_df["dish_id_v2"].nunique()),
    "sentiment_counts": {
        str(k): int(v)
        for k, v in mentions_df["mention_sentiment_label_final"].value_counts().to_dict().items()
    },
    "reliability_counts": {
        str(k): int(v)
        for k, v in mentions_df["sentiment_reliability_tier"].value_counts().to_dict().items()
    },
    "signal_weight": {
        "min": float(mentions_df["signal_weight"].min()),
        "mean": float(mentions_df["signal_weight"].mean()),
        "median": float(mentions_df["signal_weight"].median()),
        "max": float(mentions_df["signal_weight"].max()),
    },
    "weighted_sentiment_value": {
        "min": float(mentions_df["weighted_sentiment_value"].min()),
        "mean": float(mentions_df["weighted_sentiment_value"].mean()),
        "median": float(mentions_df["weighted_sentiment_value"].median()),
        "max": float(mentions_df["weighted_sentiment_value"].max()),
    },
}

print(json.dumps(aggregation_input_qa, indent=2, ensure_ascii=False))

print("\nTop platos por menciones:")
display(
    mentions_df["canonical_dish_name_v2"]
    .value_counts()
    .head(50)
    .reset_index()
    .rename(columns={
        "index": "canonical_dish_name_v2",
        "canonical_dish_name_v2": "mention_count"
    })
)

{
  "total_mentions": 94932,
  "unique_reviews": 42461,
  "unique_businesses": 4088,
  "unique_dishes": 9937,
  "sentiment_counts": {
    "neutral": 45366,
    "positive": 43142,
    "negative": 6424
  },
  "reliability_counts": {
    "low": 44426,
    "medium": 25495,
    "high": 25011
  },
  "signal_weight": {
    "min": 0.020311710990965366,
    "mean": 0.37781376200795724,
    "median": 0.3624973218077422,
    "max": 0.9497699350118637
  },
  "weighted_sentiment_value": {
    "min": -1.0,
    "mean": 0.3117034681140184,
    "median": 0.041755,
    "max": 1.0
  }
}

Top platos por menciones:

      mention_count  count
0             pizza   8751
1            burger   8095
2             fries   5375
3             sushi   4470
4             tacos   4436
5            shrimp   4421
6             steak   2794
7         ice cream   2411
8             wings   2215
9             donut   2175
10          oysters   2129
11         sandwich   2127
12          pancake   2035
13             crab   1535
14          burrito   1405
15              pho   1225
16           salmon   1137
17             ribs   1095
18    fried chicken    933
19             tuna    890
20           waffle    879
21     french toast    877
22           omelet    779
23           nachos    764
24          brisket    753
25          lobster    745
26   mac and cheese    707
27           hummus    632
28      pulled pork    601
29         calamari    600
30         pad thai    543
31       fried rice    539
32          mussels    538
33       crab cakes    534
34        dumplings    498
35            ramen    460
36            latte    446
37       quesadilla    434
38     spring rolls    418
39        enchilada    407
40  mashed potatoes    400
41       cheesecake    392
42         eggplant    381
43             naan    359
44         smoothie    342
45          ravioli    328
46     cheeseburger    320
47          custard    276
48    chicken wings    275
49    eggs benedict    271

## 1. Agregación global por plato

En esta fase se agregan todas las menciones por `dish_id_v2`.

Esta tabla permite responder preguntas como:

- ¿Qué platos aparecen más?
- ¿Qué platos tienen mejor señal media?
- ¿Qué platos tienen más menciones positivas?
- ¿Qué platos tienen señales más fiables?

La tabla global todavía no es el ranking Hidden Gems definitivo. Es una tabla de señales base.

In [11]:
# ============================================================
# 11. Función auxiliar de agregación
# ============================================================

def safe_weighted_mean(values, weights):
    values = np.asarray(values, dtype=float)
    weights = np.asarray(weights, dtype=float)

    mask = ~np.isnan(values) & ~np.isnan(weights) & (weights > 0)

    if mask.sum() == 0:
        return np.nan

    return float(np.average(values[mask], weights=weights[mask]))


def compute_aggregate_quality(row) -> str:
    """
    Clasifica la calidad de una agregación.
    """

    mention_count = row.get("mention_count", 0)
    review_count = row.get("review_count", 0)
    high_reliability_mentions = row.get("high_reliability_mentions", 0)
    avg_signal_weight = row.get("avg_signal_weight", 0.0)

    if mention_count >= 50 and review_count >= 25 and high_reliability_mentions >= 10 and avg_signal_weight >= 0.35:
        return "high"

    if mention_count >= 15 and review_count >= 8 and avg_signal_weight >= 0.20:
        return "medium"

    return "low"


def compute_positive_ratio(row):
    denominator = row["positive_mentions"] + row["neutral_mentions"] + row["negative_mentions"]
    if denominator == 0:
        return 0.0
    return float(row["positive_mentions"] / denominator)


def compute_negative_ratio(row):
    denominator = row["positive_mentions"] + row["neutral_mentions"] + row["negative_mentions"]
    if denominator == 0:
        return 0.0
    return float(row["negative_mentions"] / denominator)

In [12]:
# ============================================================
# 12. Agregación global por plato
# ============================================================

global_group_cols = [
    "dish_id_v2",
    "canonical_dish_name_v2",
]

dish_global_basic_df = (
    mentions_df
    .groupby(global_group_cols, dropna=False)
    .agg(
        mention_count=("mention_id", "size"),
        review_count=("review_id", "nunique"),
        business_count=("business_id", "nunique"),

        positive_mentions=("mention_sentiment_label_final", lambda s: int((s == "positive").sum())),
        neutral_mentions=("mention_sentiment_label_final", lambda s: int((s == "neutral").sum())),
        negative_mentions=("mention_sentiment_label_final", lambda s: int((s == "negative").sum())),

        high_reliability_mentions=("is_high_reliability", "sum"),
        medium_reliability_mentions=("is_medium_reliability", "sum"),
        low_reliability_mentions=("is_low_reliability", "sum"),

        avg_ner_confidence=("ner_confidence", "mean"),
        avg_sentiment_confidence=("sentiment_confidence", "mean"),
        avg_signal_weight=("signal_weight", "mean"),
        total_signal_weight=("signal_weight", "sum"),

        avg_rating=("rating_value", "mean"),
        avg_sentiment_score_raw=("mention_sentiment_score_final", "mean"),
        avg_sentiment_score_normalized=("sentiment_score_normalized", "mean"),
        avg_weighted_sentiment_value=("weighted_sentiment_value", "mean"),

        positive_signal=("positive_signal", "sum"),
        neutral_signal=("neutral_signal", "sum"),
        negative_signal=("negative_signal", "sum"),
        weighted_sentiment_contribution=("weighted_sentiment_contribution", "sum"),
    )
    .reset_index()
)

# Weighted sentiment aggregate
weighted_rows = []

for row in tqdm(
    dish_global_basic_df.to_dict(orient="records"),
    desc="Calculando weighted sentiment global"
):
    dish_id = row["dish_id_v2"]

    subset = mentions_df[mentions_df["dish_id_v2"] == dish_id]

    weighted_mean = safe_weighted_mean(
        subset["weighted_sentiment_value"],
        subset["signal_weight"]
    )

    weighted_rows.append({
        "dish_id_v2": dish_id,
        "confidence_weighted_sentiment": weighted_mean,
    })

global_weighted_df = pd.DataFrame(weighted_rows)

dish_global_signals_df = dish_global_basic_df.merge(
    global_weighted_df,
    on="dish_id_v2",
    how="left"
)

dish_global_signals_df["positive_ratio"] = dish_global_signals_df.apply(
    compute_positive_ratio,
    axis=1
)

dish_global_signals_df["negative_ratio"] = dish_global_signals_df.apply(
    compute_negative_ratio,
    axis=1
)

dish_global_signals_df["reliability_high_ratio"] = (
    dish_global_signals_df["high_reliability_mentions"]
    / dish_global_signals_df["mention_count"]
).fillna(0.0)

dish_global_signals_df["aggregate_quality_tier"] = dish_global_signals_df.apply(
    compute_aggregate_quality,
    axis=1
)

dish_global_signals_df = dish_global_signals_df.sort_values(
    ["mention_count", "confidence_weighted_sentiment"],
    ascending=[False, False]
).reset_index(drop=True)

print("Platos globales agregados:", len(dish_global_signals_df))

display(dish_global_signals_df.head(50))

Calculando weighted sentiment global:   0%|          | 0/9937 [00:00<?, ?it/s]

Platos globales agregados: 9937

,dish_id_v2,canonical_dish_name_v2,mention_count,review_count,business_count,positive_mentions,neutral_mentions,negative_mentions,high_reliability_mentions,medium_reliability_mentions,low_reliability_mentions,avg_ner_confidence,avg_sentiment_confidence,avg_signal_weight,total_signal_weight,avg_rating,avg_sentiment_score_raw,avg_sentiment_score_normalized,avg_weighted_sentiment_value,positive_signal,neutral_signal,negative_signal,weighted_sentiment_contribution,confidence_weighted_sentiment,positive_ratio,negative_ratio,reliability_high_ratio,aggregate_quality_tier
0,dish_seed_v2_000001,pizza,8751,4599,856,3779,4392,580,2120,2405,4226,0.997650,0.536322,0.367837,3218.940705,3.648269,0.755191,0.151038,0.290476,2436.995169,437.060041,344.885495,1695.956618,0.526868,0.431836,0.066278,0.242258,high
1,dish_seed_v2_000002,burger,8095,4478,863,3564,3963,568,2071,2256,3768,0.994412,0.544419,0.378229,3061.762930,3.685361,0.778708,0.155742,0.295078,2314.414949,402.890142,344.457840,1599.673682,0.522468,0.440272,0.070167,0.255837,high
2,dish_seed_v2_000003,fries,5375,4094,1093,2421,2466,488,1705,1348,2322,0.997493,0.572823,0.420975,2262.741152,3.600744,0.824837,0.164967,0.291497,1676.142129,269.823090,316.775933,1120.752702,0.495308,0.450419,0.090791,0.317209,high
3,dish_seed_v2_000004,sushi,4470,2482,266,2028,2171,271,1125,1250,2095,0.999147,0.543060,0.376949,1684.962116,3.833781,0.809885,0.161977,0.312184,1309.028935,215.565349,160.367832,928.652208,0.551141,0.453691,0.060626,0.251678,high
4,dish_seed_v2_000005,tacos,4436,2707,533,1859,2274,303,1076,1113,2247,0.995108,0.528524,0.359207,1593.443117,3.783138,0.775993,0.155199,0.282318,1202.246045,221.020725,170.176347,843.924612,0.529623,0.419071,0.068305,0.242561,high
5,dish_seed_v2_000006,shrimp,4421,3269,865,2022,2057,342,1259,1086,2076,0.993723,0.554314,0.392569,1735.547668,3.902285,0.878616,0.175723,0.308506,1322.279291,205.058687,208.209689,919.380469,0.529735,0.457363,0.077358,0.284777,high
6,dish_seed_v2_000007,steak,2794,2102,830,1095,1410,289,765,667,1362,0.994526,0.541866,0.379903,1061.449278,3.556908,0.642151,0.128430,0.232460,730.532019,142.315091,188.602168,445.381380,0.419597,0.391911,0.103436,0.273801,high
7,dish_seed_v2_000008,ice cream,2411,1588,475,1048,1283,80,495,647,1269,0.999356,0.511730,0.334994,807.671738,4.096640,0.831030,0.166206,0.319143,647.558194,119.489486,40.624058,486.698209,0.602594,0.434674,0.033181,0.205309,medium
8,dish_seed_v2_000009,wings,2215,1493,588,1053,1002,160,655,590,970,0.995117,0.567206,0.409473,906.982334,3.597743,0.861874,0.172375,0.322385,699.882576,105.385614,101.714145,490.275996,0.540557,0.475395,0.072235,0.295711,high
9,dish_seed_v2_000010,donut,2175,973,175,881,1171,123,477,567,1131,0.997435,0.516398,0.343593,747.315529,4.061149,0.745292,0.149058,0.278699,559.389931,113.962448,73.963150,391.187438,0.523457,0.405057,0.056552,0.219310,medium
10,dish_seed_v2_000011,oysters,2129,1321,203,977,1019,133,556,666,907,0.996097,0.558993,0.393736,838.263332,4.076562,0.894882,0.178976,0.320321,637.888711,128.569830,71.804791,463.623219,0.553076,0.458901,0.062471,0.261155,high
11,dish_seed_v2_000012,sandwich,2127,1851,820,1109,941,77,628,586,913,0.986934,0.571840,0.409348,870.682271,4.000940,1.046872,0.209374,0.388655,735.391718,92.068850,43.221703,563.555036,0.647257,0.521392,0.036201,0.295252,high
12,dish_seed_v2_000013,pancake,2035,1314,267,921,1016,98,529,486,1020,0.995683,0.534893,0.369732,752.405296,3.935135,0.891665,0.178333,0.325291,599.679814,95.334810,57.390672,441.574804,0.586884,0.452580,0.048157,0.259951,high
13,dish_seed_v2_000014,crab,1535,1138,423,616,811,108,358,384,793,0.993465,0.524191,0.351813,540.033431,3.869055,0.767153,0.153431,0.268815,395.774558,82.036647,62.222225,274.644237,0.508569,0.401303,0.070358,0.233225,high
14,dish_seed_v2_000015,burrito,1405,971,320,536,771,98,297,334,774,0.997031,0.504319,0.329312,462.682715,3.729537,0.654544,0.130909,0.248452,335.212029,70.971076,56.499611,225.369641,0.487093,0.381495,0.069751,0.211388,medium
15,dish_seed_v2_000016,pho,1225,708,91,528,642,55,289,316,620,0.997323,0.526306,0.357225,437.600280,3.958367,0.837019,0.167404,0.309571,343.932052,63.435619,30.232609,254.692682,0.582021,0.431020,0.044898,0.235918,high
16,dish_seed_v2_000017,salmon,1137,920,456,483,549,105,329,284,524,0.993813,0.556991,0.397498,451.954728,3.733509,0.798603,0.159721,0.271997,329.867961,57.783117,64.303651,220.065386,0.486919,0.424802,0.092348,0.289358,high
17,dish_seed_v2_000018,ribs,1095,837,320,472,498,125,345,265,485,0.995228,0.567565,0.414873,454.285432,3.699543,0.717495,0.143499,0.256206,316.883500,52.657723,84.744209,190.681573,0.419740,0.431050,0.114155,0.315068,high
18,dish_seed_v2_000019,fried chicken,933,781,247,445,422,66,262,247,424,0.998554,0.555455,0.394933,368.472758,3.857449,0.891630,0.178326,0.326455,286.427968,42.419857,39.624933,202.140141,0.548589,0.476956,0.070740,0.280815,high
19,dish_seed_v2_000020,tuna,890,687,336,364,451,75,228,238,424,0.993997,0.541642,0.375205,333.932404,3.797753,0.800377,0.160075,0.267094,244.271684,47.854304,41.806416,168.211826,0.503730,0.408989,0.084270,0.256180,high
20,dish_seed_v2_000021,waffle,879,646,226,371,465,43,221,207,451,0.997726,0.528609,0.362171,318.348186,3.937429,0.852651,0.170530,0.302234,244.834787,46.096273,27.417125,178.142581,0.559584,0.422071,0.048919,0.251422,high
21,dish_seed_v2_000022,french toast,877,718,203,439,393,45,258,218,401,0.998977,0.563313,0.405049,355.227580,4.148233,1.010068,0.202014,0.362723,289.196179,39.221815,26.809585,215.591248,0.606910,0.500570,0.051311,0.294185,high
22,dish_seed_v2_000023,omelet,779,648,243,337,382,60,211,192,376,0.978987,0.547533,0.377775,294.286834,3.816431,0.831721,0.166344,0.289350,221.183840,36.679267,36.423726,152.233268,0.517296,0.432606,0.077022,0.270860,high
23,dish_seed_v2_000024,nachos,764,592,264,340,371,53,204,188,372,0.996110,0.542409,0.378997,289.553349,3.691099,0.831129,0.166226,0.302354,219.708739,38.471506,31.373104,155.001376,0.535312,0.445026,0.069372,0.267016,high
24,dish_seed_v2_000025,brisket,753,570,166,335,351,67,224,194,335,0.993688,0.562309,0.404960,304.935048,3.723772,0.807293,0.161459,0.287852,225.102278,38.646845,41.185925,151.464550,0.496711,0.444887,0.088977,0.297477,high
25,dish_seed_v2_000026,lobster,745,533,203,286,403,56,194,172,379,0.991445,0.527301,0.362867,270.335580,3.797315,0.739586,0.147917,0.252442,191.915480,43.074428,35.345672,129.413504,0.478714,0.383893,0.075168,0.260403,high
26,dish_seed_v2_000027,mac and cheese,707,584,217,330,322,55,225,178,304,0.998984,0.575168,0.423948,299.731112,3.855728,0.932775,0.186555,0.318123,226.852765,36.000381,36.877965,158.295728,0.528126,0.466761,0.077793,0.318246,high
27,dish_seed_v2_000028,hummus,632,503,179,320,285,27,190,157,285,0.996845,0.563739,0.406698,257.033320,4.022152,1.046161,0.209232,0.374576,212.695188,28.794363,15.543769,161.914073,0.629934,0.506329,0.042722,0.300633,high
28,dish_seed_v2_000029,pulled pork,601,529,203,296,270,35,181,158,262,0.997854,0.571696,0.415608,249.780535,3.901830,0.978908,0.195782,0.350803,197.556771,29.446869,22.776895,143.862953,0.575957,0.492512,0.058236,0.301165,high
29,dish_seed_v2_000030,calamari,600,484,240,276,273,51,197,145,258,0.996559,0.578723,0.428287,256.972462,3.730000,0.915163,0.183033,0.307811,193.949276,30.051006,32.972180,134.502977,0.523414,0.460000,0.085000,0.328333,high
30,dish_seed_v2_000031,pad thai,543,412,102,237,261,45,152,146,245,0.999095,0.557132,0.397295,215.731381,3.749540,0.713813,0.142763,0.279801,155.703381,28.759178,31.268823,100.229760,0.464604,0.436464,0.082873,0.279926,high
31,dish_seed_v2_000032,fried rice,539,451,222,210,278,51,147,110,282,0.999038,0.531244,0.370346,199.616762,3.589981,0.695408,0.139082,0.240423,140.170132,27.286860,32.159771,89.764946,0.449686,0.389610,0.094620,0.272727,high
32,dish_seed_v2_000033,mussels,538,428,168,258,246,34,162,130,246,0.997719,0.563574,0.407138,219.039979,4.011152,0.977841,0.195568,0.339081,173.544825,25.069758,20.425397,126.534392,0.577677,0.479554,0.063197,0.301115,high
33,dish_seed_v2_000034,crab cakes,534,432,188,232,258,44,146,135,253,0.998382,0.548518,0.386987,206.651275,3.737828,0.753773,0.150755,0.281603,148.052330,28.534858,30.064087,96.098507,0.465027,0.434457,0.082397,0.273408,high
34,dish_seed_v2_000035,dumplings,498,391,175,216,240,42,125,144,229,0.989611,0.551127,0.379803,189.142001,3.903614,0.813076,0.162615,0.284024,138.650936,26.292125,24.198940,94.019442,0.497084,0.433735,0.084337,0.251004,high
35,dish_seed_v2_000036,ramen,460,251,41,149,271,40,92,104,264,0.993478,0.488189,0.312472,143.737127,3.660870,0.515611,0.103122,0.190114,95.759393,24.983846,22.993887,59.154477,0.411546,0.323913,0.086957,0.200000,medium
36,dish_seed_v2_000037,latte,446,371,149,212,219,15,119,116,211,0.994709,0.545377,0.380465,169.687509,4.118834,0.952555,0.190511,0.353786,140.709818,21.419477,7.558215,107.746745,0.634972,0.475336,0.033632,0.266816,high
37,dish_seed_v2_000038,quesadilla,434,356,190,185,222,27,115,87,232,0.994235,0.528003,0.363126,157.596757,3.622120,0.757606,0.151521,0.289668,116.012274,21.329410,20.255073,78.576396,0.498591,0.426267,0.062212,0.264977,high
38,dish_seed_v2_000039,spring rolls,418,361,141,232,163,23,154,109,155,0.996470,0.611444,0.468577,195.865188,3.976077,1.124757,0.224951,0.403733,163.055430,17.488619,15.321140,121.228176,0.618937,0.555024,0.055024,0.368421,high
39,dish_seed_v2_000040,enchilada,407,332,118,157,214,36,115,89,203,0.996093,0.540644,0.380322,154.791158,3.567568,0.733681,0.146736,0.244601,109.569237,22.190402,23.031518,72.347207,0.467386,0.385749,0.088452,0.282555,high
40,dish_seed_v2_000041,mashed potatoes,400,357,214,151,210,39,104,93,203,0.998794,0.529037,0.365787,146.314775,3.510000,0.635131,0.127026,0.226459,99.545406,22.446562,24.322807,62.040009,0.424017,0.377500,0.097500,0.260000,high
41,dish_seed_v2_000042,cheesecake,392,308,163,175,196,21,88,96,208,0.995714,0.520850,0.345726,135.524725,3.964286,0.858805,0.171761,0.315473,107.066888,16.861055,11.596782,77.902285,0.574820,0.446429,0.053571,0.224490,medium
42,dish_seed_v2_000043,eggplant,381,329,197,181,186,14,110,101,170,0.993921,0.561407,0.401336,152.909111,3.986877,1.000083,0.200017,0.354914,122.880164,21.496261,8.532685,93.818761,0.613559,0.475066,0.036745,0.288714,high
43,dish_seed_v2_000044,naan,359,290,72,170,165,24,115,91,153,0.996415,0.576265,0.422461,151.663478,3.935933,0.959113,0.191823,0.331483,117.788790,18.506915,15.367773,84.211192,0.555250,0.473538,0.066852,0.320334,high
44,dish_seed_v2_000045,smoothie,342,250,106,139,190,13,87,74,181,0.994037,0.522355,0.355842,121.698117,3.847953,0.914354,0.182871,0.303478,96.070011,19.130901,6.497205,74.849020,0.615038,0.406433,0.038012,0.254386,high
45,dish_seed_v2_000046,ravioli,328,268,127,147,157,24,85,79,164,0.986096,0.533467,0.363579,119.253979,3.859756,0.780777,0.156155,0.298404,88.810819,14.708387,15.734773,59.191347,0.496347,0.448171,0.073171,0.259146,high
46,dish_seed_v2_000047,cheeseburger,320,279,177,118,186,16,69,71,180,0.997139,0.499258,0.327308,104.738601,3.528125,0.699952,0.139990,0.256184,77.326646,17.479934,9.932021,55.756664,0.532341,0.368750,0.050000,0.215625,medium
47,dish_seed_v2_000048,custard,276,198,57,128,139,9,59,72,145,0.963480,0.512393,0.329636,90.979526,4.239130,0.847616,0.169523,0.339587,74.380782,12.093381,4.505364,55.611201,0.611250,0.463768,0.032609,0.213768,medium
48,dish_seed_v2_000049,chicken wings,275,240,181,132,120,23,93,59,123,0.997783,0.579452,0.430171,118.297100,3.694545,0.901358,0.180272,0.320731,90.198641,10.568981,17.529477,60.443049,0.510943,0.480000,0.083636,0.338182,high
49,dish_seed_v2_000050,eggs benedict,271,243,114,134,122,15,86,62,123,0.998541,0.573446,0.419960,113.809120,3.952030,1.106568,0.221314,0.362884,92.260033,12.297859,9.251228,70.114245,0.616069,0.494465,0.055351,0.317343,high

## 2. Agregación por plato + negocio

Esta tabla será la base más importante para el ranking Hidden Gems.

A nivel global, `pizza` o `burger` pueden ser muy frecuentes, pero Hidden Gems necesita saber:

```text
en qué negocio concreto se habla especialmente bien de un plato concreto
```
Por eso se agregan señales por:
```
business_id + dish_id_v2
```
Ejemplo:
```
Local A + ramen
Local B + burger
Local C + fried chicken
```

In [13]:
# ============================================================
# 13. Agregación por negocio y plato
# ============================================================

business_group_cols = [
    "business_id",
    "dish_id_v2",
    "canonical_dish_name_v2",
]

optional_business_cols = [
    "business_name",
    "city",
    "state",
]

for col in optional_business_cols:
    if col not in mentions_df.columns:
        mentions_df[col] = ""

business_info_df = (
    mentions_df
    .groupby("business_id", dropna=False)
    .agg(
        business_name=("business_name", "first"),
        city=("city", "first"),
        state=("state", "first"),
    )
    .reset_index()
)

dish_business_basic_df = (
    mentions_df
    .groupby(business_group_cols, dropna=False)
    .agg(
        mention_count=("mention_id", "size"),
        review_count=("review_id", "nunique"),

        positive_mentions=("mention_sentiment_label_final", lambda s: int((s == "positive").sum())),
        neutral_mentions=("mention_sentiment_label_final", lambda s: int((s == "neutral").sum())),
        negative_mentions=("mention_sentiment_label_final", lambda s: int((s == "negative").sum())),

        high_reliability_mentions=("is_high_reliability", "sum"),
        medium_reliability_mentions=("is_medium_reliability", "sum"),
        low_reliability_mentions=("is_low_reliability", "sum"),

        avg_ner_confidence=("ner_confidence", "mean"),
        avg_sentiment_confidence=("sentiment_confidence", "mean"),
        avg_signal_weight=("signal_weight", "mean"),
        total_signal_weight=("signal_weight", "sum"),

        avg_rating=("rating_value", "mean"),
        avg_sentiment_score_raw=("mention_sentiment_score_final", "mean"),
        avg_sentiment_score_normalized=("sentiment_score_normalized", "mean"),
        avg_weighted_sentiment_value=("weighted_sentiment_value", "mean"),

        positive_signal=("positive_signal", "sum"),
        neutral_signal=("neutral_signal", "sum"),
        negative_signal=("negative_signal", "sum"),
        weighted_sentiment_contribution=("weighted_sentiment_contribution", "sum"),
    )
    .reset_index()
)

weighted_business_rows = []

for row in tqdm(
    dish_business_basic_df.to_dict(orient="records"),
    desc="Calculando weighted sentiment por negocio-plato"
):
    business_id = row["business_id"]
    dish_id = row["dish_id_v2"]

    subset = mentions_df[
        (mentions_df["business_id"] == business_id)
        & (mentions_df["dish_id_v2"] == dish_id)
    ]

    weighted_mean = safe_weighted_mean(
        subset["weighted_sentiment_value"],
        subset["signal_weight"]
    )

    weighted_business_rows.append({
        "business_id": business_id,
        "dish_id_v2": dish_id,
        "confidence_weighted_sentiment": weighted_mean,
    })

business_weighted_df = pd.DataFrame(weighted_business_rows)

dish_business_signals_df = dish_business_basic_df.merge(
    business_weighted_df,
    on=["business_id", "dish_id_v2"],
    how="left"
)

dish_business_signals_df = dish_business_signals_df.merge(
    business_info_df,
    on="business_id",
    how="left"
)

dish_business_signals_df["positive_ratio"] = dish_business_signals_df.apply(
    compute_positive_ratio,
    axis=1
)

dish_business_signals_df["negative_ratio"] = dish_business_signals_df.apply(
    compute_negative_ratio,
    axis=1
)

dish_business_signals_df["reliability_high_ratio"] = (
    dish_business_signals_df["high_reliability_mentions"]
    / dish_business_signals_df["mention_count"]
).fillna(0.0)

dish_business_signals_df["aggregate_quality_tier"] = dish_business_signals_df.apply(
    compute_aggregate_quality,
    axis=1
)

# Señal mínima para que luego pueda entrar en ranking.
dish_business_signals_df["is_rankable_candidate_v1"] = (
    (dish_business_signals_df["mention_count"] >= 2)
    & (dish_business_signals_df["review_count"] >= 2)
    & (dish_business_signals_df["total_signal_weight"] >= 0.75)
)

dish_business_signals_df = dish_business_signals_df.sort_values(
    [
        "is_rankable_candidate_v1",
        "confidence_weighted_sentiment",
        "mention_count",
        "positive_ratio",
    ],
    ascending=[False, False, False, False]
).reset_index(drop=True)

print("Pares negocio-plato agregados:", len(dish_business_signals_df))
print("Candidatos rankeables v1:", int(dish_business_signals_df["is_rankable_candidate_v1"].sum()))

display(dish_business_signals_df.head(50))

Calculando weighted sentiment por negocio-plato:   0%|          | 0/31036 [00:00<?, ?it/s]

Pares negocio-plato agregados: 31036
Candidatos rankeables v1: 6375

,business_id,dish_id_v2,canonical_dish_name_v2,mention_count,review_count,positive_mentions,neutral_mentions,negative_mentions,high_reliability_mentions,medium_reliability_mentions,low_reliability_mentions,avg_ner_confidence,avg_sentiment_confidence,avg_signal_weight,total_signal_weight,avg_rating,avg_sentiment_score_raw,avg_sentiment_score_normalized,avg_weighted_sentiment_value,positive_signal,neutral_signal,negative_signal,weighted_sentiment_contribution,confidence_weighted_sentiment,business_name,city,state,positive_ratio,negative_ratio,reliability_high_ratio,aggregate_quality_tier,is_rankable_candidate_v1
0,kxX2SOes4o-D3ZQBkiMRfA,dish_seed_v2_001268,makhani,2,2,2,0,0,1,1,0,0.824138,0.935850,0.646765,1.293530,5.000000,5.000000,1.000000,1.000000,1.293530,0.000000,0.0,1.293530,1.000000,Zaika,Philadelphia,PA,1.000000,0.0,0.500000,low,True
1,Kzf6VUWTKtSBd4OWUfwlkg,dish_seed_v2_000002,burger,2,2,2,0,0,2,0,0,0.997551,0.950000,0.947673,1.895347,5.000000,4.806500,0.961300,0.986455,1.895347,0.000000,0.0,1.869622,0.986427,Frosty Boy Drive-In,New Palestine,IN,1.000000,0.0,1.000000,low,True
2,ena3aLdMz2ym_OPVuTIJ2g,dish_seed_v2_000014,crab,2,2,2,0,0,2,0,0,0.999470,0.950000,0.949497,1.898993,4.500000,4.796000,0.959200,0.985720,1.898993,0.000000,0.0,1.871873,0.985719,Broadway Bar & Grille,Clifton Heights,PA,1.000000,0.0,1.000000,low,True
3,DeVlppoc8dPBhOCPrm4wmg,dish_seed_v2_000237,wedge salad,2,2,2,0,0,1,0,1,0.800147,0.774000,0.517928,1.035856,4.000000,2.906500,0.581300,0.853455,1.035856,0.000000,0.0,1.009340,0.974402,Harry & Izzy's,Indianapolis,IN,1.000000,0.0,0.500000,low,True
4,i-tDq8zC7ZmSqSbg_7oddA,dish_seed_v2_000062,salad,3,2,3,0,0,1,1,1,0.851320,0.680200,0.433360,1.300080,5.000000,3.453167,0.690633,0.891722,1.300080,0.000000,0.0,1.266214,0.973951,LA Smokehouse,New Orleans,LA,1.000000,0.0,0.333333,low,True
5,O3Gsne_JJ24yMvLrDoNjqA,dish_seed_v2_000074,korma,2,2,2,0,0,2,0,0,0.996777,0.950000,0.946938,1.893877,4.500000,4.577500,0.915500,0.970425,1.893877,0.000000,0.0,1.837906,0.970446,Nirvana Fusion,Hatboro,PA,1.000000,0.0,1.000000,low,True
6,SZU9c8V2GuREDN5KgyHFJw,dish_seed_v2_000194,lobster bisque,2,2,2,0,0,2,0,0,0.896303,0.945350,0.847541,1.695081,4.500000,4.519000,0.903800,0.966330,1.695081,0.000000,0.0,1.641310,0.968278,Santa Barbara Shellfish Company,Santa Barbara,CA,1.000000,0.0,1.000000,low,True
7,z22hSRptt_DS0nWjsIka2A,dish_seed_v2_000018,ribs,3,2,2,1,0,2,0,1,0.999211,0.726667,0.656167,1.968500,3.666667,3.416667,0.683333,0.672500,1.898560,0.069940,0.0,1.899784,0.965092,Outback Steakhouse,Royersford,PA,0.666667,0.0,0.666667,low,True
8,xwKYBPO0ByGlkvNcr8FdqQ,dish_seed_v2_000007,steak,4,2,4,0,0,4,0,0,0.998727,0.950000,0.948790,3.795162,5.000000,4.472125,0.894425,0.963049,3.795162,0.000000,0.0,3.654883,0.963037,Le Rendez-vous,Tucson,AZ,1.000000,0.0,1.000000,low,True
9,ew_Hhp12Silh3qjoPaW9IA,dish_seed_v2_000035,dumplings,2,2,2,0,0,2,0,0,0.999450,0.894950,0.894461,1.788921,5.000000,4.375500,0.875100,0.956285,1.788921,0.000000,0.0,1.714477,0.958386,Thai Legacy Restaurant,Brandon,FL,1.000000,0.0,1.000000,low,True
10,ltBBYdNzkeKdCNPDAsxwAA,dish_seed_v2_001444,singapore stir fry,2,2,2,0,0,1,1,0,0.740429,0.919650,0.593089,1.186178,4.500000,4.202500,0.840500,0.944175,1.186178,0.000000,0.0,1.134371,0.956324,Tavern,Nashville,TN,1.000000,0.0,0.500000,low,True
11,05471AhNLv1NxKoaVs4gYw,dish_seed_v2_000003,fries,2,2,2,0,0,2,0,0,0.999468,0.950000,0.949495,1.898990,4.000000,4.342000,0.868400,0.953940,1.898990,0.000000,0.0,1.811520,0.953939,Sam's Brick Oven Pizza,Ardmore,PA,1.000000,0.0,1.000000,low,True
12,h85b3MFPWyaopMBy8DpBpA,dish_seed_v2_000027,mac and cheese,4,2,4,0,0,4,0,0,0.999116,0.917025,0.916219,3.664877,5.000000,4.215750,0.843150,0.945102,3.664877,0.000000,0.0,3.485415,0.951032,Ron's Caribbean Cuisine,Philadelphia,PA,1.000000,0.0,1.000000,low,True
13,WO5nr-4sjVs506BdCLL0aA,dish_seed_v2_000007,steak,2,2,2,0,0,2,0,0,0.997650,0.934650,0.932474,1.864949,5.000000,4.275500,0.855100,0.949285,1.864949,0.000000,0.0,1.771729,0.950015,Kuchi Sushi & Hibachi,Tampa,FL,1.000000,0.0,1.000000,low,True
14,gK9CdFaCXmHoW8aLfXiSqg,dish_seed_v2_000009,wings,2,2,2,0,0,2,0,0,0.998839,0.950000,0.948897,1.897794,4.500000,4.281500,0.856300,0.949705,1.897794,0.000000,0.0,1.802274,0.949668,Tired Hands Fermentaria,Ardmore,PA,1.000000,0.0,1.000000,low,True
15,tnPjcpTSdCZB7LGoH1ZjuQ,dish_seed_v2_000012,sandwich,2,2,2,0,0,1,1,0,0.856709,0.932300,0.686924,1.373847,5.000000,4.300500,0.860100,0.951035,1.373847,0.000000,0.0,1.304281,0.949364,The Twisted Iron,Tampa,FL,1.000000,0.0,0.500000,low,True
16,zrd6bulYNAKhCdSVtJ8aXQ,dish_seed_v2_000047,cheeseburger,2,2,2,0,0,2,0,0,0.999025,0.950000,0.949073,1.898147,4.000000,4.269000,0.853800,0.948830,1.898147,0.000000,0.0,1.801018,0.948830,Texas Roadhouse,Sicklerville,NJ,1.000000,0.0,1.000000,low,True
17,DXYhpEv17mWqSqFjau7vhg,dish_seed_v2_000041,mashed potatoes,4,4,3,1,0,2,0,2,0.999322,0.633850,0.514383,2.057531,5.000000,2.829750,0.565950,0.685582,1.980671,0.076860,0.0,1.951835,0.948629,Eatalia,Philadelphia,PA,0.750000,0.0,0.500000,low,True
18,yeHLiKNp0hyR-ig4M6us-w,dish_seed_v2_001521,tres leche cake with housemade coffee ice cream,2,2,2,0,0,2,0,0,0.987030,0.950000,0.937679,1.875358,5.000000,4.238000,0.847600,0.946660,1.875358,0.000000,0.0,1.775326,0.946660,Livery - Indianapolis,Indianapolis,IN,1.000000,0.0,1.000000,low,True
19,4RMHlggaIdNibPUJPVEd6w,dish_seed_v2_000003,fries,2,2,2,0,0,2,0,0,0.999126,0.919850,0.919046,1.838092,4.500000,4.208500,0.841700,0.944595,1.838092,0.000000,0.0,1.736294,0.944618,Bridgewater's Pub,Philadelphia,PA,1.000000,0.0,1.000000,low,True
20,a7FSs8soBoxfkPXvzSsvbg,dish_seed_v2_000038,quesadilla,2,2,2,0,0,1,0,1,0.998907,0.634200,0.514427,1.028854,4.500000,2.609500,0.521900,0.832665,1.028854,0.000000,0.0,0.971078,0.943844,Garcias Mexican Restaurant,Franklin,TN,1.000000,0.0,0.500000,low,True
21,pVHbXwsqLxNzAx9rdwy2EA,dish_seed_v2_000854,steak spring roll,3,3,2,1,0,2,0,1,0.999219,0.729233,0.656832,1.970497,5.000000,3.240833,0.648167,0.660192,1.898637,0.071860,0.0,1.858914,0.943373,Marmont Steakhouse & Bar,Philadelphia,PA,0.666667,0.0,0.666667,low,True
22,8G4mt9y5mRg161XBs-hePw,dish_seed_v2_000030,calamari,2,2,2,0,0,1,0,1,0.999143,0.634200,0.514364,1.028729,4.000000,2.599000,0.519800,0.831930,1.028729,0.000000,0.0,0.969548,0.942472,Izakaya Ren,Valley Park,MO,1.000000,0.0,0.500000,low,True
23,o3RGMdSY37_PX1k1vZsXpA,dish_seed_v2_000020,tuna,3,2,3,0,0,3,0,0,0.973846,0.950000,0.925154,2.775462,3.666667,4.175167,0.835033,0.942262,2.775462,0.000000,0.0,2.613870,0.941778,Cafe Ponte,Clearwater,FL,1.000000,0.0,1.000000,low,True
24,ICqgjbOpBD9SUtE5PQC9sA,dish_seed_v2_000020,tuna,4,4,3,1,0,3,0,1,0.993790,0.782075,0.724678,2.898713,3.750000,3.402625,0.680525,0.725684,2.829354,0.069359,0.0,2.723595,0.939588,Captain Bill's Oyster Bar,Treasure Island,FL,0.750000,0.0,0.750000,low,True
25,UakVMT3xrpbFB2pHdxPjnw,dish_seed_v2_000128,grouper sandwich,2,2,2,0,0,2,0,0,0.882998,0.904150,0.801170,1.602341,3.000000,4.112500,0.822500,0.937875,1.602341,0.000000,0.0,1.505312,0.939445,Crown & Bull,Dunedin,FL,1.000000,0.0,1.000000,low,True
26,TDKBPcViJQDMrdUm6a9XZA,dish_seed_v2_000062,salad,2,2,2,0,0,1,1,0,0.851349,0.901800,0.639392,1.278784,4.000000,4.154500,0.830900,0.940815,1.278784,0.000000,0.0,1.198652,0.937337,The Depot Craft Brewery Distillery,Reno,NV,1.000000,0.0,0.500000,low,True
27,KP5OncF2jhT7_J1phHPPww,dish_seed_v2_000024,nachos,2,2,1,1,0,1,0,1,0.964381,0.616850,0.507635,1.015270,5.000000,2.673250,0.534650,0.512127,0.949349,0.065921,0.0,0.950948,0.936645,Besito Mexican Restaurant,Tampa,FL,0.500000,0.0,0.500000,low,True
28,xJIeT5--AiPdvPb5BRflyQ,dish_seed_v2_001404,salad : the size was,2,2,2,0,0,0,2,0,0.789709,0.929200,0.476968,0.953937,4.000000,4.092000,0.818400,0.936440,0.953937,0.000000,0.0,0.893304,0.936440,East Coast Pizza,Riverview,FL,1.000000,0.0,0.000000,low,True
29,xJIeT5--AiPdvPb5BRflyQ,dish_seed_v2_001536,up,2,2,2,0,0,0,2,0,0.659370,0.903900,0.387403,0.774805,4.000000,4.092000,0.818400,0.936440,0.774805,0.000000,0.0,0.725559,0.936440,East Coast Pizza,Riverview,FL,1.000000,0.0,0.000000,low,True
30,OSkLTJeSDAqdcfPGLPj81A,dish_seed_v2_000070,lo mein,2,2,1,1,0,1,0,1,0.960910,0.616900,0.503030,1.006060,5.000000,2.673250,0.534650,0.512127,0.939903,0.066157,0.0,0.941508,0.935836,Chopstick House,Antioch,TN,0.500000,0.0,0.500000,low,True
31,-sSGKR1V1oBm7BJicIXozg,dish_seed_v2_000030,calamari,2,2,1,1,0,1,0,1,0.998512,0.605750,0.506673,1.013346,3.500000,2.509500,0.501900,0.500665,0.948030,0.065316,0.0,0.948117,0.935630,Barra Rossa Ristorante & Wine Bar - Downington,Downingtown,PA,0.500000,0.0,0.500000,low,True
32,5lksp7gCxjCytIG1QZM8yg,dish_seed_v2_000019,fried chicken,2,2,1,1,0,1,0,1,0.999365,0.590700,0.492286,0.984572,3.500000,2.490500,0.498100,0.499335,0.919233,0.065339,0.0,0.919146,0.933548,Manna From Heaven,St. Petersburg,FL,0.500000,0.0,0.500000,low,True
33,1XttS5NTqLxhyNb-Rt2fOQ,dish_seed_v2_000014,crab,2,2,2,0,0,2,0,0,0.996958,0.950000,0.947110,1.894220,4.500000,4.046000,0.809200,0.933220,1.894220,0.000000,0.0,1.768017,0.933375,Keith's Oaks Bar & Grill,Brandon,FL,1.000000,0.0,1.000000,low,True
34,Fe9WDVsrEM9H0X_aFDuYVA,dish_seed_v2_000017,salmon,2,2,1,1,0,1,0,1,0.999152,0.608850,0.508130,1.016261,3.000000,2.445750,0.489150,0.496203,0.949408,0.066853,0.0,0.948159,0.932987,Herbie's Restaurant,Clayton,MO,0.500000,0.0,0.500000,low,True
35,ICqgjbOpBD9SUtE5PQC9sA,dish_seed_v2_000030,calamari,2,2,1,1,0,1,0,1,0.999194,0.614200,0.509438,1.018875,4.500000,2.615500,0.523100,0.508085,0.949339,0.069536,0.0,0.950463,0.932855,Captain Bill's Oyster Bar,Treasure Island,FL,0.500000,0.0,0.500000,low,True
36,lj-E32x9_FA7GmUrBGBEWg,dish_seed_v2_000034,crab cakes,2,2,1,1,0,1,0,1,0.998782,0.614200,0.509149,1.018297,4.000000,2.615500,0.523100,0.508085,0.948777,0.069520,0.0,0.949902,0.932833,Brio Italian Grille,St Louis,MO,0.500000,0.0,0.500000,low,True
37,yqRF449dYddbt1bDg50J_Q,dish_seed_v2_000053,sashimi,2,2,1,1,0,1,0,1,0.998936,0.614200,0.509167,1.018333,4.500000,2.615500,0.523100,0.508085,0.948793,0.069540,0.0,0.949918,0.932816,Rickshaw Sushi,Reno,NV,0.500000,0.0,0.500000,low,True
38,zTdUzhwCUDglY6bHJUEuzg,dish_seed_v2_000011,oysters,2,2,1,1,0,1,0,1,0.999225,0.614200,0.509305,1.018610,4.500000,2.615500,0.523100,0.508085,0.949048,0.069562,0.0,0.950173,0.932813,Kabuki Sushi and Grill,Edmonton,AB,0.500000,0.0,0.500000,low,True
39,b7V_5q22_eTeHlYzq1bpFw,dish_seed_v2_000199,fried shrimp,2,2,1,1,0,1,0,1,0.996357,0.614150,0.507716,1.015431,4.000000,2.615500,0.523100,0.508085,0.946076,0.069356,0.0,0.947197,0.932803,Harbor Seafood & Oyster Bar,Kenner,LA,0.500000,0.0,0.500000,low,True
40,z22hSRptt_DS0nWjsIka2A,dish_seed_v2_000026,lobster,2,2,1,1,0,1,0,1,0.998274,0.614900,0.509521,1.019042,3.500000,2.625000,0.525000,0.508750,0.949280,0.069762,0.0,0.950501,0.932740,Outback Steakhouse,Royersford,PA,0.500000,0.0,0.500000,low,True
41,BjBDHqHhMXSxgyVipccznQ,dish_seed_v2_000033,mussels,2,2,1,1,0,1,0,1,0.998222,0.614200,0.508428,1.016857,4.500000,2.615500,0.523100,0.508085,0.947307,0.069550,0.0,0.948432,0.932709,Rusty Pelican - Tampa,Tampa,FL,0.500000,0.0,0.500000,low,True
42,vzvm7_QXEDaMTxMOKLBNyQ,dish_seed_v2_000006,shrimp,2,2,1,1,0,1,0,1,0.996315,0.614200,0.506709,1.013417,3.500000,2.615500,0.523100,0.508085,0.943882,0.069535,0.0,0.945006,0.932495,Guilin Chinese,Tucson,AZ,0.500000,0.0,0.500000,low,True
43,Y-2Vjxwv5TbV_Wfnxei6Vg,dish_seed_v2_000012,sandwich,2,2,1,1,0,1,0,1,0.999384,0.618850,0.510689,1.021379,5.000000,2.673250,0.534650,0.512127,0.949505,0.071874,0.0,0.951248,0.931337,The Soup and Sandwich,Sherwood Park,AB,0.500000,0.0,0.500000,low,True
44,AP_sb7dETsflRNNkJinYUQ,dish_seed_v2_000041,mashed potatoes,2,2,1,1,0,1,0,1,0.999258,0.618850,0.510611,1.021221,4.500000,2.673250,0.534650,0.512127,0.949354,0.071867,0.0,0.951097,0.931333,Chill Restaurant & Bar,Saint Pete Beach,FL,0.500000,0.0,0.500000,low,True
45,U18r2iiKDtuXtwmiEnsmlQ,dish_seed_v2_000037,latte,2,2,1,1,0,1,0,1,0.998858,0.618850,0.510344,1.020688,5.000000,2.673250,0.534650,0.512127,0.948839,0.071849,0.0,0.950582,0.931315,Paradise Sweets,St. Pete Beach,FL,0.500000,0.0,0.500000,low,True
46,wZhGuW7vQpfhxeEvLHkTrA,dish_seed_v2_000007,steak,2,2,1,1,0,1,0,1,0.997506,0.618800,0.509432,1.018865,5.000000,2.673250,0.534650,0.512127,0.947104,0.071760,0.0,0.948845,0.931277,Express Cafe,Meridian,ID,0.500000,0.0,0.500000,low,True
47,-Or44IdY51Ukd618kikmtA,dish_seed_v2_000085,chicken sandwich,3,3,3,0,0,3,0,0,0.997371,0.928700,0.926233,2.778698,4.666667,3.983667,0.796733,0.928857,2.778698,0.000000,0.0,2.587675,0.931255,Federal Donuts,Philadelphia,PA,1.000000,0.0,1.000000,low,True
48,P6_0KGFZO3K0qHSfhUuINg,dish_seed_v2_000001,pizza,2,2,1,1,0,1,0,1,0.994367,0.614200,0.505351,1.010702,2.500000,2.384500,0.476900,0.491915,0.941245,0.069457,0.0,0.940122,0.930167,Bernie's Restaurant & Bar - Hatboro,Hatboro,PA,0.500000,0.0,0.500000,low,True
49,pVHbXwsqLxNzAx9rdwy2EA,dish_seed_v2_000534,cheese fries,2,2,2,0,0,0,2,0,0.742508,0.920050,0.444044,0.888088,5.000000,4.000500,0.800100,0.930035,0.888088,0.000000,0.0,0.825953,0.930035,Marmont Steakhouse & Bar,Philadelphia,PA,1.000000,0.0,0.000000,low,True

In [14]:
# ============================================================
# 14. QA de agregaciones
# ============================================================

aggregation_summary = {
    "notebook": "10_dish_signal_aggregation",
    "version": "signal_aggregation_v1",
    "source_mentions_path": str(MENTIONS_SENTIMENT_PATH),

    "input": aggregation_input_qa,

    "global_signals": {
        "total_dishes": int(len(dish_global_signals_df)),
        "quality_tier_counts": {
            str(k): int(v)
            for k, v in dish_global_signals_df["aggregate_quality_tier"].value_counts().to_dict().items()
        },
        "top_by_mentions": (
            dish_global_signals_df
            .sort_values("mention_count", ascending=False)
            .head(30)
            [
                [
                    "canonical_dish_name_v2",
                    "mention_count",
                    "review_count",
                    "business_count",
                    "positive_ratio",
                    "negative_ratio",
                    "confidence_weighted_sentiment",
                    "aggregate_quality_tier",
                ]
            ]
            .to_dict(orient="records")
        ),
        "top_by_weighted_sentiment_min_20_mentions": (
            dish_global_signals_df[
                dish_global_signals_df["mention_count"] >= 20
            ]
            .sort_values("confidence_weighted_sentiment", ascending=False)
            .head(30)
            [
                [
                    "canonical_dish_name_v2",
                    "mention_count",
                    "review_count",
                    "business_count",
                    "positive_ratio",
                    "negative_ratio",
                    "confidence_weighted_sentiment",
                    "aggregate_quality_tier",
                ]
            ]
            .to_dict(orient="records")
        ),
    },

    "business_dish_signals": {
        "total_business_dish_pairs": int(len(dish_business_signals_df)),
        "rankable_candidates_v1": int(dish_business_signals_df["is_rankable_candidate_v1"].sum()),
        "quality_tier_counts": {
            str(k): int(v)
            for k, v in dish_business_signals_df["aggregate_quality_tier"].value_counts().to_dict().items()
        },
        "top_rankable_candidates": (
            dish_business_signals_df[
                dish_business_signals_df["is_rankable_candidate_v1"]
            ]
            .sort_values(
                ["confidence_weighted_sentiment", "mention_count", "positive_ratio"],
                ascending=[False, False, False]
            )
            .head(50)
            [
                [
                    "business_id",
                    "business_name",
                    "city",
                    "state",
                    "canonical_dish_name_v2",
                    "mention_count",
                    "review_count",
                    "positive_ratio",
                    "negative_ratio",
                    "confidence_weighted_sentiment",
                    "total_signal_weight",
                    "aggregate_quality_tier",
                ]
            ]
            .to_dict(orient="records")
        ),
    }
}

print(json.dumps(aggregation_summary, indent=2, ensure_ascii=False)[:7000])

print("\nGlobal quality tiers:")
display(dish_global_signals_df["aggregate_quality_tier"].value_counts())

print("\nBusiness-dish quality tiers:")
display(dish_business_signals_df["aggregate_quality_tier"].value_counts())

print("\nTop global por sentimiento ponderado, mínimo 20 menciones:")
display(
    dish_global_signals_df[
        dish_global_signals_df["mention_count"] >= 20
    ]
    .sort_values("confidence_weighted_sentiment", ascending=False)
    .head(30)
    [
        [
            "canonical_dish_name_v2",
            "mention_count",
            "review_count",
            "business_count",
            "positive_ratio",
            "negative_ratio",
            "confidence_weighted_sentiment",
            "aggregate_quality_tier",
        ]
    ]
)

{
  "notebook": "10_dish_signal_aggregation",
  "version": "signal_aggregation_v1",
  "source_mentions_path": "/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_with_sentiment_hybrid_v1.jsonl",
  "input": {
    "total_mentions": 94932,
    "unique_reviews": 42461,
    "unique_businesses": 4088,
    "unique_dishes": 9937,
    "sentiment_counts": {
      "neutral": 45366,
      "positive": 43142,
      "negative": 6424
    },
    "reliability_counts": {
      "low": 44426,
      "medium": 25495,
      "high": 25011
    },
    "signal_weight": {
      "min": 0.020311710990965366,
      "mean": 0.37781376200795724,
      "median": 0.3624973218077422,
      "max": 0.9497699350118637
    },
    "weighted_sentiment_value": {
      "min": -1.0,
      "mean": 0.3117034681140184,
      "median": 0.041755,
      "max": 1.0
    }
  },
  "global_signals": {
    "total_dishes": 9937,
    "quality_tier_counts": {
      "low": 9782,
      "medium": 95,
      "high": 60
    },
    "top_by_mentions": [
      {
        "canonical_dish_name_v2": "pizza",
        "mention_count": 8751,
        "review_count": 4599,
        "business_count": 856,
        "positive_ratio": 0.431836361558679,
        "negative_ratio": 0.06627813964118387,
        "confidence_weighted_sentiment": 0.526867927479517,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "burger",
        "mention_count": 8095,
        "review_count": 4478,
        "business_count": 863,
        "positive_ratio": 0.44027177269919704,
        "negative_ratio": 0.07016676961087091,
        "confidence_weighted_sentiment": 0.5224681722482504,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "fries",
        "mention_count": 5375,
        "review_count": 4094,
        "business_count": 1093,
        "positive_ratio": 0.4504186046511628,
        "negative_ratio": 0.09079069767441861,
        "confidence_weighted_sentiment": 0.495307517076623,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "sushi",
        "mention_count": 4470,
        "review_count": 2482,
        "business_count": 266,
        "positive_ratio": 0.45369127516778524,
        "negative_ratio": 0.060626398210290824,
        "confidence_weighted_sentiment": 0.5511412982657379,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "tacos",
        "mention_count": 4436,
        "review_count": 2707,
        "business_count": 533,
        "positive_ratio": 0.4190712353471596,
        "negative_ratio": 0.06830477908025248,
        "confidence_weighted_sentiment": 0.5296233063435303,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "shrimp",
        "mention_count": 4421,
        "review_count": 3269,
        "business_count": 865,
        "positive_ratio": 0.457362587649853,
        "negative_ratio": 0.07735806378647365,
        "confidence_weighted_sentiment": 0.5297350722226231,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "steak",
        "mention_count": 2794,
        "review_count": 2102,
        "business_count": 830,
        "positive_ratio": 0.3919112383679313,
        "negative_ratio": 0.10343593414459556,
        "confidence_weighted_sentiment": 0.41959742187602145,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "ice cream",
        "mention_count": 2411,
        "review_count": 1588,
        "business_count": 475,
        "positive_ratio": 0.4346744089589382,
        "negative_ratio": 0.03318125259228536,
        "confidence_weighted_sentiment": 0.6025940809840803,
        "aggregate_quality_tier": "medium"
      },
      {
        "canonical_dish_name_v2": "wings",
        "mention_count": 2215,
        "review_count": 1493,
        "business_count": 588,
        "positive_ratio": 0.47539503386004517,
        "negative_ratio": 0.07223476297968397,
        "confidence_weighted_sentiment": 0.5405573823251678,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "donut",
        "mention_count": 2175,
        "review_count": 973,
        "business_count": 175,
        "positive_ratio": 0.4050574712643678,
        "negative_ratio": 0.05655172413793103,
        "confidence_weighted_sentiment": 0.5234568566237225,
        "aggregate_quality_tier": "medium"
      },
      {
        "canonical_dish_name_v2": "oysters",
        "mention_count": 2129,
        "review_count": 1321,
        "business_count": 203,
        "positive_ratio": 0.4589008924377642,
        "negative_ratio": 0.0624706434945984,
        "confidence_weighted_sentiment": 0.5530758667271676,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "sandwich",
        "mention_count": 2127,
        "review_count": 1851,
        "business_count": 820,
        "positive_ratio": 0.5213916314057357,
        "negative_ratio": 0.03620122237893747,
        "confidence_weighted_sentiment": 0.6472568179013339,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "pancake",
        "mention_count": 2035,
        "review_count": 1314,
        "business_count": 267,
        "positive_ratio": 0.45257985257985256,
        "negative_ratio": 0.04815724815724816,
        "confidence_weighted_sentiment": 0.5868842316711084,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "crab",
        "mention_count": 1535,
        "review_count": 1138,
        "business_count": 423,
        "positive_ratio": 0.4013029315960912,
        "negative_ratio": 0.07035830618892508,
        "confidence_weighted_sentiment": 0.5085689546163795,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "burrito",
        "mention_count": 1405,
        "review_count": 971,
        "business_count": 320,
        "positive_ratio": 0.38149466192170817,
        "negative_ratio": 0.06975088967971531,
        "confidence_weighted_sentiment": 0.48709327943870667,
        "aggregate_quality_tier": "medium"
      },
      {
        "canonical_dish_name_v2": "pho",
        "mention_count": 1225,
        "review_count": 708,
        "business_count": 91,
        "positive_ratio": 0.4310204081632653,
        "negative_ratio": 0.044897959183673466,
        "confidence_weighted_sentiment": 0.5820212970282324,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "salmon",
        "mention_count": 1137,
        "review_count": 920,
        "business_count": 456,
        "positive_ratio": 0.42480211081794195,
        "negative_ratio": 0.09234828496042216,
        "confidence_weighted_sentiment": 0.4869190916649011,
        "aggregate_quality_tier": "high"
      },
      {
        "canonical_dish_name_v2": "ribs",


Global quality tiers:

aggregate_quality_tier
low       9782
medium      95
high        60
Name: count, dtype: int64

Business-dish quality tiers:

aggregate_quality_tier
low       30219
medium      698
high        119
Name: count, dtype: int64

Top global por sentimiento ponderado, mínimo 20 menciones:

,canonical_dish_name_v2,mention_count,review_count,business_count,positive_ratio,negative_ratio,confidence_weighted_sentiment,aggregate_quality_tier
124,lobster risotto,20,19,6,0.700000,0.000000,0.803143,medium
85,caesar salad,41,38,36,0.658537,0.024390,0.789225,medium
97,bbq shrimp,31,30,9,0.741935,0.000000,0.772352,medium
94,brisket ramen,32,28,2,0.593750,0.000000,0.765963,medium
75,coffee,68,68,53,0.779412,0.058824,0.752304,high
116,curry,23,22,21,0.521739,0.043478,0.743579,medium
90,greek salad,34,32,28,0.470588,0.029412,0.739871,medium
99,tempura shrimp,30,28,18,0.566667,0.000000,0.739072,medium
95,lobster mac and cheese,32,28,12,0.656250,0.031250,0.738933,medium
103,sonoran,27,26,8,0.777778,0.000000,0.736071,medium
122,cupcake,21,19,14,0.523810,0.047619,0.735107,medium
89,brisket taco,35,31,12,0.457143,0.000000,0.702464,medium
120,mashed,22,22,19,0.409091,0.000000,0.702398,medium
93,pasta,33,33,31,0.666667,0.090909,0.693368,medium
79,lobster ravioli,58,53,30,0.500000,0.051724,0.683553,high
104,fettuccine,27,27,22,0.555556,0.037037,0.682179,medium
125,tuna taco,20,18,13,0.450000,0.000000,0.680904,medium
82,chicken sandwich,42,40,32,0.571429,0.071429,0.677718,medium
91,steak fries,34,32,27,0.382353,0.000000,0.675675,medium
76,steak taco,68,65,40,0.573529,0.029412,0.672672,high
73,korma,72,58,30,0.416667,0.041667,0.660109,medium
113,veggie burger,24,21,15,0.458333,0.041667,0.659011,medium
51,gnocchi,251,202,86,0.561753,0.031873,0.649598,high
11,sandwich,2127,1851,820,0.521392,0.036201,0.647257,high
109,kale salad,25,22,21,0.560000,0.040000,0.646277,medium
66,waffle fries,122,107,33,0.663934,0.049180,0.644553,high
36,latte,446,371,149,0.475336,0.033632,0.634972,high
61,salad,176,173,153,0.551136,0.068182,0.632378,medium
27,hummus,632,503,179,0.506329,0.042722,0.629934,high
80,tea,57,51,42,0.578947,0.052632,0.623484,medium

In [15]:
# ============================================================
# 15. Guardar outputs del primer bloque
# ============================================================

global_signals_path = SIGNALS_DIR / "dish_global_signals_v1.csv"
business_signals_path = SIGNALS_DIR / "dish_business_signals_v1.csv"
summary_path = ARTIFACTS_DIR / "dish_signal_aggregation_summary_v1.json"

dish_global_signals_df.to_csv(global_signals_path, index=False)
dish_business_signals_df.to_csv(business_signals_path, index=False)

aggregation_summary["outputs"] = {
    "dish_global_signals": str(global_signals_path),
    "dish_business_signals": str(business_signals_path),
    "summary": str(summary_path),
}

with summary_path.open("w", encoding="utf-8") as f:
    json.dump(aggregation_summary, f, indent=2, ensure_ascii=False)

print("Outputs guardados:")
print("global_signals_path:", global_signals_path)
print("business_signals_path:", business_signals_path)
print("summary_path:", summary_path)

Outputs guardados:
global_signals_path: /kaggle/working/hidden_gems_ai/outputs/dish_signal_aggregation/signals/dish_global_signals_v1.csv
business_signals_path: /kaggle/working/hidden_gems_ai/outputs/dish_signal_aggregation/signals/dish_business_signals_v1.csv
summary_path: /kaggle/working/hidden_gems_ai/outputs/dish_signal_aggregation/artifacts/dish_signal_aggregation_summary_v1.json

## 3. Scoring inicial para ranking

La agregación por negocio-plato ya está creada, pero todavía no debe usarse directamente como ranking.

Problemas detectados:

1. Algunos pares tienen sentimiento muy alto, pero solo 2 menciones.
2. Algunos nombres canónicos siguen siendo ruidosos o demasiado extendidos.
3. El ranking necesita penalizar baja evidencia.
4. El ranking necesita separar candidatos fuertes, emergentes y no listos.

En este bloque se añade una capa de scoring preliminar:

- control de calidad del nombre del plato;
- tier de evidencia;
- sentimiento bayesiano con prior neutral;
- penalización por baja evidencia;
- penalización por ruido;
- score preliminar para ranking.

Este score todavía no incorpora barrios. Será la base para el siguiente notebook de ranking.

In [16]:
# ============================================================
# 16. Reglas de calidad para nombres de platos
# ============================================================

DISH_NAME_EXACT_NOISE = {
    "",
    "#",
    "up",
    "food",
    "meal",
    "menu",
    "dish",
    "dishes",
    "side",
    "sides",
    "appetizer",
    "appetizers",
    "starter",
    "starters",
    "entree",
    "entrees",
    "drink",
    "drinks",
    "water",
    "sauce",
    "dressing",
    "good",
    "great",
    "was",
    "were",
    "ordered",
    "order",
    "service",
    "place",
    "restaurant",
}

SUSPICIOUS_WORDS_IN_DISH_NAME = {
    "wife",
    "husband",
    "server",
    "waiter",
    "waitress",
    "price",
    "size",
    "ordered",
    "order",
    "came",
    "come",
    "served",
    "was",
    "were",
    "is",
    "are",
    "very",
    "really",
    "good",
    "great",
    "bad",
}

POSSIBLE_BEVERAGE_TERMS = {
    "coffee",
    "latte",
    "tea",
    "smoothie",
    "mojito",
    "beer",
    "wine",
    "cocktail",
    "margarita",
    "espresso",
    "cappuccino",
}

def build_dish_name_quality_flags(name: str) -> list[str]:
    flags = []

    if not isinstance(name, str):
        return ["invalid_name"]

    clean = re.sub(r"\s+", " ", name.lower()).strip()
    words = clean.split()

    if not clean:
        flags.append("empty_name")

    if clean in DISH_NAME_EXACT_NOISE:
        flags.append("exact_noise_name")

    if len(clean) <= 2 and clean not in {"bbq"}:
        flags.append("too_short_name")

    if len(clean) > 70:
        flags.append("too_long_name")

    if len(words) > 7:
        flags.append("too_many_words")

    if re.search(r"[:#@<>]", clean):
        flags.append("suspicious_punctuation")

    if re.search(r"\d", clean):
        flags.append("contains_digit")

    if words:
        if words[0] in {"was", "were", "is", "are", "the", "a", "an"}:
            flags.append("bad_start_word")

        if words[-1] in {"was", "were", "is", "are", "with", "and", "or", "the", "a", "an"}:
            flags.append("bad_end_word")

    suspicious_hits = sorted(set(words) & SUSPICIOUS_WORDS_IN_DISH_NAME)

    if suspicious_hits:
        flags.append("contains_suspicious_words")

    if clean in POSSIBLE_BEVERAGE_TERMS:
        flags.append("possible_beverage")

    return sorted(set(flags))


def is_hard_noise_dish_name(flags: list[str]) -> bool:
    hard_flags = {
        "empty_name",
        "invalid_name",
        "exact_noise_name",
        "too_short_name",
        "too_long_name",
        "too_many_words",
        "suspicious_punctuation",
        "contains_digit",
        "bad_start_word",
        "bad_end_word",
    }

    return any(flag in hard_flags for flag in flags)


for df_name, df_obj in [
    ("dish_global_signals_df", dish_global_signals_df),
    ("dish_business_signals_df", dish_business_signals_df),
]:
    df_obj["dish_name_quality_flags"] = df_obj["canonical_dish_name_v2"].apply(
        build_dish_name_quality_flags
    )

    df_obj["is_hard_noise_dish_name"] = df_obj["dish_name_quality_flags"].apply(
        is_hard_noise_dish_name
    )

    df_obj["is_possible_beverage"] = df_obj["dish_name_quality_flags"].apply(
        lambda flags: "possible_beverage" in flags
    )

    print(df_name)
    print("hard noise:", int(df_obj["is_hard_noise_dish_name"].sum()))
    print("possible beverage:", int(df_obj["is_possible_beverage"].sum()))
    print()

dish_global_signals_df
hard noise: 696
possible beverage: 8

dish_business_signals_df
hard noise: 806
possible beverage: 359

In [17]:
# ============================================================
# 17. Tiers de evidencia
# ============================================================

def compute_business_evidence_tier(row) -> str:
    mention_count = int(row.get("mention_count", 0))
    review_count = int(row.get("review_count", 0))
    total_signal_weight = float(row.get("total_signal_weight", 0.0))
    high_reliability_mentions = int(row.get("high_reliability_mentions", 0))

    if (
        mention_count >= 10
        and review_count >= 8
        and total_signal_weight >= 4.0
        and high_reliability_mentions >= 3
    ):
        return "strong"

    if (
        mention_count >= 5
        and review_count >= 4
        and total_signal_weight >= 2.0
    ):
        return "solid"

    if (
        mention_count >= 3
        and review_count >= 3
        and total_signal_weight >= 1.25
    ):
        return "emerging"

    return "weak"


def compute_global_evidence_tier(row) -> str:
    mention_count = int(row.get("mention_count", 0))
    review_count = int(row.get("review_count", 0))
    business_count = int(row.get("business_count", 0))
    total_signal_weight = float(row.get("total_signal_weight", 0.0))

    if (
        mention_count >= 500
        and review_count >= 250
        and business_count >= 50
        and total_signal_weight >= 100
    ):
        return "strong"

    if (
        mention_count >= 100
        and review_count >= 50
        and business_count >= 15
        and total_signal_weight >= 25
    ):
        return "solid"

    if (
        mention_count >= 20
        and review_count >= 10
        and business_count >= 3
        and total_signal_weight >= 5
    ):
        return "emerging"

    return "weak"


dish_business_signals_df["business_dish_evidence_tier"] = dish_business_signals_df.apply(
    compute_business_evidence_tier,
    axis=1
)

dish_global_signals_df["global_evidence_tier"] = dish_global_signals_df.apply(
    compute_global_evidence_tier,
    axis=1
)

print("Business-dish evidence tiers:")
display(dish_business_signals_df["business_dish_evidence_tier"].value_counts())

print("\nGlobal evidence tiers:")
display(dish_global_signals_df["global_evidence_tier"].value_counts())

Business-dish evidence tiers:

business_dish_evidence_tier
weak        27194
emerging     1440
solid        1406
strong        996
Name: count, dtype: int64

Global evidence tiers:

global_evidence_tier
weak        9815
emerging      55
strong        34
solid         33
Name: count, dtype: int64

In [18]:
# ============================================================
# 18. Scoring conservador negocio-plato
# ============================================================

PRIOR_SIGNAL_WEIGHT = 3.0
NEUTRAL_SENTIMENT_PRIOR = 0.0

business_scoring_df = dish_business_signals_df.copy()

# Sentimiento bayesiano con prior neutral.
# Evita que pares con 2 menciones y score perfecto dominen el ranking.
business_scoring_df["bayesian_sentiment_score"] = (
    (
        business_scoring_df["confidence_weighted_sentiment"].fillna(0.0)
        * business_scoring_df["total_signal_weight"].fillna(0.0)
    )
    + (NEUTRAL_SENTIMENT_PRIOR * PRIOR_SIGNAL_WEIGHT)
) / (
    business_scoring_df["total_signal_weight"].fillna(0.0)
    + PRIOR_SIGNAL_WEIGHT
)

business_scoring_df["bayesian_sentiment_component"] = (
    (business_scoring_df["bayesian_sentiment_score"] + 1.0) / 2.0
).clip(0.0, 1.0)

business_scoring_df["evidence_score"] = (
    np.log1p(business_scoring_df["review_count"])
    / np.log1p(12)
).clip(0.0, 1.0)

business_scoring_df["mention_volume_score"] = (
    np.log1p(business_scoring_df["mention_count"])
    / np.log1p(15)
).clip(0.0, 1.0)

business_scoring_df["signal_weight_score"] = (
    business_scoring_df["total_signal_weight"] / 5.0
).clip(0.0, 1.0)

business_scoring_df["confidence_quality_score"] = (
    business_scoring_df["avg_signal_weight"] / 0.55
).clip(0.0, 1.0)

business_scoring_df["positive_balance_score"] = (
    business_scoring_df["positive_ratio"]
    - business_scoring_df["negative_ratio"]
).clip(-1.0, 1.0)

business_scoring_df["positive_balance_component"] = (
    (business_scoring_df["positive_balance_score"] + 1.0) / 2.0
).clip(0.0, 1.0)

business_scoring_df["negative_penalty_factor"] = (
    1.0 - (business_scoring_df["negative_ratio"] * 1.25)
).clip(0.55, 1.0)

business_scoring_df["noise_penalty_factor"] = np.where(
    business_scoring_df["is_hard_noise_dish_name"],
    0.0,
    1.0
)

business_scoring_df["beverage_penalty_factor"] = np.where(
    business_scoring_df["is_possible_beverage"],
    0.85,
    1.0
)

business_scoring_df["preliminary_ranking_score_v1"] = 100.0 * (
    0.34 * business_scoring_df["bayesian_sentiment_component"]
    + 0.18 * business_scoring_df["positive_balance_component"]
    + 0.18 * business_scoring_df["evidence_score"]
    + 0.12 * business_scoring_df["mention_volume_score"]
    + 0.10 * business_scoring_df["signal_weight_score"]
    + 0.08 * business_scoring_df["reliability_high_ratio"].clip(0.0, 1.0)
)

business_scoring_df["preliminary_ranking_score_v1"] = (
    business_scoring_df["preliminary_ranking_score_v1"]
    * business_scoring_df["negative_penalty_factor"]
    * business_scoring_df["noise_penalty_factor"]
    * business_scoring_df["beverage_penalty_factor"]
)

business_scoring_df["preliminary_ranking_score_v1"] = (
    business_scoring_df["preliminary_ranking_score_v1"]
    .clip(0.0, 100.0)
)

business_scoring_df["is_ranking_ready_v1"] = (
    ~business_scoring_df["is_hard_noise_dish_name"]
    & business_scoring_df["business_dish_evidence_tier"].isin({"emerging", "solid", "strong"})
    & (business_scoring_df["total_signal_weight"] >= 1.25)
    & (business_scoring_df["review_count"] >= 3)
    & (business_scoring_df["mention_count"] >= 3)
)

def assign_preliminary_candidate_tier(row) -> str:
    if not row["is_ranking_ready_v1"]:
        return "not_ready"

    score = float(row["preliminary_ranking_score_v1"])
    evidence_tier = row["business_dish_evidence_tier"]

    if score >= 75 and evidence_tier in {"solid", "strong"}:
        return "strong_candidate"

    if score >= 65 and evidence_tier in {"emerging", "solid", "strong"}:
        return "promising_candidate"

    if score >= 55:
        return "weak_candidate"

    return "not_ready"


business_scoring_df["preliminary_candidate_tier_v1"] = business_scoring_df.apply(
    assign_preliminary_candidate_tier,
    axis=1
)

business_scoring_df = business_scoring_df.sort_values(
    [
        "is_ranking_ready_v1",
        "preliminary_ranking_score_v1",
        "business_dish_evidence_tier",
        "review_count",
        "mention_count",
    ],
    ascending=[False, False, True, False, False]
).reset_index(drop=True)

print("Pares negocio-plato:", len(business_scoring_df))
print("Ranking ready v1:", int(business_scoring_df["is_ranking_ready_v1"].sum()))

print("\nCandidate tiers:")
display(business_scoring_df["preliminary_candidate_tier_v1"].value_counts())

display(
    business_scoring_df[
        [
            "business_name",
            "city",
            "state",
            "canonical_dish_name_v2",
            "mention_count",
            "review_count",
            "positive_ratio",
            "negative_ratio",
            "confidence_weighted_sentiment",
            "bayesian_sentiment_score",
            "total_signal_weight",
            "business_dish_evidence_tier",
            "preliminary_ranking_score_v1",
            "preliminary_candidate_tier_v1",
            "dish_name_quality_flags",
        ]
    ].head(50)
)

Pares negocio-plato: 31036
Ranking ready v1: 3841

Candidate tiers:

preliminary_candidate_tier_v1
not_ready              28147
weak_candidate          1223
promising_candidate     1021
strong_candidate         645
Name: count, dtype: int64

,business_name,city,state,canonical_dish_name_v2,mention_count,review_count,positive_ratio,negative_ratio,confidence_weighted_sentiment,bayesian_sentiment_score,total_signal_weight,business_dish_evidence_tier,preliminary_ranking_score_v1,preliminary_candidate_tier_v1,dish_name_quality_flags
0,The Little Lamb,Clearwater,FL,burger,15,13,0.866667,0.000000,0.802149,0.600349,8.924912,strong,88.805930,strong_candidate,[]
1,East Beach Grill,Santa Barbara,CA,pancake,24,14,0.791667,0.000000,0.804999,0.665284,14.285097,strong,88.768158,strong_candidate,[]
2,Three Muses,New Orleans,LA,steak,32,26,0.781250,0.000000,0.776507,0.663566,17.626015,strong,88.061879,strong_candidate,[]
3,Sushi Ushi,Valrico,FL,sushi,53,28,0.716981,0.000000,0.770510,0.694509,27.414415,strong,87.580242,strong_candidate,[]
4,4 Rivers Smokehouse,Tampa Bay,FL,brisket,16,13,0.750000,0.000000,0.783810,0.606483,10.260428,strong,87.560215,strong_candidate,[]
5,Goody's Soda Fountain & Candy Store,Boise,ID,ice cream,30,20,0.666667,0.000000,0.778703,0.657213,16.228838,strong,87.439295,strong_candidate,[]
6,Backspace Bar & Kitchen,New Orleans,LA,burger,18,14,0.777778,0.000000,0.824746,0.640074,10.398027,strong,87.436818,strong_candidate,[]
7,Barbecue and Bourbon,Speedway,IN,pulled pork,12,12,0.833333,0.000000,0.754434,0.553283,8.251728,strong,87.340456,strong_candidate,[]
8,Empress Garden,Philadelphia,PA,pancake,15,14,0.866667,0.000000,0.818223,0.602247,8.365439,strong,87.238194,strong_candidate,[]
9,Plaza Deli,Santa Barbara,CA,sandwich,19,16,0.789474,0.000000,0.781770,0.607592,10.464968,strong,87.223795,strong_candidate,[]
10,Zeppoli,Collingswood,NJ,gnocchi,27,19,0.814815,0.000000,0.770078,0.636316,14.271146,strong,87.113660,strong_candidate,[]
11,Blues City Deli,Saint Louis,MO,sandwich,108,87,0.731481,0.000000,0.740591,0.701165,53.353000,strong,87.021653,strong_candidate,[]
12,HipCityVeg - University City,Philadelphia,PA,fries,37,31,0.702703,0.000000,0.758389,0.659745,20.064392,strong,86.999445,strong_candidate,[]
13,Sabrina's West Street Kitchen,Reno,NV,tacos,14,12,0.857143,0.000000,0.837639,0.594387,7.330511,strong,86.968109,strong_candidate,[]
14,Izumi,Philadelphia,PA,sashimi,14,11,0.785714,0.000000,0.801808,0.595016,8.632080,strong,86.917085,strong_candidate,[]
15,District Donuts Sliders Brew,New Orleans,LA,waffle fries,27,26,0.814815,0.000000,0.744911,0.614678,14.159490,strong,86.745823,strong_candidate,[]
16,Tako Japanese Restaurant,Bensalem,PA,sushi,31,22,0.645161,0.000000,0.790613,0.665698,15.987598,strong,86.736220,strong_candidate,[]
17,Sam's Brick Oven Pizza,Ardmore,PA,pizza,17,13,0.823529,0.000000,0.775488,0.588299,9.428420,strong,86.706959,strong_candidate,[]
18,Dawn Patrol,Santa Barbara,CA,pancake,15,10,0.800000,0.000000,0.815813,0.609816,8.880957,strong,86.661208,strong_candidate,[]
19,Persis Biryani Indian Grill,Mount Juliet,TN,naan,12,11,0.750000,0.000000,0.818390,0.588099,7.661169,strong,86.620622,strong_candidate,[]
20,Chatham Tap Mass. Ave.,Indianapolis,IN,wings,29,23,0.758621,0.000000,0.780782,0.640702,13.721384,strong,86.478133,strong_candidate,[]
21,The Fat Ham,Philadelphia,PA,shrimp,22,15,0.681818,0.000000,0.795294,0.628677,11.319526,strong,86.460235,strong_candidate,[]
22,Saki Endless Sushi & Hibachi Eatery,Clearwater,FL,shrimp,14,11,0.714286,0.000000,0.826524,0.604191,8.152526,strong,86.430211,strong_candidate,[]
23,Two Chicks Cafe,New Orleans,LA,french toast,18,16,0.722222,0.000000,0.794162,0.604096,9.535039,strong,86.325185,strong_candidate,[]
24,Jesse's Steak and Seafood,Brandon,FL,steak,14,12,0.857143,0.000000,0.773257,0.555453,7.650749,strong,86.306235,strong_candidate,[]
25,Uncle Maddios Pizza,Lutz,FL,pizza,36,17,0.638889,0.000000,0.781626,0.667559,17.556962,strong,86.209606,strong_candidate,[]
26,Two Chicks Cafe,New Orleans,LA,shrimp,31,24,0.645161,0.000000,0.804689,0.663626,14.113452,strong,86.184871,strong_candidate,[]
27,Taqueria Cuernavaca,Santa Barbara,CA,tacos,73,45,0.630137,0.000000,0.763692,0.697991,31.871341,strong,86.167225,strong_candidate,[]
28,Surrey's Café & Juice Bar,New Orleans,LA,shrimp,159,120,0.628931,0.006289,0.750381,0.721687,75.452922,strong,86.158288,strong_candidate,[]
29,Kei Sushi,Reno,NV,sushi,64,31,0.640625,0.000000,0.754215,0.681367,28.059837,strong,86.098868,strong_candidate,[]
30,Pho 36,Avon,IN,spring rolls,20,15,0.650000,0.000000,0.796517,0.616521,10.275607,strong,85.930859,strong_candidate,[]
31,Prep & Pastry,Tucson,AZ,omelet,24,20,0.666667,0.000000,0.775682,0.621384,12.081544,strong,85.896867,strong_candidate,[]
32,Red Pony,Franklin,TN,shrimp,17,15,0.764706,0.000000,0.747645,0.568926,9.550073,strong,85.848216,strong_candidate,[]
33,M.L.Rose Craft Beer & Burgers - Melrose,Nashville,TN,waffle fries,21,14,0.761905,0.000000,0.751319,0.580782,10.216841,strong,85.778054,strong_candidate,[]
34,Khyber Pass Pub,Philadelphia,PA,nachos,21,17,0.666667,0.000000,0.781934,0.606656,10.383343,strong,85.741728,strong_candidate,[]
35,Mazzaro's Italian Market,Saint Petersburg,FL,sandwich,41,33,0.804878,0.024390,0.728968,0.647692,23.907178,strong,85.634912,strong_candidate,[]
36,El Limon - Malvern,Malvern,PA,tacos,39,28,0.589744,0.000000,0.767583,0.657248,17.870512,strong,85.557827,strong_candidate,[]
37,Khyber Pass Pub,Philadelphia,PA,burger,17,11,0.705882,0.000000,0.769830,0.586884,9.623868,strong,85.532955,strong_candidate,[]
38,Wildflower Cafe,Clearwater,FL,french toast,15,11,0.733333,0.000000,0.796424,0.573098,7.698582,strong,85.514285,strong_candidate,[]
39,Zeko's Mediterranean Grill,Tampa,FL,hummus,13,10,0.769231,0.000000,0.808095,0.586266,7.928629,strong,85.447030,strong_candidate,[]
40,Paola's Pizzeria,Wayne,PA,pizza,23,14,0.652174,0.000000,0.770670,0.607586,11.176801,strong,85.328957,strong_candidate,[]
41,The Fountain On Locust,Saint Louis,MO,sandwich,20,18,0.700000,0.000000,0.793720,0.601017,9.356632,strong,85.317286,strong_candidate,[]
42,Mr. B's Bistro,New Orleans,LA,spring rolls,15,14,0.733333,0.000000,0.765878,0.556459,7.971485,strong,85.259805,strong_candidate,[]
43,Olio,Saint Louis,MO,hummus,15,13,0.666667,0.000000,0.818703,0.589684,7.724470,strong,85.224629,strong_candidate,[]
44,Gateway To India,St. Petersburg,FL,naan,22,17,0.590909,0.000000,0.767019,0.603003,11.029409,strong,85.205589,strong_candidate,[]
45,Ron's Original Bar & Grille,Exton,PA,pizza,15,13,0.666667,0.000000,0.837277,0.587033,7.037507,strong,85.179556,strong_candidate,[]
46,R2L,Philadelphia,PA,tuna,13,12,0.692308,0.000000,0.822040,0.578361,7.120344,strong,85.177275,strong_candidate,[]
47,Honey's Sit-N-Eat,Philadelphia,PA,french toast,26,21,0.576923,0.000000,0.776540,0.622288,12.102624,strong,85.155813,strong_candidate,[]
48,Puckett's Grocery & Restaurant,Franklin,TN,brisket,14,11,0.785714,0.000000,0.763570,0.551822,7.818081,strong,85.039930,strong_candidate,[]
49,Barbecue and Bourbon,Speedway,IN,brisket,12,10,0.750000,0.000000,0.788952,0.568648,7.743595,strong,85.012671,strong_candidate,[]

In [19]:
# ============================================================
# 19. Scoring global por plato
# ============================================================

global_scoring_df = dish_global_signals_df.copy()

global_scoring_df["global_sentiment_component"] = (
    (global_scoring_df["confidence_weighted_sentiment"].fillna(0.0) + 1.0) / 2.0
).clip(0.0, 1.0)

global_scoring_df["global_evidence_score"] = (
    np.log1p(global_scoring_df["review_count"])
    / np.log1p(500)
).clip(0.0, 1.0)

global_scoring_df["global_business_coverage_score"] = (
    np.log1p(global_scoring_df["business_count"])
    / np.log1p(200)
).clip(0.0, 1.0)

global_scoring_df["global_positive_balance_score"] = (
    global_scoring_df["positive_ratio"]
    - global_scoring_df["negative_ratio"]
).clip(-1.0, 1.0)

global_scoring_df["global_positive_balance_component"] = (
    (global_scoring_df["global_positive_balance_score"] + 1.0) / 2.0
).clip(0.0, 1.0)

global_scoring_df["global_negative_penalty_factor"] = (
    1.0 - (global_scoring_df["negative_ratio"] * 1.25)
).clip(0.55, 1.0)

global_scoring_df["global_noise_penalty_factor"] = np.where(
    global_scoring_df["is_hard_noise_dish_name"],
    0.0,
    1.0
)

global_scoring_df["global_beverage_penalty_factor"] = np.where(
    global_scoring_df["is_possible_beverage"],
    0.85,
    1.0
)

global_scoring_df["global_ranking_signal_score_v1"] = 100.0 * (
    0.35 * global_scoring_df["global_sentiment_component"]
    + 0.20 * global_scoring_df["global_positive_balance_component"]
    + 0.20 * global_scoring_df["global_evidence_score"]
    + 0.15 * global_scoring_df["global_business_coverage_score"]
    + 0.10 * global_scoring_df["reliability_high_ratio"].clip(0.0, 1.0)
)

global_scoring_df["global_ranking_signal_score_v1"] = (
    global_scoring_df["global_ranking_signal_score_v1"]
    * global_scoring_df["global_negative_penalty_factor"]
    * global_scoring_df["global_noise_penalty_factor"]
    * global_scoring_df["global_beverage_penalty_factor"]
).clip(0.0, 100.0)

global_scoring_df = global_scoring_df.sort_values(
    [
        "global_ranking_signal_score_v1",
        "global_evidence_tier",
        "mention_count",
    ],
    ascending=[False, True, False]
).reset_index(drop=True)

print("Global scoring generado:", len(global_scoring_df))

display(
    global_scoring_df[
        [
            "canonical_dish_name_v2",
            "mention_count",
            "review_count",
            "business_count",
            "positive_ratio",
            "negative_ratio",
            "confidence_weighted_sentiment",
            "global_evidence_tier",
            "global_ranking_signal_score_v1",
            "dish_name_quality_flags",
        ]
    ].head(50)
)

Global scoring generado: 9937

,canonical_dish_name_v2,mention_count,review_count,business_count,positive_ratio,negative_ratio,confidence_weighted_sentiment,global_evidence_tier,global_ranking_signal_score_v1,dish_name_quality_flags
0,sandwich,2127,1851,820,0.521392,0.036201,0.647257,strong,77.937467,[]
1,hummus,632,503,179,0.506329,0.042722,0.629934,strong,76.536377,[]
2,ice cream,2411,1588,475,0.434674,0.033181,0.602594,strong,75.832065,[]
3,eggplant,381,329,197,0.475066,0.036745,0.613559,solid,75.487664,[]
4,french toast,877,718,203,0.500570,0.051311,0.606910,strong,75.388615,[]
5,pancake,2035,1314,267,0.452580,0.048157,0.586884,strong,74.633747,[]
6,spring rolls,418,361,141,0.555024,0.055024,0.618937,solid,74.485805,[]
7,pulled pork,601,529,203,0.492512,0.058236,0.575957,strong,74.114866,[]
8,gnocchi,251,202,86,0.561753,0.031873,0.649598,solid,73.816951,[]
9,waffle,879,646,226,0.422071,0.048919,0.559584,strong,73.735905,[]
10,sushi,4470,2482,266,0.453691,0.060626,0.551141,strong,72.636432,[]
11,pizza here,8,8,8,1.000000,0.000000,0.818468,weak,72.606758,[]
12,oysters,2129,1321,203,0.458901,0.062471,0.553076,strong,72.604865,[]
13,mussels,538,428,168,0.479554,0.063197,0.577677,strong,72.569991,[]
14,pho,1225,708,91,0.431020,0.044898,0.582021,strong,72.390991,[]
15,fried chicken,933,781,247,0.476956,0.070740,0.548589,strong,71.987688,[]
16,beet salad,18,17,15,0.888889,0.000000,0.795110,weak,71.888689,[]
17,wings,2215,1493,588,0.475395,0.072235,0.540557,strong,71.819938,[]
18,mussels appetizer,6,6,6,0.833333,0.000000,0.904344,weak,71.756901,[]
19,tortilla soup,9,9,9,0.888889,0.000000,0.838604,weak,71.651669,[]
20,eggs benedict,271,243,114,0.494465,0.055351,0.616069,solid,71.627733,[]
21,mushroom ravioli,4,4,4,1.000000,0.000000,0.820816,weak,71.594319,[]
22,donut,2175,973,175,0.405057,0.056552,0.523457,strong,71.522495,[]
23,nachos,764,592,264,0.445026,0.069372,0.535312,strong,71.505366,[]
24,cheesecake,392,308,163,0.446429,0.053571,0.574820,solid,71.473008,[]
25,pizza,8751,4599,856,0.431836,0.066278,0.526868,strong,71.352939,[]
26,oysters were great,2,2,2,1.000000,0.000000,0.982694,weak,71.338934,[contains_suspicious_words]
27,pizza itself,4,4,4,1.000000,0.000000,0.804889,weak,71.315594,[]
28,oysters were fresh,2,2,2,1.000000,0.000000,0.978488,weak,71.265330,[contains_suspicious_words]
29,mac and cheese,707,584,217,0.466761,0.077793,0.528126,strong,71.150284,[]
30,caesar salad,41,38,36,0.658537,0.024390,0.789225,emerging,71.075924,[]
31,burger,8095,4478,863,0.440272,0.070167,0.522468,strong,71.069894,[]
32,tacos,4436,2707,533,0.419071,0.068305,0.529623,strong,71.067436,[]
33,egg sandwich,3,3,3,1.000000,0.000000,0.864806,weak,71.015111,[]
34,marathon burger,4,4,2,1.000000,0.000000,0.869230,weak,70.996740,[]
35,shrimp spring roll,19,19,15,0.736842,0.000000,0.791878,weak,70.943024,[]
36,shrimp,4421,3269,865,0.457363,0.077358,0.529735,strong,70.835333,[]
37,shrimp taco,178,159,69,0.533708,0.044944,0.620181,solid,70.426797,[]
38,quesadilla,434,356,190,0.426267,0.062212,0.498591,solid,70.349124,[]
39,omelet,779,648,243,0.432606,0.077022,0.517296,strong,70.325094,[]
40,crab,1535,1138,423,0.401303,0.070358,0.508569,strong,70.266000,[]
41,cheeseburger,320,279,177,0.368750,0.050000,0.532341,solid,70.260180,[]
42,calamari,600,484,240,0.460000,0.085000,0.523414,strong,70.238612,[]
43,ceaser salad,2,2,2,1.000000,0.000000,0.918149,weak,70.209402,[]
44,custard,276,198,57,0.463768,0.032609,0.611250,solid,70.178287,[]
45,shrimp curry,2,2,2,1.000000,0.000000,0.912731,weak,70.114571,[]
46,salad bar,3,3,3,1.000000,0.000000,0.811554,weak,70.083196,[]
47,toasted ravioli for an appetizer,2,2,2,1.000000,0.000000,0.909845,weak,70.064067,[]
48,sushi was fresh,2,2,2,1.000000,0.000000,0.903026,weak,69.944750,[contains_suspicious_words]
49,greek omelette,2,2,2,1.000000,0.000000,0.901900,weak,69.925042,[]

In [20]:
# ============================================================
# 20. QA del scoring preliminar
# ============================================================

scoring_summary = {
    "notebook": "10_dish_signal_aggregation",
    "version": "signal_scoring_v1",
    "source_mentions_path": str(MENTIONS_SENTIMENT_PATH),

    "input": aggregation_input_qa,

    "business_dish_scoring": {
        "total_pairs": int(len(business_scoring_df)),
        "ranking_ready_v1": int(business_scoring_df["is_ranking_ready_v1"].sum()),
        "candidate_tier_counts": {
            str(k): int(v)
            for k, v in business_scoring_df["preliminary_candidate_tier_v1"].value_counts().to_dict().items()
        },
        "evidence_tier_counts": {
            str(k): int(v)
            for k, v in business_scoring_df["business_dish_evidence_tier"].value_counts().to_dict().items()
        },
        "hard_noise_pairs": int(business_scoring_df["is_hard_noise_dish_name"].sum()),
        "possible_beverage_pairs": int(business_scoring_df["is_possible_beverage"].sum()),
        "score_summary": {
            "min": float(business_scoring_df["preliminary_ranking_score_v1"].min()),
            "mean": float(business_scoring_df["preliminary_ranking_score_v1"].mean()),
            "median": float(business_scoring_df["preliminary_ranking_score_v1"].median()),
            "max": float(business_scoring_df["preliminary_ranking_score_v1"].max()),
        },
        "top_ranking_ready": (
            business_scoring_df[
                business_scoring_df["is_ranking_ready_v1"]
            ]
            .head(50)
            [
                [
                    "business_id",
                    "business_name",
                    "city",
                    "state",
                    "canonical_dish_name_v2",
                    "mention_count",
                    "review_count",
                    "positive_ratio",
                    "negative_ratio",
                    "confidence_weighted_sentiment",
                    "bayesian_sentiment_score",
                    "total_signal_weight",
                    "business_dish_evidence_tier",
                    "preliminary_ranking_score_v1",
                    "preliminary_candidate_tier_v1",
                ]
            ]
            .to_dict(orient="records")
        ),
    },

    "global_scoring": {
        "total_dishes": int(len(global_scoring_df)),
        "evidence_tier_counts": {
            str(k): int(v)
            for k, v in global_scoring_df["global_evidence_tier"].value_counts().to_dict().items()
        },
        "hard_noise_dishes": int(global_scoring_df["is_hard_noise_dish_name"].sum()),
        "possible_beverage_dishes": int(global_scoring_df["is_possible_beverage"].sum()),
        "top_global_scored": (
            global_scoring_df
            .head(50)
            [
                [
                    "canonical_dish_name_v2",
                    "mention_count",
                    "review_count",
                    "business_count",
                    "positive_ratio",
                    "negative_ratio",
                    "confidence_weighted_sentiment",
                    "global_evidence_tier",
                    "global_ranking_signal_score_v1",
                ]
            ]
            .to_dict(orient="records")
        ),
    }
}

print(json.dumps(scoring_summary, indent=2, ensure_ascii=False)[:7000])

print("\nCandidate tiers:")
display(business_scoring_df["preliminary_candidate_tier_v1"].value_counts())

print("\nEvidence tiers negocio-plato:")
display(business_scoring_df["business_dish_evidence_tier"].value_counts())

print("\nTop ranking ready:")
display(
    business_scoring_df[
        business_scoring_df["is_ranking_ready_v1"]
    ]
    [
        [
            "business_name",
            "city",
            "state",
            "canonical_dish_name_v2",
            "mention_count",
            "review_count",
            "positive_ratio",
            "negative_ratio",
            "bayesian_sentiment_score",
            "total_signal_weight",
            "business_dish_evidence_tier",
            "preliminary_ranking_score_v1",
            "preliminary_candidate_tier_v1",
        ]
    ]
    .head(50)
)

print("\nPares rechazados por ruido:")
display(
    business_scoring_df[
        business_scoring_df["is_hard_noise_dish_name"]
    ]
    [
        [
            "business_name",
            "canonical_dish_name_v2",
            "mention_count",
            "review_count",
            "dish_name_quality_flags",
        ]
    ]
    .head(50)
)

{
  "notebook": "10_dish_signal_aggregation",
  "version": "signal_scoring_v1",
  "source_mentions_path": "/kaggle/input/datasets/ivanarteagacordero/hidden-gems-yelp-nlp/dish_mentions_with_sentiment_hybrid_v1.jsonl",
  "input": {
    "total_mentions": 94932,
    "unique_reviews": 42461,
    "unique_businesses": 4088,
    "unique_dishes": 9937,
    "sentiment_counts": {
      "neutral": 45366,
      "positive": 43142,
      "negative": 6424
    },
    "reliability_counts": {
      "low": 44426,
      "medium": 25495,
      "high": 25011
    },
    "signal_weight": {
      "min": 0.020311710990965366,
      "mean": 0.37781376200795724,
      "median": 0.3624973218077422,
      "max": 0.9497699350118637
    },
    "weighted_sentiment_value": {
      "min": -1.0,
      "mean": 0.3117034681140184,
      "median": 0.041755,
      "max": 1.0
    }
  },
  "business_dish_scoring": {
    "total_pairs": 31036,
    "ranking_ready_v1": 3841,
    "candidate_tier_counts": {
      "not_ready": 28147,
      "weak_candidate": 1223,
      "promising_candidate": 1021,
      "strong_candidate": 645
    },
    "evidence_tier_counts": {
      "weak": 27194,
      "emerging": 1440,
      "solid": 1406,
      "strong": 996
    },
    "hard_noise_pairs": 806,
    "possible_beverage_pairs": 359,
    "score_summary": {
      "min": 0.0,
      "mean": 42.625817046278364,
      "median": 44.23464218804102,
      "max": 88.80593009884784
    },
    "top_ranking_ready": [
      {
        "business_id": "tXf6TpqHOLiwyMNbYAOOCQ",
        "business_name": "The Little Lamb",
        "city": "Clearwater",
        "state": "FL",
        "canonical_dish_name_v2": "burger",
        "mention_count": 15,
        "review_count": 13,
        "positive_ratio": 0.8666666666666667,
        "negative_ratio": 0.0,
        "confidence_weighted_sentiment": 0.8021487459030389,
        "bayesian_sentiment_score": 0.6003488293439906,
        "total_signal_weight": 8.924911956070959,
        "business_dish_evidence_tier": "strong",
        "preliminary_ranking_score_v1": 88.80593009884784,
        "preliminary_candidate_tier_v1": "strong_candidate"
      },
      {
        "business_id": "zu4p6IZLSVn2Noto-vcwzw",
        "business_name": "East Beach Grill",
        "city": "Santa Barbara",
        "state": "CA",
        "canonical_dish_name_v2": "pancake",
        "mention_count": 24,
        "review_count": 14,
        "positive_ratio": 0.7916666666666666,
        "negative_ratio": 0.0,
        "confidence_weighted_sentiment": 0.8049994037082865,
        "bayesian_sentiment_score": 0.6652837762755077,
        "total_signal_weight": 14.285097275798917,
        "business_dish_evidence_tier": "strong",
        "preliminary_ranking_score_v1": 88.76815753001695,
        "preliminary_candidate_tier_v1": "strong_candidate"
      },
      {
        "business_id": "jMZ56S8Y1t7cA1Ob-d-qeA",
        "business_name": "Three Muses",
        "city": "New Orleans",
        "state": "LA",
        "canonical_dish_name_v2": "steak",
        "mention_count": 32,
        "review_count": 26,
        "positive_ratio": 0.78125,
        "negative_ratio": 0.0,
        "confidence_weighted_sentiment": 0.7765074117452293,
        "bayesian_sentiment_score": 0.663566436190169,
        "total_signal_weight": 17.626014816916584,
        "business_dish_evidence_tier": "strong",
        "preliminary_ranking_score_v1": 88.06187941523285,
        "preliminary_candidate_tier_v1": "strong_candidate"
      },
      {
        "business_id": "LnQRfj3pPz0369stRnwUWw",
        "business_name": "Sushi Ushi",
        "city": "Valrico",
        "state": "FL",
        "canonical_dish_name_v2": "sushi",
        "mention_count": 53,
        "review_count": 28,
        "positive_ratio": 0.7169811320754716,
        "negative_ratio": 0.0,
        "confidence_weighted_sentiment": 0.770510425523587,
        "bayesian_sentiment_score": 0.6945092501450588,
        "total_signal_weight": 27.414414843692185,
        "business_dish_evidence_tier": "strong",
        "preliminary_ranking_score_v1": 87.58024215812638,
        "preliminary_candidate_tier_v1": "strong_candidate"
      },
      {
        "business_id": "OAHRMd971k-yDQwRxzgc2g",
        "business_name": "4 Rivers Smokehouse",
        "city": "Tampa Bay",
        "state": "FL",
        "canonical_dish_name_v2": "brisket",
        "mention_count": 16,
        "review_count": 13,
        "positive_ratio": 0.75,
        "negative_ratio": 0.0,
        "confidence_weighted_sentiment": 0.7838100803228097,
        "bayesian_sentiment_score": 0.6064832121206958,
        "total_signal_weight": 10.260428410027027,
        "business_dish_evidence_tier": "strong",
        "preliminary_ranking_score_v1": 87.56021460605183,
        "preliminary_candidate_tier_v1": "strong_candidate"
      },
      {
        "business_id": "eFwFIh7olBwMHQ6ByoRH-Q",
        "business_name": "Goody's Soda Fountain & Candy Store",
        "city": "Boise",
        "state": "ID",
        "canonical_dish_name_v2": "ice cream",
        "mention_count": 30,
        "review_count": 20,
        "positive_ratio": 0.6666666666666666,
        "negative_ratio": 0.0,
        "confidence_weighted_sentiment": 0.778703366644064,
        "bayesian_sentiment_score": 0.6572134434315373,
        "total_signal_weight": 16.228838393827527,
        "business_dish_evidence_tier": "strong",
        "preliminary_ranking_score_v1": 87.4392952050028,
        "preliminary_candidate_tier_v1": "strong_candidate"
      },
      {
        "business_id": "rOsC1rDpIxvNoHxEvNFjeA",
        "business_name": "Backspace Bar & Kitchen",
        "city": "New Orleans",
        "state": "LA",
        "canonical_dish_name_v2": "burger",
        "mention_count": 18,
        "review_count": 14,
        "positive_ratio": 0.7777777777777778,
        "negative_ratio": 0.0,
        "confidence_weighted_sentiment": 0.8247461282952135,
        "bayesian_sentiment_score": 0.6400742821204315,
        "total_signal_weight": 10.398027020014226,
        "business_dish_evidence_tier": "strong",
        "preliminary_ranking_score_v1": 87.43681835160288,
        "preliminary_candidate_tier_v1": "strong_candidate"
      },
      {
        "business_id": "c-IgS6Pk6vMyax7Rbr38eA",
        "business_name": "Barbecue and Bourbon",
        "city": "Speedway",
        "state": "IN",
        "canonical_dish_name_v2": "pulled pork",
        "mention_count": 12,
        "review_count": 12,
        "positive_ratio": 0.8333333333333334,
        "negative_ratio": 0.0,
        "confidence_weighted_sentiment": 0.7544341222680865,
        "bayesian_sentiment_score": 0.5532825789526605,
        "total_signal_weight": 8.251727575637698,
        "business_dish_evidence_tier": "strong",
        "preliminary_ranking_score_v1": 87.34045632995185,
        "preliminary_candidate_tier_v1": "strong_candidate"
      },
      {
        "business_id": "mCo2uVTTGYrEhRrkQW-CMw",
        "business_name": "Empress Garden",
        "city": "Ph

Candidate tiers:

preliminary_candidate_tier_v1
not_ready              28147
weak_candidate          1223
promising_candidate     1021
strong_candidate         645
Name: count, dtype: int64

Evidence tiers negocio-plato:

business_dish_evidence_tier
weak        27194
emerging     1440
solid        1406
strong        996
Name: count, dtype: int64

Top ranking ready:

,business_name,city,state,canonical_dish_name_v2,mention_count,review_count,positive_ratio,negative_ratio,bayesian_sentiment_score,total_signal_weight,business_dish_evidence_tier,preliminary_ranking_score_v1,preliminary_candidate_tier_v1
0,The Little Lamb,Clearwater,FL,burger,15,13,0.866667,0.000000,0.600349,8.924912,strong,88.805930,strong_candidate
1,East Beach Grill,Santa Barbara,CA,pancake,24,14,0.791667,0.000000,0.665284,14.285097,strong,88.768158,strong_candidate
2,Three Muses,New Orleans,LA,steak,32,26,0.781250,0.000000,0.663566,17.626015,strong,88.061879,strong_candidate
3,Sushi Ushi,Valrico,FL,sushi,53,28,0.716981,0.000000,0.694509,27.414415,strong,87.580242,strong_candidate
4,4 Rivers Smokehouse,Tampa Bay,FL,brisket,16,13,0.750000,0.000000,0.606483,10.260428,strong,87.560215,strong_candidate
5,Goody's Soda Fountain & Candy Store,Boise,ID,ice cream,30,20,0.666667,0.000000,0.657213,16.228838,strong,87.439295,strong_candidate
6,Backspace Bar & Kitchen,New Orleans,LA,burger,18,14,0.777778,0.000000,0.640074,10.398027,strong,87.436818,strong_candidate
7,Barbecue and Bourbon,Speedway,IN,pulled pork,12,12,0.833333,0.000000,0.553283,8.251728,strong,87.340456,strong_candidate
8,Empress Garden,Philadelphia,PA,pancake,15,14,0.866667,0.000000,0.602247,8.365439,strong,87.238194,strong_candidate
9,Plaza Deli,Santa Barbara,CA,sandwich,19,16,0.789474,0.000000,0.607592,10.464968,strong,87.223795,strong_candidate
10,Zeppoli,Collingswood,NJ,gnocchi,27,19,0.814815,0.000000,0.636316,14.271146,strong,87.113660,strong_candidate
11,Blues City Deli,Saint Louis,MO,sandwich,108,87,0.731481,0.000000,0.701165,53.353000,strong,87.021653,strong_candidate
12,HipCityVeg - University City,Philadelphia,PA,fries,37,31,0.702703,0.000000,0.659745,20.064392,strong,86.999445,strong_candidate
13,Sabrina's West Street Kitchen,Reno,NV,tacos,14,12,0.857143,0.000000,0.594387,7.330511,strong,86.968109,strong_candidate
14,Izumi,Philadelphia,PA,sashimi,14,11,0.785714,0.000000,0.595016,8.632080,strong,86.917085,strong_candidate
15,District Donuts Sliders Brew,New Orleans,LA,waffle fries,27,26,0.814815,0.000000,0.614678,14.159490,strong,86.745823,strong_candidate
16,Tako Japanese Restaurant,Bensalem,PA,sushi,31,22,0.645161,0.000000,0.665698,15.987598,strong,86.736220,strong_candidate
17,Sam's Brick Oven Pizza,Ardmore,PA,pizza,17,13,0.823529,0.000000,0.588299,9.428420,strong,86.706959,strong_candidate
18,Dawn Patrol,Santa Barbara,CA,pancake,15,10,0.800000,0.000000,0.609816,8.880957,strong,86.661208,strong_candidate
19,Persis Biryani Indian Grill,Mount Juliet,TN,naan,12,11,0.750000,0.000000,0.588099,7.661169,strong,86.620622,strong_candidate
20,Chatham Tap Mass. Ave.,Indianapolis,IN,wings,29,23,0.758621,0.000000,0.640702,13.721384,strong,86.478133,strong_candidate
21,The Fat Ham,Philadelphia,PA,shrimp,22,15,0.681818,0.000000,0.628677,11.319526,strong,86.460235,strong_candidate
22,Saki Endless Sushi & Hibachi Eatery,Clearwater,FL,shrimp,14,11,0.714286,0.000000,0.604191,8.152526,strong,86.430211,strong_candidate
23,Two Chicks Cafe,New Orleans,LA,french toast,18,16,0.722222,0.000000,0.604096,9.535039,strong,86.325185,strong_candidate
24,Jesse's Steak and Seafood,Brandon,FL,steak,14,12,0.857143,0.000000,0.555453,7.650749,strong,86.306235,strong_candidate
25,Uncle Maddios Pizza,Lutz,FL,pizza,36,17,0.638889,0.000000,0.667559,17.556962,strong,86.209606,strong_candidate
26,Two Chicks Cafe,New Orleans,LA,shrimp,31,24,0.645161,0.000000,0.663626,14.113452,strong,86.184871,strong_candidate
27,Taqueria Cuernavaca,Santa Barbara,CA,tacos,73,45,0.630137,0.000000,0.697991,31.871341,strong,86.167225,strong_candidate
28,Surrey's Café & Juice Bar,New Orleans,LA,shrimp,159,120,0.628931,0.006289,0.721687,75.452922,strong,86.158288,strong_candidate
29,Kei Sushi,Reno,NV,sushi,64,31,0.640625,0.000000,0.681367,28.059837,strong,86.098868,strong_candidate
30,Pho 36,Avon,IN,spring rolls,20,15,0.650000,0.000000,0.616521,10.275607,strong,85.930859,strong_candidate
31,Prep & Pastry,Tucson,AZ,omelet,24,20,0.666667,0.000000,0.621384,12.081544,strong,85.896867,strong_candidate
32,Red Pony,Franklin,TN,shrimp,17,15,0.764706,0.000000,0.568926,9.550073,strong,85.848216,strong_candidate
33,M.L.Rose Craft Beer & Burgers - Melrose,Nashville,TN,waffle fries,21,14,0.761905,0.000000,0.580782,10.216841,strong,85.778054,strong_candidate
34,Khyber Pass Pub,Philadelphia,PA,nachos,21,17,0.666667,0.000000,0.606656,10.383343,strong,85.741728,strong_candidate
35,Mazzaro's Italian Market,Saint Petersburg,FL,sandwich,41,33,0.804878,0.024390,0.647692,23.907178,strong,85.634912,strong_candidate
36,El Limon - Malvern,Malvern,PA,tacos,39,28,0.589744,0.000000,0.657248,17.870512,strong,85.557827,strong_candidate
37,Khyber Pass Pub,Philadelphia,PA,burger,17,11,0.705882,0.000000,0.586884,9.623868,strong,85.532955,strong_candidate
38,Wildflower Cafe,Clearwater,FL,french toast,15,11,0.733333,0.000000,0.573098,7.698582,strong,85.514285,strong_candidate
39,Zeko's Mediterranean Grill,Tampa,FL,hummus,13,10,0.769231,0.000000,0.586266,7.928629,strong,85.447030,strong_candidate
40,Paola's Pizzeria,Wayne,PA,pizza,23,14,0.652174,0.000000,0.607586,11.176801,strong,85.328957,strong_candidate
41,The Fountain On Locust,Saint Louis,MO,sandwich,20,18,0.700000,0.000000,0.601017,9.356632,strong,85.317286,strong_candidate
42,Mr. B's Bistro,New Orleans,LA,spring rolls,15,14,0.733333,0.000000,0.556459,7.971485,strong,85.259805,strong_candidate
43,Olio,Saint Louis,MO,hummus,15,13,0.666667,0.000000,0.589684,7.724470,strong,85.224629,strong_candidate
44,Gateway To India,St. Petersburg,FL,naan,22,17,0.590909,0.000000,0.603003,11.029409,strong,85.205589,strong_candidate
45,Ron's Original Bar & Grille,Exton,PA,pizza,15,13,0.666667,0.000000,0.587033,7.037507,strong,85.179556,strong_candidate
46,R2L,Philadelphia,PA,tuna,13,12,0.692308,0.000000,0.578361,7.120344,strong,85.177275,strong_candidate
47,Honey's Sit-N-Eat,Philadelphia,PA,french toast,26,21,0.576923,0.000000,0.622288,12.102624,strong,85.155813,strong_candidate
48,Puckett's Grocery & Restaurant,Franklin,TN,brisket,14,11,0.785714,0.000000,0.551822,7.818081,strong,85.039930,strong_candidate
49,Barbecue and Bourbon,Speedway,IN,brisket,12,10,0.750000,0.000000,0.568648,7.743595,strong,85.012671,strong_candidate

Pares rechazados por ruido:

,business_name,canonical_dish_name_v2,mention_count,review_count,dish_name_quality_flags
30230,Burger Republic,96 burger,4,4,[contains_digit]
30231,500 Degrees,500 burger,5,4,[contains_digit]
30232,Mr. B's Bistro,soup 1-1-1,4,4,[contains_digit]
30233,Livery - Indianapolis,tres leche cake with housemade coffee ice cream,2,2,[too_many_words]
30234,East Coast Pizza,salad : the size was,2,2,"[bad_end_word, contains_suspicious_words, suspicious_punctuation]"
30235,East Coast Pizza,up,2,2,"[exact_noise_name, too_short_name]"
30236,Burger Republic,4 cheese garlic burger,2,2,[contains_digit]
30237,Seasons Cafe & Bakery,mi,2,2,[too_short_name]
30238,Luke,french 75,2,2,[contains_digit]
30239,Mr. B's Bistro,1-1-1,2,2,[contains_digit]
30240,Cheeburger Cheeburger,3 / 4 pound burger,2,1,[contains_digit]
30241,Red Garter Saloon,burger was,1,1,"[bad_end_word, contains_suspicious_words]"
30242,Hendricks BBQ,it,1,1,[too_short_name]
30243,O'Fallon Brewery,was good,1,1,"[bad_start_word, contains_suspicious_words]"
30244,Pei Wei Asian Diner,sauce,1,1,[exact_noise_name]
30245,Red Habanero,was so good,1,1,"[bad_start_word, contains_suspicious_words]"
30246,Hellas Restaurant,cheesecake was,1,1,"[bad_end_word, contains_suspicious_words]"
30247,Los Rancheros,verde - pork was,1,1,"[bad_end_word, contains_suspicious_words]"
30248,Prep & Pastry,coffee was,1,1,"[bad_end_word, contains_suspicious_words]"
30249,Asahi Japanese Sushi,spicy tuna was,1,1,"[bad_end_word, contains_suspicious_words]"
30250,Taziki's Mediterranean Cafe - West End,side of hummus for an extra $ 2 maybe,1,1,"[contains_digit, too_many_words]"
30251,The Original Habit Burger Grill,food was real good burger was good shake,1,1,"[contains_suspicious_words, too_many_words]"
30252,Edgehill Cafe,granola the coffee was,1,1,"[bad_end_word, contains_suspicious_words]"
30253,Deccan Spice,65 was to die,1,1,"[contains_digit, contains_suspicious_words]"
30254,IHOP,belgium waffle it was,1,1,"[bad_end_word, contains_suspicious_words]"
30255,Siam Cafe,panang curry i had was,1,1,"[bad_end_word, contains_suspicious_words]"
30256,Marrakesh Express,was deliciou,1,1,"[bad_start_word, contains_suspicious_words]"
30257,California Pizza Kitchen,it,1,1,[too_short_name]
30258,Beef 'O' Brady's,new bbq bacon burger was,1,1,"[bad_end_word, contains_suspicious_words]"
30259,Capofitto,was very good,1,1,"[bad_start_word, contains_suspicious_words]"
30260,Knockouts Bar and Hookah Lounge,chicken parm sanwich wich was,1,1,"[bad_end_word, contains_suspicious_words]"
30261,Pizzeria Vetri,pizza ( i got the crudo ) was good,1,1,"[contains_suspicious_words, too_many_words]"
30262,Pieology Pizzeria,salad was very good pizza was,1,1,"[bad_end_word, contains_suspicious_words]"
30263,Brixx Wood Fired Pizza,4x4 pizza,1,1,[contains_digit]
30264,Burger Up,woodstock burger which he thought was,1,1,"[bad_end_word, contains_suspicious_words]"
30265,Zorba's Taverna,wrap it was in was,1,1,"[bad_end_word, contains_suspicious_words]"
30266,Jet's Pizza,ordered,1,1,"[contains_suspicious_words, exact_noise_name]"
30267,Salty's Island Bar & Grille,shrimp 4,1,1,[contains_digit]
30268,Luke,crabmeat omelet was,1,1,"[bad_end_word, contains_suspicious_words]"
30269,HipCityVeg,chicken sandwich ( which was,1,1,"[bad_end_word, contains_suspicious_words]"
30270,Henry's Coffee Bistro,was fresh,1,1,"[bad_start_word, contains_suspicious_words]"
30271,Barra Rossa Ristorante & Wine Bar - Downington,chicken parm was,1,1,"[bad_end_word, contains_suspicious_words]"
30272,YO! Sushi,eggplant dish from the,1,1,[bad_end_word]
30273,Tired Hands Fermentaria,ribs were,1,1,"[bad_end_word, contains_suspicious_words]"
30274,Italia Pizza & Pasta,was flavorful,1,1,"[bad_start_word, contains_suspicious_words]"
30275,Richard's,cheese ravioli with pesto cream sauce as my main,1,1,[too_many_words]
30276,Burger Republic,four cheese garlic bacon burger with tater tot,1,1,[too_many_words]
30277,On The Border Mexican Grill & Cantina,one of the burrito bowls with portobello mushroom,1,1,[too_many_words]
30278,China Bowl & State Street Cafe,we,1,1,[too_short_name]
30279,Raijin Ramen,were cooked well,1,1,"[bad_start_word, contains_suspicious_words]"

In [21]:
# ============================================================
# 21. Muestras de revisión para ranking
# ============================================================

ranking_ready_sample_df = (
    business_scoring_df[
        business_scoring_df["is_ranking_ready_v1"]
    ]
    .head(500)
    .copy()
)

strong_candidates_sample_df = (
    business_scoring_df[
        business_scoring_df["preliminary_candidate_tier_v1"] == "strong_candidate"
    ]
    .head(500)
    .copy()
)

promising_candidates_sample_df = (
    business_scoring_df[
        business_scoring_df["preliminary_candidate_tier_v1"] == "promising_candidate"
    ]
    .head(500)
    .copy()
)

emerging_candidates_sample_df = (
    business_scoring_df[
        (business_scoring_df["business_dish_evidence_tier"] == "emerging")
        & (business_scoring_df["is_ranking_ready_v1"])
    ]
    .head(500)
    .copy()
)

noise_rejected_sample_df = (
    business_scoring_df[
        business_scoring_df["is_hard_noise_dish_name"]
    ]
    .head(500)
    .copy()
)

top_global_scored_sample_df = global_scoring_df.head(500).copy()

print("ranking_ready_sample_df:", len(ranking_ready_sample_df))
print("strong_candidates_sample_df:", len(strong_candidates_sample_df))
print("promising_candidates_sample_df:", len(promising_candidates_sample_df))
print("emerging_candidates_sample_df:", len(emerging_candidates_sample_df))
print("noise_rejected_sample_df:", len(noise_rejected_sample_df))
print("top_global_scored_sample_df:", len(top_global_scored_sample_df))

ranking_ready_sample_df: 500
strong_candidates_sample_df: 500
promising_candidates_sample_df: 500
emerging_candidates_sample_df: 500
noise_rejected_sample_df: 500
top_global_scored_sample_df: 500

In [22]:
# ============================================================
# 22. Guardar outputs de scoring
# ============================================================

business_ranking_candidates_path = SIGNALS_DIR / "dish_business_ranking_candidates_v1.csv"
global_ranking_signals_path = SIGNALS_DIR / "dish_global_ranking_signals_v1.csv"
scoring_summary_path = ARTIFACTS_DIR / "dish_signal_scoring_summary_v1.json"

ranking_ready_sample_path = SAMPLES_DIR / "dish_business_ranking_ready_sample_v1.csv"
strong_candidates_sample_path = SAMPLES_DIR / "dish_business_strong_candidates_sample_v1.csv"
promising_candidates_sample_path = SAMPLES_DIR / "dish_business_promising_candidates_sample_v1.csv"
emerging_candidates_sample_path = SAMPLES_DIR / "dish_business_emerging_candidates_sample_v1.csv"
noise_rejected_sample_path = SAMPLES_DIR / "dish_business_noise_rejected_sample_v1.csv"
top_global_scored_sample_path = SAMPLES_DIR / "dish_global_scored_sample_v1.csv"

business_scoring_df.to_csv(business_ranking_candidates_path, index=False)
global_scoring_df.to_csv(global_ranking_signals_path, index=False)

ranking_ready_sample_df.to_csv(ranking_ready_sample_path, index=False)
strong_candidates_sample_df.to_csv(strong_candidates_sample_path, index=False)
promising_candidates_sample_df.to_csv(promising_candidates_sample_path, index=False)
emerging_candidates_sample_df.to_csv(emerging_candidates_sample_path, index=False)
noise_rejected_sample_df.to_csv(noise_rejected_sample_path, index=False)
top_global_scored_sample_df.to_csv(top_global_scored_sample_path, index=False)

scoring_summary["outputs"] = {
    "business_ranking_candidates": str(business_ranking_candidates_path),
    "global_ranking_signals": str(global_ranking_signals_path),
    "scoring_summary": str(scoring_summary_path),
    "ranking_ready_sample": str(ranking_ready_sample_path),
    "strong_candidates_sample": str(strong_candidates_sample_path),
    "promising_candidates_sample": str(promising_candidates_sample_path),
    "emerging_candidates_sample": str(emerging_candidates_sample_path),
    "noise_rejected_sample": str(noise_rejected_sample_path),
    "top_global_scored_sample": str(top_global_scored_sample_path),
}

with scoring_summary_path.open("w", encoding="utf-8") as f:
    json.dump(scoring_summary, f, indent=2, ensure_ascii=False)

print("Outputs de scoring guardados:")
print("business_ranking_candidates_path:", business_ranking_candidates_path)
print("global_ranking_signals_path:", global_ranking_signals_path)
print("scoring_summary_path:", scoring_summary_path)

Outputs de scoring guardados:
business_ranking_candidates_path: /kaggle/working/hidden_gems_ai/outputs/dish_signal_aggregation/signals/dish_business_ranking_candidates_v1.csv
global_ranking_signals_path: /kaggle/working/hidden_gems_ai/outputs/dish_signal_aggregation/signals/dish_global_ranking_signals_v1.csv
scoring_summary_path: /kaggle/working/hidden_gems_ai/outputs/dish_signal_aggregation/artifacts/dish_signal_scoring_summary_v1.json

In [23]:
# ============================================================
# 23. Comprimir outputs del módulo 10
# ============================================================

import shutil

zip_base = Path("/kaggle/working") / "dish_signal_aggregation_outputs_v1"

if zip_base.with_suffix(".zip").exists():
    zip_base.with_suffix(".zip").unlink()

shutil.make_archive(
    base_name=str(zip_base),
    format="zip",
    root_dir=str(OUTPUT_DIR)
)

print("ZIP generado:")
print(str(zip_base) + ".zip")

ZIP generado:
/kaggle/working/dish_signal_aggregation_outputs_v1.zip

## Cierre del Notebook 10

En este notebook se ha construido la capa de agregación de señales gastronómicas.

El flujo realizado ha sido:

1. Carga de menciones con sentimiento.
2. Creación de pesos de fiabilidad.
3. Agregación global por plato.
4. Agregación por negocio + plato.
5. Control de calidad de nombres de platos.
6. Scoring conservador para ranking.
7. Generación de candidatos preliminares.

Archivos principales generados:

- `dish_global_signals_v1.csv`
- `dish_business_signals_v1.csv`
- `dish_business_ranking_candidates_v1.csv`
- `dish_global_ranking_signals_v1.csv`
- `dish_signal_aggregation_summary_v1.json`
- `dish_signal_scoring_summary_v1.json`

El archivo principal para el siguiente notebook será:

`dish_business_ranking_candidates_v1.csv`

Este archivo servirá como entrada para:

`11_hidden_gems_ranking_v1.ipynb`