# 13. Sevilla Dish Candidate Detection

Este notebook construye la primera detección seria de **candidatos de platos** sobre las reviews reales de Google Places Sevilla exportadas desde PostgreSQL.

El objetivo no es todavía generar el ranking final, sino crear una capa intermedia fiable:

```text
reviews reales de Sevilla
→ menciones candidatas de platos
→ clasificación inicial
→ artefactos revisables
→ base para normalización, sentimiento y ranking sevilla_pilot
```

La estrategia inicial es híbrida y explicable:

- lexicón gastronómico español/andaluz;
- patrones para platos compuestos;
- clasificación de términos genéricos, bebidas e ingredientes;
- contexto local de la mención;
- puntuación de confianza;
- exportación para revisión manual.

No se usa GPU ni modelos pesados en esta fase.

In [2]:
# ============================================================
# 01. Imports y configuración general
# ============================================================

import json
import re
import hashlib
import unicodedata
from pathlib import Path
from collections import Counter, defaultdict
from datetime import datetime, timezone

import pandas as pd

try:
    from IPython.display import display
except Exception:
    display = print


pd.set_option("display.max_columns", 120)
pd.set_option("display.max_colwidth", 220)
pd.set_option("display.width", 160)

# Resolver raíz del proyecto de forma flexible buscando una carpeta data/ hacia arriba.
def find_project_dir() -> Path:
    cwd = Path.cwd().resolve()
    for candidate in [cwd, *cwd.parents]:
        if (candidate / "data").exists():
            return candidate
    return cwd

PROJECT_DIR = find_project_dir()

INPUT_PATH = PROJECT_DIR / "data" / "artifacts" / "ai" / "sevilla" / "reviews_for_ai_google_places.jsonl"
OUTPUT_DIR = PROJECT_DIR / "data" / "artifacts" / "ai" / "sevilla" / "dish_detection"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

RUN_NAME = "sevilla_dish_candidate_detection_v1"
GENERATED_AT = datetime.now(timezone.utc).isoformat()

print("PROJECT_DIR:", PROJECT_DIR)
print("INPUT_PATH:", INPUT_PATH)
print("OUTPUT_DIR:", OUTPUT_DIR)

PROJECT_DIR: C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline
INPUT_PATH: C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\reviews_for_ai_google_places.jsonl
OUTPUT_DIR: C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection

In [3]:
# ============================================================
# 02. Carga del JSONL exportado para IA
# ============================================================

def read_jsonl(path: Path):
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"JSON inválido en línea {line_number}: {exc}") from exc
    return rows

if not INPUT_PATH.exists():
    raise FileNotFoundError(f"No existe el archivo de entrada: {INPUT_PATH}")

reviews = read_jsonl(INPUT_PATH)
df = pd.DataFrame(reviews)

print("Reviews cargadas:", len(df))
print("Columnas:", list(df.columns))
display(df.head(3))

Reviews cargadas: 4110
Columnas: ['review_id', 'place_id', 'place_source_ref_id', 'source_system_code', 'source_review_id', 'source_place_record_id', 'place_source_record_id', 'place_name', 'place_canonical_name', 'address_text', 'city', 'neighborhood_id', 'neighborhood_name', 'district_id', 'district_name', 'rating_value', 'review_language', 'review_created_at', 'review_updated_at', 'text', 'text_normalized', 'is_operational_review', 'is_training_eligible', 'source_review_url', 'place_latitude', 'place_longitude', 'text_length_chars']

,review_id,place_id,place_source_ref_id,source_system_code,source_review_id,source_place_record_id,place_source_record_id,place_name,place_canonical_name,address_text,city,neighborhood_id,neighborhood_name,district_id,district_name,rating_value,review_language,review_created_at,review_updated_at,text,text_normalized,is_operational_review,is_training_eligible,source_review_url,place_latitude,place_longitude,text_length_chars
0,0d0946cb-a72c-4197-9d43-b5f3dbfcc620,8cb19db3-e9a8-4a42-be63-73e86e22a3d9,2acb2538-7f10-4760-a646-85c41436f9e8,google_places,a299c238d5349ed3eb5fc64b5db7e6def4db213c4ed81730074b12931536495c,ChIJ50jgAn5tEg0RBySkaJ7I8eE,ChIJ50jgAn5tEg0RBySkaJ7I8eE,Tropitali,Tropitali,"C. San Julián, 13, Casco Antiguo, 41003 Sevilla",Sevilla,e554ef0e-d9f1-4d89-8777-f92cee028f7f,SAN JULIAN,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,5.0,es,2026-05-10T19:07:36.701337+02:00,2026-05-10T19:07:36.701337+02:00,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables. Gracias por traer un pedacito de Brasil ❤️🇧🇷 volveré y seguro indicaré a mis ami...","Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables. Gracias por traer un pedacito de Brasil ❤️🇧🇷 volveré y seguro indicaré a mis ami...",True,True,https://www.google.com/maps/reviews/data=!4m6!14m5!1m4!2m3!1sCi9DQUlRQUNvZENodHljRjlvT21oaWFuRkNhV3RFYUc5TVFVNDJWVGRQZGxkbk5uYxAB!2m1!1s0xd126d7e02e048e7:0xe1f1c89e68a42407,37.399171,-5.985623,221
1,b680ad6e-8999-48a0-a754-84ea920429ab,a6ba370c-eb3d-4456-94cf-58617d1a3b0a,9f4c2eb7-2ff7-44ce-8db2-1be259e6985d,google_places,4897b8c24f949dda32b4e6c5cad74f4a91228c64182c5ce9408158505e192ce0,ChIJuQj13EFvEg0RPkUdEUzL0BA,ChIJuQj13EFvEg0RPkUdEUzL0BA,Cariña VZ,Cariña VZ,"C. Pdte. Cárdenas, 10, 41013 Sevilla",Sevilla,65af0982-2885-49df-9f09-8b784c2f3d7b,GIRALDA SUR,22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,5.0,es,2026-05-10T18:17:25.948671+02:00,2026-05-10T18:17:25.948671+02:00,"Buena comida y con un excelente servicio de Leo que nos atendió y nos explicó todo muy bien, sin duda iremos más de una vez.","Buena comida y con un excelente servicio de Leo que nos atendió y nos explicó todo muy bien, sin duda iremos más de una vez.",True,True,https://www.google.com/maps/reviews/data=!4m6!14m5!1m4!2m3!1sCi9DQUlRQUNvZENodHljRjlvT2sxVGNtOXFka2xKV0daTVNrZFJWRGhZUm1OMVpHYxAB!2m1!1s0xd126f41dcf508b9:0x10d0cb4c111d453e,37.373058,-5.977433,124
2,b2ac02e7-4348-481d-ad2e-cb37ab9c2685,7d39aad6-1d3f-4fc8-8d4b-22896354507e,4fa65ed3-e51a-4a96-b82c-cbe002c03141,google_places,c19ee9e9030a22bbcd80d00ef0680365a36e284ccb72955b931c805b5c37aade,ChIJmU6FwYdvEg0RYLF2daPZQkc,ChIJmU6FwYdvEg0RYLF2daPZQkc,TOTORA,TOTORA,"Av. los Gavilanes, 89, 41006 Sevilla",Sevilla,76a474aa-a390-48b4-a7ad-d68f6d747832,LA PLATA,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,2.0,es,2026-05-10T18:03:34.257906+02:00,2026-05-10T18:03:34.257906+02:00,"Demasiada tiempo de espera para recibir mi pedido\nEl ceviche muy ácido , lo rescatable los anticuchos10/10","Demasiada tiempo de espera para recibir mi pedido El ceviche muy ácido , lo rescatable los anticuchos10/10",True,True,https://www.google.com/maps/reviews/data=!4m6!14m5!1m4!2m3!1sCi9DQUlRQUNvZENodHljRjlvT25Oc2MzRTNhamx2Y0hoa2JqRk5ZekJGUm01dFdYYxAB!2m1!1s0xd126f87c1854e99:0x4742d9a37576b160,37.371563,-5.951597,106

In [4]:
# ============================================================
# 03. Preparación de campos auxiliares
# ============================================================

REQUIRED_COLUMNS = [
    "review_id",
    "place_id",
    "place_source_ref_id",
    "source_system_code",
    "source_review_id",
    "source_place_record_id",
    "place_name",
    "district_name",
    "neighborhood_name",
    "rating_value",
    "review_language",
    "text",
]

missing_columns = [col for col in REQUIRED_COLUMNS if col not in df.columns]
if missing_columns:
    raise ValueError(f"Faltan columnas obligatorias: {missing_columns}")

def rating_to_sentiment(rating):
    try:
        rating = float(rating)
    except Exception:
        return "unknown"
    if rating >= 4:
        return "positive"
    if rating <= 2:
        return "negative"
    return "neutral"

# Texto principal.
df["text"] = df["text"].fillna("").astype(str)
df["text_clean"] = df["text"].str.replace(r"\s+", " ", regex=True).str.strip()
df["text_length_chars"] = df["text_clean"].str.len()
df["text_length_words"] = df["text_clean"].str.split().apply(len)
df["review_sentiment_from_rating"] = df["rating_value"].apply(rating_to_sentiment)

# Mantener preferentemente español para el prototipo, pero sin borrar los demás de entrada.
display(df[["review_language", "rating_value", "review_sentiment_from_rating", "text_length_chars"]].describe(include="all"))
print("Idiomas:")
print(df["review_language"].value_counts(dropna=False))
print("Ratings:")
print(df["rating_value"].value_counts(dropna=False).sort_index())

       review_language  rating_value review_sentiment_from_rating  text_length_chars
count             4110   4110.000000                         4110        4110.000000
unique               3           NaN                            3                NaN
top                 es           NaN                     positive                NaN
freq              4108           NaN                         3424                NaN
mean               NaN      4.325061                          NaN         353.586861
std                NaN      1.234859                          NaN         282.810384
min                NaN      1.000000                          NaN          24.000000
25%                NaN      4.000000                          NaN         177.000000
50%                NaN      5.000000                          NaN         282.000000
75%                NaN      5.000000                          NaN         433.000000
max                NaN      5.000000                          NaN        3093.000000

Idiomas:
review_language
es    4108
fr       1
pt       1
Name: count, dtype: int64
Ratings:
rating_value
1.0     348
2.0     128
3.0     210
4.0     578
5.0    2846
Name: count, dtype: int64

## 04. Normalización de texto

Para detectar candidatos de forma robusta, usamos una normalización para matching que:

- convierte a minúsculas;
- elimina tildes;
- mantiene la longitud aproximada del texto para poder recuperar spans del texto original.

Esto permite detectar `jamón` como `jamon`, `atún` como `atun`, etc.

In [5]:
# ============================================================
# 04. Normalización para matching y utilidades de contexto
# ============================================================

def normalize_for_match_keep_len(text: str) -> str:
    """Normaliza a minúsculas y elimina tildes intentando mantener 1 char por char original."""
    out = []
    for ch in str(text):
        decomposed = unicodedata.normalize("NFD", ch)
        base = "".join(c for c in decomposed if unicodedata.category(c) != "Mn")
        if not base:
            base = ch
        # Mantener un solo carácter para preservar offsets en la mayoría de casos.
        out.append(base[0].lower())
    return "".join(out)

def normalize_text_value(text: str) -> str:
    text = normalize_for_match_keep_len(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def compact_spaces(text: str) -> str:
    return re.sub(r"\s+", " ", str(text)).strip()

def get_sentence_context(text: str, start: int, end: int) -> str:
    """Devuelve la oración aproximada que contiene el span."""
    text = str(text)
    for match in re.finditer(r"[^.!?\n]+[.!?]*", text):
        if match.start() <= start < match.end():
            return compact_spaces(match.group(0))
    # Fallback: ventana local.
    left = max(0, start - 140)
    right = min(len(text), end + 140)
    return compact_spaces(text[left:right])

def get_window_context(text: str, start: int, end: int, window: int = 120) -> str:
    left = max(0, start - window)
    right = min(len(text), end + window)
    return compact_spaces(text[left:right])

def stable_id(*parts) -> str:
    raw = "||".join("" if p is None else str(p) for p in parts)
    return hashlib.sha1(raw.encode("utf-8")).hexdigest()

# Prueba rápida.
example = "Pedimos croquetas de jamón, solomillo al whisky y una tarta de queso."
print(normalize_for_match_keep_len(example))
print(get_sentence_context(example, 8, 27))

pedimos croquetas de jamon, solomillo al whisky y una tarta de queso.
Pedimos croquetas de jamón, solomillo al whisky y una tarta de queso.

## 05. Lexicón gastronómico inicial

Se separan cuatro grupos:

1. `dish_core`: platos o formatos que pueden funcionar como candidatos de plato.
2. `generic_food_term`: términos demasiado genéricos para ranking directo.
3. `beverage`: bebidas, excluidas del ranking de platos.
4. `ingredient_or_side`: ingredientes o acompañamientos que solo serán útiles si aparecen en compuestos.

Esta separación evita que el ranking acabe recomendando `cerveza`, `pan`, `tapas` o `comida` como si fueran platos concretos.

In [6]:
# ============================================================
# 05. Lexicón gastronómico inicial ES/Sevilla
# ============================================================

alias_records = []

def add_alias(alias, canonical=None, group="dish_core", priority=1.0):
    alias = compact_spaces(alias)
    canonical = compact_spaces(canonical or alias)
    alias_records.append({
        "alias": alias,
        "alias_norm": normalize_text_value(alias),
        "canonical": normalize_text_value(canonical),
        "group": group,
        "priority": priority,
    })

# Platos y formatos frecuentes en Sevilla / España.
DISH_ALIASES = {
    # Tapas/platos concretos tradicionales
    "croqueta": ["croqueta", "croquetas", "croquetas caseras", "croquetas de jamón", "croquetas de puchero", "croquetas de setas", "croquetas de boletus"],
    "ensaladilla": ["ensaladilla", "ensaladilla rusa"],
    "salmorejo": ["salmorejo"],
    "gazpacho": ["gazpacho"],
    "tortilla de patatas": ["tortilla", "tortilla de patatas", "tortilla española"],
    "patatas bravas": ["bravas", "patatas bravas", "papas bravas"],
    "patatas alioli": ["patatas alioli", "papas alioli", "patatas con alioli"],
    "huevos rotos": ["huevos rotos", "huevos estrellados"],
    "carrillada": ["carrillada", "carrillada ibérica", "carrillera", "carrilleras"],
    "solomillo al whisky": ["solomillo", "solomillo al whisky", "solomillo whisky"],
    "presa ibérica": ["presa", "presa ibérica", "presa iberica"],
    "secreto ibérico": ["secreto", "secreto ibérico", "secreto iberico"],
    "lagarto ibérico": ["lagarto", "lagarto ibérico", "lagarto iberico"],
    "lomo": ["lomo", "lomo al whisky"],
    "rabo de toro": ["rabo de toro", "cola de toro"],
    "pringá": ["pringá", "pringa", "montadito de pringá", "montadito de pringa"],
    "flamenquín": ["flamenquín", "flamenquin"],
    "albóndigas": ["albóndigas", "albondigas"],
    "chicharrones": ["chicharrones"],
    "morcilla": ["morcilla"],
    # Pescado/marisco
    "bacalao": ["bacalao", "bacalao dorado"],
    "atún": ["atún", "atun", "atún rojo", "atun rojo", "tataki de atún", "tataki de atun"],
    "gambas": ["gambas", "gambas al ajillo"],
    "langostinos": ["langostinos"],
    "pulpo": ["pulpo", "pulpo a la brasa", "pulpo a la gallega"],
    "calamares": ["calamares", "calamar"],
    "chocos": ["chocos", "choco"],
    "puntillitas": ["puntillitas"],
    "boquerones": ["boquerones"],
    "cazón en adobo": ["cazón en adobo", "cazon en adobo", "adobo"],
    "pescado frito": ["pescado frito", "fritura de pescado", "frito variado"],
    "mejillones": ["mejillones"],
    "almejas": ["almejas"],
    "navajas": ["navajas"],
    # Arroces/pastas/internacional
    "paella": ["paella"],
    "arroz": ["arroz", "arroz negro", "arroz con pollo", "arroz con leche"],
    "risotto": ["risotto"],
    "pasta": ["pasta", "ravioli", "gnocchi", "lasaña", "lasagna"],
    "pizza": ["pizza", "pizzas"],
    "hamburguesa": ["hamburguesa", "hamburguesas", "burger", "burguer"],
    "sushi": ["sushi"],
    "ramen": ["ramen"],
    "taco": ["taco", "tacos"],
    "burrito": ["burrito", "burritos"],
    "kebab": ["kebab"],
    "arepa": ["arepa", "arepas"],
    "coxinha": ["coxinha", "coxinhas"],
    "açai": ["açai", "acai"],
    "poke": ["poke", "poké"],
    # Desayunos/postres
    "tostada": ["tostada", "tostadas"],
    "churros": ["churros", "churros con chocolate"],
    "tarta de queso": ["tarta", "tarta de queso", "cheesecake"],
    "torrija": ["torrija", "torrijas"],
    "helado": ["helado", "helados"],
    "flan": ["flan"],
    "brownie": ["brownie"],
    "crepe": ["crepe", "crepes"],
    "gofre": ["gofre", "gofres"],
    "pastel": ["pastel", "pasteles"],
    "dulce": ["dulce", "dulces"],
    # Formatos de carta que pueden ser plato si van compuestos
    "montadito": ["montadito", "montaditos"],
    "bocadillo": ["bocadillo", "bocadillos"],
    "tosta": ["tosta", "tostas"],
    "empanada": ["empanada", "empanadas"],
    "ensalada": ["ensalada", "ensaladas"],
}

for canonical, aliases in DISH_ALIASES.items():
    for alias in aliases:
        add_alias(alias, canonical=canonical, group="dish_core", priority=1.0)

GENERIC_FOOD_TERMS = [
    "tapa", "tapas", "ración", "racion", "raciones", "plato", "platos", "comida", "cena", "almuerzo",
    "desayuno", "menú", "menu", "carta", "cocina", "entrante", "entrantes", "postre", "postres",
    "aperitivo", "aperitivos", "producto", "productos", "especialidad", "especialidades",
]
for term in GENERIC_FOOD_TERMS:
    add_alias(term, canonical=term, group="generic_food_term", priority=0.35)

BEVERAGE_TERMS = [
    "cerveza", "cervezas", "vino", "vinos", "copa", "copas", "café", "cafe", "cafés", "cafes",
    "refresco", "refrescos", "agua", "tinto", "tinto de verano", "vermut", "manzanilla", "rebujito",
    "mojito", "cóctel", "coctel", "cócteles", "cocteles", "sangría", "sangria", "batido", "batidos",
]
for term in BEVERAGE_TERMS:
    add_alias(term, canonical=term, group="beverage", priority=0.2)

INGREDIENT_OR_SIDE_TERMS = [
    "pan", "queso", "salsa", "carne", "pescado", "pollo", "ternera", "cerdo", "jamón", "jamon",
    "patatas", "papas", "arroz", "huevo", "huevos", "tomate", "setas", "verduras", "trufa",
    "chocolate", "nata", "miel", "alioli", "mayonesa", "cebolla", "pimientos", "marisco",
]
for term in INGREDIENT_OR_SIDE_TERMS:
    add_alias(term, canonical=term, group="ingredient_or_side", priority=0.45)

aliases_df = pd.DataFrame(alias_records).drop_duplicates(subset=["alias_norm", "group", "canonical"])

# Si un alias cae en varios grupos, priorizamos dish_core > ingredient > generic > beverage.
group_priority = {"dish_core": 4, "ingredient_or_side": 3, "generic_food_term": 2, "beverage": 1}
aliases_df["group_priority"] = aliases_df["group"].map(group_priority)
aliases_df = (
    aliases_df.sort_values(["alias_norm", "group_priority", "priority"], ascending=[True, False, False])
    .drop_duplicates(subset=["alias_norm"], keep="first")
    .sort_values("alias_norm")
    .reset_index(drop=True)
)

print("Aliases únicos:", len(aliases_df))
print("Distribución por grupo:")
print(aliases_df["group"].value_counts())
display(aliases_df.head(30))

Aliases únicos: 201
Distribución por grupo:
group
dish_core             131
ingredient_or_side     25
generic_food_term      23
beverage               22
Name: count, dtype: int64

              alias       alias_norm       canonical               group  priority  group_priority
0              açai             acai            acai           dish_core      1.00               4
1             adobo            adobo  cazon en adobo           dish_core      1.00               4
2              agua             agua            agua            beverage      0.20               1
3        albóndigas       albondigas      albondigas           dish_core      1.00               4
4            alioli           alioli          alioli  ingredient_or_side      0.45               3
5           almejas          almejas         almejas           dish_core      1.00               4
6          almuerzo         almuerzo        almuerzo   generic_food_term      0.35               2
7         aperitivo        aperitivo       aperitivo   generic_food_term      0.35               2
8        aperitivos       aperitivos      aperitivos   generic_food_term      0.35               2
9             arepa            arepa           arepa           dish_core      1.00               4
10           arepas           arepas           arepa           dish_core      1.00               4
11            arroz            arroz           arroz           dish_core      1.00               4
12  arroz con leche  arroz con leche           arroz           dish_core      1.00               4
13  arroz con pollo  arroz con pollo           arroz           dish_core      1.00               4
14      arroz negro      arroz negro           arroz           dish_core      1.00               4
15             atún             atun            atun           dish_core      1.00               4
16        atún rojo        atun rojo            atun           dish_core      1.00               4
17          bacalao          bacalao         bacalao           dish_core      1.00               4
18   bacalao dorado   bacalao dorado         bacalao           dish_core      1.00               4
19           batido           batido          batido            beverage      0.20               1
20          batidos          batidos         batidos            beverage      0.20               1
21        bocadillo        bocadillo       bocadillo           dish_core      1.00               4
22       bocadillos       bocadillos       bocadillo           dish_core      1.00               4
23       boquerones       boquerones      boquerones           dish_core      1.00               4
24           bravas           bravas  patatas bravas           dish_core      1.00               4
25          brownie          brownie         brownie           dish_core      1.00               4
26           burger           burger     hamburguesa           dish_core      1.00               4
27          burguer          burguer     hamburguesa           dish_core      1.00               4
28          burrito          burrito         burrito           dish_core      1.00               4
29         burritos         burritos         burrito           dish_core      1.00               4

In [18]:
# ============================================================
# 06. Patrones de platos compuestos
# ============================================================

# Estos patrones capturan menciones más ricas que una palabra suelta:
# croquetas de jamón, solomillo al whisky, tarta de queso, montadito de pringá, etc.

DESCRIPTOR_TERMS = [
    "jamon iberico", "jamon", "puchero", "setas", "boletus", "queso de cabra", "queso", "pollo",
    "atun rojo", "atun", "bacalao", "gambas", "langostinos", "chocos", "calamares", "pulpo",
    "rabo de toro", "cola de toro", "carne mechada", "carne", "presa", "secreto", "iberico", "iberica",
    "pringa", "morcilla", "salmorejo", "tomate", "patatas", "papas", "verduras", "trufa", "miel",
    "whisky", "roquefort", "pimienta", "alioli", "ajo", "la abuela", "chocolate", "leche", "marisco",
]

# Se normalizan y se ordenan de más largo a más corto para que el regex prefiera expresiones compuestas.
descriptor_norms = sorted({normalize_text_value(x) for x in DESCRIPTOR_TERMS}, key=len, reverse=True)
DESCRIPTOR_ALT = "(?:" + "|".join(re.escape(x).replace("\ ", r"\s+") for x in descriptor_norms) + ")"

HEAD_TERMS = [
    "croqueta", "croquetas", "tortilla", "tarta", "tosta", "tostas", "tostada", "tostadas",
    "montadito", "montaditos", "bocadillo", "bocadillos", "hamburguesa", "hamburguesas",
    "pizza", "ensalada", "arroz", "pasta", "ravioli", "empanada", "arepa", "arepas", "taco", "tacos",
    "huevos", "solomillo", "lomo", "presa", "secreto", "carrillada", "bacalao", "atun",
    "pulpo", "gambas", "langostinos", "calamares", "chocos", "pollo", "pescado",
]
HEAD_ALT = "(?:" + "|".join(re.escape(normalize_text_value(x)) for x in sorted(HEAD_TERMS, key=len, reverse=True)) + ")"

COMPOUND_PATTERNS = [
    ("head_de_descriptor", re.compile(rf"(?<![a-z0-9_]){HEAD_ALT}\s+(?:de|del|con)\s+{DESCRIPTOR_ALT}(?![a-z0-9_])")),
    ("head_al_descriptor", re.compile(rf"(?<![a-z0-9_]){HEAD_ALT}\s+(?:al|a\s+la|a\s+los|a\s+las)\s+{DESCRIPTOR_ALT}(?![a-z0-9_])")),
    ("patatas_style", re.compile(r"(?<![a-z0-9_])(?:patatas|papas)\s+(?:bravas|alioli|fritas|arrugadas|gajo)(?![a-z0-9_])")),
    ("huevos_style", re.compile(r"(?<![a-z0-9_])huevos\s+(?:rotos|estrellados|revueltos)(?![a-z0-9_])")),
    ("pescado_style", re.compile(r"(?<![a-z0-9_])pescado\s+(?:frito|a\s+la\s+plancha)(?![a-z0-9_])")),
    ("solomillo_style", re.compile(r"(?<![a-z0-9_])(?:solomillo|lomo)\s+(?:al\s+whisky|al\s+roquefort|a\s+la\s+pimienta)(?![a-z0-9_])")),
    ("tarta_style", re.compile(r"(?<![a-z0-9_])tarta\s+(?:de\s+queso|de\s+chocolate|de\s+la\s+abuela)(?![a-z0-9_])")),
]

print("Patrones compuestos definidos:", [name for name, _ in COMPOUND_PATTERNS])

Patrones compuestos definidos: ['head_de_descriptor', 'head_al_descriptor', 'patatas_style', 'huevos_style', 'pescado_style', 'solomillo_style', 'tarta_style']

<>:18: SyntaxWarning: invalid escape sequence '\ '
<>:18: SyntaxWarning: invalid escape sequence '\ '
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_12284\2069402714.py:18: SyntaxWarning: invalid escape sequence '\ '
  DESCRIPTOR_ALT = "(?:" + "|".join(re.escape(x).replace("\ ", r"\s+") for x in descriptor_norms) + ")"

In [8]:
# ============================================================
# 07. Señales contextuales y reglas de confianza
# ============================================================

ORDER_TRIGGERS = [
    "pedimos", "pedi", "pedí", "pedir", "probamos", "probe", "probé", "probar", "tomamos",
    "comimos", "cenamos", "desayunamos", "recomiendo", "recomendamos", "recomendable",
    "nos pusieron", "nos sirvieron", "nos trajeron", "especialidad", "plato", "tapa", "racion", "ración",
]
POSITIVE_TERMS = [
    "rico", "riquisimo", "riquísimo", "bueno", "buenisimo", "buenísimo", "espectacular", "brutal",
    "increible", "increíble", "excelente", "delicioso", "deliciosa", "casero", "casera", "fresco", "fresca",
    "sabroso", "sabrosa", "perfecto", "perfecta", "repetir", "volveremos", "imprescindible",
]
NEGATIVE_TERMS = [
    "malo", "mala", "regular", "frio", "fría", "fria", "seco", "seca", "duro", "dura",
    "soso", "sosa", "salado", "salada", "quemado", "quemada", "decepcionante", "caro", "cara",
    "sin sabor", "no merece", "no volver", "horrible", "fatal",
]
CONTRAST_TERMS = ["pero", "aunque", "sin embargo", "no obstante", "eso si", "eso sí"]

ORDER_TRIGGERS_N = [normalize_text_value(x) for x in ORDER_TRIGGERS]
POSITIVE_TERMS_N = [normalize_text_value(x) for x in POSITIVE_TERMS]
NEGATIVE_TERMS_N = [normalize_text_value(x) for x in NEGATIVE_TERMS]
CONTRAST_TERMS_N = [normalize_text_value(x) for x in CONTRAST_TERMS]

CANDIDATE_TYPE_PRIORITY = {
    "dish_candidate": 5,
    "uncertain": 4,
    "ingredient_or_side": 3,
    "generic_food_term": 2,
    "beverage": 1,
    "excluded": 0,
}

def contains_any(context_norm: str, terms) -> bool:
    return any(term in context_norm for term in terms)

def context_signals(text_match: str, start: int, end: int, window: int = 90):
    left = max(0, start - window)
    right = min(len(text_match), end + window)
    context = text_match[left:right]
    return {
        "has_order_trigger": contains_any(context, ORDER_TRIGGERS_N),
        "has_positive_context": contains_any(context, POSITIVE_TERMS_N),
        "has_negative_context": contains_any(context, NEGATIVE_TERMS_N),
        "has_contrast_context": contains_any(context, CONTRAST_TERMS_N),
    }

def base_candidate_type(group: str, mention_norm: str, detection_method: str) -> str:
    if group == "dish_core":
        return "dish_candidate"
    if group == "beverage":
        return "beverage"
    if group == "generic_food_term":
        return "generic_food_term"
    if group == "ingredient_or_side":
        return "ingredient_or_side"
    if detection_method.startswith("compound"):
        return "dish_candidate"
    return "uncertain"

def compute_confidence(candidate_type: str, detection_method: str, mention_norm: str, signals: dict) -> float:
    if detection_method.startswith("compound"):
        score = 0.90
    elif candidate_type == "dish_candidate":
        # Una palabra suelta como "tarta" o "tortilla" es algo menos segura que "tarta de queso".
        score = 0.80 if " " not in mention_norm else 0.88
    elif candidate_type == "ingredient_or_side":
        score = 0.52
    elif candidate_type == "generic_food_term":
        score = 0.45
    elif candidate_type == "beverage":
        score = 0.35
    else:
        score = 0.50

    if signals.get("has_order_trigger"):
        score += 0.05
    if signals.get("has_positive_context") or signals.get("has_negative_context"):
        score += 0.03
    if signals.get("has_contrast_context"):
        score -= 0.02

    # Penalizaciones intencionadas.
    if candidate_type in {"generic_food_term", "beverage"}:
        score -= 0.05

    return round(max(0.05, min(0.99, score)), 4)

In [ ]:
# ============================================================
# 08. Compilación de aliases y resolución de solapes
# ============================================================

def alias_to_regex(alias_norm: str) -> re.Pattern:
    escaped = re.escape(alias_norm)..replace("\\ ", r"\s+"))
    return re.compile(rf"(?<![a-z0-9_]){escaped}(?![a-z0-9_])")

compiled_aliases = []
for row in aliases_df.to_dict("records"):
    compiled_aliases.append({
        **row,
        "regex": alias_to_regex(row["alias_norm"]),
        "alias_length": len(row["alias_norm"]),
    })

# Priorizar aliases más largos y de grupo más importante.
compiled_aliases = sorted(
    compiled_aliases,
    key=lambda x: (group_priority.get(x["group"], 0), x["alias_length"]),
    reverse=True,
)


def spans_overlap(a, b) -> bool:
    return not (a["end_char"] <= b["start_char"] or b["end_char"] <= a["start_char"])


def resolve_overlaps(candidates):
    """Conserva la mejor mención cuando varios candidatos se pisan."""
    ordered = sorted(
        candidates,
        key=lambda c: (
            CANDIDATE_TYPE_PRIORITY.get(c["candidate_type"], 0),
            c["confidence"],
            c["end_char"] - c["start_char"],
        ),
        reverse=True,
    )
    selected = []
    for cand in ordered:
        if not any(spans_overlap(cand, prev) for prev in selected):
            selected.append(cand)
    return sorted(selected, key=lambda c: (c["start_char"], c["end_char"]))

<>:6: SyntaxWarning: invalid escape sequence '\ '
<>:6: SyntaxWarning: invalid escape sequence '\ '
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_12284\2555315659.py:6: SyntaxWarning: invalid escape sequence '\ '
  escaped = re.escape(alias_norm).replace("\ ", r"\s+")

In [10]:
# ============================================================
# 09. Extracción de candidatos por review
# ============================================================

def canonical_from_phrase(mention_norm: str) -> str:
    """Normalización inicial de nombre canónico. La normalización fina vendrá en el notebook 14."""
    mention_norm = compact_spaces(mention_norm.lower())
    # Reglas directas para variantes muy frecuentes.
    direct = {
        "bravas": "patatas bravas",
        "papas bravas": "patatas bravas",
        "croquetas": "croqueta",
        "croquetas caseras": "croqueta",
        "tortilla": "tortilla de patatas",
        "tarta": "tarta de queso",
        "atun": "atun",
        "atún": "atun",
        "carrilleras": "carrillada",
        "carrillera": "carrillada",
        "hamburguesas": "hamburguesa",
        "tostadas": "tostada",
        "montaditos": "montadito",
        "bocadillos": "bocadillo",
    }
    if mention_norm in direct:
        return direct[mention_norm]
    return mention_norm


def build_candidate(row, start, end, mention_text, mention_norm, canonical, group, detection_method, pattern_name=None):
    text = row["text_clean"]
    text_match = row["text_match"]
    signals = context_signals(text_match, start, end)
    ctype = base_candidate_type(group, mention_norm, detection_method)
    confidence = compute_confidence(ctype, detection_method, mention_norm, signals)

    return {
        "mention_id": stable_id(row["review_id"], start, end, mention_norm, detection_method),
        "review_id": row["review_id"],
        "place_id": row["place_id"],
        "place_source_ref_id": row.get("place_source_ref_id"),
        "source_review_id": row.get("source_review_id"),
        "source_place_record_id": row.get("source_place_record_id"),
        "place_name": row.get("place_name"),
        "district_id": row.get("district_id"),
        "district_name": row.get("district_name"),
        "neighborhood_id": row.get("neighborhood_id"),
        "neighborhood_name": row.get("neighborhood_name"),
        "rating_value": row.get("rating_value"),
        "review_sentiment_from_rating": row.get("review_sentiment_from_rating"),
        "review_language": row.get("review_language"),
        "dish_mention_text": compact_spaces(mention_text),
        "dish_mention_normalized": compact_spaces(mention_norm),
        "canonical_dish_name_es_v1": canonical_from_phrase(canonical),
        "candidate_type": ctype,
        "lexicon_group": group,
        "detection_method": detection_method,
        "pattern_name": pattern_name,
        "confidence": confidence,
        "start_char": int(start),
        "end_char": int(end),
        "context_sentence": get_sentence_context(text, start, end),
        "window_context": get_window_context(text, start, end, window=140),
        "has_order_trigger": signals["has_order_trigger"],
        "has_positive_context": signals["has_positive_context"],
        "has_negative_context": signals["has_negative_context"],
        "has_contrast_context": signals["has_contrast_context"],
        "text": text,
    }


def extract_candidates_from_review(row):
    text = row["text_clean"]
    text_match = row["text_match"]
    candidates = []

    # 1) Aliases exactos.
    for item in compiled_aliases:
        for m in item["regex"].finditer(text_match):
            start, end = m.span()
            mention_text = text[start:end]
            mention_norm = normalize_text_value(mention_text)
            candidates.append(build_candidate(
                row=row,
                start=start,
                end=end,
                mention_text=mention_text,
                mention_norm=mention_norm,
                canonical=item["canonical"],
                group=item["group"],
                detection_method="exact_alias",
                pattern_name=None,
            ))

    # 2) Patrones compuestos.
    for pattern_name, pattern in COMPOUND_PATTERNS:
        for m in pattern.finditer(text_match):
            start, end = m.span()
            mention_text = text[start:end]
            mention_norm = normalize_text_value(mention_text)
            candidates.append(build_candidate(
                row=row,
                start=start,
                end=end,
                mention_text=mention_text,
                mention_norm=mention_norm,
                canonical=mention_norm,
                group="dish_core",
                detection_method="compound_pattern",
                pattern_name=pattern_name,
            ))

    # 3) Resolver solapes y devolver.
    return resolve_overlaps(candidates)

# Preparar texto normalizado para matching.
df["text_match"] = df["text_clean"].apply(normalize_for_match_keep_len)

# Smoke test con una review manual.
manual_row = {
    "review_id": "manual_1",
    "place_id": "place_1",
    "place_source_ref_id": "psr_1",
    "source_review_id": "source_review_1",
    "source_place_record_id": "source_place_1",
    "place_name": "Demo",
    "district_id": None,
    "district_name": "Demo",
    "neighborhood_id": None,
    "neighborhood_name": "Demo",
    "rating_value": 5,
    "review_sentiment_from_rating": "positive",
    "review_language": "es",
    "text_clean": "Pedimos croquetas de jamón, solomillo al whisky, patatas bravas y una cerveza.",
}
manual_row["text_match"] = normalize_for_match_keep_len(manual_row["text_clean"])
manual_candidates = extract_candidates_from_review(manual_row)
pd.DataFrame(manual_candidates)[["dish_mention_text", "canonical_dish_name_es_v1", "candidate_type", "confidence", "detection_method"]]

     dish_mention_text canonical_dish_name_es_v1  candidate_type  confidence  detection_method
0   croquetas de jamón        croquetas de jamon  dish_candidate        0.95  compound_pattern
1  solomillo al whisky       solomillo al whisky  dish_candidate        0.95  compound_pattern
2       patatas bravas            patatas bravas  dish_candidate        0.95  compound_pattern
3              cerveza                   cerveza        beverage        0.35       exact_alias

In [11]:
# ============================================================
# 10. Ejecutar detección sobre todo el corpus
# ============================================================

all_candidates = []
for row in df.to_dict("records"):
    all_candidates.extend(extract_candidates_from_review(row))

candidates_df = pd.DataFrame(all_candidates)

print("Candidatos detectados:", len(candidates_df))
if len(candidates_df):
    print("Reviews con candidatos:", candidates_df["review_id"].nunique())
    print("Locales con candidatos:", candidates_df["place_id"].nunique())
    print("Distribución candidate_type:")
    print(candidates_df["candidate_type"].value_counts())
    display(candidates_df.head(20))
else:
    print("No se detectaron candidatos. Revisar lexicón/patrones.")

Candidatos detectados: 12854
Reviews con candidatos: 3681
Locales con candidatos: 825
Distribución candidate_type:
candidate_type
generic_food_term     5999
dish_candidate        3659
ingredient_or_side    1944
beverage              1252
Name: count, dtype: int64

,mention_id,review_id,place_id,place_source_ref_id,source_review_id,source_place_record_id,place_name,district_id,district_name,neighborhood_id,neighborhood_name,rating_value,review_sentiment_from_rating,review_language,dish_mention_text,dish_mention_normalized,canonical_dish_name_es_v1,candidate_type,lexicon_group,detection_method,pattern_name,confidence,start_char,end_char,context_sentence,window_context,has_order_trigger,has_positive_context,has_negative_context,has_contrast_context,text
0,1fde28a5f80c28e3948ba1bf865c0b74017762f5,0d0946cb-a72c-4197-9d43-b5f3dbfcc620,8cb19db3-e9a8-4a42-be63-73e86e22a3d9,2acb2538-7f10-4760-a646-85c41436f9e8,a299c238d5349ed3eb5fc64b5db7e6def4db213c4ed81730074b12931536495c,ChIJ50jgAn5tEg0RBySkaJ7I8eE,Tropitali,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,e554ef0e-d9f1-4d89-8777-f92cee028f7f,SAN JULIAN,5.0,positive,es,Açai,acai,acai,dish_candidate,dish_core,exact_alias,NaN,0.83,19,23,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables.","Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables. Gracias por traer un pedaci",False,True,False,False,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables. Gracias por traer un pedacito de Brasil ❤️🇧🇷 volveré y seguro indicaré a mis ami..."
1,b70f05c16925cdb70c7f0ea3f4ce0d328d3ccc24,0d0946cb-a72c-4197-9d43-b5f3dbfcc620,8cb19db3-e9a8-4a42-be63-73e86e22a3d9,2acb2538-7f10-4760-a646-85c41436f9e8,a299c238d5349ed3eb5fc64b5db7e6def4db213c4ed81730074b12931536495c,ChIJ50jgAn5tEg0RBySkaJ7I8eE,Tropitali,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,e554ef0e-d9f1-4d89-8777-f92cee028f7f,SAN JULIAN,5.0,positive,es,coxinha,coxinha,coxinha,dish_candidate,dish_core,exact_alias,NaN,0.83,59,66,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables.","Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables. Gracias por traer un pedacito de Brasil ❤️🇧🇷 volveré y seguro indicaré",False,True,False,False,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables. Gracias por traer un pedacito de Brasil ❤️🇧🇷 volveré y seguro indicaré a mis ami..."
2,d2e53ecfefa1be6efcb77e2ab76c4c6274308211,b680ad6e-8999-48a0-a754-84ea920429ab,a6ba370c-eb3d-4456-94cf-58617d1a3b0a,9f4c2eb7-2ff7-44ce-8db2-1be259e6985d,4897b8c24f949dda32b4e6c5cad74f4a91228c64182c5ce9408158505e192ce0,ChIJuQj13EFvEg0RPkUdEUzL0BA,Cariña VZ,22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,65af0982-2885-49df-9f09-8b784c2f3d7b,GIRALDA SUR,5.0,positive,es,comida,comida,comida,generic_food_term,generic_food_term,exact_alias,NaN,0.43,6,12,"Buena comida y con un excelente servicio de Leo que nos atendió y nos explicó todo muy bien, sin duda iremos más de una vez.","Buena comida y con un excelente servicio de Leo que nos atendió y nos explicó todo muy bien, sin duda iremos más de una vez.",False,True,False,False,"Buena comida y con un excelente servicio de Leo que nos atendió y nos explicó todo muy bien, sin duda iremos más de una vez."
3,c0d9d8a473412c03003e6346dae49d8eef4c322f,80af93bc-d556-46a4-8254-485a921f7ac2,7d39aad6-1d3f-4fc8-8d4b-22896354507e,4fa65ed3-e51a-4a96-b82c-cbe002c03141,a74b0bb34a2b817d7ead9adbb12509984985802fe0be90942815bf3c5f52db00,ChIJmU6FwYdvEg0RYLF2daPZQkc,TOTORA,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,76a474aa-a390-48b4-a7ad-d68f6d747832,LA PLATA,2.0,negative,es,platos,platos,platos,generic_food_term,generic_food_term,exact_alias,NaN,0.45,76,82,"Una decepción, esperé 2 horas mi pedido, la camarera viendo que salían otro platos de personas que recién llegaban y no tuvo la delicadeza de ver que no llegaba el nuestro , vino la camarera a escribir mi pedido nuev...","Una decepción, esperé 2 horas mi pedido, la camarera viendo que salían otro platos de personas que recién llegaban y no tuvo la delicadeza de ver que no llegaba el nuestro , vino la camarera a escribir mi pedido nuev...",True,False,False,False,"Una decepción, esperé 2 horas mi pedido, la camarera viendo que salían otro platos de personas que recién llegaban y no tuvo la delicadeza de ver que no llegaba el nuestro , vino la camarera a escribir mi pedido nuev..."
4,789b75edffc4721dd2f191021ecbf78b66e26f16,80af93bc-d556-46a4-8254-485a921f7ac2,7d39aad6-1d3f-4fc8-8d4b-22896354507e,4fa65ed3-e51a-4a96-b82c-cbe002c03141,a74b0bb34a2b817d7ead9adbb12509984985802fe0be90942815bf3c5f52db00,ChIJmU6FwYdvEg0RYLF2daPZQkc,TOTORA,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,76a474aa-a390-48b4-a7ad-d68f6d747832,LA PLATA,2.0,negative,es,vino,vino,vino,beverage,beverage,exact_alias,NaN,0.35,174,178,"Una decepción, esperé 2 horas mi pedido, la camarera viendo que salían otro platos de personas que recién llegaban y no tuvo la delicadeza de ver que no llegaba el nuestro , vino la camarera a escribir mi pedido nuev...","edido, la camarera viendo que salían otro platos de personas que recién llegaban y no tuvo la delicadeza de ver que no llegaba el nuestro , vino la camarera a escribir mi pedido nuevamente porque no encontraban el pa...",True,False,False,False,"Una decepción, esperé 2 horas mi pedido, la camarera viendo que salían otro platos de personas que recién llegaban y no tuvo la delicadeza de ver que no llegaba el nuestro , vino la camarera a escribir mi pedido nuev..."
5,251cb1b2944013dfa2869dddfd04503626b94d87,80af93bc-d556-46a4-8254-485a921f7ac2,7d39aad6-1d3f-4fc8-8d4b-22896354507e,4fa65ed3-e51a-4a96-b82c-cbe002c03141,a74b0bb34a2b817d7ead9adbb12509984985802fe0be90942815bf3c5f52db00,ChIJmU6FwYdvEg0RYLF2daPZQkc,TOTORA,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,76a474aa-a390-48b4-a7ad-d68f6d747832,LA PLATA,2.0,negative,es,vino,vino,vino,beverage,beverage,exact_alias,NaN,0.35,295,299,"Una decepción, esperé 2 horas mi pedido, la camarera viendo que salían otro platos de personas que recién llegaban y no tuvo la delicadeza de ver que no llegaba el nuestro , vino la camarera a escribir mi pedido nuev...","egaba el nuestro , vino la camarera a escribir mi pedido nuevamente porque no encontraban el papel y aun así seguía sin llegar y por último vino otro muchacho a volver a decirme que fue lo que pedí cuando ya eran las...",True,False,False,False,"Una decepción, esperé 2 horas mi pedido, la camarera viendo que salían otro platos de personas que recién llegaban y no tuvo la delicadeza de ver que no llegaba el nuestro , vino la camarera a escribir mi pedido nuev..."
6,cac663e3158a8c410f81e15a46b05a37a813fcf1,227b359d-b549-4d0c-957e-69d54a335485,7d39aad6-1d3f-4fc8-8d4b-22896354507e,4fa65ed3-e51a-4a96-b82c-cbe002c03141,5fd80af02c0194bea0e0e7f2dcf10a85b9d1d4db7a745eb552846f0086058c7e,ChIJmU6FwYdvEg0RYLF2daPZQkc,TOTORA,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,76a474aa-a390-48b4-a7ad-d68f6d747832,LA PLATA,5.0,positive,es,comida,comida,comida,generic_food_term,generic_food_term,exact_alias,NaN,0.40,3,9,la comida peruana en sevilla anticuchos de primera acompañados con boniato dulce un acierto volveremos,la comida peruana en sevilla anticuchos de primera acompañados con boniato dulce un acierto volveremos,False,False,False,False,la comida peruana en sevilla anticuchos de primera acompañados con boniato dulce un acierto volveremos
7,6fd1354fbc386e6f82fa62e85110e27c657ddbe1,227b359d-b549-4d0c-957e-69d54a335485,7d39aad6-1d3f-4fc8-8d4b-22896354507e,4fa65ed3-e51a-4a96-b82c-cbe002c03141,5fd80af02c0194bea0e0e7f2dcf10a85b9d1d4db7a745eb552846f0086058c7e,ChIJmU6FwYdvEg0RYLF2daPZQkc,TOTORA,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,76a474aa-a390-48b4-a7ad-d68f6d747832,LA PLATA,5.0,positive,es,dulce,dulce,dulce,dish_candidate,dish_core,exact_alias,NaN,0.83,75,80,la comida peruana en sevilla anticuchos de primera acompañados con boniato dulce un acierto volveremos,la comida peruana en sevilla anticuchos de primera acompañados con boniato dulce un acierto volveremos,False,True,False,False,la comida peruana en sevilla anticuchos de primera acompañados con boniato dulce un acierto volveremos
8,f0af0edf7d70c3cd3d27a0a3f5c70b9d461412c1,e8f1661c-93ab-4fdc-bb27-26b410078b3c,60842856-c885-4d69-9b4c-053af0226be5,b16bbbeb-4d35-4717-887e-df4a78d01354,8f3d577a7a23cbb3e5e75c89bb495c2c48de70dbab84e32f42d0572fc230cdd8,ChIJE5l1RWptEg0RhmE0wJFIigI,Bar HERMANAS ASPRON GARCIA C.B.,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,8dea766c-0cd6-499c-b34c-2fed439f58df,SANTA CRUZ,1.0,negative,es,vino,vino,vino,beverage,beverage,exact_alias,NaN,0.28,43,47,"Preguntamos por el precio de la botella de vino, la camarera (ojos azules y ancha) nos dijo son 2algo euros, pero delante tenéis un chino que es mas barato.","Preguntamos por el precio de la botella de vino, la camarera (ojos azules y ancha) nos dijo son 2algo euros, pero delante tenéis un chino que es mas barato. Muy desagradable e inapropiado",False,False,False,True,"Preguntamos por el precio de la botella de vino, la camarera (ojos azules y ancha) nos dijo son 2algo euros, pero delante tenéis un chino que es mas barato. Muy desagradable e inapropiado por su parte. No entramos, p..."
9,891eb336fcf950efcbc523eb64ab823fd39e5a7a,2b16e153-117a-441d-af78-43926f3450fa,8f3242ce-c17f-46a6-be33-115b0fedccdd,4e4e23c2-1883-48b9-aa04-314828baf9c2,42195f152dbab99d78d5aafdaabc2cee9b8684ff0686ef97cf0e69e83880be54,ChIJu6sk80ZtEg0R62ZhVBDO2vI,Restaurante marohe,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,0c02556b-4c80-4a87-876b-bcf430924273,MUSEO,2.0,negative,es,comida,comida,comida,generic_food_term,generic_food_term,exact_alias,NaN,0.43,3,9,"La comida estaba bastante buena, pero en cuanto al servicio… ESPERÉ UNA HORA Y MEDIA UN PLATO QUE ACABÓ ESTANDO CRUDO.","La comida estaba bastante buena, pero en cuanto al servicio… ESPERÉ UNA HORA Y MEDIA UN PLATO QUE ACABÓ ESTANDO CRUDO. Mi familia entera comió, menos",True,False,False,True,"La comida estaba bastante buena, pero en cuanto al servicio… ESPERÉ UNA HORA Y MEDIA UN PLATO QUE ACABÓ ESTANDO CRUDO. Mi familia entera comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi mism..."
10,a4144c6492fd42dc8768446f1f1c31c3967d85e1,2b16e153-117a-441d-af78-43926f3450fa,8f3242ce-c17f-46a6-be33-115b0fedccdd,4e4e23c2-1883-48b9-aa04-314828baf9c2,42195f152dbab99d78d5aafdaabc2cee9b8684ff0686ef97cf0e69e83880be54,ChIJu6sk80ZtEg0R62ZhVBDO2vI,Restaurante marohe,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,0c02556b-4c80-4a87-876b-bcf430924273,MUSEO,2.0,negative,es,PLATO,plato,plato,generic_food_term,generic_food_term,exact_alias,NaN,0.43,88,93,"La comida estaba bastante buena, pero en cuanto al servicio… ESPERÉ UNA HORA Y MEDIA UN PLATO QUE ACABÓ ESTANDO CRUDO.","La comida estaba bastante buena, pero en cuanto al servicio… ESPERÉ UNA HORA Y MEDIA UN PLATO QUE ACABÓ ESTANDO CRUDO. Mi familia entera comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi mism...",True,False,False,True,"La comida estaba bastante buena, pero en cuanto al servicio… ESPERÉ UNA HORA Y MEDIA UN PLATO QUE ACABÓ ESTANDO CRUDO. Mi familia entera comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi mism..."
11,940a5462f6c5647076bda66f1a6f5f6f25ce0663,2b16e153-117a-441d-af78-43926f3450fa,8f3242ce-c17f-46a6-be33-115b0fedccdd,4e4e23c2-1883-48b9-aa04-314828baf9c2,42195f152dbab99d78d5aafdaabc2cee9b8684ff0686ef97cf0e69e83880be54,ChIJu6sk80ZtEg0R62ZhVBDO2vI,Restaurante marohe,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,0c02556b-4c80-4a87-876b-bcf430924273,MUSEO,2.0,negative,es,salsa,salsa,salsa,ingredient_or_side,ingredient_or_side,exact_alias,NaN,0.55,194,199,"Mi familia entera comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi misma mesa pedimos 2 platos como este.","vicio… ESPERÉ UNA HORA Y MEDIA UN PLATO QUE ACABÓ ESTANDO CRUDO. Mi familia entera comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi misma mesa pedimos 2 platos como este. En fin, se salva po...",True,False,False,True,"La comida estaba bastante buena, pero en cuanto al servicio… ESPERÉ UNA HORA Y MEDIA UN PLATO QUE ACABÓ ESTANDO CRUDO. Mi familia entera comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi mism..."
12,a8e2284154221bb6de8f247f80104ae2c7b3fbcf,2b16e153-117a-441d-af78-43926f3450fa,8f3242ce-c17f-46a6-be33-115b0fedccdd,4e4e23c2-1883-48b9-aa04-314828baf9c2,42195f152dbab99d78d5aafdaabc2cee9b8684ff0686ef97cf0e69e83880be54,ChIJu6sk80ZtEg0R62ZhVBDO2vI,Restaurante marohe,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,0c02556b-4c80-4a87-876b-bcf430924273,MUSEO,2.0,negative,es,platos,platos,platos,generic_food_term,generic_food_term,exact_alias,NaN,0.43,233,239,"Mi familia entera comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi misma mesa pedimos 2 platos como este.","QUE ACABÓ ESTANDO CRUDO. Mi familia entera comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi misma mesa pedimos 2 platos como este. En fin, se salva por la comida que si estaba rica, pero ser...",True,False,False,True,"La comida estaba bastante buena, pero en cuanto al servicio… ESPERÉ UNA HORA Y MEDIA UN PLATO QUE ACABÓ ESTANDO CRUDO. Mi familia entera comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi mism..."
13,0f28e5f385dc98754131ddd3e94bd281c9bcc0fd,2b16e153-117a-441d-af78-43926f3450fa,8f3242ce-c17f-46a6-be33-115b0fedccdd,4e4e23c2-1883-48b9-aa04-314828baf9c2,42195f152dbab99d78d5aafdaabc2cee9b8684ff0686ef97cf0e69e83880be54,ChIJu6sk80ZtEg0R62ZhVBDO2vI,Restaurante marohe,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,0c02556b-4c80-4a87-876b-bcf430924273,MUSEO,2.0,negative,es,comida,comida,comida,generic_food_term,generic_food_term,exact_alias,NaN,0.43,275,281,"En fin, se salva por la comida que si estaba rica, pero servicio y atención al cliente un poco nefasta","a comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi misma mesa pedimos 2 platos como este. En fin, se salva por la comida que si estaba rica, pero servicio y atención al cliente un poco nefasta",True,False,False,True,"La comida estaba bastante buena, pero en cuanto al servicio… ESPERÉ UNA HORA Y MEDIA UN PLATO QUE ACABÓ ESTANDO CRUDO. Mi familia entera comió, menos yo, el cual decía que estaban preparando la salsa, pero en mi mism..."
14,159fb380f51c372ca4a28498d1737f9b3564b0b3,944c8719-53fd-49a0-9da4-4223da24a03d,a6ba370c-eb3d-4456-94cf-58617d1a3b0a,9f4c2eb7-2ff7-44ce-8db2-1be259e6985d,80289e938d35629e44007e651599356e66a6e7a106614bdae06a356afc22b758,ChIJuQj13EFvEg0RPkUdEUzL0BA,Cariña VZ,22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,65af0982-2885-49df-9f09-8b784c2f3d7b,GIRALDA SUR,5.0,positive,es,arepa,arepa,arepa,dish_candidate,dish_core,exact_alias,NaN,0.83,102,107,"Los sabores son auténticos, la arepa de reina pepiada es divina, y el ambiente te transporta a Venezuela.","Visité este restaurante venezolano y fue una experiencia espectacular. Los sabores son auténticos, la arepa de reina pepiada es divina, y el ambiente te transporta a Venezuela. Leonardo, fue súper atento, nos recomen...",False,True,False,False,"Visité este restaurante venezolano y fue una experiencia espectacular. Los sabores son auténticos, la arepa de reina pepiada es divina, y el ambiente te transporta a Venezuela. Leonardo, fue súper atento, nos recomen..."
15,578c4cb2e441b1325915ebe3d1e0a25594ce1856,944c8719-53fd-49a0-9da4-4223da24a03d,a6ba370c-eb3d-4456-94cf-58617d1a3b0a,9f4c2eb7-2ff7-44ce-8db2-1be259e6985d,80289e938d35629e44007e651599356e66a6e7a106614bdae06a356afc22b758,ChIJuQj13EFvEg0RPkUdEUzL0BA,Cariña VZ,22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,65af0982-2885-49df-9f09-8b784c2f3d7b,GIRALDA SUR,5.0,positive,es,platos,platos,platos,generic_food_term,generic_food_term,exact_alias,NaN,0.48,219,225,"Leonardo, fue súper atento, nos recomendó platos increíbles y estuvo siempre pendiente.","res son auténticos, la arepa de reina pepiada es divina, y el ambiente te transporta a Venezuela. Leonardo, fue súper atento, nos recomendó platos increíbles y estuvo siempre pendiente. Quiero agradecerle a Leonardo ...",True,True,False,False,"Visité este restaurante venezolano y fue una experiencia espectacular. Los sabores son auténticos, la arepa de reina pepiada es divina, y el ambiente te transporta a Venezuela. Leonardo, fue súper atento, nos recomen..."
16,c4faec822cda3312ac8bbd677edabd5aa781930e,7b47e63c-8f6c-4fe3-85f1-ca2b929c24b4,ef9c60c7-9e6c-4585-b60c-1c9e46646bed,ec47950a-4390-47b5-87e2-791ab7f435ec,d94598f78765fd2534ede24e1ab7c0a0037d916e5a811010a6dcdfc2ce1111b5,ChIJ_dy-AQBrEg0Rhm9LFGbvc8g,Antojo Criollo,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,342668b5-12cf-4e1f-b4b7-a52c87756e43,EL CEREZO,5.0,positive,es,comida,comida,comida,generic_food_term,generic_food_term,exact_alias,NaN,0.40,18,24,"El mejor lugar de comida venezolana, llevo años comprando sus hallacas y sus panes de jamón que son una delicia, hace poco probé sus tequeños y empanadas al igual q los pastelitos de papa con queso y fueron una OBRA ...","El mejor lugar de comida venezolana, llevo años comprando sus hallacas y sus panes de jamón que son una delicia, hace poco probé sus tequeños y empanadas al igual q",False,False,False,False,"El mejor lugar de comida venezolana, llevo años comprando sus hallacas y sus panes de jamón que son una delicia, hace poco probé sus tequeños y empanadas al igual q los pastelitos de papa con queso y fueron una OBRA ..."
17,43a2b531b143a8e4da3b0491e9fb950277e3bec5,7b47e63c-8f6c-4fe3-85f1-ca2b929c24b4,ef9c60c7-9e6c-4585-b60c-1c9e46646bed,ec47950a-4390-47b5-87e2-791ab7f435ec,d94598f78765fd2534ede24e1ab7c0a0037d916e5a811010a6dcdfc2ce1111b5,ChIJ_dy-AQBrEg0Rhm9LFGbvc8g,Antojo Criollo,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,342668b5-12cf-4e1f-b4b7-a52c87756e43,EL CEREZO,5.0,positive,es,jamón,jamon,jamon,ingredient_or_side,ingredient_or_side,exact_alias,NaN,0.57,86,91,"El mejor lugar de comida venezolana, llevo años comprando sus hallacas y sus panes de jamón que son una delicia, hace poco probé sus tequeños y empanadas al igual q los pastelitos de papa con queso y fueron una OBRA ...","El mejor lugar de comida venezolana, llevo años comprando sus hallacas y sus panes de jamón que son una delicia, hace poco probé sus tequeños y empanadas al igual q los pastelitos de papa con queso y fueron una OBRA ...",True,False,False,False,"El mejor lugar de comida venezolana, llevo años comprando sus hallacas y sus panes de jamón que son una delicia, hace poco probé sus tequeños y empanadas al igual q los pastelitos de papa con queso y fueron una OBRA ..."
18,5fb5fba4a417980ceed5eb908918a0544b4d9550,7b47e63c-8f6c-4fe3-85f1-ca2b929c24b4,ef9c60c7-9e6c-4585-b60c-1c9e46646bed,ec47950a-4390-47b5-87e2-791ab7f435ec,d94598f78765fd2534ede24e1ab7c0a0037d916e5a811010a6dcdfc2ce1111b5,ChIJ_dy-AQBrEg0Rhm9LFGbvc8g,Antojo Criollo,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,342668b5-12cf-4e1f-b4b7-a52c87756e43,EL CEREZO,5.0,positive,es,empanadas,empanadas,empanada,dish_candidate,dish_core,exact_alias,NaN,0.85,144,153,"El mejor lugar de comida venezolana, llevo años comprando sus hallacas y sus panes de jamón que son una delicia, hace poco probé sus tequeños y empanadas al igual q los pastelitos de papa con queso y fueron una OBRA ...","ejor lugar de comida venezolana, llevo años comprando sus hallacas y sus panes de jamón que son una delicia, hace poco probé sus tequeños y empanadas al igual q los pastelitos de papa con queso y fueron una OBRA MAES...",True,False,False,False,"El mejor lugar de comida venezolana, llevo años comprando sus hallacas y sus panes de jamón que son una delicia, hace poco probé sus tequeños y empanadas al igual q los pastelitos de papa con queso y fueron una OBRA ..."

In [12]:
# ============================================================
# 11. Separación de candidatos útiles para plato
# ============================================================

if len(candidates_df):
    # Candidatos fuertes para pasar a normalización posterior.
    dish_candidates_df = candidates_df[
        (candidates_df["candidate_type"] == "dish_candidate")
        & (candidates_df["confidence"] >= 0.70)
    ].copy()

    # Candidatos ampliados para revisión manual.
    reviewable_candidates_df = candidates_df[
        candidates_df["candidate_type"].isin(["dish_candidate", "uncertain", "ingredient_or_side", "generic_food_term"])
    ].copy()

    print("Dish candidates v1:", len(dish_candidates_df))
    print("Reviews con dish candidates:", dish_candidates_df["review_id"].nunique())
    print("Locales con dish candidates:", dish_candidates_df["place_id"].nunique())
    print("Candidatos revisables:", len(reviewable_candidates_df))

    display(
        dish_candidates_df[
            [
                "dish_mention_text", "canonical_dish_name_es_v1", "candidate_type", "confidence",
                "place_name", "district_name", "neighborhood_name", "rating_value", "context_sentence"
            ]
        ].sort_values(["confidence", "canonical_dish_name_es_v1"], ascending=[False, True]).head(40)
    )
else:
    dish_candidates_df = pd.DataFrame()
    reviewable_candidates_df = pd.DataFrame()

Dish candidates v1: 3659
Reviews con dish candidates: 1738
Locales con dish candidates: 706
Candidatos revisables: 11602

,dish_mention_text,canonical_dish_name_es_v1,candidate_type,confidence,place_name,district_name,neighborhood_name,rating_value,context_sentence
4164,arroz con cola de toro,arroz con cola de toro,dish_candidate,0.98,Bar El 25 Bodega,Los Remedios,LOS REMEDIOS,5.0,"El san Jacobo enorme y tierno, los calamares del campo buenísimos, arroz con cola de toro, las migas espectaculares..."
3392,arroz con leche,arroz con leche,dish_candidate,0.98,Restaurante Lalola de Javi Abascal,Casco Antiguo,FERIA,5.0,"Comida estupenda y un trato exquisito, la ensaladilla muy buena, los espárragos con setas y jabalí, luego pedimos una corvina al ajillo y terminamos con un arroz con leche con torreznos caramelizado , todo exquisito ..."
4977,arroz con leche,arroz con leche,dish_candidate,0.98,Doña Pepa,Macarena,CRUZ ROJA-CAPUCHINOS,5.0,Luna el camarero que nos atendió muy cortes y educado la comida calientita buena porción de tapas y chupito de arroz con leche riquísimo 🤤
7442,arroz con leche,arroz con leche,dish_candidate,0.98,"La Parrala Bar&Tapas. Triana, Sevilla",Triana,TRIANA CASCO ANTIGUO,4.0,Al terminar nos pusieron un chupito de licor de arroz con leche!!
6860,Arroz con rabo de toro,arroz con rabo de toro,dish_candidate,0.98,Antigua Casa Diego,Triana,TRIANA CASCO ANTIGUO,4.0,-Arroz con rabo de toro...
6629,arroz de boletus,arroz de boletus,dish_candidate,0.98,Restaurante Monte Tradición,San Pablo - Santa Justa,SANTA CLARA,5.0,Ambiente y atención sobresaliente 4 de nosotros hemos comido un arroz de boletus y Angus y un chuletón de carne madura.
296,arroz de marisco,arroz de marisco,dish_candidate,0.98,Doña Encarna,Casco Antiguo,ALFALFA,5.0,Pedimos el arroz de marisco y los buñuelos de bacalao.
5195,carrillada con queso de cabra,carrillada con queso de cabra,dish_candidate,0.98,"Mesón ""La Madre""",Los Remedios,ISLA DE GARZA,4.0,"La comida espectacular, los dos arroces que probamos con mariscos el primero y carrillada con queso de cabra excelentes , los entrantes unas croquetas de pucheros muy suaves y cremosas con muy buen sabor, la tabla co..."
8364,carrillada con queso de cabra,carrillada con queso de cabra,dish_candidate,0.98,La Tontona Abacería,Bellavista - La Palmera,BELLAVISTA,5.0,"Probamos las tostas de carrillada con queso de cabra, los chicharrones de Cádiz, la de salmón… todo estaba genial!"
4140,carrillada con setas,carrillada con setas,dish_candidate,0.98,Bar Cuando Puedas,Macarena,LOS PRINCIPES-LA FONTANILLA,5.0,"Todo espectacular de bueno, toda la sorpresa, comimos Mojama, ensaladilla de pulpo, pavia y gyozas de carrillada con setas…."
7241,carrillada de atún,carrillada de atun,dish_candidate,0.98,Tarantelo Tapas - Pino Montano,Norte,BARRIADA PINO MONTANO,5.0,"La ensaladilla y la carrillada de atún, espectaculares."
1529,croqueta de pollo,croqueta de pollo,dish_candidate,0.98,Desacato Restaurante Sevilla,Casco Antiguo,ENCARNACIÓN-REGINA,5.0,"En aquella primera ocasión probé tartaleta de gambas, croqueta de pollo, tosta de cecina y foie, raviolis de ciervo y ricota, cocochas de bacalao fritas a la brasa y panchineta."
9340,croquetas de atún,croquetas de atun,dish_candidate,0.98,Doña Emilia Manolo Mayo,Casco Antiguo,ARENAL,5.0,Destacar la ensaladilla de langostinos y las croquetas de atún con ventresca.
5803,croquetas de bacalao,croquetas de bacalao,dish_candidate,0.98,Antigua Casa Diego,Triana,TRIANA CASCO ANTIGUO,5.0,"Restaurante bonito y tranquilo con terraza, tapas muy buenas, croquetas de bacalao y rabo de toro espectacular Camareras muy amables y atentas, nos recomendaron tapas."
4755,croquetas de boletus,croquetas de boletus,dish_candidate,0.98,Bar Restaurante La Cochera,Cerro - Amate,EL CERRO,5.0,"Pedimos solomillo al whisky, croquetas de rabo de toro, croquetas de boletus, el brioche de costilla y gambas al ajillo."
11367,croquetas de carne,croquetas de carne,dish_candidate,0.98,Bar Los Dos Hermanos,Macarena,PINO FLORES,5.0,Tapas y guisos caseros y con novedad cada día como el salmorejo con remolacha o las croquetas de carne mecha.
628,croquetas de cola de toro,croquetas de cola de toro,dish_candidate,0.98,Lambel Restaurante,Sur,BAMI,5.0,"Probamos sus croquetas de cola de toro, sus carrilladas y el wok de pollo y verduras y todo buenísimo."
5387,croquetas de gambas,croquetas de gambas,dish_candidate,0.98,Cervecería Alcosa,Este - Alcosa - Torreblanca,PARQUE ALCOSA-JARDINES DEL EDÉN,5.0,"Hemos comido súper bien, las tapas son generosas, pedimos, gambas al ajillo, bacalao frito, croquetas de gambas y serranito de pollo, todo riquísimo y los camareros muy eficientes y simpáticos."
772,croquetas de jamón,croquetas de jamon,dish_candidate,0.98,Antigüedades Bar de Tapas,Casco Antiguo,SANTA CRUZ,3.0,"Nos pedimos una tortilla, unas carrilleras y unas croquetas de jamón."
1177,croquetas de jamón,croquetas de jamon,dish_candidate,0.98,Antigüedades Bar de Tapas,Casco Antiguo,SANTA CRUZ,5.0,"También pedimos langostinos al ajillo, aceitunas, croquetas de jamón serrano."
3054,croquetas de jamón,croquetas de jamon,dish_candidate,0.98,Restaurante El Paseíllo,Casco Antiguo,ALFALFA,5.0,Pedí unas croquetas de jamón que estaban brutales; literalmente se deshacían.
8082,croquetas de jamón,croquetas de jamon,dish_candidate,0.98,Bar Moli Bermejales,Bellavista - La Palmera,ELCANO-BERMEJALES,4.0,"Como no, comenzamos con unas croquetas de jamón, cremosas, sabrosas y con envoltura crujiente, estaban bastante buenas y van muy bien presentadas."
8743,croquetas de jamón,croquetas de jamon,dish_candidate,0.98,Restaurante La Reserva de Joaquín Márquez,Los Remedios,LOS REMEDIOS,4.0,"Una ensaladilla rica, unas buenas croquetas de jamón y un lomo de vaca exquisito con sus papas caseras y pimientos del padrón."
9590,croquetas de jamón,croquetas de jamon,dish_candidate,0.98,Bodega Asador La Pitarra Heliopolis,Bellavista - La Palmera,SECTOR SUR-LA PALMERA-REINA MERCEDES,5.0,"Pedimos solomillo al whishy, tosta de chicharrón de Cádiz con queso Payoyo, croquetas de jamón y chorizo criollo, lo vuelvo a decir, para repetir."
3630,croquetas de jamón ibérico,croquetas de jamon iberico,dish_candidate,0.98,La Escaloná,Casco Antiguo,ALFALFA,5.0,"Pedimos ravioles fritos de ternera, croquetas de jamón ibérico y carrillada, estaba todo DELICIOSO!!"
6903,croquetas de jamón ibérico,croquetas de jamon iberico,dish_candidate,0.98,Rincón De Tina,San Pablo - Santa Justa,SAN PABLO A Y B,5.0,"Pedimos ensaladilla de langostinos, tostas de tartar de atún rojo, croquetas de jamón ibérico, pluma ibérica de bellota y de postre torrija brioche con helado de vainilla y dulce de leche, espectacular , todo buenísimo."
6356,croquetas de la abuela,croquetas de la abuela,dish_candidate,0.98,Islamorada Tapas Bar,Casco Antiguo,ARENAL,5.0,"Muy recomendables las tortillas al tartufo o las de gambón y las croquetas de la abuela, riquísimas."
7403,croquetas de marisco,croquetas de marisco,dish_candidate,0.98,Bar El Templo de Feria,Casco Antiguo,FERIA,4.0,"Pedimos tortillas de camarones y croquetas de marisco ambos platos especialmente ricos, los recomiendo 100%."
270,croquetas de pollo,croquetas de pollo,dish_candidate,0.98,Alfarería 21 - Casa Montalván,Triana,TRIANA CASCO ANTIGUO,5.0,"100% recomendable, fue el broche perfecto de nuestro viaje a Sevilla, comida espectacular recomiendo sobre todo la ensaladilla de ventresca, las croquetas de pollo, y la tarta de queso!!!"
2140,croquetas de puchero,croquetas de puchero,dish_candidate,0.98,Casa Pepe Hillo,Casco Antiguo,ARENAL,4.0,"Tomamos ensaladilla, boquerones, rejos, solomillo al whisky, ensalada y croquetas de puchero."
7885,croquetas de pulpo,croquetas de pulpo,dish_candidate,0.98,Cafè Los Niños del Flor,Casco Antiguo,SANTA CATALINA,4.0,Probemos las croquetas de pulpo y jamón ibérico que vienen acompañadas con papas fritas muy bien hechas.
8933,croquetas de queso de cabra,croquetas de queso de cabra,dish_candidate,0.98,Bar La Escondida,Sur,EL PORVENIR,5.0,"Pedimos croquetas de queso de cabra, la ensaladilla de langostinos, lagrimitas de pollo, patatas bravas y gyosas."
1092,Croquetas de rabo de toro,croquetas de rabo de toro,dish_candidate,0.98,Voltereta París - Sevilla,Nervión,LA BUHAIRA,5.0,"Nosotros pedimos todo para compartir entre tres y aquí los puntúo: Croquetas de rabo de toro 8, Croquetas de pato teriyaki 9, Bao Ibérico 7, Cigars de Montecristo 5, Gyozas de rabo de toro 9, Tabla francesa de quesos..."
2551,croquetas de rabo de toro,croquetas de rabo de toro,dish_candidate,0.98,Bar El Caminante Andaluz,Macarena,MACARENA TRES HUERTAS-MACARENA CINCO,5.0,"Pedimos cazón, pastel de berenjena y calabacín y croquetas de rabo de toro."
4754,croquetas de rabo de toro,croquetas de rabo de toro,dish_candidate,0.98,Bar Restaurante La Cochera,Cerro - Amate,EL CERRO,5.0,"Pedimos solomillo al whisky, croquetas de rabo de toro, croquetas de boletus, el brioche de costilla y gambas al ajillo."
5613,croquetas de rabo de toro,croquetas de rabo de toro,dish_candidate,0.98,Mesón Santa Clara,San Pablo - Santa Justa,SANTA CLARA,5.0,"Recomiendo la carne, es el mejor queso de rulo de cabra que me he comido y también recomiendo las croquetas de rabo de toro (se me olvidó sacar foto)."
5099,croquetas de setas,croquetas de setas,dish_candidate,0.98,Bar La Extremeña Sevilla,Los Remedios,LOS REMEDIOS,5.0,"Súper buen servicio sobre todo de Conrado, el mejor camarero, comida espectacular el cocinero Antonio, probamos el pan de la casa de solomillo y carbonara y sus croquetas de setas y cabrales, todo riquísimo."
8668,empanada de pollo,empanada de pollo,dish_candidate,0.98,Love Horno Artesano,Casco Antiguo,ALFALFA,2.0,"La empanada de pollo que pedí estaba muy dura y tenía un sabor amargo en el centro, lo que la hacía desagradable."
7891,ensalada con atún,ensalada con atun,dish_candidate,0.98,Cafè Los Niños del Flor,Casco Antiguo,SANTA CATALINA,4.0,Hasta la ensalada con atún estaba muy bien.
5055,ensalada de patatas,ensalada de patatas,dish_candidate,0.98,Vinería San Telmo,Casco Antiguo,SAN BARTOLOME,5.0,"La comida también es excelente: no solo el salmorejo, sino también platos como alcachofas, anchoas y ensalada de patatas reflejan a la perfección la esencia de Sevilla."

In [13]:
# ============================================================
# 12. Resúmenes de candidatos
# ============================================================

if len(candidates_df):
    candidate_type_summary = (
        candidates_df.groupby("candidate_type")
        .agg(
            mention_count=("mention_id", "count"),
            review_count=("review_id", "nunique"),
            place_count=("place_id", "nunique"),
            avg_confidence=("confidence", "mean"),
        )
        .reset_index()
        .sort_values("mention_count", ascending=False)
    )

    top_canonical_dishes = (
        dish_candidates_df.groupby("canonical_dish_name_es_v1")
        .agg(
            mention_count=("mention_id", "count"),
            review_count=("review_id", "nunique"),
            place_count=("place_id", "nunique"),
            avg_confidence=("confidence", "mean"),
            avg_rating=("rating_value", "mean"),
        )
        .reset_index()
        .sort_values(["mention_count", "place_count"], ascending=False)
    )

    candidates_by_district = (
        dish_candidates_df.groupby(["district_name", "canonical_dish_name_es_v1"])
        .agg(
            mention_count=("mention_id", "count"),
            review_count=("review_id", "nunique"),
            place_count=("place_id", "nunique"),
            avg_rating=("rating_value", "mean"),
        )
        .reset_index()
        .sort_values(["district_name", "mention_count"], ascending=[True, False])
    )

    candidates_by_neighborhood = (
        dish_candidates_df.groupby(["district_name", "neighborhood_name", "canonical_dish_name_es_v1"])
        .agg(
            mention_count=("mention_id", "count"),
            review_count=("review_id", "nunique"),
            place_count=("place_id", "nunique"),
            avg_rating=("rating_value", "mean"),
        )
        .reset_index()
        .sort_values(["district_name", "neighborhood_name", "mention_count"], ascending=[True, True, False])
    )

    print("Resumen por tipo:")
    display(candidate_type_summary)
    print("Top platos canónicos v1:")
    display(top_canonical_dishes.head(50))
else:
    candidate_type_summary = pd.DataFrame()
    top_canonical_dishes = pd.DataFrame()
    candidates_by_district = pd.DataFrame()
    candidates_by_neighborhood = pd.DataFrame()

Resumen por tipo:

       candidate_type  mention_count  review_count  place_count  avg_confidence
2   generic_food_term           5999          2935          800        0.443981
1      dish_candidate           3659          1738          706        0.859874
3  ingredient_or_side           1944          1088          601        0.559249
0            beverage           1252           904          492        0.330575

Top platos canónicos v1:

    canonical_dish_name_es_v1  mention_count  review_count  place_count  avg_confidence  avg_rating
68                ensaladilla            216           197          153        0.846528    4.180556
40                   croqueta            211           198          160        0.852938    4.312796
171                   tostada            209           167          119        0.830000    3.794258
29                 carrillada            172           152          123        0.850756    4.488372
146       solomillo al whisky            167           152          126        0.880958    4.209581
4                       arroz            153           132          109        0.851895    4.169935
19                       atun            117            99           70        0.851111    4.401709
157            tarta de queso            114           100           81        0.892018    4.473684
96                  montadito            108            95           73        0.842593    4.398148
116            patatas bravas            105            98           76        0.912095    4.161905
71                     gambas            104            97           79        0.864904    4.163462
75                hamburguesa             90            75           51        0.833778    3.966667
61                      dulce             81            75           56        0.836173    4.456790
37                    churros             75            61           26        0.837867    4.240000
36                     chocos             73            67           59        0.841507    4.191781
158                   torrija             70            68           56        0.838857    4.585714
122                     pizza             66            50           20        0.833333    4.181818
130             presa iberica             64            55           51        0.876250    4.015625
20                    bacalao             61            57           51        0.849672    4.360656
140                 salmorejo             59            55           50        0.841864    4.084746
132                     pulpo             59            51           48        0.857119    4.152542
80                     helado             58            51           46        0.829483    4.189655
161       tortilla de patatas             58            55           44        0.859655    3.827586
64                   ensalada             57            49           44        0.862456    3.947368
35               chicharrones             57            48           30        0.839649    4.596491
163                     tosta             52            47           39        0.840192    4.211538
90                       lomo             48            45           40        0.838958    4.000000
89                langostinos             43            41           36        0.850000    4.488372
1                  albondigas             42            40           36        0.844524    4.380952
25                 boquerones             40            37           32        0.844750    4.350000
28                  calamares             38            34           31        0.840789    4.078947
135              rabo de toro             37            36           32        0.927568    4.918919
150                      taco             35            31           27        0.848286    3.971429
113                    pastel             34            33           27        0.827647    3.852941
131                    pringa             31            27           26        0.836774    4.419355
139                   risotto             29            29           26        0.842414    4.344828
117            patatas fritas             26            24           23        0.949231    3.384615
107                    paella             25            23           21        0.842800    3.960000
111                     pasta             25            22           18        0.831600    3.720000
62                   empanada             24            22           19        0.834583    4.666667
69                 flamenquin             23            22           18        0.838261    3.565217
22                  bocadillo             21            17           16        0.842857    3.190476
3                       arepa             21            21           12        0.858095    4.476190
48         croquetas de jamon             18            18           16        0.949444    4.611111
141           secreto iberico             18            18           16        0.892222    4.055556
34             cazon en adobo             18            16           15        0.857778    4.166667
86               huevos rotos             17            17           16        0.946471    4.117647
74                      gofre             16            12           11        0.845000    4.375000
149                     sushi             16            14            7        0.839375    4.750000
87                      kebab             15             9            5        0.836000    4.133333

In [14]:
# ============================================================
# 13. Muestras para revisión manual
# ============================================================

if len(candidates_df):
    # 1) Muestra prioritaria: candidatos de plato con más confianza y contexto.
    manual_top_dish = dish_candidates_df.sort_values(
        ["confidence", "canonical_dish_name_es_v1", "rating_value"],
        ascending=[False, True, False]
    ).head(500)

    # 2) Muestra de casos dudosos/generic/ingredient para decidir reglas de exclusión.
    manual_uncertain = reviewable_candidates_df[
        reviewable_candidates_df["candidate_type"] != "dish_candidate"
    ].sort_values(["candidate_type", "confidence"], ascending=[True, False]).head(500)

    manual_review_df = pd.concat([manual_top_dish, manual_uncertain], ignore_index=True)

    manual_cols = [
        "candidate_type", "dish_mention_text", "canonical_dish_name_es_v1", "confidence", "detection_method", "pattern_name",
        "place_name", "district_name", "neighborhood_name", "rating_value", "review_sentiment_from_rating",
        "has_order_trigger", "has_positive_context", "has_negative_context", "has_contrast_context",
        "context_sentence", "window_context", "review_id", "place_id", "mention_id",
    ]
    manual_cols = [c for c in manual_cols if c in manual_review_df.columns]
    manual_review_df = manual_review_df[manual_cols]

    display(manual_review_df.head(50))
else:
    manual_review_df = pd.DataFrame()

,candidate_type,dish_mention_text,canonical_dish_name_es_v1,confidence,detection_method,pattern_name,place_name,district_name,neighborhood_name,rating_value,review_sentiment_from_rating,has_order_trigger,has_positive_context,has_negative_context,has_contrast_context,context_sentence,window_context,review_id,place_id,mention_id
0,dish_candidate,arroz con cola de toro,arroz con cola de toro,0.98,compound_pattern,head_de_descriptor,Bar El 25 Bodega,Los Remedios,LOS REMEDIOS,5.0,positive,True,True,False,False,"El san Jacobo enorme y tierno, los calamares del campo buenísimos, arroz con cola de toro, las migas espectaculares...","es. Incluso las patatas fritas que acompañan algunos platos son caseras. El san Jacobo enorme y tierno, los calamares del campo buenísimos, arroz con cola de toro, las migas espectaculares... Todo buenísimo. El trato...",eec2d563-3a50-49ca-8445-948e4df86ea1,e62bfa58-5506-4a06-8767-27d5c18ee68a,07f2f5464379efe4bc54d40e50aa0a86ed9af15c
1,dish_candidate,arroz con leche,arroz con leche,0.98,compound_pattern,head_de_descriptor,Restaurante Lalola de Javi Abascal,Casco Antiguo,FERIA,5.0,positive,True,False,True,False,"Comida estupenda y un trato exquisito, la ensaladilla muy buena, los espárragos con setas y jabalí, luego pedimos una corvina al ajillo y terminamos con un arroz con leche con torreznos caramelizado , todo exquisito ...","y un trato exquisito, la ensaladilla muy buena, los espárragos con setas y jabalí, luego pedimos una corvina al ajillo y terminamos con un arroz con leche con torreznos caramelizado , todo exquisito , muy recomendable",1541ca78-01be-4be2-a4dd-b140c7cd2e77,9d5876f8-a61f-4c94-8b42-f511dd44930c,023e06ff77f5d7aa523d2104dd0066528c518ea2
2,dish_candidate,arroz con leche,arroz con leche,0.98,compound_pattern,head_de_descriptor,Doña Pepa,Macarena,CRUZ ROJA-CAPUCHINOS,5.0,positive,True,True,False,False,Luna el camarero que nos atendió muy cortes y educado la comida calientita buena porción de tapas y chupito de arroz con leche riquísimo 🤤,impio y muy bonito decorado! Luna el camarero que nos atendió muy cortes y educado la comida calientita buena porción de tapas y chupito de arroz con leche riquísimo 🤤,aeed265b-6de1-432d-bd98-8586dbd82694,d59bcf32-9b47-4a64-a04d-a16779a81f46,c710c6c4f227e27fb08400e4c2c4486f18ae6073
3,dish_candidate,arroz con leche,arroz con leche,0.98,compound_pattern,head_de_descriptor,"La Parrala Bar&Tapas. Triana, Sevilla",Triana,TRIANA CASCO ANTIGUO,4.0,positive,True,True,False,False,Al terminar nos pusieron un chupito de licor de arroz con leche!!,"dos los platos a la vez, eso podrían mejorarlo para que no se acumule (y enfríe) la comida. Al terminar nos pusieron un chupito de licor de arroz con leche!! Repetiré!!",714b93dc-cdbc-47c1-b291-c5d278a02c30,08374e09-2b07-424c-b290-3761827a725d,528c29ecd3b9dc2f6fe2a9f47bb532cb6ac491b1
4,dish_candidate,Arroz con rabo de toro,arroz con rabo de toro,0.98,compound_pattern,head_de_descriptor,Antigua Casa Diego,Triana,TRIANA CASCO ANTIGUO,4.0,positive,True,True,False,False,-Arroz con rabo de toro...,"ado para otro intentando llegar a todo...o sea FALTA PERSONAL porque van sin aliento. Pedimos: -Guiso de espinacas muy rico, algo picante. -Arroz con rabo de toro...muy flojito -Ensaladilla de pulpo, rica, correcta. ...",4eb2a628-a5be-4e89-bbf8-8a299385b4be,e868e012-6e0d-4782-8882-8ddb60dc060c,37433da838d77d7afef7abc7e21d2bb6212b8035
5,dish_candidate,arroz de boletus,arroz de boletus,0.98,compound_pattern,head_de_descriptor,Restaurante Monte Tradición,San Pablo - Santa Justa,SANTA CLARA,5.0,positive,True,False,True,False,Ambiente y atención sobresaliente 4 de nosotros hemos comido un arroz de boletus y Angus y un chuletón de carne madura.,s venido a jugar un torneo de pádel 13 personas y hemos cenado aquí un día. Ambiente y atención sobresaliente 4 de nosotros hemos comido un arroz de boletus y Angus y un chuletón de carne madura. Mientras escribo est...,61352342-d76f-42c0-806b-24ce6eb5291a,26d7bd1c-85c7-4c8e-b3b4-55fc386784e6,331b157adf76479a1b805c866b104dd67e23bb8c
6,dish_candidate,arroz de marisco,arroz de marisco,0.98,compound_pattern,head_de_descriptor,Doña Encarna,Casco Antiguo,ALFALFA,5.0,positive,True,True,False,False,Pedimos el arroz de marisco y los buñuelos de bacalao.,"Pedimos el arroz de marisco y los buñuelos de bacalao. Todo estaba bueno y la cantidad del arroz es muy buena, además está al dente. Los camareros muy amables y atento",dfd86474-5234-4777-a8f1-174fce45ea52,76d59dfb-dd06-4539-a6f0-c87919823228,c1e11628a3e3c9ac9d81ae90d9ca32fa925a3f0f
7,dish_candidate,carrillada con queso de cabra,carrillada con queso de cabra,0.98,compound_pattern,head_de_descriptor,La Tontona Abacería,Bellavista - La Palmera,BELLAVISTA,5.0,positive,True,True,False,False,"Probamos las tostas de carrillada con queso de cabra, los chicharrones de Cádiz, la de salmón… todo estaba genial!","Fantástica experiencia! Comimos tapas originales y deliciosas. Probamos las tostas de carrillada con queso de cabra, los chicharrones de Cádiz, la de salmón… todo estaba genial! Gracias Irene por tu amabilidad",64264ac2-db6b-4675-a822-c169665ee4a4,ae8db142-2bb5-4c0f-af86-b367d528a14b,3f42c510c3df17a65c615f0717609e2ba5c0c2c9
8,dish_candidate,carrillada con queso de cabra,carrillada con queso de cabra,0.98,compound_pattern,head_de_descriptor,"Mesón ""La Madre""",Los Remedios,ISLA DE GARZA,4.0,positive,True,True,False,False,"La comida espectacular, los dos arroces que probamos con mariscos el primero y carrillada con queso de cabra excelentes , los entrantes unas croquetas de pucheros muy suaves y cremosas con muy buen sabor, la tabla co...","ían todo lo que podían a la menor indicación que les hacías. La comida espectacular, los dos arroces que probamos con mariscos el primero y carrillada con queso de cabra excelentes , los entrantes unas croquetas de p...",9b2085b3-5486-49e5-95e4-c9a9190fb0c6,9320c83e-4e3e-442a-a4ae-d5351e0ba92e,929197b6a0a3b76c32e48e0e853cd90f3a15ab94
9,dish_candidate,carrillada con setas,carrillada con setas,0.98,compound_pattern,head_de_descriptor,Bar Cuando Puedas,Macarena,LOS PRINCIPES-LA FONTANILLA,5.0,positive,True,True,False,False,"Todo espectacular de bueno, toda la sorpresa, comimos Mojama, ensaladilla de pulpo, pavia y gyozas de carrillada con setas….","Todo espectacular de bueno, toda la sorpresa, comimos Mojama, ensaladilla de pulpo, pavia y gyozas de carrillada con setas….ests últimas un lujo la verdad. Muy recomendable",df1278d1-f37d-4a39-9c5d-4fd0f58ceb41,76bef7d8-a6c0-4ec2-9e2b-5f722d9ea797,6bcc243fd71807193413682222218a94e587774d
10,dish_candidate,carrillada de atún,carrillada de atun,0.98,compound_pattern,head_de_descriptor,Tarantelo Tapas - Pino Montano,Norte,BARRIADA PINO MONTANO,5.0,positive,True,True,False,False,"La ensaladilla y la carrillada de atún, espectaculares.","sitio como este típico de Cádiz, en Sevilla. Trata muy bien el atún y en particular recomiendo el patacón de tarantelo. La ensaladilla y la carrillada de atún, espectaculares.",b527bfde-93b6-498e-ae5b-1ea9a8b77ee6,82aabaaf-8560-44f9-985b-26ceac089b9b,8d7a02a256f4e761d754505f1b6c66a5f78910ba
11,dish_candidate,croqueta de pollo,croqueta de pollo,0.98,compound_pattern,head_de_descriptor,Desacato Restaurante Sevilla,Casco Antiguo,ENCARNACIÓN-REGINA,5.0,positive,True,True,False,False,"En aquella primera ocasión probé tartaleta de gambas, croqueta de pollo, tosta de cecina y foie, raviolis de ciervo y ricota, cocochas de bacalao fritas a la brasa y panchineta.","uanto antes, esta vez a título personal, para comprobar si la experiencia se repetía. En aquella primera ocasión probé tartaleta de gambas, croqueta de pollo, tosta de cecina y foie, raviolis de ciervo y ricota, coco...",c8acc196-a55b-40a2-baf6-a80b15ef86d0,42e937c1-a980-4efc-9199-7ac33bab8e8f,aaa799a35047844d4843f7c6962ee67b55bb6f13
12,dish_candidate,croquetas de atún,croquetas de atun,0.98,compound_pattern,head_de_descriptor,Doña Emilia Manolo Mayo,Casco Antiguo,ARENAL,5.0,positive,True,True,False,False,Destacar la ensaladilla de langostinos y las croquetas de atún con ventresca.,"de carta, elegimos las almejas, buenísimas (acabamos con casi todo el pan mojado en su salsa). Destacar la ensaladilla de langostinos y las croquetas de atún con ventresca. Platos de productos frescos y de calidad! M...",27fc82b5-f20e-4fd8-87d0-621b242679c3,0d1fdb30-33e3-4a8a-adf1-7661543fd6a7,c9d49e4d4c63dd6118255f11a319a85d23b81edb
13,dish_candidate,croquetas de bacalao,croquetas de bacalao,0.98,compound_pattern,head_de_descriptor,Antigua Casa Diego,Triana,TRIANA CASCO ANTIGUO,5.0,positive,True,True,False,False,"Restaurante bonito y tranquilo con terraza, tapas muy buenas, croquetas de bacalao y rabo de toro espectacular Camareras muy amables y atentas, nos recomendaron tapas.","Restaurante bonito y tranquilo con terraza, tapas muy buenas, croquetas de bacalao y rabo de toro espectacular Camareras muy amables y atentas, nos recomendaron tapas. Muy recomendado.",844d9284-0cb6-4cd7-8a1a-dbbd43aac757,e868e012-6e0d-4782-8882-8ddb60dc060c,b3b22c6ba30379f5bff6454c991cae66d8c32646
14,dish_candidate,croquetas de boletus,croquetas de boletus,0.98,compound_pattern,head_de_descriptor,Bar Restaurante La Cochera,Cerro - Amate,EL CERRO,5.0,positive,True,True,False,False,"Pedimos solomillo al whisky, croquetas de rabo de toro, croquetas de boletus, el brioche de costilla y gambas al ajillo.","iva y nos sorprendió mucho, camareros con un servicio excelente, rápidos y atentos. Pedimos solomillo al whisky, croquetas de rabo de toro, croquetas de boletus, el brioche de costilla y gambas al ajillo. De postre, ...",c6ad73a7-6c23-40c4-95ef-b88bb0abd852,a9bce0ce-f0c5-419b-91ee-cd125258adc0,3b0d53f27ce2e97d36924cca37eb73a7633b06eb
15,dish_candidate,croquetas de carne,croquetas de carne,0.98,compound_pattern,head_de_descriptor,Bar Los Dos Hermanos,Macarena,PINO FLORES,5.0,positive,True,True,False,False,Tapas y guisos caseros y con novedad cada día como el salmorejo con remolacha o las croquetas de carne mecha.,n este rinconcito con muy buenas tapas y a buen precio. Tapas y guisos caseros y con novedad cada día como el salmorejo con remolacha o las croquetas de carne mecha. Personal y servicio de 10. No se podéis perder el ...,20f1b3fd-5f58-4c2e-9214-f672f53e67ac,c1e712ca-1a09-4bfd-844f-cc9af5d4aea5,f8c29c3761ed4af35534df1832059eb062d59807
16,dish_candidate,croquetas de cola de toro,croquetas de cola de toro,0.98,compound_pattern,head_de_descriptor,Lambel Restaurante,Sur,BAMI,5.0,positive,True,True,True,False,"Probamos sus croquetas de cola de toro, sus carrilladas y el wok de pollo y verduras y todo buenísimo.","Restaurante muy acogedor. Probamos sus croquetas de cola de toro, sus carrilladas y el wok de pollo y verduras y todo buenísimo. De postre pedimos la torrija y de 10. Además, nos atendió una chica muy agr",d6bd53a0-0daf-4065-8250-a33f2c9dad54,b32ae8c6-e52f-460b-9a22-751b169b348b,83dea847981883d01746220e0501fbe385348608
17,dish_candidate,croquetas de gambas,croquetas de gambas,0.98,compound_pattern,head_de_descriptor,Cervecería Alcosa,Este - Alcosa - Torreblanca,PARQUE ALCOSA-JARDINES DEL EDÉN,5.0,positive,True,True,False,False,"Hemos comido súper bien, las tapas son generosas, pedimos, gambas al ajillo, bacalao frito, croquetas de gambas y serranito de pollo, todo riquísimo y los camareros muy eficientes y simpáticos.","lcosa por primera vez y el sitio es fantástico. Hemos comido súper bien, las tapas son generosas, pedimos, gambas al ajillo, bacalao frito, croquetas de gambas y serranito de pollo, todo riquísimo y los camareros muy...",5b33fa85-1a40-4661-b75b-5ff3129069e9,20b9541c-432e-4388-8002-77e583608994,e66e33afd035df99b4fba7b548f62dfd9e928fed
18,dish_candidate,croquetas de jamón,croquetas de jamon,0.98,compound_pattern,head_de_descriptor,Antigüedades Bar de Tapas,Casco Antiguo,SANTA CRUZ,5.0,positive,True,True,False,False,"También pedimos langostinos al ajillo, aceitunas, croquetas de jamón serrano.","d, porciones. La tapa de queso de cabra con miel estuvo espectacular, super recomendable. También pedimos langostinos al ajillo, aceitunas, croquetas de jamón serrano. Solo la carta un poco tétrica jajaja. Lugar muy ...",7177e051-81ba-4de7-8116-ecd0089c0240,85884689-c71a-4605-974e-f103cb01c1e3,e0a1a3970aaecf3d26a76a682ed448a32237be59
19,dish_candidate,croquetas de jamón,croquetas de jamon,0.98,compound_pattern,head_de_descriptor,Restaurante El Paseíllo,Casco Antiguo,ALFALFA,5.0,positive,True,True,False,False,Pedí unas croquetas de jamón que estaban brutales; literalmente se deshacían.,No puedo describir lo bueno que está todo. El bar es muy bonito y la camarera de fuera es súper amable y atenta. Pedí unas croquetas de jamón que estaban brutales; literalmente se deshacían. También pedí carrillera c...,788a5707-20dd-4963-813d-9706476794d5,41f7d0dc-100f-414c-b338-7c864000d7c5,e2e2b9caa7b1f4148b1972aa2f03c58430a933ac
20,dish_candidate,croquetas de jamón,croquetas de jamon,0.98,compound_pattern,head_de_descriptor,Bodega Asador La Pitarra Heliopolis,Bellavista - La Palmera,SECTOR SUR-LA PALMERA-REINA MERCEDES,5.0,positive,True,True,False,False,"Pedimos solomillo al whishy, tosta de chicharrón de Cádiz con queso Payoyo, croquetas de jamón y chorizo criollo, lo vuelvo a decir, para repetir.","bastante aceptable. La comida, para recolectar petir cada cosa. Pedimos solomillo al whishy, tosta de chicharrón de Cádiz con queso Payoyo, croquetas de jamón y chorizo criollo, lo vuelvo a decir, para repetir.",5fdac2d3-bfea-444b-9a77-54a4c2516f29,ca0da6a6-2bee-4bd8-a485-8d4248fea685,30681c5aee076a1d7a431165bf5cce2ed07a4457
21,dish_candidate,croquetas de jamón,croquetas de jamon,0.98,compound_pattern,head_de_descriptor,Bar Moli Bermejales,Bellavista - La Palmera,ELCANO-BERMEJALES,4.0,positive,True,True,False,False,"Como no, comenzamos con unas croquetas de jamón, cremosas, sabrosas y con envoltura crujiente, estaban bastante buenas y van muy bien presentadas.","y agradable. Cuenta con una extensa y variada carta, éramos nueve personas y decidimos pedir todo a compartir. Como no, comenzamos con unas croquetas de jamón, cremosas, sabrosas y con envoltura crujiente, estaban ba...",3b366f6e-69fb-456f-a370-fddb55dd271c,dba652fe-f1ca-4e2e-a992-4b8c3b53f3c9,4ba51241fa3427ea7bbc84d563ea20b4a36fa88b
22,dish_candidate,croquetas de jamón,croquetas de jamon,0.98,compound_pattern,head_de_descriptor,Restaurante La Reserva de Joaquín Márquez,Los Remedios,LOS REMEDIOS,4.0,positive,True,True,False,False,"Una ensaladilla rica, unas buenas croquetas de jamón y un lomo de vaca exquisito con sus papas caseras y pimientos del padrón.","Un lugar grato para almorzar o cenar. Ya sea con tapas en mesa alta o sentado en salón. Una ensaladilla rica, unas buenas croquetas de jamón y un lomo de vaca exquisito con sus papas caseras y pimientos del padrón.",c6365169-8e65-4e85-a31d-27296fadc423,fa10d840-0989-437c-9c26-d109dcb0c97f,033821f9d997768274774a3f16725087d0d557bb
23,dish_candidate,croquetas de jamón,croquetas de jamon,0.98,compound_pattern,head_de_descriptor,Antigüedades Bar de Tapas,Casco Antiguo,SANTA CRUZ,3.0,neutral,True,False,True,False,"Nos pedimos una tortilla, unas carrilleras y unas croquetas de jamón.","Nos pedimos una tortilla, unas carrilleras y unas croquetas de jamón. La tortilla es la peor que probé en mis 10 años en España, es seca como lengua de loro, le falta sal y ese salmorejo que le ponen arriba n",4924c76e-9466-4623-b3d7-d3b27f556d9d,85884689-c71a-4605-974e-f103cb01c1e3,817bc8d5b3822608a7d56c274ab786fe6a994c1a
24,dish_candidate,croquetas de jamón ibérico,croquetas de jamon iberico,0.98,compound_pattern,head_de_descriptor,La Escaloná,Casco Antiguo,ALFALFA,5.0,positive,True,True,False,False,"Pedimos ravioles fritos de ternera, croquetas de jamón ibérico y carrillada, estaba todo DELICIOSO!!","Nunca escribo reseñas en google Maps, pero estaba todo tan rico que no podía no dejar reseña. Pedimos ravioles fritos de ternera, croquetas de jamón ibérico y carrillada, estaba todo DELICIOSO!! Y la comida llegó muy...",259dedc1-344d-4f11-b5ab-3abaf0d912cb,354e3717-5516-4eb6-9567-7aa91393c8d9,097752e62a2c6ddf4e818af951f84ffd757beb11
25,dish_candidate,croquetas de jamón ibérico,croquetas de jamon iberico,0.98,compound_pattern,head_de_descriptor,Rincón De Tina,San Pablo - Santa Justa,SAN PABLO A Y B,5.0,positive,True,True,False,False,"Pedimos ensaladilla de langostinos, tostas de tartar de atún rojo, croquetas de jamón ibérico, pluma ibérica de bellota y de postre torrija brioche con helado de vainilla y dulce de leche, espectacular , todo buenísimo.","te de comida boliviana. Tapas generosas , género bueno y bien de precio. Pedimos ensaladilla de langostinos, tostas de tartar de atún rojo, croquetas de jamón ibérico, pluma ibérica de bellota y de postre torrija bri...",305ceafd-22dc-4842-90cd-16a5af650694,b756cbc6-bfdd-49d1-a0d4-96a49f393a2e,36d500141191979960dc203dc35f0de2d4cdbb39
26,dish_candidate,croquetas de la abuela,croquetas de la abuela,0.98,compound_pattern,head_de_descriptor,Islamorada Tapas Bar,Casco Antiguo,ARENAL,5.0,positive,True,True,False,False,"Muy recomendables las tortillas al tartufo o las de gambón y las croquetas de la abuela, riquísimas.","ginalidad. En la carta tienen, también, algunos platos de pescado y carne. Muy recomendables las tortillas al tartufo o las de gambón y las croquetas de la abuela, riquísimas. El servicio del camarero fue muy bueno, ...",269322f8-8fc4-4660-8498-089c5310ca7d,59e9bff3-1066-407e-8a21-5961e50ceb17,5ca4cebf6f4874eb777e60603b7b8d79aefc7a5e
27,dish_candidate,croquetas de marisco,croquetas de marisco,0.98,compound_pattern,head_de_descriptor,Bar El Templo de Feria,Casco Antiguo,FERIA,4.0,positive,True,True,False,False,"Pedimos tortillas de camarones y croquetas de marisco ambos platos especialmente ricos, los recomiendo 100%.","Sitio informal, donde tapear algo. Pedimos tortillas de camarones y croquetas de marisco ambos platos especialmente ricos, los recomiendo 100%. Además, pedimos patatas bravas, puntillitas y tacos en adobo, que recono...",784d264a-cda4-44fa-8928-fc392a179e66,d822dba8-b811-4471-a58f-eaa9ca67c2f2,8ebc5620109097c7eb8ec0dafa7a398f205c9060
28,dish_candidate,croquetas de pollo,croquetas de pollo,0.98,compound_pattern,head_de_descriptor,Alfarería 21 - Casa Montalván,Triana,TRIANA CASCO ANTIGUO,5.0,positive,True,True,False,False,"100% recomendable, fue el broche perfecto de nuestro viaje a Sevilla, comida espectacular recomiendo sobre todo la ensaladilla de ventresca, las croquetas de pollo, y la tarta de queso!!!","recomendable, fue el broche perfecto de nuestro viaje a Sevilla, comida espectacular recomiendo sobre todo la ensaladilla de ventresca, las croquetas de pollo, y la tarta de queso!!! 1000 de 10 🤤🤤🤤",f4fca014-0d41-4450-aca4-ad15bbe56569,bda69b80-2458-4b67-a1d6-fc99805679eb,daecf95b1488e016972a8c49b41bd7fe97a6e64b
29,dish_candidate,croquetas de puchero,croquetas de puchero,0.98,compound_pattern,head_de_descriptor,Casa Pepe Hillo,Casco Antiguo,ARENAL,4.0,positive,True,True,True,False,"Tomamos ensaladilla, boquerones, rejos, solomillo al whisky, ensalada y croquetas de puchero.","y nos ha parecido genial. Buen trato, rapidez y comida muy sabrosa. Tomamos ensaladilla, boquerones, rejos, solomillo al whisky, ensalada y croquetas de puchero. Sin duda repetiremos.",7b2f07e6-1487-4d69-88a0-d02a982262b1,c8509e1e-ffc2-4e2c-9ce2-93bce10ddc49,5c42b9eb07597d83d1bc2d57e0afdde40d18466f
30,dish_candidate,croquetas de pulpo,croquetas de pulpo,0.98,compound_pattern,head_de_descriptor,Cafè Los Niños del Flor,Casco Antiguo,SANTA CATALINA,4.0,positive,True,True,False,False,Probemos las croquetas de pulpo y jamón ibérico que vienen acompañadas con papas fritas muy bien hechas.,"Excelente comida a muy buen precio. Probemos las croquetas de pulpo y jamón ibérico que vienen acompañadas con papas fritas muy bien hechas. Además plato Rosa: chuletas, salchichas, huevos y papas fritas. Ha",24ccba91-f48c-49dc-ab92-478070bdae46,3258af7f-249e-428c-8bfd-e1ffc1a10215,1baa2300d0807a51bfb1b2607a7293e8a4bbd3b7

In [15]:
# ============================================================
# 14. Exportar artefactos v1
# ============================================================


def write_jsonl(df_to_write: pd.DataFrame, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in df_to_write.to_dict("records"):
            f.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")

all_candidates_csv = OUTPUT_DIR / "sevilla_dish_candidates_all_v1.csv"
all_candidates_jsonl = OUTPUT_DIR / "sevilla_dish_candidates_all_v1.jsonl"
dish_candidates_csv = OUTPUT_DIR / "sevilla_dish_candidates_v1.csv"
dish_candidates_jsonl = OUTPUT_DIR / "sevilla_dish_candidates_v1.jsonl"
manual_review_csv = OUTPUT_DIR / "sevilla_dish_candidates_for_manual_review_v1.csv"
canonical_summary_csv = OUTPUT_DIR / "sevilla_top_canonical_dishes_v1.csv"
district_summary_csv = OUTPUT_DIR / "sevilla_dish_candidates_by_district_v1.csv"
neighborhood_summary_csv = OUTPUT_DIR / "sevilla_dish_candidates_by_neighborhood_v1.csv"
type_summary_csv = OUTPUT_DIR / "sevilla_dish_candidate_type_summary_v1.csv"

if len(candidates_df):
    candidates_df.to_csv(all_candidates_csv, index=False, encoding="utf-8")
    write_jsonl(candidates_df, all_candidates_jsonl)

    dish_candidates_df.to_csv(dish_candidates_csv, index=False, encoding="utf-8")
    write_jsonl(dish_candidates_df, dish_candidates_jsonl)

    manual_review_df.to_csv(manual_review_csv, index=False, encoding="utf-8")
    top_canonical_dishes.to_csv(canonical_summary_csv, index=False, encoding="utf-8")
    candidates_by_district.to_csv(district_summary_csv, index=False, encoding="utf-8")
    candidates_by_neighborhood.to_csv(neighborhood_summary_csv, index=False, encoding="utf-8")
    candidate_type_summary.to_csv(type_summary_csv, index=False, encoding="utf-8")

    print("Artefactos generados en:", OUTPUT_DIR)
    for path in [
        all_candidates_csv,
        all_candidates_jsonl,
        dish_candidates_csv,
        dish_candidates_jsonl,
        manual_review_csv,
        canonical_summary_csv,
        district_summary_csv,
        neighborhood_summary_csv,
        type_summary_csv,
    ]:
        print("-", path)
else:
    print("No se exportan candidatos porque no hay resultados.")

Artefactos generados en: C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection
- C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection\sevilla_dish_candidates_all_v1.csv
- C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection\sevilla_dish_candidates_all_v1.jsonl
- C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection\sevilla_dish_candidates_v1.csv
- C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection\sevilla_dish_candidates_v1.jsonl
- C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection\sevilla_dish_candidates_for_manual_review_v1.csv
- C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection\sevilla_top_canonical_dishes_v1.csv
- C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection\sevilla_dish_candidates_by_district_v1.csv
- C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection\sevilla_dish_candidates_by_neighborhood_v1.csv
- C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection\sevilla_dish_candidate_type_summary_v1.csv

In [16]:
# ============================================================
# 15. Summary JSON del notebook
# ============================================================

summary = {
    "notebook": "13_sevilla_dish_candidate_detection",
    "version": RUN_NAME,
    "generated_at": GENERATED_AT,
    "input_path": str(INPUT_PATH),
    "output_dir": str(OUTPUT_DIR),
    "input": {
        "total_reviews": int(len(df)),
        "unique_places": int(df["place_id"].nunique()),
        "unique_neighborhoods": int(df["neighborhood_id"].nunique()),
        "unique_districts": int(df["district_id"].nunique()),
        "language_counts": {str(k): int(v) for k, v in df["review_language"].value_counts(dropna=False).to_dict().items()},
        "rating_counts": {str(k): int(v) for k, v in df["rating_value"].value_counts(dropna=False).sort_index().to_dict().items()},
    },
    "detection": {
        "total_candidates_all_types": int(len(candidates_df)),
        "total_dish_candidates": int(len(dish_candidates_df)),
        "reviews_with_any_candidate": int(candidates_df["review_id"].nunique()) if len(candidates_df) else 0,
        "reviews_with_dish_candidate": int(dish_candidates_df["review_id"].nunique()) if len(dish_candidates_df) else 0,
        "places_with_dish_candidate": int(dish_candidates_df["place_id"].nunique()) if len(dish_candidates_df) else 0,
        "candidate_type_counts": {str(k): int(v) for k, v in candidates_df["candidate_type"].value_counts().to_dict().items()} if len(candidates_df) else {},
        "detection_method_counts": {str(k): int(v) for k, v in candidates_df["detection_method"].value_counts().to_dict().items()} if len(candidates_df) else {},
    },
    "top_canonical_dishes": top_canonical_dishes.head(50).to_dict("records") if len(top_canonical_dishes) else [],
    "checks": {
        "has_candidates": bool(len(candidates_df) > 0),
        "has_dish_candidates": bool(len(dish_candidates_df) > 0),
        "candidate_ids_are_unique": bool(candidates_df["mention_id"].is_unique) if len(candidates_df) else True,
        "dish_candidate_ids_are_unique": bool(dish_candidates_df["mention_id"].is_unique) if len(dish_candidates_df) else True,
        "all_dish_candidates_have_place": bool(dish_candidates_df["place_id"].notna().all()) if len(dish_candidates_df) else True,
        "all_dish_candidates_have_review": bool(dish_candidates_df["review_id"].notna().all()) if len(dish_candidates_df) else True,
    },
    "artifacts": {
        "all_candidates_csv": all_candidates_csv.name,
        "all_candidates_jsonl": all_candidates_jsonl.name,
        "dish_candidates_csv": dish_candidates_csv.name,
        "dish_candidates_jsonl": dish_candidates_jsonl.name,
        "manual_review_csv": manual_review_csv.name,
        "canonical_summary_csv": canonical_summary_csv.name,
        "district_summary_csv": district_summary_csv.name,
        "neighborhood_summary_csv": neighborhood_summary_csv.name,
        "type_summary_csv": type_summary_csv.name,
    },
}

summary_path = OUTPUT_DIR / "sevilla_dish_detection_summary_v1.json"
with summary_path.open("w", encoding="utf-8") as f:
    json.dump(summary, f, ensure_ascii=False, indent=2, default=str)

print("Summary guardado en:", summary_path)
print(json.dumps(summary["detection"], ensure_ascii=False, indent=2))
print(json.dumps(summary["checks"], ensure_ascii=False, indent=2))

Summary guardado en: C:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\dish_detection\sevilla_dish_detection_summary_v1.json
{
  "total_candidates_all_types": 12854,
  "total_dish_candidates": 3659,
  "reviews_with_any_candidate": 3681,
  "reviews_with_dish_candidate": 1738,
  "places_with_dish_candidate": 706,
  "candidate_type_counts": {
    "generic_food_term": 5999,
    "dish_candidate": 3659,
    "ingredient_or_side": 1944,
    "beverage": 1252
  },
  "detection_method_counts": {
    "exact_alias": 12352,
    "compound_pattern": 502
  }
}
{
  "has_candidates": true,
  "has_dish_candidates": true,
  "candidate_ids_are_unique": true,
  "dish_candidate_ids_are_unique": true,
  "all_dish_candidates_have_place": true,
  "all_dish_candidates_have_review": true
}

## 16. Interpretación y próximos pasos

Este notebook genera candidatos de platos con una estrategia híbrida inicial. La salida no debe considerarse todavía el ranking final.

Los siguientes pasos recomendados son:

1. Revisar `sevilla_dish_candidates_for_manual_review_v1.csv`.
2. Ajustar el lexicón y exclusiones si aparecen falsos positivos.
3. Crear el notebook `14_sevilla_dish_normalization.ipynb`.
4. Construir un catálogo español de platos y aliases.
5. Pasar después a sentimiento por mención y señales `place-dish`.

Criterio recomendado para avanzar:

```text
- suficientes candidatos `dish_candidate`;
- falsos positivos controlables;
- buena cobertura por local/barrio;
- términos genéricos y bebidas separados del ranking.
```