# 16. Agregación de señales local-plato — Sevilla

Este notebook transforma las menciones de platos con sentimiento en señales agregadas por `place_id + dish_id_v1`.

Entrada:

```text
data/artifacts/ai/sevilla/sentiment/sevilla_dish_mentions_with_sentiment_v1.jsonl
```

Salidas:

```text
data/artifacts/ai/sevilla/aggregation/sevilla_place_dish_signals_v1.csv
data/artifacts/ai/sevilla/aggregation/sevilla_place_dish_signals_v1.jsonl
data/artifacts/ai/sevilla/aggregation/sevilla_place_dish_ranking_candidates_v1.csv
data/artifacts/ai/sevilla/aggregation/sevilla_global_dish_signals_v1.csv
data/artifacts/ai/sevilla/aggregation/sevilla_place_dish_signal_summary_v1.json
```

In [5]:
# ============================================================
# 01. Imports y rutas
# ============================================================

from __future__ import annotations

import ast
import json
import math
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 120)
pd.set_option("display.max_colwidth", 180)
pd.set_option("display.width", 220)

CURRENT_DIR = Path.cwd()
PROJECT_ROOT = CURRENT_DIR.parent if CURRENT_DIR.name == "notebooks" else CURRENT_DIR

INPUT_PATH = PROJECT_ROOT / "data" / "artifacts" / "ai" / "sevilla" / "sentiment" / "sevilla_dish_mentions_with_sentiment_v1.jsonl"
OUTPUT_DIR = PROJECT_ROOT / "data" / "artifacts" / "ai" / "sevilla" / "aggregation"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("INPUT_PATH:", INPUT_PATH)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("Existe input:", INPUT_PATH.exists())

PROJECT_ROOT: c:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline
INPUT_PATH: c:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\sentiment\sevilla_dish_mentions_with_sentiment_v1.jsonl
OUTPUT_DIR: c:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\aggregation
Existe input: True

In [6]:
# ============================================================
# 02. Utilidades
# ============================================================

def read_jsonl(path: Path) -> pd.DataFrame:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"JSON inválido en línea {i}: {exc}") from exc
    return pd.DataFrame(rows)


def save_jsonl(df: pd.DataFrame, path: Path) -> None:
    records = df.replace({np.nan: None}).to_dict(orient="records")
    with path.open("w", encoding="utf-8") as f:
        for row in records:
            f.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")


def save_json(data: dict[str, Any], path: Path) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2, default=str)


def parse_maybe_list(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(x) for x in value]
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return []
    if isinstance(value, str):
        txt = value.strip()
        if not txt:
            return []
        try:
            parsed = ast.literal_eval(txt)
            if isinstance(parsed, list):
                return [str(x) for x in parsed]
            return [str(parsed)]
        except Exception:
            if "," in txt:
                return [x.strip() for x in txt.split(",") if x.strip()]
            return [txt]
    return [str(value)]


def clip01(value: float) -> float:
    return float(max(0.0, min(1.0, value)))


def sigmoid_like(value: float, scale: float = 2.6) -> float:
    return float((math.tanh(value / scale) + 1.0) / 2.0)

In [7]:
# ============================================================
# 03. Carga y validación
# ============================================================

if not INPUT_PATH.exists():
    raise FileNotFoundError(
        f"No se encontró {INPUT_PATH}. Ejecuta antes el notebook 15_sevilla_mention_sentiment.ipynb."
    )

mentions_df = read_jsonl(INPUT_PATH)

print("Shape:", mentions_df.shape)
display(mentions_df.head(3))

REQUIRED_COLUMNS = [
    "mention_id", "dish_id_v1", "review_id", "place_id", "place_name",
    "district_id", "district_name", "neighborhood_id", "neighborhood_name",
    "rating_value", "display_dish_name_es_v1", "normalized_dish_name_es_v1",
    "dish_family_es_v1", "dish_group_es_v1", "mention_sentiment_label_v1",
    "mention_sentiment_score_v1", "mention_sentiment_confidence_v1",
    "mention_sentiment_weight_v1", "sentiment_reason_v1",
]

missing = [c for c in REQUIRED_COLUMNS if c not in mentions_df.columns]
if missing:
    raise KeyError(f"Faltan columnas obligatorias: {missing}")

basic_checks = {
    "has_rows": bool(len(mentions_df) > 0),
    "mention_ids_are_unique": bool(mentions_df["mention_id"].nunique(dropna=True) == len(mentions_df)),
    "all_have_place": bool(mentions_df["place_id"].notna().all()),
    "all_have_dish": bool(mentions_df["dish_id_v1"].notna().all()),
    "all_have_review": bool(mentions_df["review_id"].notna().all()),
    "all_have_sentiment_label": bool(mentions_df["mention_sentiment_label_v1"].notna().all()),
}

print(json.dumps(basic_checks, indent=2, ensure_ascii=False))

Shape: (2979, 59)

,mention_id,dish_id_v1,review_id,place_id,place_source_ref_id,source_review_id,source_place_record_id,place_name,district_id,district_name,neighborhood_id,neighborhood_name,rating_value,review_sentiment_from_rating,review_language,dish_mention_text,dish_mention_normalized,canonical_dish_name_es_v1,normalized_dish_name_es_v1,display_dish_name_es_v1,dish_group_es_v1,dish_family_es_v1,dish_specificity_v1,candidate_type,lexicon_group,detection_method,pattern_name,confidence,mention_quality_tier_v1,ranking_eligible_v1,eligibility_status_v1,eligibility_reason_v1,needs_manual_review_v1,normalization_method_v1,start_char,end_char,context_sentence,window_context,has_order_trigger,has_positive_context,has_negative_context,has_contrast_context,text,mention_sentiment_label_v1,mention_sentiment_score_v1,mention_sentiment_local_score_v1,mention_sentiment_local_strength_v1,mention_sentiment_confidence_v1,mention_sentiment_weight_v1,sentiment_reason_v1,sentiment_flags_v1,positive_terms_v1,negative_terms_v1,neutral_terms_v1,rating_prior_label_v1,rating_prior_score_v1,context_used_v1,context_source_v1,debug_sentiment_matches_v1
0,1fde28a5f80c28e3948ba1bf865c0b74017762f5,dish_es_v1_d5782aef2e608777,0d0946cb-a72c-4197-9d43-b5f3dbfcc620,8cb19db3-e9a8-4a42-be63-73e86e22a3d9,2acb2538-7f10-4760-a646-85c41436f9e8,a299c238d5349ed3eb5fc64b5db7e6def4db213c4ed81730074b12931536495c,ChIJ50jgAn5tEg0RBySkaJ7I8eE,Tropitali,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,e554ef0e-d9f1-4d89-8777-f92cee028f7f,SAN JULIAN,5,positive,es,Açai,acai,acai,acai,acai,internacional,internacional,clear_single,dish_candidate,dish_core,exact_alias,NaN,0.83,medium,True,eligible,dish_like_candidate,False,canonical_passthrough,19,23,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables.","Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables. Gracias por traer un pedaci",False,True,False,False,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables. Gracias por traer un pedacito de Brasil ...",positive,3.6520,3.6520,3.6520,0.88,0.8800,local_context_primary,"[intensifier_nearby, sentiment_may_refer_to_service]","[increible:positive_lexicon, rica:positive_lexicon]",[],[],positive,1.15,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables.",context_sentence,"[increible@99:2.00, rica@70:1.65]"
1,b70f05c16925cdb70c7f0ea3f4ce0d328d3ccc24,dish_es_v1_987dcc3d8e157f2d,0d0946cb-a72c-4197-9d43-b5f3dbfcc620,8cb19db3-e9a8-4a42-be63-73e86e22a3d9,2acb2538-7f10-4760-a646-85c41436f9e8,a299c238d5349ed3eb5fc64b5db7e6def4db213c4ed81730074b12931536495c,ChIJ50jgAn5tEg0RBySkaJ7I8eE,Tropitali,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,e554ef0e-d9f1-4d89-8777-f92cee028f7f,SAN JULIAN,5,positive,es,coxinha,coxinha,coxinha,coxinha,coxinha,internacional,internacional,clear_single,dish_candidate,dish_core,exact_alias,NaN,0.83,medium,True,eligible,dish_like_candidate,False,canonical_passthrough,59,66,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables.","Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables. Gracias por traer un pedacito de Brasil ...",False,True,False,False,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables. Gracias por traer un pedacito de Brasil ...",positive,4.3094,4.3094,4.3094,0.88,0.8800,local_context_primary,"[intensifier_nearby, sentiment_may_refer_to_service]","[increible:positive_lexicon, rica:positive_lexicon]",[],[],positive,1.15,"Sin dudas el mejor Açai que he probado aqui en Sevilla, la coxinha muy rica y el trato del personal increíble, son muy muy muy amables.",context_sentence,"[increible@99:2.36, rica@70:1.95]"
2,159fb380f51c372ca4a28498d1737f9b3564b0b3,dish_es_v1_aca2ea7ae1f740a5,944c8719-53fd-49a0-9da4-4223da24a03d,a6ba370c-eb3d-4456-94cf-58617d1a3b0a,9f4c2eb7-2ff7-44ce-8db2-1be259e6985d,80289e938d35629e44007e651599356e66a6e7a106614bdae06a356afc22b758,ChIJuQj13EFvEg0RPkUdEUzL0BA,Cariña VZ,22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,65af0982-2885-49df-9f09-8b784c2f3d7b,GIRALDA SUR,5,positive,es,arepa,arepa,arepa,arepa,arepa,internacional,internacional,clear_single,dish_candidate,dish_core,exact_alias,NaN,0.83,medium,True,eligible,dish_like_candidate,False,canonical_passthrough,102,107,"Los sabores son auténticos, la arepa de reina pepiada es divina, y el ambiente te transporta a Venezuela.","Visité este restaurante venezolano y fue una experiencia espectacular. Los sabores son auténticos, la arepa de reina pepiada es divina, y el ambiente te transporta a Venezuela....",False,True,False,False,"Visité este restaurante venezolano y fue una experiencia espectacular. Los sabores son auténticos, la arepa de reina pepiada es divina, y el ambiente te transporta a Venezuela....",positive,1.1500,0.0000,0.0000,0.36,0.2232,review_prior_fallback,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal]",[],[],[],positive,1.15,"Los sabores son auténticos, la arepa de reina pepiada es divina, y el ambiente te transporta a Venezuela.",context_sentence,[]

{
  "has_rows": true,
  "mention_ids_are_unique": true,
  "all_have_place": true,
  "all_have_dish": true,
  "all_have_review": true,
  "all_have_sentiment_label": true
}

In [8]:
# ============================================================
# 04. Preparación de variables para agregación
# ============================================================

df = mentions_df.copy()

for col in [
    "rating_value", "confidence", "mention_sentiment_score_v1",
    "mention_sentiment_local_score_v1", "mention_sentiment_local_strength_v1",
    "mention_sentiment_confidence_v1", "mention_sentiment_weight_v1",
]:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

df["mention_sentiment_label_v1"] = (
    df["mention_sentiment_label_v1"].fillna("neutral").astype(str).str.lower().str.strip()
)

valid_labels = {"positive", "neutral", "negative"}
df.loc[~df["mention_sentiment_label_v1"].isin(valid_labels), "mention_sentiment_label_v1"] = "neutral"

df["sentiment_value_v1"] = df["mention_sentiment_label_v1"].map(
    {"positive": 1.0, "neutral": 0.0, "negative": -1.0}
).fillna(0.0)

if "sentiment_flags_v1" in df.columns:
    df["sentiment_flags_list_v1"] = df["sentiment_flags_v1"].apply(parse_maybe_list)
else:
    df["sentiment_flags_list_v1"] = [[] for _ in range(len(df))]

df["has_low_confidence_flag_v1"] = df["sentiment_flags_list_v1"].apply(
    lambda xs: "low_sentiment_confidence" in xs or "weak_local_sentiment_signal" in xs
)
df["has_service_flag_v1"] = df["sentiment_flags_list_v1"].apply(lambda xs: "sentiment_may_refer_to_service" in xs)
df["has_price_flag_v1"] = df["sentiment_flags_list_v1"].apply(lambda xs: "price_context_detected" in xs)
df["has_contrast_flag_v1"] = df["sentiment_flags_list_v1"].apply(lambda xs: "contrast_marker_nearby" in xs)
df["has_negation_flag_v1"] = df["sentiment_flags_list_v1"].apply(lambda xs: "negation_detected" in xs)

df["is_local_context_v1"] = df["sentiment_reason_v1"].eq("local_context_primary")
df["is_review_prior_fallback_v1"] = df["sentiment_reason_v1"].eq("review_prior_fallback")

base_weight = df["mention_sentiment_weight_v1"].fillna(df["mention_sentiment_confidence_v1"]).fillna(0.5)
base_weight = base_weight.clip(lower=0.05, upper=1.0)

reason_multiplier = np.where(df["is_local_context_v1"], 1.00, 0.62)
service_multiplier = np.where(df["has_service_flag_v1"], 0.72, 1.00)
price_multiplier = np.where(df["has_price_flag_v1"], 0.82, 1.00)
low_conf_multiplier = np.where(df["has_low_confidence_flag_v1"], 0.78, 1.00)

df["aggregation_weight_v1"] = (
    base_weight * reason_multiplier * service_multiplier * price_multiplier * low_conf_multiplier
).clip(0.03, 1.0)

print("Dataset preparado:", df.shape)
display(df[[
    "mention_id", "place_name", "display_dish_name_es_v1", "mention_sentiment_label_v1",
    "mention_sentiment_confidence_v1", "sentiment_reason_v1", "aggregation_weight_v1",
]].head(10))

Dataset preparado: (2979, 69)

                                 mention_id             place_name display_dish_name_es_v1 mention_sentiment_label_v1  mention_sentiment_confidence_v1    sentiment_reason_v1  aggregation_weight_v1
0  1fde28a5f80c28e3948ba1bf865c0b74017762f5              Tropitali                    acai                   positive                             0.88  local_context_primary                0.63360
1  b70f05c16925cdb70c7f0ea3f4ce0d328d3ccc24              Tropitali                 coxinha                   positive                             0.88  local_context_primary                0.63360
2  159fb380f51c372ca4a28498d1737f9b3564b0b3              Cariña VZ                   arepa                   positive                             0.36  review_prior_fallback                0.10794
3  5fb5fba4a417980ceed5eb908918a0544b4d9550         Antojo Criollo                empanada                   positive                             0.36  review_prior_fallback                0.10794
4  f18cf1d71d336ce90af3ecaee466f476e42a7159         Antojo Criollo          tarta de queso                   positive                             0.36  review_prior_fallback                0.10794
5  7163b4138b0ccdeceb14354e15749ecb6da5ca34              Cariña VZ                   arepa                   positive                             0.83  local_context_primary                0.59760
6  f96c4c285c116d710bc655db098ec929d9e84e6a         Healthy Nation                    poke                   positive                             0.88  local_context_primary                0.63360
7  23bdc5adc41281a944a563a8a047ddb25e3880b7         Healthy Nation                 burrito                   positive                             0.88  local_context_primary                0.63360
8  e20cb0dbc02ff2f90456ddc2c5e78e2705fcdbf1  Abacería LP La Pareja                morcilla                   positive                             0.90  local_context_primary                0.90000
9  6c3dcefa0e85a875f871740bf111bea6cf8e164f  Abacería LP La Pareja                 bacalao                   positive                             0.90  local_context_primary                0.90000

In [9]:
# ============================================================
# 05. Agregación por local-plato
# ============================================================

GROUP_COLUMNS = [
    "place_id", "place_name", "district_id", "district_name", "neighborhood_id", "neighborhood_name",
    "dish_id_v1", "display_dish_name_es_v1", "normalized_dish_name_es_v1",
    "dish_family_es_v1", "dish_group_es_v1",
]


def aggregate_place_dish(group: pd.DataFrame) -> pd.Series:
    total = len(group)
    pos = int((group["mention_sentiment_label_v1"] == "positive").sum())
    neu = int((group["mention_sentiment_label_v1"] == "neutral").sum())
    neg = int((group["mention_sentiment_label_v1"] == "negative").sum())

    weights = group["aggregation_weight_v1"].fillna(0.05).clip(lower=0.03)
    weighted_sentiment_value = float(np.average(group["sentiment_value_v1"].fillna(0.0), weights=weights)) if total else 0.0
    weighted_sentiment_score = float(np.average(group["mention_sentiment_score_v1"].fillna(0.0), weights=weights)) if total else 0.0

    weighted_positive_count = float(((group["mention_sentiment_label_v1"] == "positive").astype(float) * weights).sum())
    weighted_neutral_count = float(((group["mention_sentiment_label_v1"] == "neutral").astype(float) * weights).sum())
    weighted_negative_count = float(((group["mention_sentiment_label_v1"] == "negative").astype(float) * weights).sum())
    total_weight = float(weights.sum())

    alpha = 1.0
    smoothed_positive_ratio = (weighted_positive_count + alpha) / (total_weight + 3 * alpha)
    smoothed_negative_ratio = (weighted_negative_count + alpha) / (total_weight + 3 * alpha)

    flags = []
    for xs in group["sentiment_flags_list_v1"]:
        flags.extend(xs)
    top_flags = [k for k, _ in Counter(flags).most_common(8)]

    example_positive = ""
    example_negative = ""
    example_neutral = ""
    if "context_used_v1" in group.columns:
        for label in ["positive", "negative", "neutral"]:
            rows = group[group["mention_sentiment_label_v1"] == label]
            if len(rows):
                selected = str(rows.sort_values("mention_sentiment_confidence_v1", ascending=False)["context_used_v1"].iloc[0])[:500]
                if label == "positive":
                    example_positive = selected
                elif label == "negative":
                    example_negative = selected
                else:
                    example_neutral = selected

    return pd.Series({
        "mention_count": int(total),
        "review_count": int(group["review_id"].nunique(dropna=True)),
        "source_review_count": int(group["source_review_id"].nunique(dropna=True)) if "source_review_id" in group.columns else int(group["review_id"].nunique(dropna=True)),
        "positive_count": pos,
        "neutral_count": neu,
        "negative_count": neg,
        "positive_ratio": round(pos / total, 4) if total else 0.0,
        "neutral_ratio": round(neu / total, 4) if total else 0.0,
        "negative_ratio": round(neg / total, 4) if total else 0.0,
        "weighted_positive_count": round(weighted_positive_count, 4),
        "weighted_neutral_count": round(weighted_neutral_count, 4),
        "weighted_negative_count": round(weighted_negative_count, 4),
        "total_signal_weight": round(total_weight, 4),
        "smoothed_positive_ratio": round(float(smoothed_positive_ratio), 4),
        "smoothed_negative_ratio": round(float(smoothed_negative_ratio), 4),
        "avg_sentiment_value": round(float(group["sentiment_value_v1"].mean()), 4),
        "weighted_sentiment_value": round(weighted_sentiment_value, 4),
        "avg_sentiment_score": round(float(group["mention_sentiment_score_v1"].fillna(0.0).mean()), 4),
        "weighted_sentiment_score": round(weighted_sentiment_score, 4),
        "avg_sentiment_confidence": round(float(group["mention_sentiment_confidence_v1"].fillna(0.0).mean()), 4),
        "avg_aggregation_weight": round(float(weights.mean()), 4),
        "local_context_count": int(group["is_local_context_v1"].sum()),
        "review_prior_fallback_count": int(group["is_review_prior_fallback_v1"].sum()),
        "local_context_ratio": round(float(group["is_local_context_v1"].mean()), 4),
        "fallback_ratio": round(float(group["is_review_prior_fallback_v1"].mean()), 4),
        "low_confidence_flag_count": int(group["has_low_confidence_flag_v1"].sum()),
        "service_flag_count": int(group["has_service_flag_v1"].sum()),
        "price_flag_count": int(group["has_price_flag_v1"].sum()),
        "contrast_flag_count": int(group["has_contrast_flag_v1"].sum()),
        "negation_flag_count": int(group["has_negation_flag_v1"].sum()),
        "top_sentiment_flags_v1": top_flags,
        "avg_rating": round(float(group["rating_value"].fillna(0.0).mean()), 4),
        "min_rating": round(float(group["rating_value"].fillna(0.0).min()), 4),
        "max_rating": round(float(group["rating_value"].fillna(0.0).max()), 4),
        "example_positive_context_v1": example_positive,
        "example_negative_context_v1": example_negative,
        "example_neutral_context_v1": example_neutral,
    })


place_dish_signals = (
    df.groupby(GROUP_COLUMNS, dropna=False)
      .apply(aggregate_place_dish)
      .reset_index()
)

print("Pares local-plato agregados:", place_dish_signals.shape)
display(place_dish_signals.head(10))

Pares local-plato agregados: (2212, 48)

,place_id,place_name,district_id,district_name,neighborhood_id,neighborhood_name,dish_id_v1,display_dish_name_es_v1,normalized_dish_name_es_v1,dish_family_es_v1,dish_group_es_v1,mention_count,review_count,source_review_count,positive_count,neutral_count,negative_count,positive_ratio,neutral_ratio,negative_ratio,weighted_positive_count,weighted_neutral_count,weighted_negative_count,total_signal_weight,smoothed_positive_ratio,smoothed_negative_ratio,avg_sentiment_value,weighted_sentiment_value,avg_sentiment_score,weighted_sentiment_score,avg_sentiment_confidence,avg_aggregation_weight,local_context_count,review_prior_fallback_count,local_context_ratio,fallback_ratio,low_confidence_flag_count,service_flag_count,price_flag_count,contrast_flag_count,negation_flag_count,top_sentiment_flags_v1,avg_rating,min_rating,max_rating,example_positive_context_v1,example_negative_context_v1,example_neutral_context_v1
0,0046efb9-63e6-4eb0-8d95-0f93b585dbcc,Bar Pino,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,73b4ba41-1e8f-41b1-aa2a-fe7975470132,PINO FLORES,dish_es_v1_03d0d732fdd6fe23,gambas,gambas,mar_y_pescado,pescado,1,1,1,1,0,0,1.0,0.0,0.0,0.9000,0.0,0.0000,0.9000,0.4872,0.2564,1.0,1.0000,1.9000,1.9000,0.9000,0.9000,1,0,1.0000,0.0000,0,0,0,0,0,[],5.00,5.0,5.0,"Todo buenísimo, las alitas fritas adobadas su santo y seña, berenjena rellena, gambas al ajillo, carnes a la brasa, pastel vegetal.......",,
1,0046efb9-63e6-4eb0-8d95-0f93b585dbcc,Bar Pino,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,73b4ba41-1e8f-41b1-aa2a-fe7975470132,PINO FLORES,dish_es_v1_2c67f67ce386e9d6,carrillada,carrillada,tapas_clasicas,carrillada,1,1,1,1,0,0,1.0,0.0,0.0,0.8600,0.0,0.0000,0.8600,0.4819,0.2591,1.0,1.0000,1.4160,1.4160,0.8600,0.8600,1,0,1.0000,0.0000,0,0,0,1,0,"[contrast_marker_nearby, intensifier_nearby]",5.00,5.0,5.0,"Es difícil destacar algo de la carta , ya que todo estaba muy bueno , pero las albóndigas , las croquetas y la carrillada estaban excelentes .",,
2,0046efb9-63e6-4eb0-8d95-0f93b585dbcc,Bar Pino,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,73b4ba41-1e8f-41b1-aa2a-fe7975470132,PINO FLORES,dish_es_v1_3b8c4e72931fd3d2,croqueta,croqueta,tapas_clasicas,croqueta,1,1,1,1,0,0,1.0,0.0,0.0,0.8600,0.0,0.0000,0.8600,0.4819,0.2591,1.0,1.0000,1.6709,1.6709,0.8600,0.8600,1,0,1.0000,0.0000,0,0,0,1,0,"[contrast_marker_nearby, intensifier_nearby]",5.00,5.0,5.0,"Es difícil destacar algo de la carta , ya que todo estaba muy bueno , pero las albóndigas , las croquetas y la carrillada estaban excelentes .",,
3,0046efb9-63e6-4eb0-8d95-0f93b585dbcc,Bar Pino,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,73b4ba41-1e8f-41b1-aa2a-fe7975470132,PINO FLORES,dish_es_v1_4c5e83397f7a5a82,albóndigas,albondigas,carne,carne,1,1,1,1,0,0,1.0,0.0,0.0,0.8600,0.0,0.0000,0.8600,0.4819,0.2591,1.0,1.0000,1.6709,1.6709,0.8600,0.8600,1,0,1.0000,0.0000,0,0,0,1,0,"[contrast_marker_nearby, intensifier_nearby]",5.00,5.0,5.0,"Es difícil destacar algo de la carta , ya que todo estaba muy bueno , pero las albóndigas , las croquetas y la carrillada estaban excelentes .",,
4,0046efb9-63e6-4eb0-8d95-0f93b585dbcc,Bar Pino,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,73b4ba41-1e8f-41b1-aa2a-fe7975470132,PINO FLORES,dish_es_v1_c325d21226b882b6,patatas bravas,patatas bravas,fritos_y_raciones,patatas,1,1,1,1,0,0,1.0,0.0,0.0,0.9000,0.0,0.0000,0.9000,0.4872,0.2564,1.0,1.0000,1.5340,1.5340,0.9000,0.9000,1,0,1.0000,0.0000,0,0,0,0,0,[],4.00,4.0,4.0,Recomiendo las patatas bravas y el serranito.,,
5,0061925b-3bc8-41fd-8bef-78ebdc871a31,Bar Hiniesta,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,e554ef0e-d9f1-4d89-8777-f92cee028f7f,SAN JULIAN,dish_es_v1_10850a8a8e314902,ensaladilla,ensaladilla,tapas_clasicas,ensaladilla,3,1,1,0,0,3,0.0,0.0,1.0,0.0000,0.0,0.9703,0.9703,0.2519,0.4963,-1.0,-1.0000,-1.6000,-2.1996,0.5467,0.3234,1,2,0.3333,0.6667,2,0,1,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, price_context_detected]",1.00,1.0,1.0,,"Adjunto foto) Paco, hay que tener la cara dura, y la tuya sirve de cimiento para decirme que tienes ensaladilla y traerme eso.",
6,0061925b-3bc8-41fd-8bef-78ebdc871a31,Bar Hiniesta,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,e554ef0e-d9f1-4d89-8777-f92cee028f7f,SAN JULIAN,dish_es_v1_441a6825f6a625c7,pringá,pringa,tapas_clasicas,pringa,1,1,1,1,0,0,1.0,0.0,0.0,0.8100,0.0,0.0000,0.8100,0.4751,0.2625,1.0,1.0000,1.0000,1.0000,0.8100,0.8100,1,0,1.0000,0.0000,0,0,0,0,0,[],5.00,5.0,5.0,Nos acercamos por el buen ambiente y cenamos estupendo con sus tapas y montaito de pringa!,,
7,0061925b-3bc8-41fd-8bef-78ebdc871a31,Bar Hiniesta,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,e554ef0e-d9f1-4d89-8777-f92cee028f7f,SAN JULIAN,dish_es_v1_874ae3f6474ddd47,ensalada de patatas,ensalada de patatas,fritos_y_raciones,patatas,1,1,1,0,0,1,0.0,0.0,1.0,0.0000,0.0,0.1079,0.1079,0.3218,0.3565,-1.0,-1.0000,-1.1500,-1.1500,0.3600,0.1079,0,1,0.0000,1.0000,1,0,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal]",1.00,1.0,1.0,,La ensalada de patatas rebozando en aceite!!!,
8,0061925b-3bc8-41fd-8bef-78ebdc871a31,Bar Hiniesta,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,e554ef0e-d9f1-4d89-8777-f92cee028f7f,SAN JULIAN,dish_es_v1_9a1e795ae0c1d04f,hamburguesa,hamburguesa,carne,carne,1,1,1,0,0,1,0.0,0.0,1.0,0.0000,0.0,0.1079,0.1079,0.3218,0.3565,-1.0,-1.0000,-1.1500,-1.1500,0.3600,0.1079,0,1,0.0000,1.0000,1,0,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal]",1.00,1.0,1.0,,Tenía que haber ido al Burger King de la esquina.,
9,0061925b-3bc8-41fd-8bef-78ebdc871a31,Bar Hiniesta,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,e554ef0e-d9f1-4d89-8777-f92cee028f7f,SAN JULIAN,dish_es_v1_ad3755cf6fd0fb67,atún,atun,mar_y_pescado,pescado,4,2,2,2,0,2,0.5,0.0,0.5,1.0179,0.0,0.2159,1.2338,0.4766,0.2872,0.0,0.6501,0.1685,1.4397,0.4975,0.3085,1,3,0.2500,0.7500,3,0,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal]",1.75,1.0,4.0,El maravilloso atún encebollado que he visto en las reseñas es otra basura de la casa.,"Dice que mañana lo trae (jajajajajaja) Le pido una ensaladilla que creo que todo el mundo sabe de que se compone (atún, mayonesa, huevo, guisante, patatas, y zanahoria) y me po...",

In [10]:
# ============================================================
# 06. Tiers de evidencia, calidad y scoring preliminar
# ============================================================

def assign_evidence_tier(row: pd.Series) -> str:
    mention_count = int(row["mention_count"])
    review_count = int(row["review_count"])
    avg_conf = float(row["avg_sentiment_confidence"])
    local_ratio = float(row["local_context_ratio"])

    if mention_count >= 5 and review_count >= 4 and avg_conf >= 0.58 and local_ratio >= 0.45:
        return "strong"
    if mention_count >= 3 and review_count >= 2 and avg_conf >= 0.52:
        return "solid"
    if mention_count >= 2 and review_count >= 2 and avg_conf >= 0.45:
        return "emerging"
    return "weak"


def assign_signal_quality_tier(row: pd.Series) -> str:
    evidence = row["evidence_tier_v1"]
    negative_ratio = float(row["negative_ratio"])
    fallback_ratio = float(row["fallback_ratio"])
    service_count = int(row["service_flag_count"])
    price_count = int(row["price_flag_count"])
    mention_count = int(row["mention_count"])

    if evidence == "strong" and negative_ratio <= 0.25 and fallback_ratio <= 0.60:
        return "high_quality_signal"
    if evidence in {"strong", "solid"} and negative_ratio <= 0.35:
        return "usable_signal"
    if evidence == "emerging" and negative_ratio <= 0.40:
        return "emerging_signal"
    if mention_count == 1:
        return "single_mention_signal"
    if service_count > 0 or price_count > 0:
        return "noisy_signal"
    return "weak_signal"


def compute_preliminary_signal_score(row: pd.Series) -> float:
    sentiment_component = sigmoid_like(float(row["weighted_sentiment_score"]), scale=2.6)
    positive_component = clip01(float(row["smoothed_positive_ratio"]))
    negative_penalty = 1.0 - clip01(float(row["smoothed_negative_ratio"]) * 1.35)

    evidence_component = clip01(math.log1p(float(row["review_count"])) / math.log1p(6.0))
    mention_component = clip01(math.log1p(float(row["mention_count"])) / math.log1p(8.0))
    confidence_component = clip01(float(row["avg_sentiment_confidence"]))
    local_context_component = clip01(float(row["local_context_ratio"]))

    fallback_penalty = 1.0 - 0.18 * clip01(float(row["fallback_ratio"]))
    service_penalty = 0.92 if int(row["service_flag_count"]) > 0 else 1.0
    price_penalty = 0.94 if int(row["price_flag_count"]) > 0 else 1.0

    base = (
        0.28 * sentiment_component
        + 0.22 * positive_component
        + 0.20 * evidence_component
        + 0.10 * mention_component
        + 0.12 * confidence_component
        + 0.08 * local_context_component
    )

    return round(float(max(0.0, min(100.0, 100.0 * base * negative_penalty * fallback_penalty * service_penalty * price_penalty))), 4)


place_dish_signals["evidence_tier_v1"] = place_dish_signals.apply(assign_evidence_tier, axis=1)
place_dish_signals["signal_quality_tier_v1"] = place_dish_signals.apply(assign_signal_quality_tier, axis=1)
place_dish_signals["preliminary_signal_score_v1"] = place_dish_signals.apply(compute_preliminary_signal_score, axis=1)

place_dish_signals["ranking_ready_v1"] = (
    (place_dish_signals["mention_count"] >= 2)
    & (place_dish_signals["review_count"] >= 2)
    & (place_dish_signals["negative_ratio"] <= 0.45)
    & (place_dish_signals["avg_sentiment_confidence"] >= 0.45)
    & (place_dish_signals["weighted_sentiment_score"] > -0.25)
)


def assign_candidate_tier(row: pd.Series) -> str:
    if not bool(row["ranking_ready_v1"]):
        return "not_ready"

    score = float(row["preliminary_signal_score_v1"])
    evidence = row["evidence_tier_v1"]
    pos = float(row["positive_ratio"])
    neg = float(row["negative_ratio"])

    if evidence == "strong" and score >= 72 and pos >= 0.70 and neg <= 0.20:
        return "strong_candidate"
    if evidence in {"strong", "solid"} and score >= 64 and pos >= 0.62 and neg <= 0.30:
        return "promising_candidate"
    if evidence in {"solid", "emerging"} and score >= 55:
        return "weak_candidate"
    return "not_ready"


place_dish_signals["candidate_tier_v1"] = place_dish_signals.apply(assign_candidate_tier, axis=1)

place_dish_signals = place_dish_signals.sort_values(
    ["ranking_ready_v1", "preliminary_signal_score_v1", "mention_count", "positive_ratio"],
    ascending=[False, False, False, False],
).reset_index(drop=True)

print("Evidence tier counts:")
display(place_dish_signals["evidence_tier_v1"].value_counts())

print("Candidate tier counts:")
display(place_dish_signals["candidate_tier_v1"].value_counts())

display(place_dish_signals.head(30))

Evidence tier counts:

evidence_tier_v1
weak        1909
emerging     215
solid         76
strong        12
Name: count, dtype: int64

Candidate tier counts:

candidate_tier_v1
not_ready         2205
weak_candidate       7
Name: count, dtype: int64

,place_id,place_name,district_id,district_name,neighborhood_id,neighborhood_name,dish_id_v1,display_dish_name_es_v1,normalized_dish_name_es_v1,dish_family_es_v1,dish_group_es_v1,mention_count,review_count,source_review_count,positive_count,neutral_count,negative_count,positive_ratio,neutral_ratio,negative_ratio,weighted_positive_count,weighted_neutral_count,weighted_negative_count,total_signal_weight,smoothed_positive_ratio,smoothed_negative_ratio,avg_sentiment_value,weighted_sentiment_value,avg_sentiment_score,weighted_sentiment_score,avg_sentiment_confidence,avg_aggregation_weight,local_context_count,review_prior_fallback_count,local_context_ratio,fallback_ratio,low_confidence_flag_count,service_flag_count,price_flag_count,contrast_flag_count,negation_flag_count,top_sentiment_flags_v1,avg_rating,min_rating,max_rating,example_positive_context_v1,example_negative_context_v1,example_neutral_context_v1,evidence_tier_v1,signal_quality_tier_v1,preliminary_signal_score_v1,ranking_ready_v1,candidate_tier_v1
0,52d0c5c7-da1f-4733-a8a1-6d3fcac2d18d,restaurante asiático shan,e1621557-0db9-443a-8065-2fbcb8a9515f,Bellavista - La Palmera,7040f0c8-e891-4ff2-ac79-044be0f73fff,BELLAVISTA,dish_es_v1_451dcf9913bf3b32,sushi,sushi,internacional,internacional,3,3,3,3,0,0,1.0000,0.0000,0.0,2.8500,0.0000,0.0,2.8500,0.6581,0.1709,1.0000,1.0000,4.9497,4.9497,0.9500,0.9500,3,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],5.0000,5.0,5.0,"Comida riquísima, el sushi flambeado y el yakisoba muy bueno.",,,solid,usable_signal,62.9487,True,weak_candidate
1,9b6cc82a-5140-4158-98e4-0b2110ec92bf,Il Ristorantino Dell´Avvocato Sevilla,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,ae182ebc-43a4-46db-9364-d006cf3a73c9,ENCARNACIÓN-REGINA,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,9,5,5,7,2,0,0.7778,0.2222,0.0,4.8419,0.1679,0.0,5.0098,0.7293,0.1248,0.7778,0.9665,1.6851,2.4826,0.6578,0.5566,5,4,0.5556,0.4444,4,0,0,1,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, neutral_or_ambiguous_terms_detected, contrast_...",4.2222,3.0,5.0,"Como platos principales pedimos pizzas, y fue todo un acierto: una fuera de carta con guiso de carne, increíblemente sabrosa y diferente, y otra de carta, ahumada, con un sabor...",,"Llegamos con ganas de comer una pizza y una bola de arroz rellena de carne y salsa, para nuestra sorpresa nos sentamos en mesa y nos dicen que solo hacen pizza, igual habrá que...",strong,high_quality_signal,62.1079,True,not_ready
2,a3db8f79-3216-4c52-8307-7730e9335737,Tarannà,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,903feb9b-aed1-4717-abbf-e693ac5585a0,SANTA CATALINA,dish_es_v1_ad3755cf6fd0fb67,atún,atun,mar_y_pescado,pescado,3,3,3,3,0,0,1.0000,0.0000,0.0,2.6075,0.0000,0.0,2.6075,0.6433,0.1783,1.0000,1.0000,3.1247,3.3604,0.8692,0.8692,3,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],4.6667,4.0,5.0,Tomamos un tartar de atún de almadraba súper recomendable y un arroz súper jugoso.,,,solid,usable_signal,60.1190,True,weak_candidate
3,ea7d6564-2b10-4bef-97e9-f91cfb33d342,Pizzería San Pablo,898f9d9e-9365-4138-a30e-d8183ddfa969,San Pablo - Santa Justa,f36f071a-eedf-4022-adcb-a0d67a0ccf28,SAN PABLO D Y E,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,6,5,5,6,0,0,1.0000,0.0000,0.0,4.4098,0.0000,0.0,4.4098,0.7301,0.1350,1.0000,1.0000,4.6146,5.3569,0.8350,0.7350,5,1,0.8333,0.1667,1,1,1,0,0,"[intensifier_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, price_context_detected, sentiment_may_refer_to...",5.0000,5.0,5.0,"Unas experiencia muy buena la pizza 10 de 10 me encanto, esta vez fue la carnivora y seguiré probando las demás pizza q tienen, 100 % recomendados",,,strong,high_quality_signal,60.0726,True,not_ready
4,1844aa47-4f98-47f5-a31d-0f5565cd4990,ALCÁZAR ANDALUSÍ TAPAS,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,dd0845a6-120f-4945-9a3d-ec166c36337c,FERIA,dish_es_v1_ad3755cf6fd0fb67,atún,atun,mar_y_pescado,pescado,3,3,3,3,0,0,1.0000,0.0000,0.0,2.8000,0.0000,0.0,2.8000,0.6552,0.1724,1.0000,1.0000,2.1607,2.1740,0.9333,0.9333,3,0,1.0000,0.0000,0,0,0,0,0,[],5.0000,5.0,5.0,mida estaba deliciosa. Recomiendo encarecidamente: - La berenjena con queso de cabra y miel. - Risotto. - Croquetas. - Ensaladilla. - Tataki de atún. - Tarta de naranja y choco...,,,solid,usable_signal,59.6501,True,weak_candidate
5,1aca2d21-7dbe-4269-b360-889b689724e9,Taberna Los Terceros,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,903feb9b-aed1-4717-abbf-e693ac5585a0,SANTA CATALINA,dish_es_v1_0a420a9251bb5aed,solomillo al whisky,solomillo al whisky,tapas_clasicas,solomillo,5,3,3,5,0,0,1.0000,0.0000,0.0,3.7379,0.0000,0.0,3.7379,0.7032,0.1484,1.0000,1.0000,1.9054,2.0695,0.7980,0.7476,4,1,0.8000,0.2000,1,0,0,1,1,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marker_nearby, intensifier_nearby, mixed_local_evidence, ...",4.4000,4.0,5.0,"Taberna típica de Sevilla, fuimos porque era de los pocos lugares que tenían sitio en la terraza y pedimos unos chocos (12€) y un solomillo al whisky (12€) el solomillo estaba ...",,,solid,usable_signal,59.4452,True,weak_candidate
6,2cf94026-9350-4b2c-abf1-54a08af310d3,BAR EL BUCHITO,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,2a3957f2-7a2e-4d5f-aab7-7ae541c9c030,PALMETE,dish_es_v1_2c67f67ce386e9d6,carrillada,carrillada,tapas_clasicas,carrillada,3,2,2,3,0,0,1.0000,0.0000,0.0,2.7700,0.0000,0.0,2.7700,0.6534,0.1733,1.0000,1.0000,2.6153,2.6099,0.9233,0.9233,3,0,1.0000,0.0000,0,0,0,2,0,[contrast_marker_nearby],5.0000,5.0,5.0,"Su carrillada está buenísima, Recomendadismo.",,,solid,usable_signal,58.0201,True,weak_candidate
7,4cd9688c-15bf-4a33-bcb9-56d0c20e0f81,Bar BOCACHICA,22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,4cc93289-8e5d-4379-8ca1-74cacb5f263a,EL PORVENIR,dish_es_v1_10850a8a8e314902,ensaladilla,ensaladilla,tapas_clasicas,ensaladilla,5,3,3,5,0,0,1.0000,0.0000,0.0,3.5079,0.0000,0.0,3.5079,0.6927,0.1537,1.0000,1.0000,1.4674,1.6142,0.7520,0.7016,4,1,0.8000,0.2000,1,0,0,2,1,"[contrast_marker_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, mixed_local_evidence, ...",4.6000,4.0,5.0,"Hace una semana fuí con un amigo, cenamos muy bien, la ensaladilla, el tartar de atún, las croquetas, todo buenísimo.",,,solid,usable_signal,57.1380,True,weak_candidate
8,56979254-f513-4d56-84c0-bf27dd97806e,Il Ristorantino Dell'Avvocato Calle Cuna,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,282de85f-269a-4337-a3b8-75d8ac5fa1ea,ALFALFA,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,5,4,4,5,0,0,1.0000,0.0000,0.0,3.5415,0.0000,0.0,3.5415,0.6943,0.1529,1.0000,1.0000,2.3963,2.7308,0.8080,0.7083,4,1,0.8000,0.2000,1,1,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, sentiment_may_refer_to_service]",5.0000,5.0,5.0,"Muy rico todo, probamos las pizzas que tienen en carta y fuera de carta, buenísima calidad y sabor.",,,strong,high_quality_signal,57.0188,True,not_ready
9,b1cba103-51cb-48de-93ba-a1f027b2f67f,Mama Döner Kebab,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,ec7b7bef-c772-438a-9318-cc5ee459a6b9,CRUZ ROJA-CAPUCHINOS,dish_es_v1_11a773a1c774fd47,kebab,kebab,internacional,internacional,5,3,3,5,0,0,1.0000,0.0000,0.0,3.0159,0.0000,0.0,3.0159,0.6675,0.1662,1.0000,1.0000,2.6770,3.5506,0.7040,0.6032,3,2,0.6000,0.4000,2,0,0,1,0,"[intensifier_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marker_nearby]",5.0000,5.0,5.0,"La primera vez que pido kebab y lo volveré a hacer, super rico de sabor y buena calidad.",,,solid,usable_signal,55.1525,True,weak_candidate
10,a9ae2e43-3b1e-4239-9b74-6ae0bd0d47a4,Bodega Mi Tierra,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,cbd5d9b1-32f4-4ca8-98af-368b91f83c4a,SANTA AURELIA-CANTABRICO-ATLANTICO-LA ROMERIA,dish_es_v1_d130c191c0bc5a8e,torrija,torrija,postres_y_desayunos,postre,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,4.5790,4.5790,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[],5.0000,5.0,5.0,Carne de gran calidad y la torrija del postre increíble.,,,emerging,emerging_signal,54.9926,True,not_ready
11,28f6f03a-81a7-421d-af2b-b29b1f8e4137,Bar Casa Aldana,6af93f2e-b5da-4456-9cb1-e68958a97dbf,Nervión,3752a9a8-1236-43ad-8256-fed6ffad110f,CIUDAD JARDIN,dish_es_v1_2c67f67ce386e9d6,carrillada,carrillada,tapas_clasicas,carrillada,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,4.4557,4.4557,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],4.5000,4.0,5.0,"La carrillada ibérica es la estrella: melosa, muy sabrosa y con una salsa para mojar pan sin pensar.",,,emerging,emerging_signal,54.9366,True,not_ready
12,92a1858e-5d69-4b4f-899a-868482838841,Bar - Terraza La Cucamona,e1621557-0db9-443a-8065-2fbcb8a9515f,Bellavista - La Palmera,2996d82c-71b5-44bf-908d-c6eaef8f7b6c,ELCANO-BERMEJALES,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,4.0716,4.0716,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],4.5000,4.0,5.0,"s) muy bueno bien preparado y acompañado de muchas patatas, pastela nos gustó también y pocos sitios la preparan y los postres la tarta de queso exquisita.",,,emerging,emerging_signal,54.7265,True,not_ready
13,5f78cb03-a338-44a8-bee7-55d64248fcc0,Restaurante DepiKofino,6af93f2e-b5da-4456-9cb1-e68958a97dbf,Nervión,b63a69e4-c0a5-4a2b-b936-97511845b8d8,HUERTA DEL PILAR,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,3.7170,3.7170,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[],4.5000,4.0,5.0,La ensaladilla con caballa estaba rica también y su tarta de quedo con lotus nos dejó buen sabor de boca.,,,emerging,emerging_signal,54.4749,True,not_ready
14,a9bce0ce-f0c5-419b-91ee-cd125258adc0,Bar Restaurante La Cochera,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,7feeccb6-1f5d-47c2-a067-02dc6466c762,EL CERRO,dish_es_v1_2c67f67ce386e9d6,carrillada,carrillada,tapas_clasicas,carrillada,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8200,0.0000,0.0,1.8200,0.5851,0.2075,1.0000,1.0000,5.4561,5.4272,0.9100,0.9100,2,0,1.0000,0.0000,0,0,0,1,0,"[intensifier_nearby, contrast_marker_nearby]",3.5000,3.0,4.0,"En una de las visitas pedimos como principal la paella de queso de cabra y carrillera, original y con muchísimo sabor, y en la otra ocasión la picaña, que estaba buenísima, en ...",,,emerging,emerging_signal,54.4655,True,not_ready
15,e1180051-384f-44e1-be00-faf7c54475a1,"Venta Campo Rico ""El Arriero""",af2fbf25-5491-4c27-811f-28b7a400ea84,Norte,77dcf0db-e6d2-4f97-b9df-fc3477fe2b0f,VALDEZORRAS,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8345,0.0000,0.0,1.8345,0.5863,0.2068,1.0000,1.0000,4.4420,4.5543,0.9172,0.9172,2,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],5.0000,5.0,5.0,"La comida estuvo espectacular: la carne, especialmente la presa ibérica de bellota, estaba muy buena, el revuelto de la casa nos encantó y la tarta de queso estaba buenísima.",,,emerging,emerging_signal,54.3343,True,not_ready
16,c93f6669-5e46-4079-b296-b6bb6410a0e3,Flor de la Caña Café y Ron SR.,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,bb03aa4d-9154-4b66-9292-529710ed9248,LEON XIII-LOS NARANJOS,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,3,3,3,3,0,0,1.0000,0.0000,0.0,2.4036,0.0000,0.0,2.4036,0.6299,0.1851,1.0000,1.0000,2.9120,3.1411,0.8833,0.8012,3,0,1.0000,0.0000,0,1,0,0,1,"[mixed_local_evidence, negation_detected, intensifier_nearby, sentiment_may_refer_to_service]",5.0000,5.0,5.0,Fuimos para comer y pedimos aborrajado macho y papá de pollo más arepas de guacamole todo super rico y casero y de postre tarta de Papayas deliciosa.,,,solid,usable_signal,54.3255,True,not_ready
17,1844aa47-4f98-47f5-a31d-0f5565cd4990,ALCÁZAR ANDALUSÍ TAPAS,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,dd0845a6-120f-4945-9a3d-ec166c36337c,FERIA,dish_es_v1_10850a8a8e314902,ensaladilla,ensaladilla,tapas_clasicas,ensaladilla,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,3.3580,3.3580,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[],5.0000,5.0,5.0,bien y la comida estaba deliciosa. Recomiendo encarecidamente: - La berenjena con queso de cabra y miel. - Risotto. - Croquetas. - Ensaladilla. - Tataki de atún. - Tarta de nar...,,,emerging,emerging_signal,54.1498,True,not_ready
18,a268a2e5-a430-4b13-9429-c7a356709b1b,"Cafeteria mi abuela, churreria",22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,fb5a5f48-54e9-49ac-9026-fc7d6cae69f5,FELIPE II-LOS DIEZ MANDAMIENTOS,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,6,5,5,6,0,0,1.0000,0.0000,0.0,3.5198,0.0000,0.0,3.5198,0.6932,0.1534,1.0000,1.0000,1.2724,1.3650,0.6928,0.5866,4,2,0.6667,0.3333,2,0,1,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, price_context_detected, intensifier_nearby]",5.0000,5.0,5.0,"Mi mujer y mis niños se han pedido churros con chocolate y estaban riquísimos, churros como hacía tiempo que no los comia, y yo una entera con jamón y café, y lo mismo el jamón...",,,strong,high_quality_signal,53.8855,True,not_ready
19,a8f8ab69-ba78-4de2-b3d5-4c055145b30c,El Sofrito Restaurante,7f42c0b3-14d1-400c-bcde-c128faafc4c5,Este - Alcosa - Torreblanca,9a832993-14ed-4c5a-b3f9-0ba3ef3898b6,"COLORES, ENTREPARQUES",dish_es_v1_10850a8a8e314902,ensaladilla,ensaladilla,tapas_clasicas,ensaladilla,5,4,4,5,0,0,1.0000,0.0000,0.0,2.8859,0.0000,0.0,2.8859,0.6602,0.1699,1.0000,1.0000,1.6400,1.9129,0.6780,0.5772,3,2,0.6000,0.4000,2,0,0,1,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, contrast_marker_nearby]",4.0000,1.0,5.0,"Ensaladilla picante buena, vieras pequeñas como almejas y muy hechas, ternera muy buena.",,,strong,high_quality_signal,53.5852,True,not_ready
20,d509374b-4fdf-4f83-a4c2-039d123e9baf,Las Golondrinas - Pagés del Corro,f9420edb-f021-42df-a2cc-e4bb21d0eceb,Triana,400ec702-65c5-4abb-835e-687ae82ea50c,TRIANA OESTE,dish_es_v1_0a420a9251bb5aed,solomillo al whisky,solomillo al whisky,tapas_clasicas,solomillo,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8600,0.0000,0.0,1.8600,0.5885,0.2058,1.0000,1.0000,3.1976,3.1867,0.9300,0.9300,2,0,1.0000,0.0000,0,0,0,1,0,"[contrast_marker_nearby, intensifier_nearby]",5.0000,5.0,5.0,"Pedimos puntas de solomillo, muy ricas; la ensaladilla rusa, muy buena; 2 tapas de pisto con bacalao, ricas; y ""caballitos"" que son unas tostas con jamón de bodega frito, se as...",,,emerging,emerging_signal,53.5683,True,not_ready
21,6ee0277a-c373-4d0d-94bc-f7d90766cdc2,I Love Churros - Cafetería churreria en Ronda de Capuchinos,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,ec7b7bef-c772-438a-9318-cc5ee459a6b9,CRUZ ROJA-CAPUCHINOS,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,8,5,5,7,1,0,0.8750,0.1250,0.0,3.5914,0.4800,0.0,4.0714,0.6493,0.1414,0.8750,0.8821,1.3752,1.6476,0.6325,0.5089,5,3,0.6250,0.3750,3,1,0,3,0,"[contrast_marker_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, sentiment_may_refer_to...",4.7500,3.0,5.0,Increíble lugar para comer churros y chocolate!,,"El chocolate y los churros normal, nada extraordinario pero están buenos.",strong,high_quality_signal,53.5446,True,not_ready
22,d509374b-4fdf-4f83-a4c2-039d123e9baf,Las Golondrinas - Pagés del Corro,f9420edb-f021-42df-a2cc-e4bb21d0eceb,Triana,400ec702-65c5-4abb-835e-687ae82ea50c,TRIANA OESTE,dish_es_v1_b9512e58dcc6d376,bacalao,bacalao,mar_y_pescado,pescado,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8600,0.0000,0.0,1.8600,0.5885,0.2058,1.0000,1.0000,3.1647,3.1618,0.9300,0.9300,2,0,1.0000,0.0000,0,0,0,1,0,"[contrast_marker_nearby, intensifier_nearby]",5.0000,5.0,5.0,"Pedimos puntas de solomillo, muy ricas; la ensaladilla rusa, muy buena; 2 tapas de pisto con bacalao, ricas; y ""caballitos"" que son unas tostas con jamón de bodega frito, se as...",,,emerging,emerging_signal,53.5398,True,not_ready
23,1b707bbc-35d9-4f6b-b588-31d4b14b3758,Casa Mikva,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,602844e3-9beb-4493-8041-bec4973baf25,SAN BARTOLOME,dish_es_v1_ad3755cf6fd0fb67,atún,atun,mar_y_pescado,pescado,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8500,0.0000,0.0,1.8500,0.5876,0.2062,1.0000,1.0000,3.1860,3.2338,0.9250,0.9250,2,0,1.0000,0.0000,0,0,0,0,0,[],5.0000,5.0,5.0,"La comida espectacular, especialmente el tartar de atún rojo de almadraba, que estaba increíble, o la pluma ibérica , que se deshacía en la boca.",,,emerging,emerging_signal,53.5234,True,not_ready
24,752f92eb-5ae7-462c-8f6b-ecb42d52f4d3,La Sra Pop,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,dd0845a6-120f-4945-9a3d-ec166c36337c,FERIA,dish_es_v1_d35dbc1062811528,helado,helado,postres_y_desayunos,postre,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8050,0.0000,0.0,1.8050,0.5838,0.2081,1.0000,1.0000,3.5305,3.6543,0.9025,0.9025,2,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],5.0000,5.0,5.0,"Probe la torrija con helado y lotus, increible deliciosa, mi amigo se pidió un cafe irlandés le gustó mucho tambien y yo tambien pedí un batido de kinder muy bueno.",,,emerging,emerging_signal,53.4816,True,not_ready
25,57bffbe1-1549-4913-9a38-321760dedc4a,Pinsería Il Forno - Restaurante Italiano,898f9d9e-9365-4138-a30e-d8183ddfa969,San Pablo - Santa Justa,b088f223-bf70-4403-b939-12e3a81b216a,EL FONTANAL-MARIA AUXILIADORA-CARRETERA DE CARMONA,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8500,0.0000,0.0,1.8500,0.5876,0.2062,1.0000,1.0000,2.9190,2.9596,0.9250,0.9250,2,0,1.0000,0.0000,0,0,0,0,0,[],5.0000,5.0,5.0,"La masa de la pizza es una locura, crujiente y esponjosa a la vez con un sabor genial, se nota que utilizan productos de buena calidad.",,,emerging,emerging_signal,53.1932,True,not_ready
26,a9bce0ce-f0c5-419b-91ee-cd125258adc0,Bar Restaurante La Cochera,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,7feeccb6-1f5d-47c2-a067-02dc6466c762,EL CERRO,dish_es_v1_10850a8a8e314902,ensaladilla,ensaladilla,tapas_clasicas,ensaladilla,2,2,2,2,0,0,1.0000,0.0000,0.0,1.7550,0.0000,0.0,1.7550,0.5794,0.2103,1.0000,1.0000,3.9437,3.9211,0.8775,0.8775,2,0,1.0000,0.0000,0,0,0,1,0,"[contrast_marker_nearby, intensifier_nearby]",4.0000,3.0,5.0,"Tanto la ensaladilla, como el queso frito, las croquetas y el pan brioche son cosas que recomiendo.",,,emerging,emerging_signal,53.1778,True,not_ready
27,ad959ed9-fa16-444b-8570-30ff9755233d,Sansa Café,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,ae182ebc-43a4-46db-9364-d006cf3a73c9,ENCARNACIÓN-REGINA,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,2.5340,2.5340,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],5.0000,5.0,5.0,"Pedimos dos cafes con leche de avena, la tarta flora y un oh baby mini y estaba todo delicioso.",,,emerging,emerging_signal,53.0462,True,not_ready

In [11]:
# ============================================================
# 07. Señales globales por plato
# ============================================================

def aggregate_global_dish(group: pd.DataFrame) -> pd.Series:
    total = len(group)
    pos = int((group["mention_sentiment_label_v1"] == "positive").sum())
    neg = int((group["mention_sentiment_label_v1"] == "negative").sum())
    neu = int((group["mention_sentiment_label_v1"] == "neutral").sum())

    weights = group["aggregation_weight_v1"].fillna(0.05).clip(lower=0.03)
    weighted_score = float(np.average(group["mention_sentiment_score_v1"].fillna(0.0), weights=weights)) if total else 0.0

    return pd.Series({
        "global_mention_count": int(total),
        "global_review_count": int(group["review_id"].nunique(dropna=True)),
        "global_place_count": int(group["place_id"].nunique(dropna=True)),
        "global_neighborhood_count": int(group["neighborhood_id"].nunique(dropna=True)),
        "global_district_count": int(group["district_id"].nunique(dropna=True)),
        "global_positive_count": pos,
        "global_neutral_count": neu,
        "global_negative_count": neg,
        "global_positive_ratio": round(pos / total, 4) if total else 0.0,
        "global_negative_ratio": round(neg / total, 4) if total else 0.0,
        "global_weighted_sentiment_score": round(weighted_score, 4),
        "global_avg_confidence": round(float(group["mention_sentiment_confidence_v1"].fillna(0.0).mean()), 4),
        "global_avg_rating": round(float(group["rating_value"].fillna(0.0).mean()), 4),
    })


global_dish_signals = (
    df.groupby([
        "dish_id_v1", "display_dish_name_es_v1", "normalized_dish_name_es_v1",
        "dish_family_es_v1", "dish_group_es_v1",
    ], dropna=False)
    .apply(aggregate_global_dish)
    .reset_index()
)

max_mentions = max(float(global_dish_signals["global_mention_count"].max()), 1.0)
global_dish_signals["global_popularity_score_v1"] = global_dish_signals["global_mention_count"].apply(
    lambda x: round(math.log1p(float(x)) / math.log1p(max_mentions), 4)
)

global_dish_signals["global_dish_signal_score_v1"] = global_dish_signals.apply(
    lambda row: round(
        100.0 * (
            0.35 * sigmoid_like(float(row["global_weighted_sentiment_score"]), scale=2.6)
            + 0.25 * clip01(float(row["global_positive_ratio"]))
            + 0.20 * clip01(math.log1p(float(row["global_place_count"])) / math.log1p(20.0))
            + 0.10 * clip01(float(row["global_avg_confidence"]))
            + 0.10 * clip01(math.log1p(float(row["global_neighborhood_count"])) / math.log1p(20.0))
        ),
        4,
    ),
    axis=1,
)

global_dish_signals = global_dish_signals.sort_values(
    ["global_mention_count", "global_dish_signal_score_v1"], ascending=[False, False]
).reset_index(drop=True)

display(global_dish_signals.head(30))

,dish_id_v1,display_dish_name_es_v1,normalized_dish_name_es_v1,dish_family_es_v1,dish_group_es_v1,global_mention_count,global_review_count,global_place_count,global_neighborhood_count,global_district_count,global_positive_count,global_neutral_count,global_negative_count,global_positive_ratio,global_negative_ratio,global_weighted_sentiment_score,global_avg_confidence,global_avg_rating,global_popularity_score_v1,global_dish_signal_score_v1
0,dish_es_v1_10850a8a8e314902,ensaladilla,ensaladilla,tapas_clasicas,ensaladilla,216.0,197.0,153.0,57.0,11.0,167.0,18.0,31.0,0.7731,0.1435,1.8679,0.6275,4.1806,1.0000,83.8813
1,dish_es_v1_3b8c4e72931fd3d2,croqueta,croqueta,tapas_clasicas,croqueta,211.0,198.0,160.0,61.0,11.0,166.0,17.0,28.0,0.7867,0.1327,1.6126,0.6072,4.3128,0.9957,82.8871
2,dish_es_v1_2c67f67ce386e9d6,carrillada,carrillada,tapas_clasicas,carrillada,172.0,152.0,123.0,62.0,11.0,149.0,12.0,11.0,0.8663,0.0640,2.2245,0.6390,4.4884,0.9579,87.6920
3,dish_es_v1_0a420a9251bb5aed,solomillo al whisky,solomillo al whisky,tapas_clasicas,solomillo,167.0,152.0,126.0,57.0,11.0,132.0,10.0,25.0,0.7904,0.1497,1.9356,0.6495,4.2096,0.9524,84.8121
4,dish_es_v1_ad3755cf6fd0fb67,atún,atun,mar_y_pescado,pescado,117.0,99.0,70.0,38.0,10.0,94.0,8.0,15.0,0.8034,0.1282,1.8923,0.7066,4.4017,0.8868,85.5311
5,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,114.0,100.0,81.0,38.0,11.0,96.0,9.0,9.0,0.8421,0.0789,2.0231,0.6626,4.4737,0.8820,86.5819
6,dish_es_v1_a646e68b8a85d929,montadito,montadito,tapas_clasicas,montadito,108.0,95.0,73.0,45.0,11.0,87.0,6.0,15.0,0.8056,0.1389,1.6205,0.5647,4.3981,0.8720,82.9715
7,dish_es_v1_c325d21226b882b6,patatas bravas,patatas bravas,fritos_y_raciones,patatas,105.0,98.0,76.0,42.0,11.0,83.0,7.0,15.0,0.7905,0.1429,1.4444,0.5900,4.1619,0.8668,81.9940
8,dish_es_v1_03d0d732fdd6fe23,gambas,gambas,mar_y_pescado,pescado,104.0,97.0,79.0,45.0,11.0,80.0,12.0,12.0,0.7692,0.1154,1.9001,0.6060,4.1635,0.8651,83.7023
9,dish_es_v1_9a1e795ae0c1d04f,hamburguesa,hamburguesa,carne,carne,90.0,75.0,51.0,36.0,11.0,63.0,8.0,19.0,0.7000,0.2111,1.3653,0.5821,3.9667,0.8385,79.2497
10,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,75.0,61.0,26.0,19.0,8.0,65.0,5.0,5.0,0.8667,0.0667,1.6206,0.5687,4.2400,0.8050,84.3792
11,dish_es_v1_f9e9b30ccbd51148,chocos,chocos,fritos_y_raciones,pescado,73.0,67.0,59.0,37.0,11.0,60.0,3.0,10.0,0.8219,0.1370,1.9002,0.6819,4.1918,0.8000,85.7792
12,dish_es_v1_d130c191c0bc5a8e,torrija,torrija,postres_y_desayunos,postre,70.0,68.0,56.0,36.0,11.0,64.0,3.0,3.0,0.9143,0.0429,2.5296,0.7199,4.5857,0.7923,90.6813
13,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,66.0,50.0,20.0,18.0,7.0,53.0,8.0,5.0,0.8030,0.0758,2.4492,0.6421,4.1818,0.7816,86.5497
14,dish_es_v1_86a018d9612ca5d5,presa ibérica,presa iberica,carne,carne,64.0,55.0,51.0,29.0,11.0,47.0,2.0,15.0,0.7344,0.2344,2.5061,0.6196,4.0156,0.7759,85.1111
15,dish_es_v1_b9512e58dcc6d376,bacalao,bacalao,mar_y_pescado,pescado,61.0,57.0,51.0,33.0,11.0,52.0,2.0,7.0,0.8525,0.1148,1.4073,0.6381,4.3607,0.7671,83.8376
16,dish_es_v1_1f3f390d900eacf3,pulpo,pulpo,mar_y_pescado,pescado,59.0,51.0,48.0,30.0,11.0,46.0,5.0,8.0,0.7797,0.1356,2.3982,0.6764,4.1525,0.7610,86.4794
17,dish_es_v1_3220110a84fa82fc,salmorejo,salmorejo,tapas_clasicas,salmorejo,59.0,55.0,50.0,29.0,9.0,48.0,2.0,9.0,0.8136,0.1525,1.9011,0.6306,4.0847,0.7610,85.0624
18,dish_es_v1_d35dbc1062811528,helado,helado,postres_y_desayunos,postre,58.0,51.0,46.0,32.0,11.0,47.0,3.0,8.0,0.8103,0.1379,1.6776,0.6277,4.1897,0.7579,83.9824
19,dish_es_v1_de134ff917cb0cb3,tortilla de patatas,tortilla de patatas,tapas_clasicas,patatas,58.0,55.0,44.0,27.0,9.0,38.0,7.0,13.0,0.6552,0.2241,1.5022,0.6237,3.8276,0.7579,79.2352
20,dish_es_v1_fdfff2d60e2bd29d,chicharrones,chicharrones,tapas_clasicas,chicharrones,57.0,48.0,30.0,26.0,9.0,50.0,1.0,6.0,0.8772,0.1053,1.5213,0.6254,4.5965,0.7547,84.8955
21,dish_es_v1_9379eb0a85f5d196,langostinos,langostinos,mar_y_pescado,pescado,43.0,41.0,36.0,25.0,11.0,36.0,5.0,2.0,0.8372,0.0465,1.4281,0.6096,4.4884,0.7034,83.2755
22,dish_es_v1_4c5e83397f7a5a82,albóndigas,albondigas,carne,carne,42.0,40.0,36.0,28.0,10.0,36.0,2.0,4.0,0.8571,0.0952,2.3960,0.7236,4.3810,0.6991,88.8794
23,dish_es_v1_84263b5b1b6b31fe,boquerones,boquerones,fritos_y_raciones,pescado,40.0,37.0,32.0,27.0,10.0,37.0,1.0,2.0,0.9250,0.0500,1.3493,0.5534,4.3500,0.6903,84.5047
24,dish_es_v1_57a313c317326691,calamares,calamares,fritos_y_raciones,pescado,38.0,34.0,31.0,23.0,11.0,26.0,3.0,9.0,0.6842,0.2368,1.0135,0.6456,4.0789,0.6810,77.5569
25,dish_es_v1_ecc7931d19b97943,rabo de toro,rabo de toro,carne,carne,37.0,36.0,32.0,20.0,11.0,35.0,1.0,1.0,0.9459,0.0270,2.3616,0.6264,4.9189,0.6761,90.0171
26,dish_es_v1_9dc4319c27f6479a,taco,taco,internacional,internacional,35.0,31.0,27.0,23.0,9.0,25.0,2.0,8.0,0.7143,0.2286,0.8890,0.5862,3.9714,0.6661,76.9804
27,dish_es_v1_ef17db539ca6b38d,patatas fritas,patatas fritas,fritos_y_raciones,patatas,32.0,29.0,28.0,21.0,10.0,19.0,3.0,10.0,0.5938,0.3125,-0.3527,0.5075,3.5000,0.6499,65.0605
28,dish_es_v1_441a6825f6a625c7,pringá,pringa,tapas_clasicas,pringa,31.0,27.0,26.0,20.0,10.0,28.0,1.0,2.0,0.9032,0.0645,1.7396,0.6851,4.4194,0.6442,87.1575
29,dish_es_v1_5d23a04ff8def966,risotto,risotto,arroces_y_pasta,risotto,29.0,29.0,26.0,19.0,9.0,26.0,1.0,2.0,0.8966,0.0690,2.7113,0.7625,4.3448,0.6322,91.0121

In [12]:
# ============================================================
# 08. Resúmenes territoriales y señales principales
# ============================================================

ranking_ready_df = place_dish_signals[place_dish_signals["ranking_ready_v1"]].copy()

summary_by_district = (
    ranking_ready_df.groupby(["district_id", "district_name"], dropna=False)
    .agg(
        place_dish_pair_count=("dish_id_v1", "count"),
        place_count=("place_id", "nunique"),
        dish_count=("dish_id_v1", "nunique"),
        total_mentions=("mention_count", "sum"),
        avg_preliminary_signal_score=("preliminary_signal_score_v1", "mean"),
        avg_positive_ratio=("positive_ratio", "mean"),
        avg_negative_ratio=("negative_ratio", "mean"),
        strong_candidate_count=("candidate_tier_v1", lambda x: int((x == "strong_candidate").sum())),
        promising_candidate_count=("candidate_tier_v1", lambda x: int((x == "promising_candidate").sum())),
        weak_candidate_count=("candidate_tier_v1", lambda x: int((x == "weak_candidate").sum())),
    )
    .reset_index()
    .sort_values(["place_dish_pair_count", "avg_preliminary_signal_score"], ascending=[False, False])
)

summary_by_neighborhood = (
    ranking_ready_df.groupby(["district_name", "neighborhood_id", "neighborhood_name"], dropna=False)
    .agg(
        place_dish_pair_count=("dish_id_v1", "count"),
        place_count=("place_id", "nunique"),
        dish_count=("dish_id_v1", "nunique"),
        total_mentions=("mention_count", "sum"),
        avg_preliminary_signal_score=("preliminary_signal_score_v1", "mean"),
        avg_positive_ratio=("positive_ratio", "mean"),
        avg_negative_ratio=("negative_ratio", "mean"),
        strong_candidate_count=("candidate_tier_v1", lambda x: int((x == "strong_candidate").sum())),
        promising_candidate_count=("candidate_tier_v1", lambda x: int((x == "promising_candidate").sum())),
        weak_candidate_count=("candidate_tier_v1", lambda x: int((x == "weak_candidate").sum())),
    )
    .reset_index()
    .sort_values(["place_dish_pair_count", "avg_preliminary_signal_score"], ascending=[False, False])
)

candidate_tier_summary = (
    place_dish_signals.groupby(["candidate_tier_v1", "evidence_tier_v1", "signal_quality_tier_v1"], dropna=False)
    .agg(
        pair_count=("dish_id_v1", "count"),
        mention_count=("mention_count", "sum"),
        review_count=("review_count", "sum"),
        avg_score=("preliminary_signal_score_v1", "mean"),
        avg_positive_ratio=("positive_ratio", "mean"),
        avg_negative_ratio=("negative_ratio", "mean"),
    )
    .reset_index()
    .sort_values(["candidate_tier_v1", "pair_count"], ascending=[True, False])
)

top_place_dish_signals = ranking_ready_df.sort_values(
    ["preliminary_signal_score_v1", "mention_count", "positive_ratio"], ascending=[False, False, False]
).head(200)

print("Ranking-ready pairs:", len(ranking_ready_df))
display(top_place_dish_signals.head(30))

print("District summary:")
display(summary_by_district.head(20))

Ranking-ready pairs: 256

,place_id,place_name,district_id,district_name,neighborhood_id,neighborhood_name,dish_id_v1,display_dish_name_es_v1,normalized_dish_name_es_v1,dish_family_es_v1,dish_group_es_v1,mention_count,review_count,source_review_count,positive_count,neutral_count,negative_count,positive_ratio,neutral_ratio,negative_ratio,weighted_positive_count,weighted_neutral_count,weighted_negative_count,total_signal_weight,smoothed_positive_ratio,smoothed_negative_ratio,avg_sentiment_value,weighted_sentiment_value,avg_sentiment_score,weighted_sentiment_score,avg_sentiment_confidence,avg_aggregation_weight,local_context_count,review_prior_fallback_count,local_context_ratio,fallback_ratio,low_confidence_flag_count,service_flag_count,price_flag_count,contrast_flag_count,negation_flag_count,top_sentiment_flags_v1,avg_rating,min_rating,max_rating,example_positive_context_v1,example_negative_context_v1,example_neutral_context_v1,evidence_tier_v1,signal_quality_tier_v1,preliminary_signal_score_v1,ranking_ready_v1,candidate_tier_v1
0,52d0c5c7-da1f-4733-a8a1-6d3fcac2d18d,restaurante asiático shan,e1621557-0db9-443a-8065-2fbcb8a9515f,Bellavista - La Palmera,7040f0c8-e891-4ff2-ac79-044be0f73fff,BELLAVISTA,dish_es_v1_451dcf9913bf3b32,sushi,sushi,internacional,internacional,3,3,3,3,0,0,1.0000,0.0000,0.0,2.8500,0.0000,0.0,2.8500,0.6581,0.1709,1.0000,1.0000,4.9497,4.9497,0.9500,0.9500,3,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],5.0000,5.0,5.0,"Comida riquísima, el sushi flambeado y el yakisoba muy bueno.",,,solid,usable_signal,62.9487,True,weak_candidate
1,9b6cc82a-5140-4158-98e4-0b2110ec92bf,Il Ristorantino Dell´Avvocato Sevilla,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,ae182ebc-43a4-46db-9364-d006cf3a73c9,ENCARNACIÓN-REGINA,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,9,5,5,7,2,0,0.7778,0.2222,0.0,4.8419,0.1679,0.0,5.0098,0.7293,0.1248,0.7778,0.9665,1.6851,2.4826,0.6578,0.5566,5,4,0.5556,0.4444,4,0,0,1,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, neutral_or_ambiguous_terms_detected, contrast_...",4.2222,3.0,5.0,"Como platos principales pedimos pizzas, y fue todo un acierto: una fuera de carta con guiso de carne, increíblemente sabrosa y diferente, y otra de carta, ahumada, con un sabor...",,"Llegamos con ganas de comer una pizza y una bola de arroz rellena de carne y salsa, para nuestra sorpresa nos sentamos en mesa y nos dicen que solo hacen pizza, igual habrá que...",strong,high_quality_signal,62.1079,True,not_ready
2,a3db8f79-3216-4c52-8307-7730e9335737,Tarannà,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,903feb9b-aed1-4717-abbf-e693ac5585a0,SANTA CATALINA,dish_es_v1_ad3755cf6fd0fb67,atún,atun,mar_y_pescado,pescado,3,3,3,3,0,0,1.0000,0.0000,0.0,2.6075,0.0000,0.0,2.6075,0.6433,0.1783,1.0000,1.0000,3.1247,3.3604,0.8692,0.8692,3,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],4.6667,4.0,5.0,Tomamos un tartar de atún de almadraba súper recomendable y un arroz súper jugoso.,,,solid,usable_signal,60.1190,True,weak_candidate
3,ea7d6564-2b10-4bef-97e9-f91cfb33d342,Pizzería San Pablo,898f9d9e-9365-4138-a30e-d8183ddfa969,San Pablo - Santa Justa,f36f071a-eedf-4022-adcb-a0d67a0ccf28,SAN PABLO D Y E,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,6,5,5,6,0,0,1.0000,0.0000,0.0,4.4098,0.0000,0.0,4.4098,0.7301,0.1350,1.0000,1.0000,4.6146,5.3569,0.8350,0.7350,5,1,0.8333,0.1667,1,1,1,0,0,"[intensifier_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, price_context_detected, sentiment_may_refer_to...",5.0000,5.0,5.0,"Unas experiencia muy buena la pizza 10 de 10 me encanto, esta vez fue la carnivora y seguiré probando las demás pizza q tienen, 100 % recomendados",,,strong,high_quality_signal,60.0726,True,not_ready
4,1844aa47-4f98-47f5-a31d-0f5565cd4990,ALCÁZAR ANDALUSÍ TAPAS,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,dd0845a6-120f-4945-9a3d-ec166c36337c,FERIA,dish_es_v1_ad3755cf6fd0fb67,atún,atun,mar_y_pescado,pescado,3,3,3,3,0,0,1.0000,0.0000,0.0,2.8000,0.0000,0.0,2.8000,0.6552,0.1724,1.0000,1.0000,2.1607,2.1740,0.9333,0.9333,3,0,1.0000,0.0000,0,0,0,0,0,[],5.0000,5.0,5.0,mida estaba deliciosa. Recomiendo encarecidamente: - La berenjena con queso de cabra y miel. - Risotto. - Croquetas. - Ensaladilla. - Tataki de atún. - Tarta de naranja y choco...,,,solid,usable_signal,59.6501,True,weak_candidate
5,1aca2d21-7dbe-4269-b360-889b689724e9,Taberna Los Terceros,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,903feb9b-aed1-4717-abbf-e693ac5585a0,SANTA CATALINA,dish_es_v1_0a420a9251bb5aed,solomillo al whisky,solomillo al whisky,tapas_clasicas,solomillo,5,3,3,5,0,0,1.0000,0.0000,0.0,3.7379,0.0000,0.0,3.7379,0.7032,0.1484,1.0000,1.0000,1.9054,2.0695,0.7980,0.7476,4,1,0.8000,0.2000,1,0,0,1,1,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marker_nearby, intensifier_nearby, mixed_local_evidence, ...",4.4000,4.0,5.0,"Taberna típica de Sevilla, fuimos porque era de los pocos lugares que tenían sitio en la terraza y pedimos unos chocos (12€) y un solomillo al whisky (12€) el solomillo estaba ...",,,solid,usable_signal,59.4452,True,weak_candidate
6,2cf94026-9350-4b2c-abf1-54a08af310d3,BAR EL BUCHITO,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,2a3957f2-7a2e-4d5f-aab7-7ae541c9c030,PALMETE,dish_es_v1_2c67f67ce386e9d6,carrillada,carrillada,tapas_clasicas,carrillada,3,2,2,3,0,0,1.0000,0.0000,0.0,2.7700,0.0000,0.0,2.7700,0.6534,0.1733,1.0000,1.0000,2.6153,2.6099,0.9233,0.9233,3,0,1.0000,0.0000,0,0,0,2,0,[contrast_marker_nearby],5.0000,5.0,5.0,"Su carrillada está buenísima, Recomendadismo.",,,solid,usable_signal,58.0201,True,weak_candidate
7,4cd9688c-15bf-4a33-bcb9-56d0c20e0f81,Bar BOCACHICA,22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,4cc93289-8e5d-4379-8ca1-74cacb5f263a,EL PORVENIR,dish_es_v1_10850a8a8e314902,ensaladilla,ensaladilla,tapas_clasicas,ensaladilla,5,3,3,5,0,0,1.0000,0.0000,0.0,3.5079,0.0000,0.0,3.5079,0.6927,0.1537,1.0000,1.0000,1.4674,1.6142,0.7520,0.7016,4,1,0.8000,0.2000,1,0,0,2,1,"[contrast_marker_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, mixed_local_evidence, ...",4.6000,4.0,5.0,"Hace una semana fuí con un amigo, cenamos muy bien, la ensaladilla, el tartar de atún, las croquetas, todo buenísimo.",,,solid,usable_signal,57.1380,True,weak_candidate
8,56979254-f513-4d56-84c0-bf27dd97806e,Il Ristorantino Dell'Avvocato Calle Cuna,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,282de85f-269a-4337-a3b8-75d8ac5fa1ea,ALFALFA,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,5,4,4,5,0,0,1.0000,0.0000,0.0,3.5415,0.0000,0.0,3.5415,0.6943,0.1529,1.0000,1.0000,2.3963,2.7308,0.8080,0.7083,4,1,0.8000,0.2000,1,1,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, sentiment_may_refer_to_service]",5.0000,5.0,5.0,"Muy rico todo, probamos las pizzas que tienen en carta y fuera de carta, buenísima calidad y sabor.",,,strong,high_quality_signal,57.0188,True,not_ready
9,b1cba103-51cb-48de-93ba-a1f027b2f67f,Mama Döner Kebab,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,ec7b7bef-c772-438a-9318-cc5ee459a6b9,CRUZ ROJA-CAPUCHINOS,dish_es_v1_11a773a1c774fd47,kebab,kebab,internacional,internacional,5,3,3,5,0,0,1.0000,0.0000,0.0,3.0159,0.0000,0.0,3.0159,0.6675,0.1662,1.0000,1.0000,2.6770,3.5506,0.7040,0.6032,3,2,0.6000,0.4000,2,0,0,1,0,"[intensifier_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marker_nearby]",5.0000,5.0,5.0,"La primera vez que pido kebab y lo volveré a hacer, super rico de sabor y buena calidad.",,,solid,usable_signal,55.1525,True,weak_candidate
10,a9ae2e43-3b1e-4239-9b74-6ae0bd0d47a4,Bodega Mi Tierra,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,cbd5d9b1-32f4-4ca8-98af-368b91f83c4a,SANTA AURELIA-CANTABRICO-ATLANTICO-LA ROMERIA,dish_es_v1_d130c191c0bc5a8e,torrija,torrija,postres_y_desayunos,postre,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,4.5790,4.5790,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[],5.0000,5.0,5.0,Carne de gran calidad y la torrija del postre increíble.,,,emerging,emerging_signal,54.9926,True,not_ready
11,28f6f03a-81a7-421d-af2b-b29b1f8e4137,Bar Casa Aldana,6af93f2e-b5da-4456-9cb1-e68958a97dbf,Nervión,3752a9a8-1236-43ad-8256-fed6ffad110f,CIUDAD JARDIN,dish_es_v1_2c67f67ce386e9d6,carrillada,carrillada,tapas_clasicas,carrillada,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,4.4557,4.4557,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],4.5000,4.0,5.0,"La carrillada ibérica es la estrella: melosa, muy sabrosa y con una salsa para mojar pan sin pensar.",,,emerging,emerging_signal,54.9366,True,not_ready
12,92a1858e-5d69-4b4f-899a-868482838841,Bar - Terraza La Cucamona,e1621557-0db9-443a-8065-2fbcb8a9515f,Bellavista - La Palmera,2996d82c-71b5-44bf-908d-c6eaef8f7b6c,ELCANO-BERMEJALES,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,4.0716,4.0716,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],4.5000,4.0,5.0,"s) muy bueno bien preparado y acompañado de muchas patatas, pastela nos gustó también y pocos sitios la preparan y los postres la tarta de queso exquisita.",,,emerging,emerging_signal,54.7265,True,not_ready
13,5f78cb03-a338-44a8-bee7-55d64248fcc0,Restaurante DepiKofino,6af93f2e-b5da-4456-9cb1-e68958a97dbf,Nervión,b63a69e4-c0a5-4a2b-b936-97511845b8d8,HUERTA DEL PILAR,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,3.7170,3.7170,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[],4.5000,4.0,5.0,La ensaladilla con caballa estaba rica también y su tarta de quedo con lotus nos dejó buen sabor de boca.,,,emerging,emerging_signal,54.4749,True,not_ready
14,a9bce0ce-f0c5-419b-91ee-cd125258adc0,Bar Restaurante La Cochera,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,7feeccb6-1f5d-47c2-a067-02dc6466c762,EL CERRO,dish_es_v1_2c67f67ce386e9d6,carrillada,carrillada,tapas_clasicas,carrillada,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8200,0.0000,0.0,1.8200,0.5851,0.2075,1.0000,1.0000,5.4561,5.4272,0.9100,0.9100,2,0,1.0000,0.0000,0,0,0,1,0,"[intensifier_nearby, contrast_marker_nearby]",3.5000,3.0,4.0,"En una de las visitas pedimos como principal la paella de queso de cabra y carrillera, original y con muchísimo sabor, y en la otra ocasión la picaña, que estaba buenísima, en ...",,,emerging,emerging_signal,54.4655,True,not_ready
15,e1180051-384f-44e1-be00-faf7c54475a1,"Venta Campo Rico ""El Arriero""",af2fbf25-5491-4c27-811f-28b7a400ea84,Norte,77dcf0db-e6d2-4f97-b9df-fc3477fe2b0f,VALDEZORRAS,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8345,0.0000,0.0,1.8345,0.5863,0.2068,1.0000,1.0000,4.4420,4.5543,0.9172,0.9172,2,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],5.0000,5.0,5.0,"La comida estuvo espectacular: la carne, especialmente la presa ibérica de bellota, estaba muy buena, el revuelto de la casa nos encantó y la tarta de queso estaba buenísima.",,,emerging,emerging_signal,54.3343,True,not_ready
16,c93f6669-5e46-4079-b296-b6bb6410a0e3,Flor de la Caña Café y Ron SR.,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,bb03aa4d-9154-4b66-9292-529710ed9248,LEON XIII-LOS NARANJOS,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,3,3,3,3,0,0,1.0000,0.0000,0.0,2.4036,0.0000,0.0,2.4036,0.6299,0.1851,1.0000,1.0000,2.9120,3.1411,0.8833,0.8012,3,0,1.0000,0.0000,0,1,0,0,1,"[mixed_local_evidence, negation_detected, intensifier_nearby, sentiment_may_refer_to_service]",5.0000,5.0,5.0,Fuimos para comer y pedimos aborrajado macho y papá de pollo más arepas de guacamole todo super rico y casero y de postre tarta de Papayas deliciosa.,,,solid,usable_signal,54.3255,True,not_ready
17,1844aa47-4f98-47f5-a31d-0f5565cd4990,ALCÁZAR ANDALUSÍ TAPAS,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,dd0845a6-120f-4945-9a3d-ec166c36337c,FERIA,dish_es_v1_10850a8a8e314902,ensaladilla,ensaladilla,tapas_clasicas,ensaladilla,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,3.3580,3.3580,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[],5.0000,5.0,5.0,bien y la comida estaba deliciosa. Recomiendo encarecidamente: - La berenjena con queso de cabra y miel. - Risotto. - Croquetas. - Ensaladilla. - Tataki de atún. - Tarta de nar...,,,emerging,emerging_signal,54.1498,True,not_ready
18,a268a2e5-a430-4b13-9429-c7a356709b1b,"Cafeteria mi abuela, churreria",22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,fb5a5f48-54e9-49ac-9026-fc7d6cae69f5,FELIPE II-LOS DIEZ MANDAMIENTOS,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,6,5,5,6,0,0,1.0000,0.0000,0.0,3.5198,0.0000,0.0,3.5198,0.6932,0.1534,1.0000,1.0000,1.2724,1.3650,0.6928,0.5866,4,2,0.6667,0.3333,2,0,1,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, price_context_detected, intensifier_nearby]",5.0000,5.0,5.0,"Mi mujer y mis niños se han pedido churros con chocolate y estaban riquísimos, churros como hacía tiempo que no los comia, y yo una entera con jamón y café, y lo mismo el jamón...",,,strong,high_quality_signal,53.8855,True,not_ready
19,a8f8ab69-ba78-4de2-b3d5-4c055145b30c,El Sofrito Restaurante,7f42c0b3-14d1-400c-bcde-c128faafc4c5,Este - Alcosa - Torreblanca,9a832993-14ed-4c5a-b3f9-0ba3ef3898b6,"COLORES, ENTREPARQUES",dish_es_v1_10850a8a8e314902,ensaladilla,ensaladilla,tapas_clasicas,ensaladilla,5,4,4,5,0,0,1.0000,0.0000,0.0,2.8859,0.0000,0.0,2.8859,0.6602,0.1699,1.0000,1.0000,1.6400,1.9129,0.6780,0.5772,3,2,0.6000,0.4000,2,0,0,1,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, contrast_marker_nearby]",4.0000,1.0,5.0,"Ensaladilla picante buena, vieras pequeñas como almejas y muy hechas, ternera muy buena.",,,strong,high_quality_signal,53.5852,True,not_ready
20,d509374b-4fdf-4f83-a4c2-039d123e9baf,Las Golondrinas - Pagés del Corro,f9420edb-f021-42df-a2cc-e4bb21d0eceb,Triana,400ec702-65c5-4abb-835e-687ae82ea50c,TRIANA OESTE,dish_es_v1_0a420a9251bb5aed,solomillo al whisky,solomillo al whisky,tapas_clasicas,solomillo,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8600,0.0000,0.0,1.8600,0.5885,0.2058,1.0000,1.0000,3.1976,3.1867,0.9300,0.9300,2,0,1.0000,0.0000,0,0,0,1,0,"[contrast_marker_nearby, intensifier_nearby]",5.0000,5.0,5.0,"Pedimos puntas de solomillo, muy ricas; la ensaladilla rusa, muy buena; 2 tapas de pisto con bacalao, ricas; y ""caballitos"" que son unas tostas con jamón de bodega frito, se as...",,,emerging,emerging_signal,53.5683,True,not_ready
21,6ee0277a-c373-4d0d-94bc-f7d90766cdc2,I Love Churros - Cafetería churreria en Ronda de Capuchinos,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,ec7b7bef-c772-438a-9318-cc5ee459a6b9,CRUZ ROJA-CAPUCHINOS,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,8,5,5,7,1,0,0.8750,0.1250,0.0,3.5914,0.4800,0.0,4.0714,0.6493,0.1414,0.8750,0.8821,1.3752,1.6476,0.6325,0.5089,5,3,0.6250,0.3750,3,1,0,3,0,"[contrast_marker_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, sentiment_may_refer_to...",4.7500,3.0,5.0,Increíble lugar para comer churros y chocolate!,,"El chocolate y los churros normal, nada extraordinario pero están buenos.",strong,high_quality_signal,53.5446,True,not_ready
22,d509374b-4fdf-4f83-a4c2-039d123e9baf,Las Golondrinas - Pagés del Corro,f9420edb-f021-42df-a2cc-e4bb21d0eceb,Triana,400ec702-65c5-4abb-835e-687ae82ea50c,TRIANA OESTE,dish_es_v1_b9512e58dcc6d376,bacalao,bacalao,mar_y_pescado,pescado,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8600,0.0000,0.0,1.8600,0.5885,0.2058,1.0000,1.0000,3.1647,3.1618,0.9300,0.9300,2,0,1.0000,0.0000,0,0,0,1,0,"[contrast_marker_nearby, intensifier_nearby]",5.0000,5.0,5.0,"Pedimos puntas de solomillo, muy ricas; la ensaladilla rusa, muy buena; 2 tapas de pisto con bacalao, ricas; y ""caballitos"" que son unas tostas con jamón de bodega frito, se as...",,,emerging,emerging_signal,53.5398,True,not_ready
23,1b707bbc-35d9-4f6b-b588-31d4b14b3758,Casa Mikva,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,602844e3-9beb-4493-8041-bec4973baf25,SAN BARTOLOME,dish_es_v1_ad3755cf6fd0fb67,atún,atun,mar_y_pescado,pescado,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8500,0.0000,0.0,1.8500,0.5876,0.2062,1.0000,1.0000,3.1860,3.2338,0.9250,0.9250,2,0,1.0000,0.0000,0,0,0,0,0,[],5.0000,5.0,5.0,"La comida espectacular, especialmente el tartar de atún rojo de almadraba, que estaba increíble, o la pluma ibérica , que se deshacía en la boca.",,,emerging,emerging_signal,53.5234,True,not_ready
24,752f92eb-5ae7-462c-8f6b-ecb42d52f4d3,La Sra Pop,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,dd0845a6-120f-4945-9a3d-ec166c36337c,FERIA,dish_es_v1_d35dbc1062811528,helado,helado,postres_y_desayunos,postre,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8050,0.0000,0.0,1.8050,0.5838,0.2081,1.0000,1.0000,3.5305,3.6543,0.9025,0.9025,2,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],5.0000,5.0,5.0,"Probe la torrija con helado y lotus, increible deliciosa, mi amigo se pidió un cafe irlandés le gustó mucho tambien y yo tambien pedí un batido de kinder muy bueno.",,,emerging,emerging_signal,53.4816,True,not_ready
25,57bffbe1-1549-4913-9a38-321760dedc4a,Pinsería Il Forno - Restaurante Italiano,898f9d9e-9365-4138-a30e-d8183ddfa969,San Pablo - Santa Justa,b088f223-bf70-4403-b939-12e3a81b216a,EL FONTANAL-MARIA AUXILIADORA-CARRETERA DE CARMONA,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,2,2,2,2,0,0,1.0000,0.0000,0.0,1.8500,0.0000,0.0,1.8500,0.5876,0.2062,1.0000,1.0000,2.9190,2.9596,0.9250,0.9250,2,0,1.0000,0.0000,0,0,0,0,0,[],5.0000,5.0,5.0,"La masa de la pizza es una locura, crujiente y esponjosa a la vez con un sabor genial, se nota que utilizan productos de buena calidad.",,,emerging,emerging_signal,53.1932,True,not_ready
26,a9bce0ce-f0c5-419b-91ee-cd125258adc0,Bar Restaurante La Cochera,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,7feeccb6-1f5d-47c2-a067-02dc6466c762,EL CERRO,dish_es_v1_10850a8a8e314902,ensaladilla,ensaladilla,tapas_clasicas,ensaladilla,2,2,2,2,0,0,1.0000,0.0000,0.0,1.7550,0.0000,0.0,1.7550,0.5794,0.2103,1.0000,1.0000,3.9437,3.9211,0.8775,0.8775,2,0,1.0000,0.0000,0,0,0,1,0,"[contrast_marker_nearby, intensifier_nearby]",4.0000,3.0,5.0,"Tanto la ensaladilla, como el queso frito, las croquetas y el pan brioche son cosas que recomiendo.",,,emerging,emerging_signal,53.1778,True,not_ready
27,ad959ed9-fa16-444b-8570-30ff9755233d,Sansa Café,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,ae182ebc-43a4-46db-9364-d006cf3a73c9,ENCARNACIÓN-REGINA,dish_es_v1_18ef91885a7312e4,tarta de queso,tarta de queso,postres_y_desayunos,tarta,2,2,2,2,0,0,1.0000,0.0000,0.0,1.9000,0.0000,0.0,1.9000,0.5918,0.2041,1.0000,1.0000,2.5340,2.5340,0.9500,0.9500,2,0,1.0000,0.0000,0,0,0,0,0,[intensifier_nearby],5.0000,5.0,5.0,"Pedimos dos cafes con leche de avena, la tarta flora y un oh baby mini y estaba todo delicioso.",,,emerging,emerging_signal,53.0462,True,not_ready

District summary:

,district_id,district_name,place_dish_pair_count,place_count,dish_count,total_mentions,avg_preliminary_signal_score,avg_positive_ratio,avg_negative_ratio,strong_candidate_count,promising_candidate_count,weak_candidate_count
3,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,76,51,25,204,43.261388,0.887051,0.005263,0,0,3
2,22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,24,16,18,62,43.208275,0.906946,0.000000,0,0,1
5,7f42c0b3-14d1-400c-bcde-c128faafc4c5,Este - Alcosa - Torreblanca,24,16,15,65,41.081896,0.883929,0.005954,0,0,0
4,6af93f2e-b5da-4456-9cb1-e68958a97dbf,Nervión,22,12,15,57,41.211332,0.965909,0.011364,0,0,0
9,f9420edb-f021-42df-a2cc-e4bb21d0eceb,Triana,20,14,12,47,41.657275,0.933330,0.000000,0,0,0
1,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,18,15,13,56,41.202761,0.951389,0.000000,0,0,1
0,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,17,13,9,49,45.918788,0.945100,0.031371,0,0,1
7,af2fbf25-5491-4c27-811f-28b7a400ea84,Norte,17,12,15,52,41.378376,0.973859,0.019606,0,0,0
6,898f9d9e-9365-4138-a30e-d8183ddfa969,San Pablo - Santa Justa,16,15,14,40,43.516531,0.916669,0.020831,0,0,0
8,e1621557-0db9-443a-8065-2fbcb8a9515f,Bellavista - La Palmera,16,16,11,37,40.526519,0.906250,0.000000,0,0,1
10,fb4a939c-375e-4928-8f52-9c31a103bb23,Los Remedios,6,5,5,13,38.140850,1.000000,0.000000,0,0,0

In [13]:
# ============================================================
# 09. Señales para revisión manual
# ============================================================

manual_review_low_evidence = (
    place_dish_signals[
        (place_dish_signals["preliminary_signal_score_v1"] >= 60)
        & (place_dish_signals["evidence_tier_v1"].isin(["weak", "emerging"]))
    ]
    .sort_values(["preliminary_signal_score_v1", "mention_count"], ascending=[False, False])
    .head(150)
)

manual_review_conflict = (
    place_dish_signals[
        (place_dish_signals["mention_count"] >= 2)
        & (
            (place_dish_signals["negative_ratio"] >= 0.35)
            | (place_dish_signals["fallback_ratio"] >= 0.75)
            | (place_dish_signals["service_flag_count"] > 0)
        )
    ]
    .sort_values(["mention_count", "negative_ratio", "fallback_ratio"], ascending=[False, False, False])
    .head(150)
)

manual_review_signals = pd.concat([
    manual_review_low_evidence.assign(manual_review_reason_v1="high_score_low_evidence"),
    manual_review_conflict.assign(manual_review_reason_v1="conflict_or_noisy_signal"),
], ignore_index=True).drop_duplicates(subset=["place_id", "dish_id_v1"], keep="first")

print("Señales para revisión manual:", len(manual_review_signals))
display(manual_review_signals.head(30))

Señales para revisión manual: 150

,place_id,place_name,district_id,district_name,neighborhood_id,neighborhood_name,dish_id_v1,display_dish_name_es_v1,normalized_dish_name_es_v1,dish_family_es_v1,dish_group_es_v1,mention_count,review_count,source_review_count,positive_count,neutral_count,negative_count,positive_ratio,neutral_ratio,negative_ratio,weighted_positive_count,weighted_neutral_count,weighted_negative_count,total_signal_weight,smoothed_positive_ratio,smoothed_negative_ratio,avg_sentiment_value,weighted_sentiment_value,avg_sentiment_score,weighted_sentiment_score,avg_sentiment_confidence,avg_aggregation_weight,local_context_count,review_prior_fallback_count,local_context_ratio,fallback_ratio,low_confidence_flag_count,service_flag_count,price_flag_count,contrast_flag_count,negation_flag_count,top_sentiment_flags_v1,avg_rating,min_rating,max_rating,example_positive_context_v1,example_negative_context_v1,example_neutral_context_v1,evidence_tier_v1,signal_quality_tier_v1,preliminary_signal_score_v1,ranking_ready_v1,candidate_tier_v1,manual_review_reason_v1
0,4d74b42b-54ef-4d31-9379-7df53dd7f6f6,Bendito Placer,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,7feeccb6-1f5d-47c2-a067-02dc6466c762,EL CERRO,dish_es_v1_9a1e795ae0c1d04f,hamburguesa,hamburguesa,carne,carne,10,5,5,5,1,4,0.5000,0.1000,0.4000,1.2418,0.0840,3.4255,4.7512,0.2892,0.5709,0.1000,-0.4596,-0.3905,-1.3944,0.5956,0.4751,5,5,0.5000,0.5000,5,0,0,2,1,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marker_nearby, intensifier_nearby, mixed_local_evidence, ...",3.2000,1.0,5.0,"n mucho sabor y se distinguían muy bien los sabores, y la especia que llevaba le daba muchiiisimo sabor, no ha gustado mucho; y de hamburguesas pedimos la Flamenca que estaba b...","La otra hamburguesa, la “Bendición Suprema”, resultó aún más decepcionante: apenas llevaba queso, el bacon seguía crudo y el chocolate blanco con topping de almendras y coco si...","Pedimos estas dos hamburguesas, la bendito placer y la templaria.",strong,weak_signal,11.0715,False,not_ready,conflict_or_noisy_signal
1,775735df-c2ed-4908-93c6-cc31da992abb,Heladería Valentina,6af93f2e-b5da-4456-9cb1-e68958a97dbf,Nervión,b63a69e4-c0a5-4a2b-b936-97511845b8d8,HUERTA DEL PILAR,dish_es_v1_d35dbc1062811528,helado,helado,postres_y_desayunos,postre,9,4,4,5,0,4,0.5556,0.0000,0.4444,1.1583,0.0000,3.3865,4.5448,0.2861,0.5814,0.1111,-0.4903,0.0168,-0.7556,0.6170,0.5050,5,4,0.5556,0.4444,4,0,0,0,0,"[intensifier_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal]",3.2222,1.0,5.0,La calidad del helado y el cucurucho son buenas.,"Lamentablemente, la cantidad es ridícula porque el helado está tan duro que no pueden presentarlo bien sobre el cucurucho.",,strong,weak_signal,10.8306,False,not_ready,conflict_or_noisy_signal
2,6ee0277a-c373-4d0d-94bc-f7d90766cdc2,I Love Churros - Cafetería churreria en Ronda de Capuchinos,1e467552-511d-4adb-bd9b-257bf108e491,Macarena,ec7b7bef-c772-438a-9318-cc5ee459a6b9,CRUZ ROJA-CAPUCHINOS,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,8,5,5,7,1,0,0.8750,0.1250,0.0000,3.5914,0.4800,0.0000,4.0714,0.6493,0.1414,0.8750,0.8821,1.3752,1.6476,0.6325,0.5089,5,3,0.6250,0.3750,3,1,0,3,0,"[contrast_marker_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, sentiment_may_refer_to...",4.7500,3.0,5.0,Increíble lugar para comer churros y chocolate!,,"El chocolate y los churros normal, nada extraordinario pero están buenos.",strong,high_quality_signal,53.5446,True,not_ready,conflict_or_noisy_signal
3,3b20f382-a6d0-4c7d-8e70-6d0ce11eee18,UDON Viapol,6af93f2e-b5da-4456-9cb1-e68958a97dbf,Nervión,00162efb-57bb-451d-a462-2bad40efc8b0,LA BUHAIRA,dish_es_v1_830869f3d7f1fb36,ramen,ramen,otros,ramen,7,1,1,1,1,5,0.1429,0.1429,0.7143,0.6749,0.4800,2.1438,3.2987,0.2659,0.4991,-0.5714,-0.4453,-1.2871,-1.7141,0.5793,0.4712,4,3,0.5714,0.4286,3,0,0,1,3,"[negation_detected, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, mixed_local_evidence, contrast_marker_nearby, n...",1.0000,1.0,1.0,Nunca me ha pasado eso al pedir ramen en ningún otro sitio.,"Me pedí el Miso Ramen y los fideos parecían que estaban hervidos en agua, sin sabor alguno, rancios, y el caldo más de lo mismo, parecía de brick y sin sabor.",El cuenco no era muy grande y las proporciones de ramen no sé quién las calcula pero no es normal que se me quedase más de la mitad del cuenco con caldo.,weak,weak_signal,12.0029,False,not_ready,conflict_or_noisy_signal
4,0fc81764-ec0b-4443-80f3-84e9971a8a96,Bar Blanco & Negro,7f42c0b3-14d1-400c-bcde-c128faafc4c5,Este - Alcosa - Torreblanca,6729f9d1-eacd-45f3-98a7-45aa43b9c4ae,TORREBLANCA,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,7,5,5,5,1,1,0.7143,0.1429,0.1429,2.1927,0.0840,0.1079,2.3846,0.5929,0.2058,0.5714,0.8743,0.5929,0.7936,0.5093,0.3407,3,4,0.4286,0.5714,4,1,0,1,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, sentiment_may_refer_to_service, contrast_marker_nearby]",3.4286,2.0,5.0,"Las mejores pizzas que existen,la mejor atención y el mejor alioli de Sevilla lo recomiendo al 100x100 ambiente familiar","Para que nos entendamos, el diámetro mediano ESTÁNDAR de cualquier pizza es de ≈30cm.",Las pizzas buenísimas como siempre aunque es una pena que después de tantísimos años los 2 locales(sobre todo el de invierno)siga exactamente igual que en los años 90.,emerging,emerging_signal,40.8953,True,not_ready,conflict_or_noisy_signal
5,d04648f5-3214-49b1-ad99-f3c94aba4d82,Sloppy Joe´s Reina Mercedes,e1621557-0db9-443a-8065-2fbcb8a9515f,Bellavista - La Palmera,2f220ce2-4b09-4cbb-9043-84c384c13349,SECTOR SUR-LA PALMERA-REINA MERCEDES,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,7,4,4,6,1,0,0.8571,0.1429,0.0000,1.4897,0.0840,0.0000,1.5737,0.5444,0.2186,0.8571,0.9467,0.9274,1.6450,0.4329,0.2248,1,6,0.1429,0.8571,6,0,0,2,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marker_nearby]",3.8571,3.0,4.0,Comimos en Sloppy Joe’s y pedimos la pizza Cubano… ¡buenísima!,,"Una vez nos habíamos comido unos nachos y una pizza, esperamos a que volviera la camarera para pedirle un postre, pero ésta nunca volvió.",weak,weak_signal,39.4402,False,not_ready,conflict_or_noisy_signal
6,08c95c21-50cb-4e73-b47b-6b9e901880a2,Bar Talo,898f9d9e-9365-4138-a30e-d8183ddfa969,San Pablo - Santa Justa,9759c83c-b132-4dc2-8176-cbb16ce04199,SAN PABLO A Y B,dish_es_v1_fdfff2d60e2bd29d,chicharrones,chicharrones,tapas_clasicas,chicharrones,6,5,5,6,0,0,1.0000,0.0000,0.0000,1.1733,0.0000,0.0000,1.1733,0.5208,0.2396,1.0000,1.0000,1.1623,1.5932,0.4467,0.1955,1,5,0.1667,0.8333,5,1,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, sentiment_may_refer_to_service]",4.5000,4.0,5.0,"los mejores chicharrones que he comido en mi vida, excelente atención..",,,weak,noisy_signal,35.4831,False,not_ready,conflict_or_noisy_signal
7,ea7d6564-2b10-4bef-97e9-f91cfb33d342,Pizzería San Pablo,898f9d9e-9365-4138-a30e-d8183ddfa969,San Pablo - Santa Justa,f36f071a-eedf-4022-adcb-a0d67a0ccf28,SAN PABLO D Y E,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,6,5,5,6,0,0,1.0000,0.0000,0.0000,4.4098,0.0000,0.0000,4.4098,0.7301,0.1350,1.0000,1.0000,4.6146,5.3569,0.8350,0.7350,5,1,0.8333,0.1667,1,1,1,0,0,"[intensifier_nearby, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, price_context_detected, sentiment_may_refer_to...",5.0000,5.0,5.0,"Unas experiencia muy buena la pizza 10 de 10 me encanto, esta vez fue la carnivora y seguiré probando las demás pizza q tienen, 100 % recomendados",,,strong,high_quality_signal,60.0726,True,not_ready,conflict_or_noisy_signal
8,b6b43d75-7e3c-451c-a4e6-39557a23133f,Asador Restaurante La Finca,898f9d9e-9365-4138-a30e-d8183ddfa969,San Pablo - Santa Justa,dc7a25ef-180f-485b-827b-fd841c61f6ac,SANTA CLARA,dish_es_v1_0a420a9251bb5aed,solomillo al whisky,solomillo al whisky,tapas_clasicas,solomillo,5,1,1,0,0,5,0.0000,0.0000,1.0000,0.0000,0.0000,0.5397,0.5397,0.2825,0.4350,-1.0000,-1.0000,-1.1500,-1.1500,0.3600,0.1079,0,5,0.0000,1.0000,5,0,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal]",1.0000,1.0,1.0,,"Yo no pedí lomo, pedí solomillo, y la camarera —fácil de identificar porque no es española— me aseguró varias veces que lo que iban a servir era solomillo.",,weak,weak_signal,11.5061,False,not_ready,conflict_or_noisy_signal
9,ad3d1ab5-170c-4550-9a01-650ec0547c4a,Marabunda Sevilla Restaurante tapas Bar,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,33dcb6fb-ea96-4aae-854b-41b4ebc4ccb3,SAN VICENTE,dish_es_v1_3b8c4e72931fd3d2,croqueta,croqueta,tapas_clasicas,croqueta,5,3,3,2,0,3,0.4000,0.0000,0.6000,0.2159,0.0000,1.8279,2.0438,0.2411,0.5607,-0.2000,-0.7887,-0.4900,-1.3437,0.5600,0.4088,2,3,0.4000,0.6000,3,0,0,1,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marker_nearby]",3.6000,1.0,5.0,Para mí el plato de croquetas y huevo roto le falta un poco de rockandroll para que brille más.,"Pedimos los siguientes platos: Volandeira, croquetas, arroz de carrillada, huevos rotos con gambon y el crudo de atún.",,solid,weak_signal,9.7506,False,not_ready,conflict_or_noisy_signal
10,06dea912-d70c-45fc-bd0f-8e5998736921,Cafetería El Pilar Gran Plaza,6af93f2e-b5da-4456-9cb1-e68958a97dbf,Nervión,ae555348-679e-47f2-943c-4a60790e0a79,NERVION,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,5,4,4,2,1,2,0.4000,0.2000,0.4000,0.2159,0.0840,0.2159,0.5157,0.3458,0.3458,0.0000,0.0000,0.0600,0.0628,0.3440,0.1031,0,5,0.0000,1.0000,5,0,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal]",3.2000,1.0,5.0,"Si deseas conocer y disfrutar de los churros típicos de toda la vida en Sevilla, !",He comprado dos raciones de churros esta mañana para llevar con un chocolate y una tostada entera de jamón.,Los churros son espectaculares.,weak,weak_signal,22.1967,False,not_ready,conflict_or_noisy_signal
11,8a28c4f9-7798-4b81-bd70-39c1633991e9,Bar Rincón De Rosita,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,baeb9abd-4ed1-4378-b313-b8c45a3298a4,SAN GIL,dish_es_v1_9e1ee3822e33c26e,almejas,almejas,otros,almejas,5,3,3,3,0,2,0.6000,0.0000,0.4000,0.3238,0.0000,0.1964,0.5203,0.3761,0.3399,0.2000,0.2448,0.2300,0.2815,0.3600,0.1041,0,5,0.0000,1.0000,5,0,1,1,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marker_nearby, price_context_detected]",3.4000,1.0,5.0,Ya he ido varias veces y me encanta pero hoy he ido con mis nietos y he pedido almejas que estaban espectaculares Pero la frase que me ha dicho mi nieto de 7 años ha sido esta.,"Pedimos almejas de carril al ajillo (sugerencia fuera de carta, ojo, preguntad siempre el precio antes, podéis llevaros una sorpresa).",,weak,noisy_signal,21.0668,False,not_ready,conflict_or_noisy_signal
12,7a0dcab4-bcac-4fbf-8973-8d3926ae9fc6,La Sita Sevilla,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,dd0845a6-120f-4945-9a3d-ec166c36337c,FERIA,dish_es_v1_ad3755cf6fd0fb67,atún,atun,mar_y_pescado,pescado,5,3,3,3,0,2,0.6000,0.0000,0.4000,2.7500,0.0000,1.6600,4.4100,0.5061,0.3590,0.2000,0.2472,0.2016,0.3064,0.8820,0.8820,5,0,1.0000,0.0000,0,0,0,0,2,"[intensifier_nearby, mixed_local_evidence, negation_detected]",4.6000,4.0,5.0,"Mencía, albariño, toro y rioja son vinos que podrás combinar con sus maravillosas gildas, tartar de atún en un ajo blanco increíble, tartar de ternera, y gildas matrimonio incr...","e viene con una tacita de caldo del puchero(maravilla),los pimientos del piquillo también muy ricos y por último una pulguita de atún, que para mi fue lo mas flojo, porque el p...",,solid,weak_signal,34.9219,True,not_ready,conflict_or_noisy_signal
13,c98c9c0e-8d72-4e9f-9c62-b2c3ff038bf4,El Primero de San Carlos,898f9d9e-9365-4138-a30e-d8183ddfa969,San Pablo - Santa Justa,a66f31dd-78dd-495f-8129-81b5539b03e6,SAN CARLOS-TARTESSOS,dish_es_v1_a646e68b8a85d929,montadito,montadito,tapas_clasicas,montadito,5,5,5,4,0,1,0.8000,0.0000,0.2000,0.4318,0.0000,0.9100,1.3418,0.3298,0.4399,0.6000,-0.3564,0.4466,-1.2353,0.4700,0.2684,1,4,0.2000,0.8000,4,0,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby]",5.0000,5.0,5.0,Carta amplia de recetas típicas sevillanas y 50 tipos de montaditos.,"De lo mejorcito en guisos y montaditos y la cerveza muy fría , repetiré sin dudarlo!",,emerging,emerging_signal,16.9909,False,not_ready,conflict_or_noisy_signal
14,93369e3a-ea14-4759-9b52-4bab20fb76d6,Cafetería La Manguada,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,e4c2f134-60f3-4727-9ebb-fdac8f258012,JUAN XXIII,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,5,5,5,4,0,1,0.8000,0.0000,0.2000,2.5465,0.0000,0.1079,2.6545,0.6272,0.1959,0.6000,0.9187,1.3816,1.9692,0.6810,0.5309,3,2,0.6000,0.4000,2,1,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, sentiment_may_refer_to_service]",4.4000,2.0,5.0,"Un bar donde te sientes como si estuviera en familia son super buenas personas siempre con bromas y una sonrisa , muy agradables ^^ Las tostadas increíble también si quieres añ...",Los churros estaban un poco quemados.,,strong,high_quality_signal,47.9105,True,not_ready,conflict_or_noisy_signal
15,d4437db5-7f40-4a80-853c-d1346f24aa63,Café Los Pilares Bar,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,7feeccb6-1f5d-47c2-a067-02dc6466c762,EL CERRO,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,5,5,5,5,0,0,1.0000,0.0000,0.0000,0.5397,0.0000,0.0000,0.5397,0.4350,0.2825,1.0000,1.0000,1.0900,1.0900,0.3600,0.1079,0,5,0.0000,1.0000,5,0,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal]",4.8000,4.0,5.0,Riquísimos los churros tanto los de lazo como las porras.,,,weak,weak_signal,30.4405,False,not_ready,conflict_or_noisy_signal
16,115f7792-cc47-4610-bdda-2d08946ee520,La Bodega de la Alfalfa,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,282de85f-269a-4337-a3b8-75d8ac5fa1ea,ALFALFA,dish_es_v1_b9512e58dcc6d376,bacalao,bacalao,mar_y_pescado,pescado,5,3,3,5,0,0,1.0000,0.0000,0.0000,1.3318,0.0000,0.0000,1.3318,0.5383,0.2309,1.0000,1.0000,1.2268,1.4095,0.4680,0.2664,1,4,0.2000,0.8000,4,0,0,1,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marker_nearby]",5.0000,5.0,5.0,"sobre todo os recomiendo el bacalao con frutos rojos, es una exquisitez.",,,emerging,emerging_signal,36.7559,True,not_ready,conflict_or_noisy_signal
17,1da48b22-1401-46bc-adec-c9a48f50c5fa,Cafetería La Marikilla,af2fbf25-5491-4c27-811f-28b7a400ea84,Norte,858fc3c3-8274-4d6e-9330-57302db0e192,SAN JERONIMO,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,5,2,2,5,0,0,1.0000,0.0000,0.0000,1.3318,0.0000,0.0000,1.3318,0.5383,0.2309,1.0000,1.0000,1.0699,1.5930,0.4680,0.2664,1,4,0.2000,0.8000,4,0,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby]",4.2000,4.0,5.0,"Gran variedad de cafés, tostadas, molletes, dulces y churros, todo muy rico y hecho con cariño, esmero y muy diligentemente.",,,emerging,emerging_signal,35.4381,True,not_ready,conflict_or_noisy_signal
18,b8ff8a2a-a5c6-4c97-b514-765223eba791,Bar Casa Pepe,22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,644f5fdb-1fd2-4e8e-8a82-df9ed3699147,TIRO DE LINEA-SANTA GENOVEVA,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,5,2,2,2,3,0,0.4000,0.6000,0.0000,1.0579,0.2519,0.0000,1.3098,0.4775,0.2320,0.4000,0.8077,0.7020,1.8065,0.4300,0.2620,1,4,0.2000,0.8000,4,0,0,1,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marker_nearby]",3.8000,3.0,5.0,El zumo de naranja está muy bien y si pides churros el chocolate es imprescindible está riquísimo.,,Hoy miércoles vinimos buscando churros.,weak,weak_signal,34.7602,False,not_ready,conflict_or_noisy_signal
19,5c0bfb32-f693-4408-b086-ea40fb14cb2f,Cala Roche Restaurante Sevilla,22b433e4-3b14-4b09-bfaa-f0ca1d7e6bdc,Sur,72eccb5a-4fae-4317-b394-85b5a8d2677c,EL PLANTINAR,dish_es_v1_ad3755cf6fd0fb67,atún,atun,mar_y_pescado,pescado,5,2,2,5,0,0,1.0000,0.0000,0.0000,1.1393,0.0000,0.0000,1.1393,0.5168,0.2416,1.0000,1.0000,1.0380,0.8022,0.4295,0.2279,1,4,0.2000,0.8000,4,0,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal]",5.0000,5.0,5.0,"La experiencia comenzó con una Gilda de atún que marca el tono de la casa: sabor, equilibrio y materia prima.",,,weak,weak_signal,32.1612,False,not_ready,conflict_or_noisy_signal
20,4039c914-07cd-4e2a-8788-0f6a54805926,Restaurante Da Pino,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,903feb9b-aed1-4717-abbf-e693ac5585a0,SANTA CATALINA,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,5,5,5,4,1,0,0.8000,0.2000,0.0000,2.2463,0.0840,0.0000,2.3303,0.6090,0.1876,0.8000,0.9640,2.7196,3.5547,0.6520,0.4661,3,2,0.6000,0.4000,2,2,0,1,1,"[intensifier_nearby, sentiment_may_refer_to_service, low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, contrast_marke...",4.4000,3.0,5.0,"Comida italiana muy buena, pedimos pizza y fetuccine con cordero y estaban las dos cosas muy buenas.",,"Las pizzas estaban ricas, de masa fina y se notaba que los ingredientes eran frescos.",strong,high_quality_signal,50.2921,True,not_ready,conflict_or_noisy_signal
21,a0d496eb-18de-4b61-8eda-224f392989af,Cafetería Chocolateria Osto E Hijos,09b2875d-a826-4c21-bd78-1d8fa48009de,Cerro - Amate,76a474aa-a390-48b4-a7ad-d68f6d747832,LA PLATA,dish_es_v1_da687fa2af0b4205,churros,churros,postres_y_desayunos,postre,5,5,5,5,0,0,1.0000,0.0000,0.0000,2.3471,0.0000,0.0000,2.3471,0.6260,0.1870,1.0000,1.0000,1.4653,1.6154,0.6660,0.4694,3,2,0.6000,0.4000,2,2,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, sentiment_may_refer_to_service, intensifier_nearby]",5.0000,5.0,5.0,"Siempre que puedo me acerco a probar los churros con mi mujer, recomiendo tanto los normales como los de papas.",,,strong,high_quality_signal,47.7796,True,not_ready,conflict_or_noisy_signal
22,56979254-f513-4d56-84c0-bf27dd97806e,Il Ristorantino Dell'Avvocato Calle Cuna,5bd4fbf1-457b-4dcb-91f1-089ac449a5db,Casco Antiguo,282de85f-269a-4337-a3b8-75d8ac5fa1ea,ALFALFA,dish_es_v1_1f6ccd2be75f1cc9,pizza,pizza,internacional,internacional,5,4,4,5,0,0,1.0000,0.0000,0.0000,3.5415,0.0000,0.0000,3.5415,0.6943,0.1529,1.0000,1.0000,2.3963,2.7308,0.8080,0.7083,4,1,0.8000,0.2000,1,1,0,0,0,"[low_sentiment_confidence, no_clear_local_sentiment, used_review_prior_fallback, weak_local_sentiment_signal, intensifier_nearby, sentiment_may_refer_to_service]",5.0000,5.0,5.0,"Muy rico todo, probamos las pizzas que tienen en carta y fuera de carta, buenísima calidad y sabor.",,,strong,high_quality_signal,57.0188,True,not_ready,conflict_or_noisy_signal

In [14]:
# ============================================================
# 10. Checks finales
# ============================================================

checks = {
    "has_place_dish_signals": len(place_dish_signals) > 0,
    "has_ranking_ready_signals": bool(place_dish_signals["ranking_ready_v1"].any()),
    "all_signals_have_place": bool(place_dish_signals["place_id"].notna().all()),
    "all_signals_have_dish": bool(place_dish_signals["dish_id_v1"].notna().all()),
    "all_signals_have_neighborhood": bool(place_dish_signals["neighborhood_id"].notna().all()),
    "all_signals_have_district": bool(place_dish_signals["district_id"].notna().all()),
    "no_negative_mention_counts": bool((place_dish_signals["mention_count"] >= 0).all()),
    "no_negative_review_counts": bool((place_dish_signals["review_count"] >= 0).all()),
    "score_in_0_100": bool(place_dish_signals["preliminary_signal_score_v1"].between(0, 100).all()),
    "has_global_dish_signals": len(global_dish_signals) > 0,
    "global_dish_ids_are_unique": bool(global_dish_signals["dish_id_v1"].nunique(dropna=True) == len(global_dish_signals)),
}

print(json.dumps(checks, indent=2, ensure_ascii=False))
failed = [k for k, v in checks.items() if not bool(v)]
if failed:
    print("Checks fallidos:", failed)
else:
    print("Todos los checks principales han pasado.")

{
  "has_place_dish_signals": true,
  "has_ranking_ready_signals": true,
  "all_signals_have_place": true,
  "all_signals_have_dish": true,
  "all_signals_have_neighborhood": true,
  "all_signals_have_district": true,
  "no_negative_mention_counts": true,
  "no_negative_review_counts": true,
  "score_in_0_100": true,
  "has_global_dish_signals": true,
  "global_dish_ids_are_unique": true
}
Todos los checks principales han pasado.

In [15]:
# ============================================================
# 11. Guardado de artefactos
# ============================================================

signals_csv_path = OUTPUT_DIR / "sevilla_place_dish_signals_v1.csv"
signals_jsonl_path = OUTPUT_DIR / "sevilla_place_dish_signals_v1.jsonl"

ranking_candidates_csv_path = OUTPUT_DIR / "sevilla_place_dish_ranking_candidates_v1.csv"
ranking_candidates_jsonl_path = OUTPUT_DIR / "sevilla_place_dish_ranking_candidates_v1.jsonl"

global_dish_csv_path = OUTPUT_DIR / "sevilla_global_dish_signals_v1.csv"
district_csv_path = OUTPUT_DIR / "sevilla_place_dish_signals_by_district_v1.csv"
neighborhood_csv_path = OUTPUT_DIR / "sevilla_place_dish_signals_by_neighborhood_v1.csv"
tier_summary_csv_path = OUTPUT_DIR / "sevilla_place_dish_signal_tier_summary_v1.csv"
top_signals_csv_path = OUTPUT_DIR / "sevilla_top_place_dish_signals_v1.csv"
manual_review_csv_path = OUTPUT_DIR / "sevilla_place_dish_signals_manual_review_v1.csv"
summary_json_path = OUTPUT_DIR / "sevilla_place_dish_signal_summary_v1.json"

signals_csv_df = place_dish_signals.copy()
signals_csv_df["top_sentiment_flags_v1"] = signals_csv_df["top_sentiment_flags_v1"].apply(
    lambda x: json.dumps(x, ensure_ascii=False) if isinstance(x, list) else x
)

ranking_candidates = place_dish_signals[place_dish_signals["ranking_ready_v1"]].copy()
ranking_candidates_csv_df = ranking_candidates.copy()
ranking_candidates_csv_df["top_sentiment_flags_v1"] = ranking_candidates_csv_df["top_sentiment_flags_v1"].apply(
    lambda x: json.dumps(x, ensure_ascii=False) if isinstance(x, list) else x
)

manual_review_csv_df = manual_review_signals.copy()
if len(manual_review_csv_df) and "top_sentiment_flags_v1" in manual_review_csv_df.columns:
    manual_review_csv_df["top_sentiment_flags_v1"] = manual_review_csv_df["top_sentiment_flags_v1"].apply(
        lambda x: json.dumps(x, ensure_ascii=False) if isinstance(x, list) else x
    )

signals_csv_df.to_csv(signals_csv_path, index=False, encoding="utf-8")
save_jsonl(place_dish_signals, signals_jsonl_path)

ranking_candidates_csv_df.to_csv(ranking_candidates_csv_path, index=False, encoding="utf-8")
save_jsonl(ranking_candidates, ranking_candidates_jsonl_path)

global_dish_signals.to_csv(global_dish_csv_path, index=False, encoding="utf-8")
summary_by_district.to_csv(district_csv_path, index=False, encoding="utf-8")
summary_by_neighborhood.to_csv(neighborhood_csv_path, index=False, encoding="utf-8")
candidate_tier_summary.to_csv(tier_summary_csv_path, index=False, encoding="utf-8")
top_place_dish_signals.to_csv(top_signals_csv_path, index=False, encoding="utf-8")
manual_review_csv_df.to_csv(manual_review_csv_path, index=False, encoding="utf-8")

summary = {
    "notebook": "16_sevilla_place_dish_signal_aggregation",
    "version": "sevilla_place_dish_signal_aggregation_v1",
    "generated_at": datetime.now(timezone.utc).isoformat(),
    "input_path": str(INPUT_PATH),
    "output_dir": str(OUTPUT_DIR),
    "input": {
        "total_mentions": int(len(df)),
        "unique_reviews": int(df["review_id"].nunique(dropna=True)),
        "unique_places": int(df["place_id"].nunique(dropna=True)),
        "unique_dishes": int(df["dish_id_v1"].nunique(dropna=True)),
        "unique_neighborhoods": int(df["neighborhood_id"].nunique(dropna=True)),
        "unique_districts": int(df["district_id"].nunique(dropna=True)),
        "sentiment_counts": df["mention_sentiment_label_v1"].value_counts().to_dict(),
    },
    "aggregation": {
        "total_place_dish_pairs": int(len(place_dish_signals)),
        "ranking_ready_pairs": int(place_dish_signals["ranking_ready_v1"].sum()),
        "not_ranking_ready_pairs": int((~place_dish_signals["ranking_ready_v1"]).sum()),
        "unique_places_with_signal": int(place_dish_signals["place_id"].nunique(dropna=True)),
        "unique_dishes_with_signal": int(place_dish_signals["dish_id_v1"].nunique(dropna=True)),
        "unique_neighborhoods_with_signal": int(place_dish_signals["neighborhood_id"].nunique(dropna=True)),
        "unique_districts_with_signal": int(place_dish_signals["district_id"].nunique(dropna=True)),
        "evidence_tier_counts": place_dish_signals["evidence_tier_v1"].value_counts().to_dict(),
        "signal_quality_tier_counts": place_dish_signals["signal_quality_tier_v1"].value_counts().to_dict(),
        "candidate_tier_counts": place_dish_signals["candidate_tier_v1"].value_counts().to_dict(),
        "preliminary_signal_score": {
            "min": float(place_dish_signals["preliminary_signal_score_v1"].min()) if len(place_dish_signals) else 0.0,
            "mean": float(place_dish_signals["preliminary_signal_score_v1"].mean()) if len(place_dish_signals) else 0.0,
            "median": float(place_dish_signals["preliminary_signal_score_v1"].median()) if len(place_dish_signals) else 0.0,
            "max": float(place_dish_signals["preliminary_signal_score_v1"].max()) if len(place_dish_signals) else 0.0,
        },
        "manual_review_signal_count": int(len(manual_review_signals)),
    },
    "global_dish_signals": {
        "dish_count": int(len(global_dish_signals)),
        "top_global_dishes": global_dish_signals.head(30).replace({np.nan: None}).to_dict(orient="records"),
    },
    "top_place_dish_signals": top_place_dish_signals.head(30).replace({np.nan: None}).to_dict(orient="records"),
    "checks": checks,
    "artifacts": {
        "signals_csv": signals_csv_path.name,
        "signals_jsonl": signals_jsonl_path.name,
        "ranking_candidates_csv": ranking_candidates_csv_path.name,
        "ranking_candidates_jsonl": ranking_candidates_jsonl_path.name,
        "global_dish_signals_csv": global_dish_csv_path.name,
        "district_summary_csv": district_csv_path.name,
        "neighborhood_summary_csv": neighborhood_csv_path.name,
        "tier_summary_csv": tier_summary_csv_path.name,
        "top_signals_csv": top_signals_csv_path.name,
        "manual_review_csv": manual_review_csv_path.name,
    },
}

save_json(summary, summary_json_path)

print("Artefactos guardados en:", OUTPUT_DIR)
print("Resumen:", summary_json_path)
print(json.dumps({
    "total_place_dish_pairs": len(place_dish_signals),
    "ranking_ready_pairs": int(place_dish_signals["ranking_ready_v1"].sum()),
    "candidate_tier_counts": place_dish_signals["candidate_tier_v1"].value_counts().to_dict(),
    "evidence_tier_counts": place_dish_signals["evidence_tier_v1"].value_counts().to_dict(),
}, indent=2, ensure_ascii=False))

Artefactos guardados en: c:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\aggregation
Resumen: c:\Users\USUARIO\Documents\Proyectos_Master_IA_Big_Data\hidden-gems-pipeline\data\artifacts\ai\sevilla\aggregation\sevilla_place_dish_signal_summary_v1.json
{
  "total_place_dish_pairs": 2212,
  "ranking_ready_pairs": 256,
  "candidate_tier_counts": {
    "not_ready": 2205,
    "weak_candidate": 7
  },
  "evidence_tier_counts": {
    "weak": 1909,
    "emerging": 215,
    "solid": 76,
    "strong": 12
  }
}